"""Expression orale — the monthly exam series of July, August and September 2026.

Transcribed from "TCF Canada — Expression orale — Séries d'examen d'entraînement
(Septembre · Août · Juillet 2026)". Each series pairs subject k of Partie n
(tâche 2) with subject k of the same Partie n (tâche 3); the subjects come from
the "Sujets d'actualité — Expression orale" pages for those months, and the
theme titles are indicative.

One entry per series, in the order the document gives them (September first).
`index` is the number of the series within its month, which is what the page
prints; the global set number a candidate's attempts are filed under is
assigned in exam_sets.py by position. Do not reorder — the numbering is
positional.
"""

SPEAKING_SERIES_2026 = [
    # Septembre 2026 · série 1 — Septembre 2026 · Partie 1 · Sujet 1
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 1,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Loisirs",
                "situation": "Je suis un(e) ami(e) canadien(ne). Vous réalisez un sondage sur mes activités pendant le week-end au Canada. Vous me posez des questions.",
                "hints": "mes occupations, les lieux que je visite, le moment, les personnes qui m'accompagnent, etc."},
     "tache3": {"theme": "Médias et Télévision",
                "question": "De nos jours, est-il faisable de vivre sans télévision ? Expliquez."}},
    # Septembre 2026 · série 2 — Septembre 2026 · Partie 1 · Sujet 2
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 2,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Culture et Traditions",
                "situation": "Je suis un(e) ami(e). Je viens de me marier au Canada. Vous me posez des questions afin de comparer le mariage dans votre pays et celui au Canada.",
                "hints": "coutumes, préparation, invités, etc."},
     "tache3": {"theme": "Société et Mode de vie",
                "question": "Actuellement, beaucoup de gens cherchent à améliorer leur apparence. Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 3 — Septembre 2026 · Partie 1 · Sujet 3
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 3,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Sport et Santé",
                "situation": "Je suis un(e) ami(e) francophone. J'ai pris part à une compétition sportive. Vous souhaitez en savoir plus et vous me posez des questions sur mon expérience et sur mon entraînement pour une prochaine compétition.",
                "hints": ""},
     "tache3": {"theme": "Santé et Bien-être",
                "question": "Est-ce que le stress peut devenir un facteur de motivation ? Pourquoi ?"}},
    # Septembre 2026 · série 4 — Septembre 2026 · Partie 1 · Sujet 4
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 4,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie sociale et Culture",
                "situation": "Je suis un(e) collègue. Vous êtes en voyage professionnel au Canada. Vous m'interrogez pour découvrir la manière dont les Canadiens passent leurs soirées.",
                "hints": "endroits, activités, habitudes, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Les métiers les plus difficiles devraient-ils être mieux payés ? Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 5 — Septembre 2026 · Partie 1 · Sujet 5
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 5,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis un(e) ami(e). J'ai fait un voyage en famille dans une ville francophone. Vous souhaitez en savoir plus et vous me posez des questions concernant ce voyage.",
                "hints": "activités, dépenses, organisation, préparatifs, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "D'après vous, quelles mesures un pays peut-il adopter pour faciliter l'intégration des étrangers ?"}},
    # Septembre 2026 · série 6 — Septembre 2026 · Partie 2 · Sujet 1
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 6,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Éducation et Vie scolaire",
                "situation": "Je suis parent d'un élève et nos enfants fréquentent la même école. Vous assistez à la fête de l'école pour la première fois et vous me demandez des informations sur l'événement.",
                "hints": "programme, horaires, animations, etc."},
     "tache3": {"theme": "Environnement",
                "question": "Selon vous, doit-on protéger tous les animaux en voie de disparition ? Pourquoi ?"}},
    # Septembre 2026 · série 7 — Septembre 2026 · Partie 2 · Sujet 2
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 7,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Logement",
                "situation": "Je suis un(e) ami(e) et je vis dans une grande ville. Vous souhaitez louer un logement ici. Vous me demandez des informations.",
                "hints": "offres disponibles, prix, quartier, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "L'essentiel dans la vie est-il de trouver du bonheur au travail ? Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 8 — Septembre 2026 · Partie 2 · Sujet 3
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 8,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Sport et Santé",
                "situation": "Je suis employé(e) dans un club de sport. Vous souhaitez vous inscrire à une activité physique. Vous me demandez des renseignements pour faire votre choix.",
                "hints": "sports disponibles, horaires, coût, etc."},
     "tache3": {"theme": "Culture et Éducation",
                "question": "Selon vous, lire est-il une activité inutile ? Pourquoi ?"}},
    # Septembre 2026 · série 9 — Septembre 2026 · Partie 2 · Sujet 4
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 9,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis employé(e) dans une agence de voyages. Vous voulez planifier vos vacances et vous me demandez des informations.",
                "hints": "coût, destinations, activités, etc."},
     "tache3": {"theme": "Société et Mode de vie",
                "question": "Pensez-vous que l'on puisse être épanoui en vivant seul ? Pourquoi ?"}},
    # Septembre 2026 · série 10 — Septembre 2026 · Partie 2 · Sujet 5
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 10,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Culture",
                "situation": "Je suis employé(e) à la ludothèque de votre ville. Vous souhaitez adhérer et vous me posez des questions.",
                "hints": "horaires, prix, jeux disponibles, etc."},
     "tache3": {"theme": "Santé et Bien-être",
                "question": "Le plus important pour conserver la santé est-il de bien se nourrir ? Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 11 — Septembre 2026 · Partie 3 · Sujet 1
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 11,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Sport et Santé",
                "situation": "Je suis professeur(e) de sport (yoga, gymnastique, ping-pong, etc.) et j'organise une formation sportive le week-end prochain. Vous souhaitez y participer et vous me demandez des renseignements.",
                "hints": "lieu, niveau, nombre de participants, déroulement, etc."},
     "tache3": {"theme": "Tourisme et Société",
                "question": "Le tourisme prend une grande place dans certaines villes. Pensez-vous que cette situation pose des problèmes aux habitants ?"}},
    # Septembre 2026 · série 12 — Septembre 2026 · Partie 3 · Sujet 2
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 12,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Médias et Loisirs",
                "situation": "Je suis un(e) ami(e) et j'ai récemment participé à une émission de télévision comme spectateur(trice). Vous me demandez des renseignements pour connaître les différentes étapes.",
                "hints": "inscription, durée, déroulement, présentateur, etc."},
     "tache3": {"theme": "Environnement et Transport",
                "question": "Devrait-on empêcher les voitures de circuler dans les centres-villes ? Expliquez."}},
    # Septembre 2026 · série 13 — Septembre 2026 · Partie 3 · Sujet 3
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 13,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis votre collègue et je rentre d'un séjour d'une semaine dans une ville que vous ne connaissez pas. Vous me demandez des renseignements pour découvrir cette ville.",
                "hints": "dimensions, quartiers, moyens de transport, atmosphère, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Pour être recruté, est-il plus important d'avoir de l'expérience que des diplômes ? Êtes-vous d'accord ?"}},
    # Septembre 2026 · série 14 — Septembre 2026 · Partie 3 · Sujet 4
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 14,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je travaille dans un bureau d'information touristique au Canada. Vous voulez organiser un séjour d'une semaine consacré à la randonnée et vous me demandez des renseignements sur les offres disponibles.",
                "hints": "tarifs, durée, endroits, activités, etc."},
     "tache3": {"theme": "Technologie et Famille",
                "question": "Est-il possible pour les parents de laisser leurs enfants utiliser Internet sans s'inquiéter ? Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 15 — Septembre 2026 · Partie 3 · Sujet 5
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 15,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Travail et Emploi",
                "situation": "Je travaille dans un service d'aide à l'emploi. Vous êtes récemment arrivé(e) au Canada et vous cherchez du travail. Vous me demandez des renseignements sur les emplois proposés.",
                "hints": "postes, rémunération, horaires, conditions, etc."},
     "tache3": {"theme": "Langues et Voyages",
                "question": "Est-il important de maîtriser l'anglais pour voyager à l'étranger ? Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 16 — Septembre 2026 · Partie 4 · Sujet 1
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 16,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Santé",
                "situation": "Vous êtes récemment installé(e) dans un nouveau pays et vous ne vous sentez pas bien. Vous me demandez des informations pour savoir comment recevoir des soins.",
                "hints": "médecins, hôpitaux, services d'urgence, etc."},
     "tache3": {"theme": "Famille et Éducation",
                "question": "Pensez-vous qu'il soit important de montrer de l'autorité pour bien élever un enfant ? Pourquoi ?"}},
    # Septembre 2026 · série 17 — Septembre 2026 · Partie 4 · Sujet 2
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 17,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Culture et Traditions",
                "situation": "Je suis un professeur de français. Vous allez célébrer le Nouvel An au Canada et vous me demandez des renseignements sur la manière dont cette fête est célébrée.",
                "hints": "coutumes, événements, endroits, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Faut-il s'informer sur un pays avant de décider d'y vivre ? Pourquoi ?"}},
    # Septembre 2026 · série 18 — Septembre 2026 · Partie 4 · Sujet 3
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 18,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Alimentation et Restauration",
                "situation": "Je suis un(e) ami(e). Vous envisagez de venir au Canada et vous êtes végétarien(ne). Vous me demandez des informations pour trouver des restaurants et des repas qui vous conviennent.",
                "hints": ""},
     "tache3": {"theme": "Immigration et Travail",
                "question": "Quels avantages peut-on tirer d'une expérience d'études ou de travail à l'étranger ?"}},
    # Septembre 2026 · série 19 — Septembre 2026 · Partie 4 · Sujet 4
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 19,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Immigration et Installation",
                "situation": "Je suis un(e) ami(e) francophone. Vous venez de vous installer dans ma ville. Vous me demandez des informations pour faciliter votre installation.",
                "hints": "logement, activités, transports, démarches administratives, etc."},
     "tache3": {"theme": "Technologie et Réseaux sociaux",
                "question": "Pourquoi est-il important de protéger sa vie personnelle sur les réseaux sociaux ?"}},
    # Septembre 2026 · série 20 — Septembre 2026 · Partie 4 · Sujet 5
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 20,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Travail et Emploi",
                "situation": "Je suis votre professeur(e) de français. Vous envisagez de travailler au Canada pendant l'été. Vous me demandez des informations pour savoir comment trouver un travail.",
                "hints": "régions, activités, rémunération, etc."},
     "tache3": {"theme": "Consommation et Technologie",
                "question": "Qu'est-ce qui encourage les gens à remplacer leur téléphone portable fréquemment ?"}},
    # Septembre 2026 · série 21 — Septembre 2026 · Partie 5 · Sujet 1
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 21,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Transport et Services",
                "situation": "Je travaille dans une agence qui loue des bicyclettes. Vous désirez en louer une. Vous me demandez des renseignements.",
                "hints": "modèles disponibles, prix, utilisation, etc."},
     "tache3": {"theme": "Environnement",
                "question": "Quel est votre avis sur les actions prises dans votre pays pour diminuer la pollution ?"}},
    # Septembre 2026 · série 22 — Septembre 2026 · Partie 5 · Sujet 2
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 22,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Transport et Services",
                "situation": "Je suis votre ami(e) canadien(ne). Vous êtes nouvellement arrivé(e) dans ma ville et vous êtes hébergé(e) chez moi. Vous souhaitez vous promener en ville et vous me posez des questions sur les transports publics.",
                "hints": "types, trajets, horaires, prix, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "À votre avis, vivre de longues années à l'étranger fait-il oublier sa culture d'origine ? Expliquez."}},
    # Septembre 2026 · série 23 — Septembre 2026 · Partie 5 · Sujet 3
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 23,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Culture et Voyages",
                "situation": "Je suis votre ami(e) francophone. Vous devez rédiger un article sur une ville pour un magazine culturel. Vous cherchez de l'inspiration et vous me posez des questions sur les villes que j'apprécie.",
                "hints": "loisirs, bâtiments, moyens de transport, etc."},
     "tache3": {"theme": "Technologie et Famille",
                "question": "À votre avis, les jeux vidéo peuvent-ils nuire aux enfants ? Pourquoi ?"}},
    # Septembre 2026 · série 24 — Septembre 2026 · Partie 5 · Sujet 4
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 24,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Culture",
                "situation": "Je suis votre ami(e). Je mets en place un festival musical dans votre ville. Vous voulez y assister et vous me posez des questions pour en savoir plus.",
                "hints": "calendrier, horaires, artistes, tarifs, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Connaître le pays d'accueil est-il essentiel pour un immigrant ? Expliquez pourquoi."}},
    # Septembre 2026 · série 25 — Septembre 2026 · Partie 5 · Sujet 5
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 25,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Culture et Traditions",
                "situation": "Je suis votre enseignant(e) de français. Vous allez célébrer le prochain Nouvel An au Canada et vous voulez découvrir leurs façons de célébrer. Vous me demandez des renseignements pour mieux comprendre.",
                "hints": "endroits, animations, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Que recherchent les gens lorsqu'ils choisissent de vivre dans un autre pays ?"}},
    # Septembre 2026 · série 26 — Septembre 2026 · Partie 6 · Sujet 1
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 26,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Culture",
                "situation": "Je suis votre collègue. Je vous propose deux places pour un spectacle auquel je ne pourrai pas aller. Vous me posez des questions pour savoir si ce spectacle vous intéresse.",
                "hints": "date, lieu, spectacle, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Dans une entreprise, tout le monde devrait avoir le même salaire. Que pensez-vous de cette affirmation ?"}},
    # Septembre 2026 · série 27 — Septembre 2026 · Partie 6 · Sujet 2
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 27,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Consommation et Achats",
                "situation": "Je suis votre voisin(e). Je déménage bientôt à l'étranger. Je souhaite vendre mon mobilier (table, chaises, télé, canapé, etc.) avant mon départ. Vous me posez des questions pour savoir si certains meubles vous intéressent.",
                "hints": "prix, état, dimensions, etc."},
     "tache3": {"theme": "Santé et Société",
                "question": "Est-ce que vous pensez que l'État devrait interdire la vente de tabac et d'alcool ? Pourquoi ?"}},
    # Septembre 2026 · série 28 — Septembre 2026 · Partie 6 · Sujet 3
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 28,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Santé",
                "situation": "Je suis votre voisin(e). Vous venez de vous installer au Québec. Vous souhaitez prendre un rendez-vous médical. Vous me posez des questions pour obtenir des informations sur les médecins de la ville.",
                "hints": "lieux, tarifs, spécialisations, etc."},
     "tache3": {"theme": "Société et Relations",
                "question": "Il n'est pas nécessaire d'avoir des ami(e)s pour être heureux(se). Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 29 — Septembre 2026 · Partie 6 · Sujet 4
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 29,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je travaille dans un office du tourisme au Québec. Vous souhaitez visiter un parc à thème (aquarium, zoo, réserve naturelle, etc.). Vous me posez des questions pour obtenir des informations.",
                "hints": "horaires d'ouverture, tarifs, restauration, etc."},
     "tache3": {"theme": "Science et Technologie",
                "question": "Les voyages dans l'espace coûtent trop cher et sont inutiles. Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 30 — Septembre 2026 · Partie 6 · Sujet 5
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 30,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Transport et Services",
                "situation": "Je travaille dans une agence de location de voitures au Québec. Vous souhaitez louer une voiture pour vos vacances. Vous me posez des questions pour obtenir des informations.",
                "hints": "tarifs, conditions de location, documents demandés, etc."},
     "tache3": {"theme": "Technologie et Famille",
                "question": "À votre avis, l'usage des téléphones portables devrait-il être interdit aux enfants ? Pourquoi ?"}},
    # Septembre 2026 · série 31 — Septembre 2026 · Partie 7 · Sujet 1
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 31,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Relations",
                "situation": "Je suis un(e) ami(e) canadien(ne) que vous n'avez pas vu(e) depuis un long moment. Vous vous informez sur ma situation et vous m'interrogez sur ma vie quotidienne.",
                "hints": "emploi, proches, passe-temps, etc."},
     "tache3": {"theme": "Culture et Éducation",
                "question": "Selon vous, les livres ont-ils perdu leur utilité dans la société actuelle ?"}},
    # Septembre 2026 · série 32 — Septembre 2026 · Partie 7 · Sujet 2
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 32,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Services",
                "situation": "Je suis un(e) ami(e). J'ai un paquet à envoyer, mais je ne peux pas m'en occuper. Je vous sollicite pour m'aider. Vous me demandez des informations pour vérifier si vous pouvez le prendre en charge.",
                "hints": "délai, taille du colis, durée de la démarche, etc."},
     "tache3": {"theme": "Santé et Bien-être",
                "question": "Est-il possible de se passer de médicaments aujourd'hui ? Pourquoi ?"}},
    # Septembre 2026 · série 33 — Septembre 2026 · Partie 7 · Sujet 3
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 33,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie sociale et Fêtes",
                "situation": "Je suis un(e) ami(e). Je vous propose de venir célébrer l'anniversaire de ma sœur. Vous me demandez des renseignements sur elle afin de choisir un cadeau approprié.",
                "hints": "goûts, loisirs, personnalité, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Est-ce plus facile de s'adapter à un nouveau pays quand on est jeune ? Quel est votre avis ?"}},
    # Septembre 2026 · série 34 — Septembre 2026 · Partie 7 · Sujet 4
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 34,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Médias et Loisirs",
                "situation": "Je suis un(e) ami(e). Vous avez envie de commencer une série, mais vous êtes indécis(e). Vous me demandez des informations pour faire votre choix.",
                "hints": "catégorie, acteurs, plateforme de streaming, etc."},
     "tache3": {"theme": "Société et Famille",
                "question": "Selon vous, les prestations sociales réduisent-elles la solidarité entre les membres d'une famille ? Expliquez."}},
    # Septembre 2026 · série 35 — Septembre 2026 · Partie 7 · Sujet 5
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 35,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Immigration et Vie sociale",
                "situation": "Vous venez d'emménager au Canada. Je suis un collègue. Vous voulez faire de nouvelles connaissances et vous me demandez comment procéder.",
                "hints": "activités, endroits, sorties, etc."},
     "tache3": {"theme": "Éducation et Travail",
                "question": "Selon vous, est-il nécessaire de suivre de longues études pour réussir dans la vie ?"}},
    # Septembre 2026 · série 36 — Septembre 2026 · Partie 8 · Sujet 1
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 36,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Logement",
                "situation": "Je suis un(e) ami(e). Je déménage le week-end prochain. Vous allez m'aider et vous me demandez des informations pour organiser la journée.",
                "hints": "heure, lieu, transport, etc."},
     "tache3": {"theme": "Travail et Technologie",
                "question": "Pensez-vous que le téléphone portable personnel devrait être interdit au travail ?"}},
    # Septembre 2026 · série 37 — Septembre 2026 · Partie 8 · Sujet 2
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 37,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Vie sociale",
                "situation": "Je suis un(e) ami(e). J'utilise régulièrement une plateforme en ligne qui organise des sorties en groupe. Vous êtes intéressé(e) et vous me posez des questions pour en savoir plus.",
                "hints": "inscription, participants, activités, etc."},
     "tache3": {"theme": "Société et Solidarité",
                "question": "Les ONG et les associations sont-elles les seules capables d'aider les personnes pauvres ? Qu'en pensez-vous ?"}},
    # Septembre 2026 · série 38 — Septembre 2026 · Partie 8 · Sujet 3
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 38,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie sociale et Fêtes",
                "situation": "Je suis un(e) ami(e). Vous souhaitez offrir un cadeau à mon enfant pour son anniversaire. Vous me posez des questions pour choisir le bon cadeau.",
                "hints": "jeux, habitudes, préférences, etc."},
     "tache3": {"theme": "Éducation et Culture",
                "question": "Pensez-vous que les disciplines culturelles (musique, dessin, théâtre, etc.) ne devraient pas faire partie de l'enseignement scolaire ? Pourquoi ?"}},
    # Septembre 2026 · série 39 — Septembre 2026 · Partie 8 · Sujet 4
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 39,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Alimentation et Restauration",
                "situation": "Je suis employé(e) dans un restaurant. Vous voulez préparer un dîner avec vos collègues. Vous me posez des questions sur le lieu.",
                "hints": "menu, prix, ambiance, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Est-ce que maîtriser la langue du pays d'accueil est suffisant pour réussir son intégration ? Pourquoi ?"}},
    # Septembre 2026 · série 40 — Septembre 2026 · Partie 8 · Sujet 5
    {"month": "2026-09", "month_label": "Septembre 2026", "index": 40,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Logement",
                "situation": "Je suis employé(e) dans une agence immobilière au Canada. Vous cherchez un appartement. Vous me posez des questions pour vous renseigner.",
                "hints": "prix, conditions, procédures, etc."},
     "tache3": {"theme": "Médias et Éducation",
                "question": "Selon vous, la télévision est-elle indispensable à l'éducation des enfants ? Pourquoi ?"}},
    # Août 2026 · série 1 — Août 2026 · Partie 1 · Sujet 1
    {"month": "2026-08", "month_label": "Août 2026", "index": 1,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Consommation et Achats",
                "situation": "Je suis un(e) ami(e). Je m'installe à l'étranger et je ne peux pas transporter toutes mes affaires. J'ai mis certains objets en vente. Vous voulez en savoir plus et vous me posez des questions sur les articles à vendre.",
                "hints": "meubles, objets, tarifs, etc."},
     "tache3": {"theme": "Famille et Éducation",
                "question": "Certains parents donnent de l'argent à leurs enfants quand ils réussissent bien à l'école. Qu'en pensez-vous ?"}},
    # Août 2026 · série 2 — Août 2026 · Partie 1 · Sujet 2
    {"month": "2026-08", "month_label": "Août 2026", "index": 2,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis un(e) ami(e). Vous recevrez prochainement des amis qui ne connaissent pas votre ville. Vous me posez des questions pour les aider à organiser leur séjour.",
                "hints": "restaurants, visites, sorties, etc."},
     "tache3": {"theme": "Environnement et Économie",
                "question": "Pensez-vous qu'il soit possible de développer l'économie tout en préservant l'environnement ?"}},
    # Août 2026 · série 3 — Août 2026 · Partie 1 · Sujet 3
    {"month": "2026-08", "month_label": "Août 2026", "index": 3,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie sociale et Fêtes",
                "situation": "Je suis un(e) collègue. J'ai participé à un mariage ce week-end. Vous voulez savoir comment s'est déroulée la cérémonie.",
                "hints": "repas, lieu, ambiance, etc."},
     "tache3": {"theme": "Culture et Voyages",
                "question": "Est-il possible de connaître un pays uniquement en lisant des livres ? Pourquoi ?"}},
    # Août 2026 · série 4 — Août 2026 · Partie 1 · Sujet 4
    {"month": "2026-08", "month_label": "Août 2026", "index": 4,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis un(e) collègue. J'ai réalisé un tour touristique au Canada. Vous voulez faire la même expérience l'été prochain et me posez des questions sur le voyage.",
                "hints": "coût, étapes, temps, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Pour bien s'intégrer dans un nouveau pays, faudrait-il renoncer à ses traditions ? Qu'en pensez-vous ?"}},
    # Août 2026 · série 5 — Août 2026 · Partie 1 · Sujet 5
    {"month": "2026-08", "month_label": "Août 2026", "index": 5,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Services",
                "situation": "Je vis dans votre quartier. Je vais partir en vacances une semaine et j'ai besoin que quelqu'un garde mon chien. Vous souhaitez m'aider et vous me demandez des informations.",
                "hints": "durée, soins, paiement, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Selon vous, est-il important qu'une entreprise privilégie le bien-être de ses salariés pour être efficace ?"}},
    # Août 2026 · série 6 — Août 2026 · Partie 2 · Sujet 1
    {"month": "2026-08", "month_label": "Août 2026", "index": 6,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Travail et Emploi",
                "situation": "Je suis votre ami(e). Vous cherchez un emploi et vous avez un entretien prochainement, vous me demandez comment le réussir.",
                "hints": "tenue, comportement, préparation, etc."},
     "tache3": {"theme": "Médias et Télévision",
                "question": "Que pensez-vous des gens qui décident de ne jamais regarder la télévision ?"}},
    # Août 2026 · série 7 — Août 2026 · Partie 2 · Sujet 2
    {"month": "2026-08", "month_label": "Août 2026", "index": 7,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Services",
                "situation": "Je suis votre voisin(e). Je m'absente en vacances et je cherche quelqu'un pour s'occuper de mon animal. Vous voulez en savoir plus avant d'accepter.",
                "hints": "dates, soins, règles, etc."},
     "tache3": {"theme": "Sport et Société",
                "question": "Certains pensent que les salaires des sportifs professionnels sont excessifs. Êtes-vous d'accord ?"}},
    # Août 2026 · série 8 — Août 2026 · Partie 2 · Sujet 3
    {"month": "2026-08", "month_label": "Août 2026", "index": 8,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je travaille à l'office de tourisme. Vous souhaitez planifier un week-end à prix réduit et vous me demandez des suggestions.",
                "hints": "activités, lieux à visiter, transports, etc."},
     "tache3": {"theme": "Technologie et Famille",
                "question": "Croyez-vous que les enfants restent trop longtemps devant les écrans (TV, téléphone, ordinateur, tablette) ? Pourquoi ?"}},
    # Août 2026 · série 9 — Août 2026 · Partie 2 · Sujet 4
    {"month": "2026-08", "month_label": "Août 2026", "index": 9,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Sport et Santé",
                "situation": "Je travaille à l'accueil d'un club sportif de la ville. Vous envisagez de vous inscrire et vous me posez des questions.",
                "hints": "horaires, types de cours, tarifs, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Quand on vit dans un nouveau pays, faut-il adapter son mode de vie (habits, nourriture, vacances, etc.) ?"}},
    # Août 2026 · série 10 — Août 2026 · Partie 2 · Sujet 5
    {"month": "2026-08", "month_label": "Août 2026", "index": 10,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Logement et Immigration",
                "situation": "Nous sommes amis et vous envisagez de vous installer au Canada. Je vous suggère de vivre avec moi en colocation à Toronto. Vous me demandez des informations pour décider si c'est une bonne solution pour vous.",
                "hints": "logement, quartier, routine, etc."},
     "tache3": {"theme": "Travail et Immigration",
                "question": "Serait-il simple de trouver un travail si vous vous installiez au Canada ? Pourquoi ?"}},
    # Août 2026 · série 11 — Août 2026 · Partie 3 · Sujet 1
    {"month": "2026-08", "month_label": "Août 2026", "index": 11,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Sport et Santé",
                "situation": "Je suis un(e) collègue. J'organise souvent des sorties de jogging en groupe. Vous souhaitez y participer et vous me posez des questions pour obtenir des informations.",
                "hints": "itinéraire, horaires, équipement, niveau, etc."},
     "tache3": {"theme": "Consommation et Technologie",
                "question": "Le développement des achats sur Internet pourrait-il entraîner la disparition des magasins physiques ? Quel est votre avis ?"}},
    # Août 2026 · série 12 — Août 2026 · Partie 3 · Sujet 2
    {"month": "2026-08", "month_label": "Août 2026", "index": 12,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Vie sociale",
                "situation": "Je suis employé(e) au service des activités de votre nouvelle ville. Vous cherchez une activité pour faire de nouvelles connaissances. Vous me posez des questions afin d'obtenir des renseignements.",
                "hints": "type d'activité, horaires, participants, etc."},
     "tache3": {"theme": "Société et Jeunesse",
                "question": "Pensez-vous que les jeunes s'impliquent moins aujourd'hui dans des domaines comme l'environnement, la politique ou la santé ? Pourquoi ?"}},
    # Août 2026 · série 13 — Août 2026 · Partie 3 · Sujet 3
    {"month": "2026-08", "month_label": "Août 2026", "index": 13,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Alimentation et Restauration",
                "situation": "Je suis employé(e) dans un restaurant. Vous envisagez d'y organiser une fête d'anniversaire familiale. Vous me posez des questions pour obtenir des renseignements.",
                "hints": "capacité d'accueil, menus proposés, tarifs, modalités de réservation, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Selon vous, devrait-on obliger toutes les personnes pouvant travailler depuis chez elles à pratiquer le télétravail ? Pourquoi ?"}},
    # Août 2026 · série 14 — Août 2026 · Partie 3 · Sujet 4
    {"month": "2026-08", "month_label": "Août 2026", "index": 14,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Consommation et Technologie",
                "situation": "Je suis employé(e) dans un magasin de téléphones. Vous cherchez un premier smartphone pour un enfant. Vous me posez des questions afin d'obtenir des informations sur les produits disponibles.",
                "hints": "appareils, accessoires, prix, etc."},
     "tache3": {"theme": "Éducation et Travail",
                "question": "Est-il nécessaire de faire de longues études pour réussir dans sa vie professionnelle ? Quel est votre avis ?"}},
    # Août 2026 · série 15 — Août 2026 · Partie 3 · Sujet 5
    {"month": "2026-08", "month_label": "Août 2026", "index": 15,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Tourisme",
                "situation": "Je suis employé(e) à l'accueil d'un parc de divertissement. Vous souhaitez y passer une journée et vous me posez des questions pour vous renseigner.",
                "hints": "tarifs, heures d'ouverture, activités, services, etc."},
     "tache3": {"theme": "Immigration et Jeunesse",
                "question": "Vivre plusieurs mois dans un pays étranger est-il nécessaire pour aider les jeunes à devenir indépendants ? Êtes-vous d'accord ?"}},
    # Août 2026 · série 16 — Août 2026 · Partie 4 · Sujet 1
    {"month": "2026-08", "month_label": "Août 2026", "index": 16,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Alimentation et Culture",
                "situation": "Je suis un(e) ami(e). Vous voulez faire goûter des spécialités québécoises à des amis. Vous me demandez des idées pour préparer ce repas.",
                "hints": "endroit, menu, coût, etc."},
     "tache3": {"theme": "Éducation et Travail",
                "question": "Pour quelles raisons le métier de professeur peut-il paraître difficile ou impressionnant ?"}},
    # Août 2026 · série 17 — Août 2026 · Partie 4 · Sujet 2
    {"month": "2026-08", "month_label": "Août 2026", "index": 17,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Formation",
                "situation": "Je suis un(e) ami(e). Je connais quelqu'un qui enseigne la cuisine. Vous souhaitez en savoir plus et vous me demandez des renseignements sur cette personne.",
                "hints": "compétences, horaires, prix, etc."},
     "tache3": {"theme": "Société et Bien-être",
                "question": "Les animaux de compagnie peuvent-ils rendre les personnes plus heureuses ? Pourquoi ?"}},
    # Août 2026 · série 18 — Août 2026 · Partie 4 · Sujet 3
    {"month": "2026-08", "month_label": "Août 2026", "index": 18,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Culture",
                "situation": "Je suis un(e) ami(e). Vous êtes arrivé(e) récemment au Québec. Vous me demandez des idées pour organiser une activité culturelle à petit budget.",
                "hints": "endroits, activités, moyens de transport, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Selon vous, que doit faire un jeune pour trouver un emploi ?"}},
    # Août 2026 · série 19 — Août 2026 · Partie 4 · Sujet 4
    {"month": "2026-08", "month_label": "Août 2026", "index": 19,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Logement",
                "situation": "Je suis un(e) colocataire. J'ai prévu d'inviter quelques amis chez nous. Vous me demandez des renseignements sur cette visite.",
                "hints": "nombre d'invités, durée, ambiance, etc."},
     "tache3": {"theme": "Société et Enjeux mondiaux",
                "question": "Quel problème mondial est le plus important aujourd'hui ? Pourquoi ?"}},
    # Août 2026 · série 20 — Août 2026 · Partie 4 · Sujet 5
    {"month": "2026-08", "month_label": "Août 2026", "index": 20,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie sociale et Fêtes",
                "situation": "Je suis un(e) voisin(e). Je prépare une soirée entre les habitants de l'immeuble et je vous propose d'y participer. Vous me demandez des renseignements sur l'événement.",
                "hints": "date, invités, repas, boissons, etc."},
     "tache3": {"theme": "Travail et Société",
                "question": "À votre avis, jusqu'à quel âge est-il raisonnable de travailler ? Expliquez."}},
    # Juillet 2026 · série 1 — Juillet 2026 · Partie 1 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 1,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Consommation et Achats",
                "situation": "Je suis un(e) ami(e). Je m'installe à l'étranger et je ne peux pas transporter toutes mes affaires. J'ai mis certains objets en vente. Vous voulez en savoir plus et vous me posez des questions sur les articles à vendre.",
                "hints": "meubles, objets, tarifs, etc."},
     "tache3": {"theme": "Famille et Éducation",
                "question": "Certains parents donnent de l'argent à leurs enfants quand ils réussissent bien à l'école. Qu'en pensez-vous ?"}},
    # Juillet 2026 · série 2 — Juillet 2026 · Partie 1 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 2,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis un(e) ami(e). Vous recevrez prochainement des amis qui ne connaissent pas votre ville. Vous me posez des questions pour les aider à organiser leur séjour.",
                "hints": "restaurants, visites, sorties, etc."},
     "tache3": {"theme": "Environnement et Économie",
                "question": "Pensez-vous qu'il soit possible de développer l'économie tout en préservant l'environnement ?"}},
    # Juillet 2026 · série 3 — Juillet 2026 · Partie 1 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 3,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie sociale et Fêtes",
                "situation": "Je suis un(e) collègue. J'ai participé à un mariage ce week-end. Vous voulez savoir comment s'est déroulée la cérémonie.",
                "hints": "repas, lieu, ambiance, etc."},
     "tache3": {"theme": "Culture et Voyages",
                "question": "Est-il possible de connaître un pays uniquement en lisant des livres ? Pourquoi ?"}},
    # Juillet 2026 · série 4 — Juillet 2026 · Partie 1 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 4,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis un(e) collègue. J'ai réalisé un tour touristique au Canada. Vous voulez faire la même expérience l'été prochain et me posez des questions sur le voyage.",
                "hints": "coût, étapes, temps, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Pour bien s'intégrer dans un nouveau pays, faudrait-il renoncer à ses traditions ? Qu'en pensez-vous ?"}},
    # Juillet 2026 · série 5 — Juillet 2026 · Partie 1 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 5,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Services",
                "situation": "Je vis dans votre quartier. Je vais partir en vacances une semaine et j'ai besoin que quelqu'un garde mon chien. Vous souhaitez m'aider et vous me demandez des informations.",
                "hints": "durée, soins, paiement, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Selon vous, est-il important qu'une entreprise privilégie le bien-être de ses salariés pour être efficace ?"}},
    # Juillet 2026 · série 6 — Juillet 2026 · Partie 2 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 6,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Travail et Emploi",
                "situation": "Je suis un(e) ami(e). Vous souhaitez connaître comment s'est passée ma première journée dans mon nouveau poste.",
                "hints": "ambiance, personnels, missions, etc."},
     "tache3": {"theme": "Immigration et Travail",
                "question": "Pensez-vous que l'expérience de la vie à l'étranger aide à réussir professionnellement ?"}},
    # Juillet 2026 · série 7 — Juillet 2026 · Partie 2 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 7,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Formation",
                "situation": "Je suis un(e) voisin(e). Une personne que je connais propose des cours de musique à la maison. Vous voulez en savoir plus et me posez des questions.",
                "hints": "prix, horaires, expérience, etc."},
     "tache3": {"theme": "Tourisme et Économie",
                "question": "Pensez-vous que le tourisme puisse favoriser le développement dans tous les pays ? Pourquoi ?"}},
    # Juillet 2026 · série 8 — Juillet 2026 · Partie 2 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 8,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Vie sociale",
                "situation": "Je suis un(e) voisin(e). Vous voulez passer une journée à la campagne avec vos amis et vous me posez des questions pour bien organiser la sortie.",
                "hints": "transport, activités, endroit, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Pensez-vous qu'il est compliqué de s'adapter dans un pays étranger ? Pourquoi ?"}},
    # Juillet 2026 · série 9 — Juillet 2026 · Partie 2 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 9,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Consommation et Services",
                "situation": "Je travaille dans une épicerie. Vous voulez que vos courses soient livrées chez vous et vous me demandez des informations.",
                "hints": "prix, délais, type de livraison, etc."},
     "tache3": {"theme": "Éducation et Langues",
                "question": "Est-il mieux d'apprendre une langue étrangère dès l'enfance ? Pourquoi ?"}},
    # Juillet 2026 · série 10 — Juillet 2026 · Partie 2 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 10,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Logement",
                "situation": "Je travaille dans une agence immobilière. Vous voulez mettre votre appartement en location pour les vacances pour augmenter vos revenus et vous me posez des questions.",
                "hints": "tarifs, période de location, type de locataires, etc."},
     "tache3": {"theme": "Médias et Société",
                "question": "Pourquoi, selon vous, les gens s'intéressent-ils à la vie des célébrités ?"}},
    # Juillet 2026 · série 11 — Juillet 2026 · Partie 3 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 11,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Logement",
                "situation": "Je suis un(e) voisin(e). Vous venez d'emménager dans l'immeuble et nous faisons connaissance dans l'ascenseur. Posez-moi des questions.",
                "hints": "quartier, magasins, activités, etc."},
     "tache3": {"theme": "Travail et Immigration",
                "question": "Pensez-vous qu'il soit simple de trouver un emploi à l'étranger ? Êtes-vous d'accord ?"}},
    # Juillet 2026 · série 12 — Juillet 2026 · Partie 3 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 12,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Logement",
                "situation": "Je suis agent immobilier. Vous souhaitez louer un chalet près de la mer pour vos vacances. Posez-moi des questions.",
                "hints": ""},
     "tache3": {"theme": "Santé et Bien-être",
                "question": "Le stress peut-il encourager une personne à donner le meilleur d'elle-même ? Expliquez."}},
    # Juillet 2026 · série 13 — Juillet 2026 · Partie 3 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 13,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Éducation et Immigration",
                "situation": "Je suis un(e) voisin(e). Vous venez de vous installer au Canada et vous souhaitez inscrire vos enfants dans une école. Posez-moi des questions.",
                "hints": ""},
     "tache3": {"theme": "Famille et Éducation",
                "question": "Est-il utile d'imposer des règles strictes à ses enfants ? Donnez votre avis."}},
    # Juillet 2026 · série 14 — Juillet 2026 · Partie 3 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 14,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Logement",
                "situation": "Je suis un(e) collègue. Je mets une chambre en colocation à votre disposition et cela vous intéresse. Posez-moi des questions.",
                "hints": ""},
     "tache3": {"theme": "Alimentation et Culture",
                "question": "Comment jugez-vous la cuisine et la nourriture dans votre pays ?"}},
    # Juillet 2026 · série 15 — Juillet 2026 · Partie 3 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 15,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Formation",
                "situation": "Je suis employé(e) à l'accueil d'une école de danse. Vous cherchez des informations sur les cours de danse. Posez-moi des questions.",
                "hints": ""},
     "tache3": {"theme": "Médias et Éducation",
                "question": "Pensez-vous que la télévision contribue à l'éveil et à l'apprentissage des enfants ? Êtes-vous d'accord ?"}},
    # Juillet 2026 · série 16 — Juillet 2026 · Partie 4 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 16,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Alimentation et Culture",
                "situation": "Je suis un(e) ami(e). Vous voulez faire goûter des spécialités québécoises à des amis. Vous me demandez des idées pour préparer ce repas.",
                "hints": "endroit, menu, coût, etc."},
     "tache3": {"theme": "Éducation et Travail",
                "question": "Pour quelles raisons le métier de professeur peut-il paraître difficile ou impressionnant ?"}},
    # Juillet 2026 · série 17 — Juillet 2026 · Partie 4 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 17,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Formation",
                "situation": "Je suis un(e) ami(e). Je connais quelqu'un qui enseigne la cuisine. Vous souhaitez en savoir plus et vous me demandez des renseignements sur cette personne.",
                "hints": "compétences, horaires, prix, etc."},
     "tache3": {"theme": "Société et Bien-être",
                "question": "Les animaux de compagnie peuvent-ils rendre les personnes plus heureuses ? Pourquoi ?"}},
    # Juillet 2026 · série 18 — Juillet 2026 · Partie 4 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 18,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Culture",
                "situation": "Je suis un(e) ami(e). Vous êtes arrivé(e) récemment au Québec. Vous me demandez des idées pour organiser une activité culturelle à petit budget.",
                "hints": "endroits, activités, moyens de transport, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Selon vous, que doit faire un jeune pour trouver un emploi ?"}},
    # Juillet 2026 · série 19 — Juillet 2026 · Partie 4 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 19,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Logement",
                "situation": "Je suis un(e) colocataire. J'ai prévu d'inviter quelques amis chez nous. Vous me demandez des renseignements sur cette visite.",
                "hints": "nombre d'invités, durée, ambiance, etc."},
     "tache3": {"theme": "Société et Enjeux mondiaux",
                "question": "Quel problème mondial est le plus important aujourd'hui ? Pourquoi ?"}},
    # Juillet 2026 · série 20 — Juillet 2026 · Partie 4 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 20,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie sociale et Fêtes",
                "situation": "Je suis un(e) voisin(e). Je prépare une soirée entre les habitants de l'immeuble et je vous propose d'y participer. Vous me demandez des renseignements sur l'événement.",
                "hints": "date, invités, repas, boissons, etc."},
     "tache3": {"theme": "Travail et Société",
                "question": "À votre avis, jusqu'à quel âge est-il raisonnable de travailler ? Expliquez."}},
    # Juillet 2026 · série 21 — Juillet 2026 · Partie 5 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 21,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Éducation et Vie scolaire",
                "situation": "Je suis parent d'un élève et nos enfants fréquentent la même école. Vous assistez à la fête de l'école pour la première fois et vous me demandez des informations sur l'événement.",
                "hints": "programme, horaires, animations, etc."},
     "tache3": {"theme": "Environnement",
                "question": "Selon vous, doit-on protéger tous les animaux en voie de disparition ? Pourquoi ?"}},
    # Juillet 2026 · série 22 — Juillet 2026 · Partie 5 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 22,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Logement",
                "situation": "Je suis un(e) ami(e) et je vis dans une grande ville. Vous souhaitez louer un logement ici. Vous me demandez des informations.",
                "hints": "offres disponibles, prix, quartier, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "L'essentiel dans la vie est-il de trouver du bonheur au travail ? Qu'en pensez-vous ?"}},
    # Juillet 2026 · série 23 — Juillet 2026 · Partie 5 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 23,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Sport et Santé",
                "situation": "Je suis employé(e) dans un club de sport. Vous souhaitez vous inscrire à une activité physique. Vous me demandez des renseignements pour faire votre choix.",
                "hints": "sports disponibles, horaires, coût, etc."},
     "tache3": {"theme": "Culture et Éducation",
                "question": "Selon vous, lire est-il une activité inutile ? Pourquoi ?"}},
    # Juillet 2026 · série 24 — Juillet 2026 · Partie 5 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 24,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis employé(e) dans une agence de voyages. Vous voulez planifier vos vacances et vous me demandez des informations.",
                "hints": "coût, destinations, activités, etc."},
     "tache3": {"theme": "Société et Mode de vie",
                "question": "Pensez-vous que l'on puisse être épanoui en vivant seul ? Pourquoi ?"}},
    # Juillet 2026 · série 25 — Juillet 2026 · Partie 5 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 25,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Culture",
                "situation": "Je suis employé(e) à la ludothèque de votre ville. Vous souhaitez adhérer et vous me posez des questions.",
                "hints": "horaires, prix, jeux disponibles, etc."},
     "tache3": {"theme": "Santé et Bien-être",
                "question": "Le plus important pour conserver la santé est-il de bien se nourrir ? Qu'en pensez-vous ?"}},
    # Juillet 2026 · série 26 — Juillet 2026 · Partie 6 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 26,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Culture et Loisirs",
                "situation": "Je suis un(e) ami(e) francophone. Vous devez préparer un article sur un film pour le journal de votre association culturelle. Vous cherchez des idées. Vous me posez des questions sur les films que j'ai aimés.",
                "hints": "endroit, genre, prix, etc."},
     "tache3": {"theme": "Voyages et Mode de vie",
                "question": "Que pensez-vous des personnes qui choisissent de voyager seules ?"}},
    # Juillet 2026 · série 27 — Juillet 2026 · Partie 6 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 27,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je travaille dans une agence de voyages. Vous voulez préparer des vacances. Vous venez me voir et vous me demandez des renseignements sur les lieux proposés.",
                "hints": "activités, visites, prix, etc."},
     "tache3": {"theme": "Travail et Société",
                "question": "Vaut-il mieux travailler sous la responsabilité d'un homme ou d'une femme ?"}},
    # Juillet 2026 · série 28 — Juillet 2026 · Partie 6 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 28,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie sociale et Fêtes",
                "situation": "Je suis votre voisin(e). Vous souhaitez organiser une rencontre conviviale entre habitants de l'immeuble. Vous me posez des questions pour avoir des idées.",
                "hints": "animations, invités, repas, etc."},
     "tache3": {"theme": "Technologie et Famille",
                "question": "Pensez-vous que les jeux vidéo peuvent participer à l'évolution d'un enfant ?"}},
    # Juillet 2026 · série 29 — Juillet 2026 · Partie 6 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 29,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Immigration et Vie sociale",
                "situation": "Je suis un(e) voisin(e). Vous vous êtes récemment installé(e) dans la ville et vous n'avez pas encore de relations. Vous me posez des questions pour savoir comment faire des connaissances.",
                "hints": ""},
     "tache3": {"theme": "Tourisme et Économie",
                "question": "Pourquoi est-il important de développer le tourisme dans un pays ?"}},
    # Juillet 2026 · série 30 — Juillet 2026 · Partie 6 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 30,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Travail et Emploi",
                "situation": "Vous souhaitez connaître le rythme professionnel au Canada. Vous me demandez des informations sur les heures de travail et les vacances. Puis, vous faites une comparaison avec votre pays.",
                "hints": ""},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Pensez-vous que vivre dans un pays étranger soit difficile ?"}},
    # Juillet 2026 · série 31 — Juillet 2026 · Partie 7 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 31,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Société et Bénévolat",
                "situation": "Je fais partie d'une association qui protège les animaux. Je vous invite à nous rejoindre. Vous me posez des questions pour mieux connaître cette association.",
                "hints": "activités, services, personnes aidées, etc."},
     "tache3": {"theme": "Éducation et Travail",
                "question": "Pensez-vous que réussir dans sa carrière dépend du niveau d'études et des diplômes ? Pourquoi ?"}},
    # Juillet 2026 · série 32 — Juillet 2026 · Partie 7 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 32,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Culture et Loisirs",
                "situation": "Nous sommes collègues. Je viens de voir un film au cinéma. Vous me posez des questions sur ce film pour savoir si vous voulez y aller.",
                "hints": "acteurs, histoire, horaires, etc."},
     "tache3": {"theme": "Travail et Société",
                "question": "Selon vous, le travail des personnes âgées est-il utile pour la société ?"}},
    # Juillet 2026 · série 33 — Juillet 2026 · Partie 7 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 33,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Immigration et Parcours",
                "situation": "Je suis votre nouveau collègue. J'ai vécu au Québec et maintenant je vis dans votre pays. Vous me posez des questions sur mon parcours.",
                "hints": "études, début de travail, expériences à l'étranger, difficultés, etc."},
     "tache3": {"theme": "Société et Solidarité",
                "question": "Certaines personnes donnent de leur temps libre pour faire du bénévolat. Qu'en pensez-vous ?"}},
    # Juillet 2026 · série 34 — Juillet 2026 · Partie 7 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 34,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Logement",
                "situation": "Je travaille dans une agence immobilière. Vous venez d'arriver au Québec et cherchez un logement. Vous me posez des questions sur la recherche d'appartement.",
                "hints": "procédures, quartiers, types de logement, etc."},
     "tache3": {"theme": "Culture et Loisirs",
                "question": "Entre le théâtre et le cinéma, que préférez-vous et pourquoi ?"}},
    # Juillet 2026 · série 35 — Juillet 2026 · Partie 7 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 35,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Culture et Services",
                "situation": "Je suis bibliothécaire. Vous voulez vous inscrire à la bibliothèque. Vous me posez des questions pour mieux comprendre comment ça fonctionne.",
                "hints": "inscription, activités, horaires, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "À votre avis, quel est le meilleur âge pour partir vivre à l'étranger ? Expliquez."}},
    # Juillet 2026 · série 36 — Juillet 2026 · Partie 8 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 36,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Travail et Emploi",
                "situation": "Je suis votre ami(e). Vous cherchez un emploi et vous avez un entretien prochainement, vous me demandez comment le réussir.",
                "hints": "tenue, comportement, préparation, etc."},
     "tache3": {"theme": "Médias et Télévision",
                "question": "Que pensez-vous des gens qui décident de ne jamais regarder la télévision ?"}},
    # Juillet 2026 · série 37 — Juillet 2026 · Partie 8 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 37,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Vie quotidienne et Services",
                "situation": "Je suis votre voisin(e). Je m'absente en vacances et je cherche quelqu'un pour s'occuper de mon animal. Vous voulez en savoir plus avant d'accepter.",
                "hints": "dates, soins, règles, etc."},
     "tache3": {"theme": "Sport et Société",
                "question": "Certains pensent que les salaires des sportifs professionnels sont excessifs. Êtes-vous d'accord ?"}},
    # Juillet 2026 · série 38 — Juillet 2026 · Partie 8 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 38,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je travaille à l'office de tourisme. Vous souhaitez planifier un week-end à prix réduit et vous me demandez des suggestions.",
                "hints": "activités, lieux à visiter, transports, etc."},
     "tache3": {"theme": "Technologie et Famille",
                "question": "Croyez-vous que les enfants restent trop longtemps devant les écrans (TV, téléphone, ordinateur, tablette) ? Pourquoi ?"}},
    # Juillet 2026 · série 39 — Juillet 2026 · Partie 8 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 39,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Sport et Santé",
                "situation": "Je travaille à l'accueil d'un club sportif de la ville. Vous envisagez de vous inscrire et vous me posez des questions.",
                "hints": "horaires, types de cours, tarifs, etc."},
     "tache3": {"theme": "Immigration et Intégration",
                "question": "Quand on vit dans un nouveau pays, faut-il adapter son mode de vie (habits, nourriture, vacances, etc.) ?"}},
    # Juillet 2026 · série 40 — Juillet 2026 · Partie 8 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 40,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Logement et Immigration",
                "situation": "Nous sommes amis et vous envisagez de vous installer au Canada. Je vous suggère de vivre avec moi en colocation à Toronto. Vous me demandez des informations pour décider si c'est une bonne solution pour vous.",
                "hints": "logement, quartier, routine, etc."},
     "tache3": {"theme": "Travail et Immigration",
                "question": "Serait-il simple de trouver un travail si vous vous installiez au Canada ? Pourquoi ?"}},
    # Juillet 2026 · série 41 — Juillet 2026 · Partie 9 · Sujet 1
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 41,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Alimentation et Services",
                "situation": "Je propose mes services de cuisine à domicile. Vous organisez un dîner familial et vous me demandez des renseignements concernant mes services.",
                "hints": "menus proposés, prix, équipements, etc."},
     "tache3": {"theme": "Immigration et Jeunesse",
                "question": "Pensez-vous qu'il soit plus facile pour les jeunes de vivre à l'étranger ? Pourquoi ?"}},
    # Juillet 2026 · série 42 — Juillet 2026 · Partie 9 · Sujet 2
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 42,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Transport et Services",
                "situation": "Je suis un(e) voisin(e) et je prends souvent la voiture pour mes déplacements. Je vous suggère de faire du covoiturage ensemble. Vous êtes intéressé(e) et vous me demandez des précisions.",
                "hints": "horaires, coût, organisation, etc."},
     "tache3": {"theme": "Travail et Emploi",
                "question": "Pensez-vous que le travail à distance aide vraiment à mieux équilibrer la vie professionnelle et la vie privée ?"}},
    # Juillet 2026 · série 43 — Juillet 2026 · Partie 9 · Sujet 3
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 43,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Loisirs et Formation",
                "situation": "Je suis employé(e) à l'accueil d'une école de musique. Vous désirez suivre des cours et vous me demandez des renseignements.",
                "hints": "tarifs, horaires, instruments, etc."},
     "tache3": {"theme": "Société et Sécurité",
                "question": "La présence de caméras dans les lieux publics permet-elle réellement d'améliorer la sécurité ? Qu'en pensez-vous ?"}},
    # Juillet 2026 · série 44 — Juillet 2026 · Partie 9 · Sujet 4
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 44,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Sport et Santé",
                "situation": "Je suis employé(e) à l'accueil d'un centre sportif. Vous désirez vous inscrire et vous me demandez des informations sur les différents sports disponibles.",
                "hints": "prix, disciplines, horaires, etc."},
     "tache3": {"theme": "Société et Mode de vie",
                "question": "L'habillement a-t-il une influence dans la vie de chaque jour ? Pourquoi ?"}},
    # Juillet 2026 · série 45 — Juillet 2026 · Partie 9 · Sujet 5
    {"month": "2026-07", "month_label": "Juillet 2026", "index": 45,
     "tache1": "Présentation du candidat — introduction personnelle.",
     "tache2": {"theme": "Voyages et Tourisme",
                "situation": "Je suis employé(e) à la réception d'un hôtel. Vous souhaitez faire une réservation et vous me demandez des renseignements.",
                "hints": "type de chambre, services, tarifs, etc."},
     "tache3": {"theme": "Environnement",
                "question": "Pensez-vous que les actions simples de chaque jour puissent réellement avoir un impact sur la protection de la planète ? Pourquoi ?"}},
]
