"""Compréhension écrite — Test 03.

Forty questions climbing A1 → C2. Profile A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Avis d'immeuble / Building notice",
        "topic": "Vie quotidienne & logement",
        "text": "AVIS\nDes travaux auront lieu dans la cour mardi et mercredi, de 8 h à 17 h.\nMerci de ne pas garer vos vélos sous les fenêtres.",
        "question_fr": "Que demande cet avis aux habitants ?",
        "options": [
            {"id": "a", "text": "De ne pas laisser leurs vélos dans la cour",
             "explanation": "« Merci de ne pas garer vos vélos sous les fenêtres » is the one instruction given."},
            {"id": "b", "text": "De rester chez eux mardi",
             "explanation": "Nobody is asked to stay in; only the bikes are mentioned."},
            {"id": "c", "text": "De fermer leurs fenêtres",
             "explanation": "The windows locate where the bikes must not be, not an action to perform."},
            {"id": "d", "text": "De payer les travaux",
             "explanation": "No cost or contribution appears on the notice."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Merci de ne pas garer vos vélos sous les fenêtres.",
        "key_line_en": "Please do not park your bikes under the windows.",
        "vocabulary": [
            {"term": "des travaux", "gloss": "building works"},
            {"term": "une cour", "gloss": "a courtyard"},
            {"term": "garer", "gloss": "to park"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Information transport / Transport information",
        "topic": "Transports & voyages",
        "text": "ARRÊT DÉPLACÉ\nL'arrêt « Mairie » est déplacé 100 mètres plus loin, devant la poste.\nDu 4 au 20 avril.",
        "question_fr": "Où se trouve l'arrêt maintenant ?",
        "options": [
            {"id": "a", "text": "À la mairie",
             "explanation": "« Mairie » is the stop's name; the stop itself has moved away from it."},
            {"id": "b", "text": "Devant la poste",
             "explanation": "« déplacé 100 mètres plus loin, devant la poste » gives the new location."},
            {"id": "c", "text": "À 100 mètres de la poste",
             "explanation": "The 100 metres measure the move, and the arrival point is the post office itself."},
            {"id": "d", "text": "Il n'y a plus d'arrêt",
             "explanation": "The stop still exists; it has only been moved."},
        ],
        "correct_answer": "b",
        "key_line_fr": "L'arrêt « Mairie » est déplacé 100 mètres plus loin, devant la poste.",
        "key_line_en": "The “Mairie” stop is moved 100 metres further on, in front of the post office.",
        "vocabulary": [
            {"term": "un arrêt", "gloss": "a stop"},
            {"term": "déplacer", "gloss": "to move"},
            {"term": "plus loin", "gloss": "further on"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Panneau de marché / Market sign",
        "topic": "Alimentation & consommation",
        "text": "MARCHÉ DE SAINT-JEAN\nMardi et samedi matin, de 7 h à 13 h.\nProduits de la région.",
        "question_fr": "Quand a lieu le marché ?",
        "options": [
            {"id": "a", "text": "Tous les jours",
             "explanation": "Only two days are listed: Tuesday and Saturday."},
            {"id": "b", "text": "Le samedi après-midi",
             "explanation": "The market runs in the morning and closes at 1 p.m."},
            {"id": "c", "text": "Le mardi et le samedi matin",
             "explanation": "« Mardi et samedi matin, de 7 h à 13 h » states both days and the time."},
            {"id": "d", "text": "Le mardi seulement",
             "explanation": "Saturday is listed too."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Mardi et samedi matin, de 7 h à 13 h.",
        "key_line_en": "Tuesday and Saturday morning, from 7 a.m. to 1 p.m.",
        "vocabulary": [
            {"term": "un marché", "gloss": "a market"},
            {"term": "la région", "gloss": "the local area"},
            {"term": "avoir lieu", "gloss": "to take place"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Mot du cabinet médical / Doctor's note",
        "topic": "Santé & bien-être",
        "text": "Le docteur Lemaire est absent du 10 au 17 mai.\nEn cas d'urgence, appelez le 15.\nLes rendez-vous sont reportés après le 17.",
        "question_fr": "Que faire en cas d'urgence pendant cette période ?",
        "options": [
            {"id": "a", "text": "Attendre le 17 mai",
             "explanation": "Waiting applies to ordinary appointments, not to emergencies."},
            {"id": "b", "text": "Aller au cabinet",
             "explanation": "The doctor is away, so the surgery is not the answer."},
            {"id": "c", "text": "Prendre un rendez-vous",
             "explanation": "Appointments are being postponed, which does not help an emergency."},
            {"id": "d", "text": "Téléphoner au 15",
             "explanation": "« En cas d'urgence, appelez le 15 » gives the emergency number directly."},
        ],
        "correct_answer": "d",
        "key_line_fr": "En cas d'urgence, appelez le 15.",
        "key_line_en": "In an emergency, call 15.",
        "vocabulary": [
            {"term": "une urgence", "gloss": "an emergency"},
            {"term": "absent", "gloss": "away"},
            {"term": "reporter", "gloss": "to postpone"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Carte de bibliothèque / Library card",
        "topic": "Études & formation",
        "text": "BIBLIOTHÈQUE UNIVERSITAIRE\nCarte gratuite pour les étudiants.\nPrésentez votre carte d'étudiant et une photo.\nInscription au bureau 2.",
        "question_fr": "Que faut-il apporter pour s'inscrire ?",
        "options": [
            {"id": "a", "text": "De l'argent",
             "explanation": "« Carte gratuite pour les étudiants » — there is nothing to pay."},
            {"id": "b", "text": "Une carte d'étudiant et une photo",
             "explanation": "« Présentez votre carte d'étudiant et une photo » lists exactly these two items."},
            {"id": "c", "text": "Un livre",
             "explanation": "No book is required to join."},
            {"id": "d", "text": "Une lettre du professeur",
             "explanation": "No letter or recommendation is mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Présentez votre carte d'étudiant et une photo.",
        "key_line_en": "Show your student card and a photograph.",
        "vocabulary": [
            {"term": "gratuit", "gloss": "free"},
            {"term": "présenter", "gloss": "to show"},
            {"term": "une inscription", "gloss": "registration"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Affiche de concert / Concert poster",
        "topic": "Loisirs, culture & médias",
        "text": "CONCERT DE JAZZ\nSamedi 18 juin, 20 h 30, parc municipal.\nEntrée libre.\nEn cas de pluie, le concert est annulé.",
        "question_fr": "Combien coûte l'entrée ?",
        "options": [
            {"id": "a", "text": "18 euros",
             "explanation": "18 is the date of the concert, not a price."},
            {"id": "b", "text": "20 euros",
             "explanation": "20 h 30 is the start time; there is no price in the poster."},
            {"id": "c", "text": "Rien",
             "explanation": "« Entrée libre » means admission is free."},
            {"id": "d", "text": "Le prix n'est pas indiqué",
             "explanation": "It is indicated — « Entrée libre » is the price information."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Entrée libre.",
        "key_line_en": "Free admission.",
        "vocabulary": [
            {"term": "entrée libre", "gloss": "free admission"},
            {"term": "la pluie", "gloss": "rain"},
            {"term": "annulé", "gloss": "cancelled"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Offre d'emploi / Job advert",
        "topic": "Travail & emploi",
        "text": "Boulangerie recherche un vendeur (H/F) à mi-temps.\nHoraires : 6 h – 12 h, du mercredi au dimanche.\nLe candidat doit habiter à proximité, aucun transport ne circule à cette heure.",
        "question_fr": "Pourquoi faut-il habiter près de la boulangerie ?",
        "options": [
            {"id": "a", "text": "Parce que les transports ne fonctionnent pas si tôt",
             "explanation": "« aucun transport ne circule à cette heure » — nothing runs at 6 a.m., so the employee must be able to get there without it."},
            {"id": "b", "text": "Parce que le poste est à mi-temps",
             "explanation": "Part-time hours say nothing about where someone lives."},
            {"id": "c", "text": "Parce qu'il faut travailler le dimanche",
             "explanation": "Sunday work is a condition of the job, not a reason to live nearby."},
            {"id": "d", "text": "Parce que le salaire est bas",
             "explanation": "No pay figure is given in the advert."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le candidat doit habiter à proximité, aucun transport ne circule à cette heure.",
        "key_line_en": "The candidate must live nearby; no transport runs at that hour.",
        "vocabulary": [
            {"term": "à mi-temps", "gloss": "part-time"},
            {"term": "à proximité", "gloss": "nearby"},
            {"term": "circuler", "gloss": "to run (of transport)"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Courriel d'agence / Agency e-mail",
        "topic": "Vie quotidienne & logement",
        "text": "Madame,\nLa visite de l'appartement est fixée jeudi à 17 h.\nMerci d'apporter vos trois derniers bulletins de salaire et une pièce d'identité.\nSans ces documents, le dossier ne pourra pas être étudié.",
        "question_fr": "Que se passe-t-il si les documents manquent ?",
        "options": [
            {"id": "a", "text": "La visite est annulée",
             "explanation": "The viewing still takes place; it is the application that cannot proceed."},
            {"id": "b", "text": "Le loyer augmente",
             "explanation": "No rent or price is mentioned."},
            {"id": "c", "text": "La candidature ne sera pas examinée",
             "explanation": "« Sans ces documents, le dossier ne pourra pas être étudié »."},
            {"id": "d", "text": "Il faut revenir vendredi",
             "explanation": "No second date is offered."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Sans ces documents, le dossier ne pourra pas être étudié.",
        "key_line_en": "Without these documents, the application cannot be considered.",
        "vocabulary": [
            {"term": "un bulletin de salaire", "gloss": "a payslip"},
            {"term": "un dossier", "gloss": "an application file"},
            {"term": "étudier un dossier", "gloss": "to consider an application"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Courrier de santé / Health letter",
        "topic": "Santé & bien-être",
        "text": "Madame, Monsieur,\nVous êtes invité(e) à un dépistage gratuit, sans rendez-vous, du 2 au 6 octobre.\nL'examen dure dix minutes. Munissez-vous de votre carte d'assurance maladie.\nCette invitation est personnelle et ne peut être transmise.",
        "question_fr": "Comment se déroule ce dépistage ?",
        "options": [
            {"id": "a", "text": "Il faut réserver à l'avance",
             "explanation": "« sans rendez-vous » — no booking is needed."},
            {"id": "b", "text": "Il faut payer sur place",
             "explanation": "The screening is « gratuit »."},
            {"id": "c", "text": "On peut y envoyer un proche",
             "explanation": "« Cette invitation est personnelle et ne peut être transmise »."},
            {"id": "d", "text": "On vient librement avec sa carte d'assurance",
             "explanation": "No appointment, ten minutes, and one document to bring: the health insurance card."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Un dépistage gratuit, sans rendez-vous […]. Munissez-vous de votre carte d'assurance maladie.",
        "key_line_en": "A free screening, no appointment needed […]. Bring your health insurance card.",
        "vocabulary": [
            {"term": "un dépistage", "gloss": "a screening test"},
            {"term": "sans rendez-vous", "gloss": "no appointment needed"},
            {"term": "se munir de", "gloss": "to bring"},
            {"term": "transmettre", "gloss": "to pass on"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Règlement de parking / Car park rules",
        "topic": "Transports & voyages",
        "text": "PARKING DE LA GARE\nLes trente premières minutes sont gratuites.\nEnsuite : 2 € par heure commencée, 18 € maximum par jour.\nLe ticket doit être payé à la borne avant de rejoindre son véhicule.",
        "question_fr": "Que paie un conducteur resté vingt minutes ?",
        "options": [
            {"id": "a", "text": "Rien",
             "explanation": "Twenty minutes falls inside the free first half-hour."},
            {"id": "b", "text": "2 euros",
             "explanation": "Charging starts only after the first thirty minutes."},
            {"id": "c", "text": "18 euros",
             "explanation": "€18 is the daily maximum, not a short-stay price."},
            {"id": "d", "text": "2 € par heure commencée",
             "explanation": "That rate applies from the thirty-first minute onwards."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les trente premières minutes sont gratuites.",
        "key_line_en": "The first thirty minutes are free.",
        "vocabulary": [
            {"term": "une heure commencée", "gloss": "each hour started"},
            {"term": "une borne", "gloss": "a payment terminal"},
            {"term": "rejoindre", "gloss": "to go back to"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Conditions de livraison / Delivery terms",
        "topic": "Alimentation & consommation",
        "text": "LIVRAISON DE COURSES\nGratuite à partir de 60 € d'achat, sinon 5 €.\nCréneaux de deux heures, à choisir au moment de la commande.\nLes produits frais sont livrés dans un sac isotherme, à rendre à la livraison suivante.",
        "question_fr": "Que doit faire le client du sac isotherme ?",
        "options": [
            {"id": "a", "text": "Le payer 5 €",
             "explanation": "The €5 is the delivery charge under €60, not the bag."},
            {"id": "b", "text": "Le garder",
             "explanation": "It is to be given back, not kept."},
            {"id": "c", "text": "Le rendre la fois suivante",
             "explanation": "« à rendre à la livraison suivante » states it directly."},
            {"id": "d", "text": "Le choisir à la commande",
             "explanation": "What is chosen at order time is the two-hour delivery slot."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les produits frais sont livrés dans un sac isotherme, à rendre à la livraison suivante.",
        "key_line_en": "Fresh items are delivered in a cool bag, to be returned at the next delivery.",
        "vocabulary": [
            {"term": "un créneau", "gloss": "a time slot"},
            {"term": "isotherme", "gloss": "insulated, cool (bag)"},
            {"term": "rendre", "gloss": "to give back"},
            {"term": "à partir de", "gloss": "from (an amount)"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Message d'application / App message",
        "topic": "Sciences & technologies",
        "text": "MISE À JOUR DISPONIBLE\nCette version corrige plusieurs erreurs et améliore la batterie.\nL'installation dure environ cinq minutes ; l'application sera indisponible pendant ce temps.\nVos données sont conservées.",
        "question_fr": "Que se passe-t-il pendant l'installation ?",
        "options": [
            {"id": "a", "text": "Les données sont effacées",
             "explanation": "« Vos données sont conservées » — nothing is lost."},
            {"id": "b", "text": "L'application ne fonctionne pas",
             "explanation": "« l'application sera indisponible pendant ce temps » — it is unavailable for about five minutes."},
            {"id": "c", "text": "La batterie se décharge",
             "explanation": "Battery life is what the update improves, not a side effect of installing it."},
            {"id": "d", "text": "Il faut redémarrer le téléphone",
             "explanation": "No restart is mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "L'application sera indisponible pendant ce temps.",
        "key_line_en": "The app will be unavailable during that time.",
        "vocabulary": [
            {"term": "une mise à jour", "gloss": "an update"},
            {"term": "indisponible", "gloss": "unavailable"},
            {"term": "conserver", "gloss": "to keep"},
            {"term": "corriger", "gloss": "to fix"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Annonce de club / Club announcement",
        "topic": "Loisirs, culture & médias",
        "text": "CLUB DE NATATION\nInscriptions ouvertes jusqu'au 15 septembre.\nDeux séances d'essai gratuites avant de s'engager.\nCertificat médical obligatoire pour la saison complète.",
        "question_fr": "Quand le certificat médical est-il nécessaire ?",
        "options": [
            {"id": "a", "text": "Dès la première séance d'essai",
             "explanation": "The trial sessions are free and come « avant de s'engager », before the season commitment."},
            {"id": "b", "text": "Jamais",
             "explanation": "It is described as « obligatoire » for the full season."},
            {"id": "c", "text": "Après le 15 septembre",
             "explanation": "15 September is the registration deadline, not a certificate date."},
            {"id": "d", "text": "Pour s'inscrire à la saison complète",
             "explanation": "« Certificat médical obligatoire pour la saison complète » ties it to the full membership."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Certificat médical obligatoire pour la saison complète.",
        "key_line_en": "A medical certificate is compulsory for the full season.",
        "vocabulary": [
            {"term": "une séance d'essai", "gloss": "a trial session"},
            {"term": "s'engager", "gloss": "to commit"},
            {"term": "un certificat médical", "gloss": "a medical certificate"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article de presse / Press article",
        "topic": "Environnement & nature",
        "text": "La ville a installé des composteurs au pied des immeubles, après deux ans de réunions avec les habitants.\n« Nous avons commencé par former des référents dans chaque cage d'escalier », explique la responsable. « Sans eux, les bacs se remplissent de plastique en une semaine. »",
        "question_fr": "Selon la responsable, qu'est-ce qui rend le dispositif viable ?",
        "options": [
            {"id": "a", "text": "Le nombre de composteurs installés",
             "explanation": "Quantity is never presented as the deciding factor; the human relay is."},
            {"id": "b", "text": "La présence d'habitants formés",
             "explanation": "« Sans eux, les bacs se remplissent de plastique en une semaine » — the trained référents are what keeps it working."},
            {"id": "c", "text": "La durée des réunions préparatoires",
             "explanation": "The two years of meetings are context, not the mechanism she credits."},
            {"id": "d", "text": "L'interdiction du plastique",
             "explanation": "No ban is mentioned; plastic is what turns up when nobody is watching."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Sans eux, les bacs se remplissent de plastique en une semaine.",
        "key_line_en": "Without them, the bins fill up with plastic in a week.",
        "vocabulary": [
            {"term": "un composteur", "gloss": "a compost bin"},
            {"term": "un référent", "gloss": "a designated contact person"},
            {"term": "une cage d'escalier", "gloss": "a stairwell"},
            {"term": "un bac", "gloss": "a bin, container"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "topic": "Travail & emploi",
        "text": "Interrogés sur le télétravail, les salariés se disent satisfaits à 78 %.\nLes managers, eux, ne sont que 41 % à l'être. L'écart ne porte pas sur la productivité, que les deux groupes jugent stable, mais sur la difficulté à intégrer les nouveaux arrivants.",
        "question_fr": "Sur quoi porte le désaccord entre salariés et managers ?",
        "options": [
            {"id": "a", "text": "Sur la productivité du télétravail",
             "explanation": "« L'écart ne porte pas sur la productivité, que les deux groupes jugent stable » — they agree there."},
            {"id": "b", "text": "Sur le nombre de jours à distance",
             "explanation": "No number of days is discussed anywhere."},
            {"id": "c", "text": "Sur l'accueil des nouveaux employés",
             "explanation": "The gap is « sur la difficulté à intégrer les nouveaux arrivants »."},
            {"id": "d", "text": "Sur le matériel fourni",
             "explanation": "Equipment is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "L'écart ne porte pas sur la productivité […] mais sur la difficulté à intégrer les nouveaux arrivants.",
        "key_line_en": "The gap is not about productivity […] but about the difficulty of integrating newcomers.",
        "vocabulary": [
            {"term": "un écart", "gloss": "a gap, difference"},
            {"term": "porter sur", "gloss": "to concern"},
            {"term": "intégrer", "gloss": "to bring in, integrate"},
            {"term": "un nouvel arrivant", "gloss": "a newcomer"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Présentation de formation / Course description",
        "topic": "Études & formation",
        "text": "Les cours du soir s'adressent à des adultes qui travaillent.\nLe rythme est volontairement lent : une matière par trimestre, deux heures par semaine. Mieux vaut terminer un module que d'en abandonner trois, rappelle la brochure.",
        "question_fr": "Pourquoi le rythme de la formation est-il lent ?",
        "options": [
            {"id": "a", "text": "Parce que les enseignants manquent",
             "explanation": "Staffing is never mentioned."},
            {"id": "b", "text": "Parce que les matières sont difficiles",
             "explanation": "Difficulty is not raised; the pace is about what working adults can sustain."},
            {"id": "c", "text": "Parce que les cours sont peu demandés",
             "explanation": "Demand is not discussed, and « volontairement » shows the pace is chosen, not imposed."},
            {"id": "d", "text": "Pour que les participants aillent au bout",
             "explanation": "« Mieux vaut terminer un module que d'en abandonner trois » — completion is the stated aim."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Mieux vaut terminer un module que d'en abandonner trois.",
        "key_line_en": "Better to finish one module than to drop three.",
        "vocabulary": [
            {"term": "s'adresser à", "gloss": "to be aimed at"},
            {"term": "volontairement", "gloss": "deliberately"},
            {"term": "un trimestre", "gloss": "a term, quarter"},
            {"term": "abandonner", "gloss": "to drop, give up"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Information santé / Health information",
        "topic": "Santé & bien-être",
        "text": "Un médicament générique contient la même substance active que l'original, au même dosage.\nSeuls les colorants, la forme ou le goût peuvent différer. Si un patient préfère l'original, la différence de prix reste à sa charge.",
        "question_fr": "Que doit payer un patient qui refuse le générique ?",
        "options": [
            {"id": "a", "text": "La différence de prix",
             "explanation": "« la différence de prix reste à sa charge » — the patient covers the gap."},
            {"id": "b", "text": "Le prix entier du médicament",
             "explanation": "Only the difference is at their expense, not the whole cost."},
            {"id": "c", "text": "Rien de plus",
             "explanation": "There is an extra cost, and the text names it."},
            {"id": "d", "text": "Une consultation supplémentaire",
             "explanation": "No further appointment is mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Si un patient préfère l'original, la différence de prix reste à sa charge.",
        "key_line_en": "If a patient prefers the original, the price difference is at their own expense.",
        "vocabulary": [
            {"term": "une substance active", "gloss": "an active ingredient"},
            {"term": "à sa charge", "gloss": "at one's own expense"},
            {"term": "différer", "gloss": "to differ"},
            {"term": "un dosage", "gloss": "a dosage"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article municipal / Local news",
        "topic": "Transports & voyages",
        "text": "Le service de vélos partagés a doublé sa flotte, mais les usagers se plaignent toujours.\nLe problème n'est pas le nombre de vélos : c'est leur répartition. Le matin, les stations des quartiers hauts sont vides ; le soir, celles du centre débordent.",
        "question_fr": "Quel est le vrai problème du service, d'après l'article ?",
        "options": [
            {"id": "a", "text": "Le manque de vélos",
             "explanation": "« Le problème n'est pas le nombre de vélos » — the fleet has doubled."},
            {"id": "b", "text": "Le mauvais état des vélos",
             "explanation": "Condition and maintenance are never mentioned."},
            {"id": "c", "text": "La répartition des vélos dans la ville",
             "explanation": "Empty uphill stations in the morning, overflowing central ones at night: « c'est leur répartition »."},
            {"id": "d", "text": "Le prix de l'abonnement",
             "explanation": "No price appears in the article."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le problème n'est pas le nombre de vélos : c'est leur répartition.",
        "key_line_en": "The problem is not the number of bikes: it is how they are distributed.",
        "vocabulary": [
            {"term": "une flotte", "gloss": "a fleet"},
            {"term": "la répartition", "gloss": "distribution"},
            {"term": "déborder", "gloss": "to overflow"},
            {"term": "un usager", "gloss": "a user"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Reportage / Report",
        "topic": "Alimentation & consommation",
        "text": "Le supermarché vend depuis un an ses produits proches de la date limite à moitié prix, dans un rayon dédié.\nLes invendus ont baissé d'un tiers. « Nous ne perdons rien, précise le gérant : ces produits finissaient à la poubelle. »",
        "question_fr": "Quel est l'effet de cette mesure pour le magasin ?",
        "options": [
            {"id": "a", "text": "Elle lui coûte de l'argent",
             "explanation": "« Nous ne perdons rien » — the goods were being thrown away anyway."},
            {"id": "b", "text": "Elle réduit ses pertes",
             "explanation": "Unsold stock fell by a third, and the items sold at half price would otherwise have gone in the bin."},
            {"id": "c", "text": "Elle augmente le prix des autres produits",
             "explanation": "No effect on other prices is mentioned."},
            {"id": "d", "text": "Elle attire moins de clients",
             "explanation": "Customer numbers are not discussed, and nothing suggests a fall."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nous ne perdons rien : ces produits finissaient à la poubelle.",
        "key_line_en": "We lose nothing: these products used to end up in the bin.",
        "vocabulary": [
            {"term": "la date limite", "gloss": "the use-by date"},
            {"term": "les invendus", "gloss": "unsold goods"},
            {"term": "un rayon", "gloss": "an aisle, section"},
            {"term": "un gérant", "gloss": "a manager"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Information administrative / Administrative notice",
        "topic": "Société, citoyenneté & administration",
        "text": "Pour voter, il faut être inscrit sur les listes électorales de sa commune.\nUn déménagement n'entraîne pas l'inscription automatique : la démarche doit être faite, en ligne ou en mairie, avant le 31 décembre.",
        "question_fr": "Que doit faire une personne qui a déménagé ?",
        "options": [
            {"id": "a", "text": "Attendre l'inscription automatique",
             "explanation": "« Un déménagement n'entraîne pas l'inscription automatique » — nothing happens by itself."},
            {"id": "b", "text": "Voter dans son ancienne commune",
             "explanation": "Registration is tied to the commune where one lives; the notice asks for a new registration."},
            {"id": "c", "text": "S'inscrire avant la fin de l'année",
             "explanation": "« la démarche doit être faite […] avant le 31 décembre », online or at the town hall."},
            {"id": "d", "text": "Se présenter le jour du vote",
             "explanation": "Turning up on polling day is not enough without being on the roll."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La démarche doit être faite, en ligne ou en mairie, avant le 31 décembre.",
        "key_line_en": "The step must be taken, online or at the town hall, before 31 December.",
        "vocabulary": [
            {"term": "les listes électorales", "gloss": "the electoral roll"},
            {"term": "une démarche", "gloss": "a formality, procedure"},
            {"term": "entraîner", "gloss": "to bring about"},
            {"term": "une commune", "gloss": "a municipality"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "topic": "Société, citoyenneté & administration",
        "text": "On multiplie les consultations citoyennes, et l'on s'étonne de la lassitude qu'elles provoquent.\nRien n'use davantage la confiance que d'être consulté sans jamais savoir ce que la réponse a changé. Une consultation sans retour n'est pas une participation, c'est un sondage.",
        "question_fr": "Que reproche l'auteur à ces consultations ?",
        "options": [
            {"id": "a", "text": "Elles ne rendent jamais compte de leurs effets",
             "explanation": "« être consulté sans jamais savoir ce que la réponse a changé » — no feedback, so it is a poll, not participation."},
            {"id": "b", "text": "Elles sont trop peu nombreuses",
             "explanation": "The opposite: « On multiplie les consultations »."},
            {"id": "c", "text": "Elles coûtent trop cher",
             "explanation": "Cost is never mentioned."},
            {"id": "d", "text": "Elles posent des questions trop techniques",
             "explanation": "The wording of the questions is not at issue; what happens afterwards is."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Une consultation sans retour n'est pas une participation, c'est un sondage.",
        "key_line_en": "A consultation with no feedback is not participation, it is an opinion poll.",
        "vocabulary": [
            {"term": "la lassitude", "gloss": "weariness"},
            {"term": "user", "gloss": "to wear down"},
            {"term": "un retour", "gloss": "feedback"},
            {"term": "un sondage", "gloss": "an opinion poll"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "topic": "Loisirs, culture & médias",
        "text": "Les plateformes ont mis la totalité de la musique enregistrée à portée de main, et l'on écoute moins d'artistes qu'avant.\nQuand tout est disponible, le choix devient coûteux ; on s'en remet à ce qui est proposé. L'abondance n'élargit pas les goûts, elle délègue leur formation.",
        "question_fr": "Quel effet paradoxal l'auteur décrit-il ?",
        "options": [
            {"id": "a", "text": "L'accès illimité rétrécit les écoutes",
             "explanation": "With everything available, choosing costs effort, so listeners fall back on what is recommended: « L'abondance n'élargit pas les goûts »."},
            {"id": "b", "text": "Les plateformes proposent trop peu de titres",
             "explanation": "They offer « la totalité de la musique enregistrée »."},
            {"id": "c", "text": "Les auditeurs paient trop cher",
             "explanation": "The cost described is the effort of choosing, not a price."},
            {"id": "d", "text": "Les artistes produisent moins qu'avant",
             "explanation": "Artists' output is not discussed; what changes is listening behaviour."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'abondance n'élargit pas les goûts, elle délègue leur formation.",
        "key_line_en": "Abundance does not broaden taste, it delegates how taste is formed.",
        "vocabulary": [
            {"term": "à portée de main", "gloss": "within reach"},
            {"term": "s'en remettre à", "gloss": "to rely on, defer to"},
            {"term": "élargir", "gloss": "to broaden"},
            {"term": "déléguer", "gloss": "to delegate"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "topic": "Sciences & technologies",
        "text": "La traduction automatique a fait des progrès spectaculaires sur les textes courants.\nElle reste pourtant démunie devant l'implicite : une phrase polie qui signifie un refus, une allusion partagée. La machine traduit les mots, rarement ce que le locuteur faisait en les disant.",
        "question_fr": "Quelle limite l'auteur relève-t-il ?",
        "options": [
            {"id": "a", "text": "La machine est trop lente",
             "explanation": "Speed is not discussed; progress on ordinary texts is acknowledged as spectacular."},
            {"id": "b", "text": "Elle ne restitue pas l'intention du locuteur",
             "explanation": "It renders words, « rarement ce que le locuteur faisait en les disant » — the act behind them."},
            {"id": "c", "text": "Elle ne connaît pas assez de langues",
             "explanation": "The number of languages is never mentioned."},
            {"id": "d", "text": "Elle fait beaucoup de fautes de grammaire",
             "explanation": "Grammar is precisely where the progress is; the gap is pragmatic, not grammatical."},
        ],
        "correct_answer": "b",
        "key_line_fr": "La machine traduit les mots, rarement ce que le locuteur faisait en les disant.",
        "key_line_en": "The machine translates the words, rarely what the speaker was doing in saying them.",
        "vocabulary": [
            {"term": "démuni", "gloss": "helpless, ill-equipped"},
            {"term": "l'implicite", "gloss": "what is implied"},
            {"term": "une allusion", "gloss": "an allusion"},
            {"term": "un locuteur", "gloss": "a speaker"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "topic": "Environnement & nature",
        "text": "Les quartiers les plus chauds de la ville ne sont pas les plus exposés au soleil, mais les plus minéraux.\nUn relevé mené en août montre jusqu'à sept degrés d'écart entre une rue plantée et une place bétonnée voisine. La différence ne tient pas au climat, elle tient au revêtement.",
        "question_fr": "Qu'est-ce qui explique l'écart de température observé ?",
        "options": [
            {"id": "a", "text": "L'exposition au soleil",
             "explanation": "Explicitly ruled out: the hottest districts « ne sont pas les plus exposés au soleil »."},
            {"id": "b", "text": "Le climat de la région",
             "explanation": "« La différence ne tient pas au climat » — the two places share the same weather."},
            {"id": "c", "text": "La nature du sol et la végétation",
             "explanation": "Seven degrees between a planted street and a concreted square: « elle tient au revêtement »."},
            {"id": "d", "text": "La densité de population",
             "explanation": "Population is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La différence ne tient pas au climat, elle tient au revêtement.",
        "key_line_en": "The difference is not down to the climate, it is down to the surfacing.",
        "vocabulary": [
            {"term": "minéral", "gloss": "hard-surfaced, built-up"},
            {"term": "un relevé", "gloss": "a set of measurements"},
            {"term": "le revêtement", "gloss": "the surfacing"},
            {"term": "tenir à", "gloss": "to be due to"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "topic": "Travail & emploi",
        "text": "Bonjour,\nNous accueillons quatre stagiaires en mars. Je rappelle que le tuteur doit prévoir deux heures par semaine, inscrites à son planning.\nUn stage sans tuteur disponible coûte plus qu'il ne rapporte : nous préférons en accueillir deux et les former correctement.",
        "question_fr": "Quelle est la position exprimée dans ce message ?",
        "options": [
            {"id": "a", "text": "Il faut accueillir le plus de stagiaires possible",
             "explanation": "The message says the opposite: better two properly supervised than more without."},
            {"id": "b", "text": "Les stages coûtent trop cher à l'entreprise",
             "explanation": "Only unsupervised placements are said to cost more than they return."},
            {"id": "c", "text": "Les tuteurs doivent être payés davantage",
             "explanation": "Pay is not mentioned; what is asked is protected time."},
            {"id": "d", "text": "Le nombre de stagiaires doit suivre l'encadrement disponible",
             "explanation": "Two hours a week per tutor, timetabled, and fewer placements if that cannot be met."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Un stage sans tuteur disponible coûte plus qu'il ne rapporte.",
        "key_line_en": "A placement without an available supervisor costs more than it returns.",
        "vocabulary": [
            {"term": "un stagiaire", "gloss": "an intern, trainee"},
            {"term": "un tuteur", "gloss": "a supervisor, mentor"},
            {"term": "l'encadrement", "gloss": "supervision"},
            {"term": "rapporter", "gloss": "to bring in, yield"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article consommation / Consumer article",
        "topic": "Alimentation & consommation",
        "text": "L'étiquette nutritionnelle a été simplifiée pour être lisible en trois secondes, ce qui était l'objectif.\nElle classe pourtant un jus de fruits pressé et un soda allégé dans la même couleur. Un repère grossier vaut mieux que rien, à condition que nul ne le prenne pour une expertise.",
        "question_fr": "Quelle est la position nuancée de l'auteur ?",
        "options": [
            {"id": "a", "text": "L'étiquette est utile mais ne doit pas être surinterprétée",
             "explanation": "« Un repère grossier vaut mieux que rien, à condition que nul ne le prenne pour une expertise »."},
            {"id": "b", "text": "L'étiquette devrait être supprimée",
             "explanation": "He defends it as better than nothing."},
            {"id": "c", "text": "L'étiquette est parfaitement fiable",
             "explanation": "The juice-and-soda example is there precisely to show its coarseness."},
            {"id": "d", "text": "L'étiquette est trop compliquée à lire",
             "explanation": "Readability in three seconds is credited as an achieved aim."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Un repère grossier vaut mieux que rien, à condition que nul ne le prenne pour une expertise.",
        "key_line_en": "A crude guide is better than nothing, provided nobody mistakes it for expertise.",
        "vocabulary": [
            {"term": "un repère", "gloss": "a guide, marker"},
            {"term": "grossier", "gloss": "rough, crude"},
            {"term": "allégé", "gloss": "reduced-sugar, light"},
            {"term": "à condition que", "gloss": "provided that"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article santé / Health article",
        "topic": "Santé & bien-être",
        "text": "Les entreprises proposent des ateliers de gestion du stress, et l'on ne peut leur en faire grief.\nMais apprendre à mieux supporter une charge n'est pas la même chose que la réduire. Soigner l'individu plutôt que l'organisation revient à réparer sans cesse ce que l'on continue de casser.",
        "question_fr": "Que critique l'auteur dans ces ateliers ?",
        "options": [
            {"id": "a", "text": "Ils sont réservés aux cadres",
             "explanation": "Who attends is never mentioned."},
            {"id": "b", "text": "Ils traitent les personnes sans changer la cause",
             "explanation": "« Soigner l'individu plutôt que l'organisation revient à réparer sans cesse ce que l'on continue de casser »."},
            {"id": "c", "text": "Ils sont inefficaces sur le stress",
             "explanation": "Their effect is not denied — « on ne peut leur en faire grief » — only their scope."},
            {"id": "d", "text": "Ils prennent trop de temps de travail",
             "explanation": "Their duration is not raised."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Apprendre à mieux supporter une charge n'est pas la même chose que la réduire.",
        "key_line_en": "Learning to bear a load better is not the same as reducing it.",
        "vocabulary": [
            {"term": "faire grief à", "gloss": "to hold against, blame for"},
            {"term": "supporter", "gloss": "to bear, put up with"},
            {"term": "une charge", "gloss": "a load, burden"},
            {"term": "revenir à", "gloss": "to amount to"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "topic": "Sciences & technologies",
        "text": "On dit que l'attention se disperse ; il serait plus juste de dire qu'elle se vend.\nCe qui a changé n'est pas notre capacité à nous concentrer, mais l'existence d'industries dont le revenu dépend précisément de notre échec à le faire.",
        "question_fr": "Quel déplacement l'auteur opère-t-il ?",
        "options": [
            {"id": "a", "text": "D'une faiblesse individuelle à un intérêt économique",
             "explanation": "Not a lost capacity but industries « dont le revenu dépend précisément de notre échec » — the cause moves from the person to a business model."},
            {"id": "b", "text": "D'un problème récent à un problème ancien",
             "explanation": "No historical comparison of that kind is made."},
            {"id": "c", "text": "D'une question technique à une question morale",
             "explanation": "No moral judgement of users is offered; the analysis stays economic."},
            {"id": "d", "text": "D'un constat général à un cas particulier",
             "explanation": "The movement runs the other way: from an individual complaint to a structural claim."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'existence d'industries dont le revenu dépend précisément de notre échec à le faire.",
        "key_line_en": "The existence of industries whose revenue depends precisely on our failure to do so.",
        "vocabulary": [
            {"term": "se disperser", "gloss": "to scatter, be spread thin"},
            {"term": "un revenu", "gloss": "an income, revenue"},
            {"term": "un échec", "gloss": "a failure"},
            {"term": "il serait plus juste de", "gloss": "it would be more accurate to"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "topic": "Société, citoyenneté & administration",
        "text": "Le formulaire a été refait par des ergonomes : il est clair, aéré, agréable à remplir.\nIl demande toujours les mêmes pièces que l'administration détient déjà. On aura rarement rendu si plaisante une démarche aussi inutile.",
        "question_fr": "Que vise la critique de l'auteur ?",
        "options": [
            {"id": "a", "text": "La mauvaise conception du formulaire",
             "explanation": "Its design is praised without irony: clear, uncluttered, pleasant."},
            {"id": "b", "text": "Le coût du travail des ergonomes",
             "explanation": "No cost is mentioned."},
            {"id": "c", "text": "La persistance d'une démarche superflue",
             "explanation": "It still asks for documents « que l'administration détient déjà »; the form got nicer, the pointlessness stayed."},
            {"id": "d", "text": "La lenteur du traitement des dossiers",
             "explanation": "Processing time is never discussed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On aura rarement rendu si plaisante une démarche aussi inutile.",
        "key_line_en": "Rarely has so pointless a procedure been made so pleasant.",
        "vocabulary": [
            {"term": "aéré", "gloss": "uncluttered, well spaced"},
            {"term": "détenir", "gloss": "to hold, possess"},
            {"term": "une pièce", "gloss": "a document"},
            {"term": "plaisant", "gloss": "pleasant"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "topic": "Travail & emploi",
        "text": "On annonce que les compétences se périment en cinq ans, et l'on en conclut qu'il faut se former sans cesse.\nLa conclusion est hâtive : ce qui se périme, ce sont les outils, non le raisonnement qui permet d'en apprendre de nouveaux.",
        "question_fr": "Que conteste l'auteur ?",
        "options": [
            {"id": "a", "text": "Que les outils évoluent rapidement",
             "explanation": "He grants exactly that: tools are what goes out of date."},
            {"id": "b", "text": "Que la formation continue existe",
             "explanation": "Its existence is not in question, only what it should target."},
            {"id": "c", "text": "L'idée que tout doit être réappris en permanence",
             "explanation": "« La conclusion est hâtive »: reasoning does not expire, so perpetual retraining does not follow."},
            {"id": "d", "text": "Le chiffre de cinq ans",
             "explanation": "He does not dispute the figure; he disputes what is inferred from it."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ce qui se périme, ce sont les outils, non le raisonnement qui permet d'en apprendre de nouveaux.",
        "key_line_en": "What expires is the tools, not the reasoning that lets you learn new ones.",
        "vocabulary": [
            {"term": "se périmer", "gloss": "to go out of date"},
            {"term": "hâtif", "gloss": "hasty"},
            {"term": "le raisonnement", "gloss": "reasoning"},
            {"term": "sans cesse", "gloss": "constantly"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "topic": "Loisirs, culture & médias",
        "text": "On lui avait tant répété qu'il ressemblait à son père qu'il avait fini par emprunter sa démarche.\nÀ trente ans, il ne savait plus démêler ce qu'il tenait de lui de ce qu'il lui avait pris pour ne pas décevoir.",
        "question_fr": "Que dit ce passage du personnage ?",
        "options": [
            {"id": "a", "text": "Il refuse toute ressemblance avec son père",
             "explanation": "He adopted the resemblance rather than refusing it."},
            {"id": "b", "text": "Il ne distingue plus l'héritage de l'imitation",
             "explanation": "« il ne savait plus démêler ce qu'il tenait de lui de ce qu'il lui avait pris »."},
            {"id": "c", "text": "Il a perdu contact avec son père",
             "explanation": "No estrangement is described."},
            {"id": "d", "text": "Il admire son père sans réserve",
             "explanation": "The motive named is « pour ne pas décevoir », which is pressure, not admiration."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Il ne savait plus démêler ce qu'il tenait de lui de ce qu'il lui avait pris pour ne pas décevoir.",
        "key_line_en": "He could no longer untangle what he had inherited from him from what he had taken so as not to disappoint.",
        "vocabulary": [
            {"term": "démêler", "gloss": "to untangle, tell apart"},
            {"term": "tenir de quelqu'un", "gloss": "to get from someone (traits)"},
            {"term": "une démarche", "gloss": "a way of walking"},
            {"term": "décevoir", "gloss": "to disappoint"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "topic": "Environnement & nature",
        "text": "Compter les espèces d'un milieu renseigne moins qu'on ne le croit.\nUn étang peut en abriter davantage après une pollution, les espèces tolérantes remplaçant les espèces exigeantes. Le nombre monte, la richesse baisse : c'est la composition, non le total, qui décrit l'état d'un milieu.",
        "question_fr": "Pourquoi le nombre d'espèces peut-il induire en erreur ?",
        "options": [
            {"id": "a", "text": "Parce qu'il est difficile à mesurer",
             "explanation": "Measurement difficulty is not the issue; the count can be perfectly accurate and still mislead."},
            {"id": "b", "text": "Parce que les espèces tolérantes sont rares",
             "explanation": "The opposite: they are the ones that spread after pollution."},
            {"id": "c", "text": "Parce qu'il peut augmenter quand le milieu se dégrade",
             "explanation": "« Le nombre monte, la richesse baisse » — tolerant species replace demanding ones."},
            {"id": "d", "text": "Parce qu'il varie selon les saisons",
             "explanation": "Seasonality is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le nombre monte, la richesse baisse : c'est la composition, non le total, qui décrit l'état d'un milieu.",
        "key_line_en": "The number rises, the richness falls: it is the composition, not the total, that describes the state of a habitat.",
        "vocabulary": [
            {"term": "un milieu", "gloss": "a habitat, environment"},
            {"term": "abriter", "gloss": "to host, shelter"},
            {"term": "exigeant", "gloss": "demanding, sensitive"},
            {"term": "induire en erreur", "gloss": "to mislead"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Commentaire institutionnel / Institutional commentary",
        "topic": "Société, citoyenneté & administration",
        "text": "Le budget voté augmente la ligne consacrée à la rénovation des écoles de douze pour cent.\nIl reconduit dans le même temps un gel des recrutements. On rénovera donc des bâtiments que l'on peinera à faire fonctionner.",
        "question_fr": "Quelle contradiction l'auteur relève-t-il ?",
        "options": [
            {"id": "a", "text": "Le budget baisse malgré les annonces",
             "explanation": "The renovation line rises by twelve per cent; the figure is not disputed."},
            {"id": "b", "text": "On investit dans les murs sans pouvoir recruter",
             "explanation": "The building money goes up while the hiring freeze stays: « des bâtiments que l'on peinera à faire fonctionner »."},
            {"id": "c", "text": "Les écoles n'ont pas besoin de rénovation",
             "explanation": "The need is not questioned anywhere."},
            {"id": "d", "text": "Le gel des recrutements est levé",
             "explanation": "« Il reconduit […] un gel des recrutements » — it is renewed, not lifted."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On rénovera donc des bâtiments que l'on peinera à faire fonctionner.",
        "key_line_en": "So buildings will be renovated that will be hard to staff and run.",
        "vocabulary": [
            {"term": "reconduire", "gloss": "to renew, roll over"},
            {"term": "un gel", "gloss": "a freeze"},
            {"term": "peiner à", "gloss": "to struggle to"},
            {"term": "une ligne (budgétaire)", "gloss": "a budget line"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse urbaine / Urban analysis",
        "topic": "Vie quotidienne & logement",
        "text": "Un quartier vivant ne se décrète pas ; il se reconnaît à un signe modeste : on y trouve des raisons de sortir sans avoir rien à acheter.\nPartout où le seul motif de descendre est la consommation, la rue se vide dès que les commerces ferment.",
        "question_fr": "À quoi l'auteur reconnaît-il un quartier vivant ?",
        "options": [
            {"id": "a", "text": "Au nombre de commerces ouverts",
             "explanation": "Shops alone empty the street the moment they close — that is the counter-example, not the sign."},
            {"id": "b", "text": "À la densité de sa population",
             "explanation": "Population is never mentioned."},
            {"id": "c", "text": "À la présence de motifs de sortir gratuits",
             "explanation": "« des raisons de sortir sans avoir rien à acheter » is the modest sign he names."},
            {"id": "d", "text": "Aux décisions de la municipalité",
             "explanation": "« ne se décrète pas » — it cannot be brought about by decree."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On y trouve des raisons de sortir sans avoir rien à acheter.",
        "key_line_en": "You find reasons there to go out without having anything to buy.",
        "vocabulary": [
            {"term": "se décréter", "gloss": "to be brought about by decree"},
            {"term": "un motif", "gloss": "a reason, motive"},
            {"term": "descendre", "gloss": "to go down (into the street)"},
            {"term": "se vider", "gloss": "to empty"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur le style / Essay on style",
        "topic": "Loisirs, culture & médias",
        "text": "Le style n'est pas ce que l'on ajoute à une pensée pour la rendre agréable ; c'est ce qui reste quand on a retiré tout ce qui pouvait être dit autrement.\nUne phrase qu'on peut reformuler sans perte n'avait pas de style : elle avait un sens, ce qui est moins.",
        "question_fr": "Comment l'auteur définit-il le style ?",
        "options": [
            {"id": "a", "text": "Comme un ornement ajouté à la pensée",
             "explanation": "The definition opens by rejecting exactly this."},
            {"id": "b", "text": "Comme la clarté d'une formulation",
             "explanation": "Clarity would survive reformulation, which is the test the text uses to rule style out."},
            {"id": "c", "text": "Comme la partie irremplaçable d'une formulation",
             "explanation": "What cannot be said otherwise: « Une phrase qu'on peut reformuler sans perte n'avait pas de style »."},
            {"id": "d", "text": "Comme le sens que porte une phrase",
             "explanation": "Meaning is explicitly ranked below style here — « ce qui est moins »."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une phrase qu'on peut reformuler sans perte n'avait pas de style.",
        "key_line_en": "A sentence that can be reworded without loss had no style.",
        "vocabulary": [
            {"term": "retirer", "gloss": "to remove"},
            {"term": "reformuler", "gloss": "to reword"},
            {"term": "sans perte", "gloss": "without loss"},
            {"term": "un ornement", "gloss": "an ornament"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "topic": "Société, citoyenneté & administration",
        "text": "L'unanimité rassure et devrait inquiéter. Une décision que personne ne conteste n'a pas été examinée : elle a été acceptée.\nLe désaccord n'est pas le prix à payer pour la délibération, il en est l'instrument — le seul qui oblige à formuler ce que l'on tenait pour évident.",
        "question_fr": "Quel rôle l'auteur attribue-t-il au désaccord ?",
        "options": [
            {"id": "a", "text": "Un obstacle qu'il faut accepter",
             "explanation": "« n'est pas le prix à payer » refuses precisely this framing."},
            {"id": "b", "text": "Le moyen même de l'examen collectif",
             "explanation": "« il en est l'instrument — le seul qui oblige à formuler ce que l'on tenait pour évident »."},
            {"id": "c", "text": "Un signe de mauvaise foi",
             "explanation": "No motive is attributed to those who disagree."},
            {"id": "d", "text": "Une conséquence de décisions mal préparées",
             "explanation": "Disagreement is a cause of good deliberation here, not a symptom of bad preparation."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Le désaccord n'est pas le prix à payer pour la délibération, il en est l'instrument.",
        "key_line_en": "Disagreement is not the price of deliberation, it is its instrument.",
        "vocabulary": [
            {"term": "l'unanimité", "gloss": "unanimity"},
            {"term": "contester", "gloss": "to challenge"},
            {"term": "tenir pour évident", "gloss": "to take for granted"},
            {"term": "un instrument", "gloss": "an instrument, means"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Critique musicale / Music review",
        "topic": "Loisirs, culture & médias",
        "text": "L'orchestre joue juste, ensemble, et sans une hésitation. Le chef obtient tout ce qu'il demande.\nOn voudrait seulement qu'il demandât davantage : à force de ne rien risquer, cette lecture ne perd rien non plus qu'elle n'ait déjà refusé de gagner.",
        "question_fr": "Que reproche le critique à cette interprétation ?",
        "options": [
            {"id": "a", "text": "Des erreurs techniques audibles",
             "explanation": "The playing is in tune, together and unhesitating — technically beyond reproach."},
            {"id": "b", "text": "Un chef incapable de se faire obéir",
             "explanation": "« Le chef obtient tout ce qu'il demande » — the problem is what he asks for."},
            {"id": "c", "text": "Un manque de risque qui limite la portée",
             "explanation": "« à force de ne rien risquer » — nothing is lost because nothing was attempted."},
            {"id": "d", "text": "Un tempo trop lent",
             "explanation": "No tempo is discussed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "À force de ne rien risquer, cette lecture ne perd rien non plus qu'elle n'ait déjà refusé de gagner.",
        "key_line_en": "By risking nothing, this reading loses nothing it had not already declined to win.",
        "vocabulary": [
            {"term": "jouer juste", "gloss": "to play in tune"},
            {"term": "une lecture", "gloss": "an interpretation, reading"},
            {"term": "risquer", "gloss": "to risk"},
            {"term": "à force de", "gloss": "through constantly"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "topic": "Sciences & technologies",
        "text": "Prévoir n'est pas connaître l'avenir, c'est décrire les conditions dans lesquelles on se trompera.\nUne prévision qui ne dit pas ce qui la démentirait n'engage personne : elle sera vraie quoi qu'il arrive, et donc dépourvue de tout contenu.",
        "question_fr": "Quelle exigence l'auteur pose-t-il pour une prévision ?",
        "options": [
            {"id": "a", "text": "Qu'elle indique ce qui pourrait la réfuter",
             "explanation": "A forecast that does not say « ce qui la démentirait » commits to nothing and is empty of content."},
            {"id": "b", "text": "Qu'elle se révèle exacte",
             "explanation": "Being true whatever happens is presented as the defect, not the goal."},
            {"id": "c", "text": "Qu'elle repose sur des données chiffrées",
             "explanation": "No requirement about data or figures is stated."},
            {"id": "d", "text": "Qu'elle porte sur un avenir proche",
             "explanation": "The time horizon is never mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Une prévision qui ne dit pas ce qui la démentirait n'engage personne.",
        "key_line_en": "A forecast that does not say what would disprove it commits nobody.",
        "vocabulary": [
            {"term": "démentir", "gloss": "to contradict, disprove"},
            {"term": "engager", "gloss": "to commit, bind"},
            {"term": "dépourvu de", "gloss": "devoid of"},
            {"term": "quoi qu'il arrive", "gloss": "whatever happens"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "topic": "Vie quotidienne & logement",
        "text": "L'immeuble neuf n'a pas de seuil : on passe du trottoir au hall sans marquer d'arrêt, et du hall à l'ascenseur sans croiser personne.\nOn a gagné en fluidité ce que l'on a perdu en occasions — car c'est sur les seuils, et nulle part ailleurs, que se saluent ceux qui ne se cherchaient pas.",
        "question_fr": "Que regrette l'auteur dans cette conception ?",
        "options": [
            {"id": "a", "text": "La disparition des rencontres non prévues",
             "explanation": "Thresholds are where « se saluent ceux qui ne se cherchaient pas »; removing them removes the chance encounter."},
            {"id": "b", "text": "La lenteur des déplacements dans l'immeuble",
             "explanation": "Movement has become more fluid, which is the gain he acknowledges."},
            {"id": "c", "text": "Le manque de sécurité à l'entrée",
             "explanation": "Security is never raised."},
            {"id": "d", "text": "L'absence d'ascenseur",
             "explanation": "There is a lift; the point is that one reaches it without meeting anyone."},
        ],
        "correct_answer": "a",
        "key_line_fr": "C'est sur les seuils, et nulle part ailleurs, que se saluent ceux qui ne se cherchaient pas.",
        "key_line_en": "It is on thresholds, and nowhere else, that people who were not looking for each other say hello.",
        "vocabulary": [
            {"term": "un seuil", "gloss": "a threshold, doorstep"},
            {"term": "la fluidité", "gloss": "smoothness of flow"},
            {"term": "croiser", "gloss": "to pass, run into"},
            {"term": "se saluer", "gloss": "to greet one another"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la politesse / Essay on politeness",
        "topic": "Société, citoyenneté & administration",
        "text": "On raille la politesse comme une hypocrisie, au motif qu'elle dit autre chose que ce que l'on pense.\nC'est justement son office : elle interpose entre deux humeurs une forme convenue, et ce délai suffit souvent à ce que l'humeur passe avant que le mot ne soit dit.",
        "question_fr": "Quelle fonction l'auteur attribue-t-il à la politesse ?",
        "options": [
            {"id": "a", "text": "Dissimuler durablement ses opinions",
             "explanation": "Nothing is hidden long-term; what the form buys is a delay in which the mood dissolves."},
            {"id": "b", "text": "Exprimer fidèlement ce que l'on ressent",
             "explanation": "The text grants that politeness says something other than what one thinks — and defends it for that."},
            {"id": "c", "text": "Marquer les différences sociales",
             "explanation": "Social hierarchy plays no part in the argument."},
            {"id": "d", "text": "Introduire un délai qui désamorce l'humeur",
             "explanation": "« ce délai suffit souvent à ce que l'humeur passe avant que le mot ne soit dit »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Ce délai suffit souvent à ce que l'humeur passe avant que le mot ne soit dit.",
        "key_line_en": "That delay is often enough for the mood to pass before the word is spoken.",
        "vocabulary": [
            {"term": "railler", "gloss": "to mock"},
            {"term": "l'office", "gloss": "the function, role"},
            {"term": "interposer", "gloss": "to place between"},
            {"term": "convenu", "gloss": "conventional, agreed"},
        ],
    },
]

QUESTIONS = balance(_RAW)
