"""Compréhension écrite — Test 01.

Forty questions climbing A1 → C2. Distribution: A1 6, A2 7, B1 7, B2 7, C1 7,
C2 6.

The question layer is French only — no question_en and no text_en — because the
paper is read the way the real exam is read. The English appears afterwards, in
the explanations, the key line's translation and the vocabulary glosses.

Options are written below in whatever order reads best; balance() then rotates
each set so the answer key cycles a, b, c, d and lands ten times on each letter.
Write the questions, not the key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "SMS",
        "topic": "Loisirs, culture & médias",
        "text": "Salut Marc,\nJe suis malade, je ne peux pas aller au cinéma ce soir. On y va samedi ?\nJulie",
        "question_fr": "Pourquoi Julie écrit-elle ?",
        "options": [
            {"id": "a", "text": "Pour acheter des billets",
             "explanation": "No tickets are bought or mentioned; she is calling the evening off."},
            {"id": "b", "text": "Pour annuler la sortie de ce soir",
             "explanation": "« je ne peux pas aller au cinéma ce soir » cancels tonight's outing, and she proposes Saturday instead."},
            {"id": "c", "text": "Pour demander l'adresse du cinéma",
             "explanation": "She asks no question about the place; both already know where the cinema is."},
            {"id": "d", "text": "Pour inviter Marc au restaurant",
             "explanation": "No restaurant and no meal appear in the message."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Je suis malade, je ne peux pas aller au cinéma ce soir.",
        "key_line_en": "I'm ill, I can't go to the cinema tonight.",
        "vocabulary": [
            {"term": "malade", "gloss": "ill, sick"},
            {"term": "ce soir", "gloss": "tonight"},
            {"term": "on y va ?", "gloss": "shall we go?"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Affiche / Notice",
        "topic": "Loisirs, culture & médias",
        "text": "PISCINE MUNICIPALE\nFermée mercredi 6 mars pour nettoyage.\nRéouverture jeudi 7 mars à 8 h.",
        "question_fr": "Que se passe-t-il mercredi 6 mars ?",
        "options": [
            {"id": "a", "text": "La piscine est fermée",
             "explanation": "The notice says it outright: « Fermée mercredi 6 mars »."},
            {"id": "b", "text": "La piscine ouvre à 8 h",
             "explanation": "8 a.m. is the reopening time on Thursday 7, not Wednesday 6."},
            {"id": "c", "text": "La piscine organise une compétition",
             "explanation": "No event or competition is announced; the reason given is cleaning."},
            {"id": "d", "text": "La piscine change de prix",
             "explanation": "No price is mentioned anywhere on the notice."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Fermée mercredi 6 mars pour nettoyage.",
        "key_line_en": "Closed Wednesday 6 March for cleaning.",
        "vocabulary": [
            {"term": "le nettoyage", "gloss": "cleaning"},
            {"term": "la réouverture", "gloss": "reopening"},
            {"term": "une piscine", "gloss": "swimming pool"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Menu",
        "topic": "Alimentation & consommation",
        "text": "FORMULE MIDI — 14 €\nEntrée + plat OU plat + dessert.\nBoisson non comprise.\nDu lundi au vendredi, de 12 h à 14 h.",
        "question_fr": "Que comprend la formule à 14 € ?",
        "options": [
            {"id": "a", "text": "Trois plats et une boisson",
             "explanation": "The formula offers two courses, not three, and the drink is excluded."},
            {"id": "b", "text": "Deux plats, sans boisson",
             "explanation": "« Entrée + plat OU plat + dessert » is two courses, and « Boisson non comprise » excludes the drink."},
            {"id": "c", "text": "Un plat et une boisson",
             "explanation": "Two courses are included, and the drink is explicitly not."},
            {"id": "d", "text": "Un dessert seulement",
             "explanation": "The dessert only comes as part of a two-course choice, never alone."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Entrée + plat OU plat + dessert. Boisson non comprise.",
        "key_line_en": "Starter + main OR main + dessert. Drink not included.",
        "vocabulary": [
            {"term": "une entrée", "gloss": "a starter"},
            {"term": "un plat", "gloss": "a main course"},
            {"term": "non compris", "gloss": "not included"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Mot du voisin / Note from a neighbour",
        "topic": "Vie quotidienne & logement",
        "text": "Bonjour,\nLe facteur est passé ce matin. J'ai pris votre colis. Il est chez moi, appartement 12.\nMme Roux",
        "question_fr": "Où est le colis ?",
        "options": [
            {"id": "a", "text": "À la poste",
             "explanation": "The postman came and the parcel was taken in by the neighbour, so it never went back."},
            {"id": "b", "text": "Devant la porte",
             "explanation": "Nothing was left outside; Mme Roux says she took it in."},
            {"id": "c", "text": "Chez Mme Roux",
             "explanation": "« Il est chez moi, appartement 12 » — the neighbour is holding it in flat 12."},
            {"id": "d", "text": "Chez le facteur",
             "explanation": "The postman delivered it and left; he is not keeping it."},
        ],
        "correct_answer": "c",
        "key_line_fr": "J'ai pris votre colis. Il est chez moi, appartement 12.",
        "key_line_en": "I took in your parcel. It's at my place, flat 12.",
        "vocabulary": [
            {"term": "le facteur", "gloss": "the postman"},
            {"term": "un colis", "gloss": "a parcel"},
            {"term": "chez moi", "gloss": "at my place"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Panneau / Sign",
        "topic": "Vie quotidienne & logement",
        "text": "PARC DES TILLEULS\nLes chiens doivent être tenus en laisse.\nJeux interdits aux enfants de plus de 12 ans.",
        "question_fr": "Que dit ce panneau à propos des chiens ?",
        "options": [
            {"id": "a", "text": "Les chiens sont interdits dans le parc",
             "explanation": "Dogs are allowed; only their being loose is forbidden. The ban concerns the play area and older children."},
            {"id": "b", "text": "Les chiens doivent rester attachés",
             "explanation": "« tenus en laisse » means kept on a lead, i.e. attached and under control."},
            {"id": "c", "text": "Les chiens peuvent courir librement",
             "explanation": "The opposite of « en laisse », which is exactly what the sign requires."},
            {"id": "d", "text": "Les chiens sont acceptés le matin seulement",
             "explanation": "No time restriction appears on the sign."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les chiens doivent être tenus en laisse.",
        "key_line_en": "Dogs must be kept on a lead.",
        "vocabulary": [
            {"term": "une laisse", "gloss": "a lead, leash"},
            {"term": "tenir", "gloss": "to hold, keep"},
            {"term": "interdit", "gloss": "forbidden"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Courriel / E-mail",
        "topic": "Alimentation & consommation",
        "text": "Bonjour Paul,\nTu as encore mon livre de cuisine ? J'en ai besoin dimanche pour préparer le repas de famille.\nMerci ! Anne",
        "question_fr": "Que veut Anne ?",
        "options": [
            {"id": "a", "text": "Récupérer son livre",
             "explanation": "She asks whether Paul still has her book and says she needs it on Sunday — she wants it back."},
            {"id": "b", "text": "Offrir un livre à Paul",
             "explanation": "The book is hers (« mon livre »); nothing is being given away."},
            {"id": "c", "text": "Inviter Paul dimanche",
             "explanation": "Sunday is when she needs the book, not an invitation to Paul."},
            {"id": "d", "text": "Acheter un livre de cuisine",
             "explanation": "No purchase is mentioned; the book already exists and Paul has it."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Tu as encore mon livre de cuisine ? J'en ai besoin dimanche.",
        "key_line_en": "Do you still have my cookery book? I need it on Sunday.",
        "vocabulary": [
            {"term": "encore", "gloss": "still"},
            {"term": "avoir besoin de", "gloss": "to need"},
            {"term": "un repas", "gloss": "a meal"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Petite annonce / Classified ad",
        "topic": "Travail & emploi",
        "text": "RESTAURANT LE PONT recherche un serveur (H/F).\nTravail le week-end obligatoire, deux jours de repos en semaine.\nDébutants acceptés, formation assurée.\nSe présenter avec un CV du mardi au jeudi, après 15 h.",
        "question_fr": "Quelle contrainte ce poste impose-t-il ?",
        "options": [
            {"id": "a", "text": "Avoir déjà travaillé en restauration",
             "explanation": "« Débutants acceptés » removes any experience requirement."},
            {"id": "b", "text": "Travailler samedi et dimanche",
             "explanation": "« Travail le week-end obligatoire » makes weekend work a condition of the job."},
            {"id": "c", "text": "Suivre une formation payante",
             "explanation": "Training is provided (« formation assurée ») and nothing suggests the candidate pays for it."},
            {"id": "d", "text": "Se présenter le lundi matin",
             "explanation": "Applications are taken Tuesday to Thursday, after 3 p.m. — Monday morning is excluded twice over."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Travail le week-end obligatoire, deux jours de repos en semaine.",
        "key_line_en": "Weekend work compulsory, two days off during the week.",
        "vocabulary": [
            {"term": "obligatoire", "gloss": "compulsory"},
            {"term": "le repos", "gloss": "rest, days off"},
            {"term": "un débutant", "gloss": "a beginner"},
            {"term": "se présenter", "gloss": "to come in, apply in person"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Règlement / Rules",
        "topic": "Santé & bien-être",
        "text": "SALLE DE SPORT ÉNERGIE — RÈGLEMENT\nL'accès est réservé aux membres munis de leur badge.\nUne serviette est obligatoire sur les appareils.\nLes sacs restent dans les casiers, jamais dans la salle.",
        "question_fr": "Que doit apporter un membre pour utiliser les appareils ?",
        "options": [
            {"id": "a", "text": "Un sac de sport",
             "explanation": "Bags are the one thing that must stay out of the room, in the lockers."},
            {"id": "b", "text": "Un certificat médical",
             "explanation": "No medical certificate is mentioned in these rules."},
            {"id": "c", "text": "Une serviette",
             "explanation": "« Une serviette est obligatoire sur les appareils » — a towel is required to use the machines."},
            {"id": "d", "text": "Une bouteille d'eau",
             "explanation": "Water is never mentioned; only the badge, the towel and the lockers are."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une serviette est obligatoire sur les appareils.",
        "key_line_en": "A towel is compulsory on the machines.",
        "vocabulary": [
            {"term": "une serviette", "gloss": "a towel"},
            {"term": "un appareil", "gloss": "a machine"},
            {"term": "un casier", "gloss": "a locker"},
            {"term": "muni de", "gloss": "carrying, provided with"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Recette / Recipe",
        "topic": "Alimentation & consommation",
        "text": "GÂTEAU AU YAOURT\nMélangez le yaourt, le sucre et les œufs.\nAjoutez la farine, puis l'huile en dernier.\nFaites cuire 35 minutes à 180 °C.\nLaissez refroidir avant de démouler.",
        "question_fr": "Quand faut-il ajouter l'huile ?",
        "options": [
            {"id": "a", "text": "Avant la farine",
             "explanation": "The order is explicit: flour first, then the oil « en dernier »."},
            {"id": "b", "text": "En même temps que les œufs",
             "explanation": "The eggs belong to the first step, with the yoghurt and sugar."},
            {"id": "c", "text": "Après la cuisson",
             "explanation": "Nothing is added after baking; the last step is cooling and turning out."},
            {"id": "d", "text": "Après la farine",
             "explanation": "« Ajoutez la farine, puis l'huile en dernier » puts the oil after the flour."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Ajoutez la farine, puis l'huile en dernier.",
        "key_line_en": "Add the flour, then the oil last.",
        "vocabulary": [
            {"term": "la farine", "gloss": "flour"},
            {"term": "en dernier", "gloss": "last"},
            {"term": "faire cuire", "gloss": "to bake, cook"},
            {"term": "démouler", "gloss": "to turn out of the tin"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Conditions de billet / Ticket conditions",
        "topic": "Transports & voyages",
        "text": "BILLET TARIF ÉCO\nÉchange possible jusqu'à 24 h avant le départ, moyennant 15 €.\nAucun remboursement après l'achat.\nBillet nominatif, non transmissible.",
        "question_fr": "Que peut faire le voyageur avec ce billet ?",
        "options": [
            {"id": "a", "text": "Le changer avant le départ en payant",
             "explanation": "Exchange is allowed up to 24 hours before departure, for a €15 fee."},
            {"id": "b", "text": "Se faire rembourser à tout moment",
             "explanation": "« Aucun remboursement après l'achat » rules refunds out entirely."},
            {"id": "c", "text": "Le donner à un ami",
             "explanation": "« nominatif, non transmissible » means it is in one name and cannot be passed on."},
            {"id": "d", "text": "L'échanger gratuitement",
             "explanation": "The exchange exists but costs €15; it is not free."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Échange possible jusqu'à 24 h avant le départ, moyennant 15 €.",
        "key_line_en": "Exchange possible up to 24 hours before departure, for a €15 charge.",
        "vocabulary": [
            {"term": "moyennant", "gloss": "for, in return for"},
            {"term": "un remboursement", "gloss": "a refund"},
            {"term": "nominatif", "gloss": "in a named person's name"},
            {"term": "transmissible", "gloss": "transferable"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Annonce de bibliothèque / Library announcement",
        "topic": "Études & formation",
        "text": "ATELIER D'ÉCRITURE\nTous les samedis de 10 h à 12 h, salle 3.\nGratuit pour les inscrits à la bibliothèque.\nNombre de places limité : inscription obligatoire à l'accueil.",
        "question_fr": "Comment participer à cet atelier ?",
        "options": [
            {"id": "a", "text": "Payer une participation sur place",
             "explanation": "The workshop is free for library members; no payment is asked."},
            {"id": "b", "text": "S'inscrire à l'avance à l'accueil",
             "explanation": "Places are limited and « inscription obligatoire à l'accueil » makes booking at the desk compulsory."},
            {"id": "c", "text": "Venir directement le samedi matin",
             "explanation": "Turning up is not enough: booking is required because places are limited."},
            {"id": "d", "text": "Envoyer un texte avant l'atelier",
             "explanation": "Nothing has to be written or sent beforehand."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nombre de places limité : inscription obligatoire à l'accueil.",
        "key_line_en": "Limited number of places: booking at the front desk is compulsory.",
        "vocabulary": [
            {"term": "un atelier", "gloss": "a workshop"},
            {"term": "une inscription", "gloss": "registration, booking"},
            {"term": "les inscrits", "gloss": "registered members"},
            {"term": "l'accueil", "gloss": "reception desk"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Confirmation de réservation / Booking confirmation",
        "topic": "Transports & voyages",
        "text": "Votre réservation est confirmée.\nArrivée : à partir de 15 h. Départ : avant 11 h.\nLe petit-déjeuner est servi de 7 h à 9 h 30, en supplément (9 € par personne).\nAnnulation gratuite jusqu'à 48 h avant l'arrivée.",
        "question_fr": "Que dit ce message au sujet du petit-déjeuner ?",
        "options": [
            {"id": "a", "text": "Il est compris dans le prix",
             "explanation": "« en supplément » means it costs extra, on top of the room."},
            {"id": "b", "text": "Il est servi jusqu'à 11 h",
             "explanation": "11 a.m. is the check-out time. Breakfast stops at 9:30."},
            {"id": "c", "text": "Il coûte 9 € par personne",
             "explanation": "The price is stated: « en supplément (9 € par personne) »."},
            {"id": "d", "text": "Il faut le réserver 48 h à l'avance",
             "explanation": "The 48 hours concern free cancellation of the room, not breakfast."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le petit-déjeuner est servi de 7 h à 9 h 30, en supplément (9 € par personne).",
        "key_line_en": "Breakfast is served from 7:00 to 9:30, at an extra charge (€9 per person).",
        "vocabulary": [
            {"term": "en supplément", "gloss": "at extra cost"},
            {"term": "une annulation", "gloss": "a cancellation"},
            {"term": "à partir de", "gloss": "from (a time onwards)"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Information aux voyageurs / Passenger information",
        "topic": "Transports & voyages",
        "text": "LIGNE 14 — MODIFICATION\nÀ partir du 2 avril, le dernier bus partira à 22 h 15 au lieu de 23 h.\nLe premier départ reste inchangé.\nUne navette de nuit dessert la gare le vendredi et le samedi.",
        "question_fr": "Qu'est-ce qui change sur la ligne 14 ?",
        "options": [
            {"id": "a", "text": "L'heure du premier bus",
             "explanation": "« Le premier départ reste inchangé » — the first departure is explicitly unchanged."},
            {"id": "b", "text": "Le trajet de la ligne",
             "explanation": "The route is not modified; only a departure time is."},
            {"id": "c", "text": "L'heure du dernier bus",
             "explanation": "The last bus moves from 23:00 to 22:15 from 2 April."},
            {"id": "d", "text": "Le prix du billet",
             "explanation": "No fare is mentioned in the notice."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le dernier bus partira à 22 h 15 au lieu de 23 h.",
        "key_line_en": "The last bus will leave at 22:15 instead of 23:00.",
        "vocabulary": [
            {"term": "au lieu de", "gloss": "instead of"},
            {"term": "inchangé", "gloss": "unchanged"},
            {"term": "une navette", "gloss": "a shuttle"},
            {"term": "desservir", "gloss": "to serve (a stop, an area)"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Article de presse / Press article",
        "topic": "Environnement & nature",
        "text": "Depuis janvier, l'entreprise a retiré toutes les bouteilles en plastique de ses bureaux et installé des fontaines à eau.\n« Certains salariés ont d'abord protesté », reconnaît la directrice. « Mais nous avons offert une gourde à chacun, et les réticences sont tombées en quelques semaines. »",
        "question_fr": "Comment l'entreprise a-t-elle fait accepter ce changement ?",
        "options": [
            {"id": "a", "text": "En imposant une amende aux salariés",
             "explanation": "No penalty is mentioned; the approach described is the opposite of a sanction."},
            {"id": "b", "text": "En fournissant une gourde à chaque salarié",
             "explanation": "« nous avons offert une gourde à chacun, et les réticences sont tombées » names the measure and its effect."},
            {"id": "c", "text": "En consultant les salariés avant la décision",
             "explanation": "The bottles were removed first; the protest came after, which shows there was no prior consultation."},
            {"id": "d", "text": "En augmentant les salaires",
             "explanation": "Pay is never discussed in the article."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nous avons offert une gourde à chacun, et les réticences sont tombées en quelques semaines.",
        "key_line_en": "We gave everyone a reusable bottle, and the resistance faded within a few weeks.",
        "vocabulary": [
            {"term": "une gourde", "gloss": "a reusable water bottle"},
            {"term": "une réticence", "gloss": "reluctance, resistance"},
            {"term": "reconnaître", "gloss": "to admit"},
            {"term": "retirer", "gloss": "to remove, withdraw"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "topic": "Alimentation & consommation",
        "text": "Selon une enquête menée auprès de 1 500 jeunes de 18 à 25 ans, huit sur dix déclarent aimer cuisiner.\nPourtant, la moitié d'entre eux préparent un vrai repas moins d'une fois par semaine, faute de temps plutôt que d'envie.",
        "question_fr": "Que révèle cette enquête ?",
        "options": [
            {"id": "a", "text": "Les jeunes n'aiment pas cuisiner",
             "explanation": "Eight out of ten say they enjoy cooking; the taste is there."},
            {"id": "b", "text": "Les jeunes cuisinent tous les jours",
             "explanation": "Half of them cook a real meal less than once a week."},
            {"id": "c", "text": "L'envie de cuisiner ne se traduit pas en pratique",
             "explanation": "« Pourtant » sets the liking against the practice: they enjoy it but rarely do it, « faute de temps »."},
            {"id": "d", "text": "Les jeunes trouvent la cuisine trop difficile",
             "explanation": "The obstacle named is time, explicitly « plutôt que d'envie » — not difficulty."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La moitié d'entre eux préparent un vrai repas moins d'une fois par semaine, faute de temps plutôt que d'envie.",
        "key_line_en": "Half of them cook a proper meal less than once a week, for lack of time rather than desire.",
        "vocabulary": [
            {"term": "faute de", "gloss": "for lack of"},
            {"term": "pourtant", "gloss": "yet, however"},
            {"term": "l'envie", "gloss": "the desire, wish"},
            {"term": "déclarer", "gloss": "to state, report"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Lettre de réclamation / Letter of complaint",
        "topic": "Santé & bien-être",
        "text": "Madame, Monsieur,\nJe suis abonné à votre salle depuis deux ans. Or la piscine, qui figure dans mon abonnement, est fermée depuis six semaines sans qu'aucune date de réouverture ne soit annoncée.\nJe demande un geste commercial sur les mois concernés, ou la possibilité de suspendre mon abonnement sans frais.",
        "question_fr": "Que demande ce client ?",
        "options": [
            {"id": "a", "text": "La réouverture immédiate de la piscine",
             "explanation": "He complains about the closure but asks for compensation or a pause, not for the pool to reopen."},
            {"id": "b", "text": "La résiliation définitive de son abonnement",
             "explanation": "He asks to suspend it, which is temporary; nothing suggests he wants to leave for good."},
            {"id": "c", "text": "Une compensation ou une suspension gratuite",
             "explanation": "The two requests are stated as alternatives: « un geste commercial […] ou la possibilité de suspendre […] sans frais »."},
            {"id": "d", "text": "Un changement de salle de sport",
             "explanation": "No transfer to another gym is requested."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Je demande un geste commercial sur les mois concernés, ou la possibilité de suspendre mon abonnement sans frais.",
        "key_line_en": "I am asking for a gesture of goodwill on the months concerned, or the option to suspend my membership free of charge.",
        "vocabulary": [
            {"term": "un abonnement", "gloss": "a membership, subscription"},
            {"term": "un geste commercial", "gloss": "a gesture of goodwill (discount, credit)"},
            {"term": "sans frais", "gloss": "free of charge"},
            {"term": "or", "gloss": "now, yet (introducing a contrast)"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Chronique santé / Health column",
        "topic": "Santé & bien-être",
        "text": "Inutile de s'inscrire dans une salle pour être en forme : marcher trente minutes par jour d'un bon pas produit des effets comparables sur le cœur.\nL'avantage décisif de la marche n'est pas son efficacité, c'est qu'on l'abandonne rarement.",
        "question_fr": "Selon l'auteur, quel est le principal atout de la marche ?",
        "options": [
            {"id": "a", "text": "Elle est plus efficace que la salle de sport",
             "explanation": "The text says the effects are « comparables », not superior — and explicitly denies that efficiency is the decisive point."},
            {"id": "b", "text": "Elle ne coûte rien",
             "explanation": "Cost is implied by « inutile de s'inscrire » but is never named as the decisive advantage."},
            {"id": "c", "text": "On continue à la pratiquer dans la durée",
             "explanation": "« l'avantage décisif […] c'est qu'on l'abandonne rarement » — people stick with it."},
            {"id": "d", "text": "Elle demande moins de trente minutes par jour",
             "explanation": "Thirty minutes is exactly what is recommended, not an upper limit to undercut."},
        ],
        "correct_answer": "c",
        "key_line_fr": "L'avantage décisif de la marche n'est pas son efficacité, c'est qu'on l'abandonne rarement.",
        "key_line_en": "Walking's decisive advantage is not its effectiveness, it is that people rarely give it up.",
        "vocabulary": [
            {"term": "d'un bon pas", "gloss": "at a brisk pace"},
            {"term": "décisif", "gloss": "decisive"},
            {"term": "abandonner", "gloss": "to give up"},
            {"term": "être en forme", "gloss": "to be fit"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Offre d'emploi / Job advert",
        "topic": "Travail & emploi",
        "text": "Cabinet médical recherche un(e) secrétaire.\nLe poste exige une parfaite maîtrise du français écrit ; la connaissance d'une seconde langue est appréciée.\nExpérience en milieu médical souhaitée mais non exigée : une formation interne est prévue.",
        "question_fr": "Quelle est la seule condition véritablement obligatoire ?",
        "options": [
            {"id": "a", "text": "Parler une deuxième langue",
             "explanation": "« appréciée » marks it as welcome, not required."},
            {"id": "b", "text": "Avoir travaillé dans le milieu médical",
             "explanation": "« souhaitée mais non exigée » says it in as many words: desirable, not compulsory."},
            {"id": "c", "text": "Maîtriser parfaitement le français écrit",
             "explanation": "« Le poste exige » applies to written French alone — it is the one non-negotiable requirement."},
            {"id": "d", "text": "Avoir suivi une formation médicale",
             "explanation": "Training is provided by the employer, so it cannot be a condition of applying."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le poste exige une parfaite maîtrise du français écrit.",
        "key_line_en": "The post requires a perfect command of written French.",
        "vocabulary": [
            {"term": "exiger", "gloss": "to require"},
            {"term": "souhaité", "gloss": "desirable"},
            {"term": "apprécié", "gloss": "valued, welcome"},
            {"term": "la maîtrise", "gloss": "command, mastery"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Article municipal / Local news",
        "topic": "Transports & voyages",
        "text": "La ville teste depuis six mois un service de bus de nuit le week-end. La fréquentation dépasse les prévisions, surtout chez les moins de trente ans.\nLes commerçants du centre, d'abord sceptiques, demandent aujourd'hui son extension au jeudi soir.",
        "question_fr": "Quelle est la position actuelle des commerçants ?",
        "options": [
            {"id": "a", "text": "Ils réclament un service plus étendu",
             "explanation": "« d'abord sceptiques, demandent aujourd'hui son extension au jeudi soir » — they now want it extended."},
            {"id": "b", "text": "Ils s'opposent toujours au service",
             "explanation": "« d'abord sceptiques » places the opposition in the past; « aujourd'hui » marks the reversal."},
            {"id": "c", "text": "Ils demandent la suppression du service",
             "explanation": "The opposite of extension; nothing suggests they want it stopped."},
            {"id": "d", "text": "Ils souhaitent un service réservé aux jeunes",
             "explanation": "Under-thirties are simply the biggest user group, not a restriction anyone is asking for."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les commerçants du centre, d'abord sceptiques, demandent aujourd'hui son extension au jeudi soir.",
        "key_line_en": "The town-centre shopkeepers, sceptical at first, are now asking for it to be extended to Thursday evenings.",
        "vocabulary": [
            {"term": "la fréquentation", "gloss": "usage, number of users"},
            {"term": "les prévisions", "gloss": "forecasts"},
            {"term": "sceptique", "gloss": "sceptical"},
            {"term": "une extension", "gloss": "an extension"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Appel à participation / Call for participants",
        "topic": "Environnement & nature",
        "text": "Le jardin partagé du quartier cherche de nouveaux participants.\nChaque famille dispose d'une parcelle et s'engage à venir au moins deux fois par mois, y compris en hiver.\n« Les récoltes se partagent, mais l'entretien aussi », rappelle le responsable.",
        "question_fr": "Qu'implique la participation à ce jardin ?",
        "options": [
            {"id": "a", "text": "Venir uniquement pendant la belle saison",
             "explanation": "« y compris en hiver » makes the commitment year-round."},
            {"id": "b", "text": "Payer une parcelle chaque mois",
             "explanation": "No fee is mentioned; what is asked is presence and work."},
            {"id": "c", "text": "Participer régulièrement à l'entretien",
             "explanation": "Twice a month minimum, all year, and « l'entretien aussi » se partage — upkeep is shared, not just the harvest."},
            {"id": "d", "text": "Céder ses récoltes à l'association",
             "explanation": "« Les récoltes se partagent » — they are shared among participants, not handed over."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les récoltes se partagent, mais l'entretien aussi.",
        "key_line_en": "The harvest is shared, but so is the upkeep.",
        "vocabulary": [
            {"term": "une parcelle", "gloss": "a plot"},
            {"term": "s'engager à", "gloss": "to commit to"},
            {"term": "une récolte", "gloss": "a harvest"},
            {"term": "l'entretien", "gloss": "upkeep, maintenance"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "topic": "Études & formation",
        "text": "Le débat sur les devoirs oppose depuis trente ans les mêmes arguments. On oublie l'essentiel : à quantité égale, un devoir corrigé et repris en classe fait progresser, un devoir simplement rendu ne fait rien.\nCe n'est pas la charge qu'il faudrait discuter, c'est ce qu'on en fait ensuite.",
        "question_fr": "Quel déplacement l'auteur propose-t-il dans le débat ?",
        "options": [
            {"id": "a", "text": "Passer de la quantité de devoirs à leur exploitation",
             "explanation": "« Ce n'est pas la charge […] c'est ce qu'on en fait ensuite » moves the question from how much to what is done with it."},
            {"id": "b", "text": "Supprimer complètement les devoirs",
             "explanation": "Abolition is never proposed; homework that is corrected and reused is presented as effective."},
            {"id": "c", "text": "Augmenter la quantité de devoirs",
             "explanation": "The author explicitly sets quantity aside (« à quantité égale »)."},
            {"id": "d", "text": "Confier la correction aux parents",
             "explanation": "The correction discussed happens « en classe »; parents are not mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce n'est pas la charge qu'il faudrait discuter, c'est ce qu'on en fait ensuite.",
        "key_line_en": "It is not the workload that should be debated, but what is done with it afterwards.",
        "vocabulary": [
            {"term": "la charge", "gloss": "the workload"},
            {"term": "reprendre", "gloss": "to go back over"},
            {"term": "à quantité égale", "gloss": "for an equal amount"},
            {"term": "l'essentiel", "gloss": "the main point"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "topic": "Santé & bien-être",
        "text": "Les campagnes manquent de médecins, et l'on répond par des primes à l'installation. Les résultats déçoivent : un médecin s'installe là où son conjoint trouve du travail et où ses enfants trouvent une école.\nTant que ces conditions manqueront, aucune prime ne sera assez élevée.",
        "question_fr": "Pourquoi les primes échouent-elles, selon l'auteur ?",
        "options": [
            {"id": "a", "text": "Parce que leur montant est trop faible",
             "explanation": "The last sentence rules this out: « aucune prime ne sera assez élevée » — no amount would suffice."},
            {"id": "b", "text": "Parce qu'elles arrivent trop tard",
             "explanation": "Timing is never discussed; the obstacle described is the surrounding environment."},
            {"id": "c", "text": "Parce que le choix dépend de l'entourage familial",
             "explanation": "The doctor settles where the partner finds work and the children find a school — money cannot supply either."},
            {"id": "d", "text": "Parce que les médecins préfèrent les hôpitaux",
             "explanation": "Hospitals are not mentioned; the contrast is rural versus urban living conditions."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Un médecin s'installe là où son conjoint trouve du travail et où ses enfants trouvent une école.",
        "key_line_en": "A doctor settles where their partner finds work and their children find a school.",
        "vocabulary": [
            {"term": "une prime", "gloss": "a bonus, incentive payment"},
            {"term": "s'installer", "gloss": "to set up (a practice), settle"},
            {"term": "un conjoint", "gloss": "a spouse, partner"},
            {"term": "tant que", "gloss": "as long as"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Critique de film / Film review",
        "topic": "Loisirs, culture & médias",
        "text": "Le film tient sur les épaules de son actrice principale, absolument remarquable. Autour d'elle, hélas, le scénario multiplie les personnages sans jamais leur donner d'épaisseur.\nOn sort convaincu par une interprétation, pas par une histoire.",
        "question_fr": "Que reproche le critique à ce film ?",
        "options": [
            {"id": "a", "text": "Le jeu de l'actrice principale",
             "explanation": "Her performance is what the reviewer admires: « absolument remarquable »."},
            {"id": "b", "text": "Le manque de consistance du scénario",
             "explanation": "« sans jamais leur donner d'épaisseur » plus « pas par une histoire » target the writing, not the acting."},
            {"id": "c", "text": "La longueur excessive du film",
             "explanation": "Running time is never mentioned."},
            {"id": "d", "text": "Le nombre insuffisant de personnages",
             "explanation": "The opposite: the script « multiplie les personnages ». The fault is depth, not number."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On sort convaincu par une interprétation, pas par une histoire.",
        "key_line_en": "You leave convinced by a performance, not by a story.",
        "vocabulary": [
            {"term": "tenir sur les épaules de", "gloss": "to rest on the shoulders of"},
            {"term": "l'épaisseur", "gloss": "depth, substance"},
            {"term": "un scénario", "gloss": "a screenplay"},
            {"term": "une interprétation", "gloss": "a performance"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "topic": "Environnement & nature",
        "text": "Trier ses déchets est utile, mais l'ordre des priorités est souvent inversé dans les esprits.\nRéduire ce que l'on achète évite cent fois plus d'émissions que recycler ce que l'on a acheté. Le recyclage est la dernière étape d'une chaîne, pas la première.",
        "question_fr": "Quelle idée l'auteur cherche-t-il à corriger ?",
        "options": [
            {"id": "a", "text": "L'idée que le recyclage serait inutile",
             "explanation": "The author calls sorting « utile »; he ranks it, he does not dismiss it."},
            {"id": "b", "text": "L'idée que recycler suffit à agir",
             "explanation": "He reorders the priorities: buying less avoids a hundred times more than recycling, which is « la dernière étape […] pas la première »."},
            {"id": "c", "text": "L'idée que réduire sa consommation est impossible",
             "explanation": "Feasibility is never discussed, only effectiveness."},
            {"id": "d", "text": "L'idée que les émissions sont mal mesurées",
             "explanation": "Measurement is not questioned; the figures are used as given."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Le recyclage est la dernière étape d'une chaîne, pas la première.",
        "key_line_en": "Recycling is the last step in a chain, not the first.",
        "vocabulary": [
            {"term": "les déchets", "gloss": "waste"},
            {"term": "inversé", "gloss": "reversed"},
            {"term": "une étape", "gloss": "a step, stage"},
            {"term": "les émissions", "gloss": "emissions"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "topic": "Travail & emploi",
        "text": "Bonjour à tous,\nLe client accepte le report de la livraison au 30 mai, ce qui nous laisse trois semaines de plus. Je préfère être claire : ce délai ne servira pas à ajouter des fonctionnalités, mais à stabiliser ce qui existe.\nToute nouvelle demande sera reportée à la version suivante.",
        "question_fr": "Que précise la responsable à propos du délai supplémentaire ?",
        "options": [
            {"id": "a", "text": "Il permettra d'ajouter des fonctionnalités",
             "explanation": "Explicitly ruled out: « ce délai ne servira pas à ajouter des fonctionnalités »."},
            {"id": "b", "text": "Il sera consacré à fiabiliser l'existant",
             "explanation": "« mais à stabiliser ce qui existe » states the sole purpose of the extra three weeks."},
            {"id": "c", "text": "Il a été refusé par le client",
             "explanation": "The opposite: « Le client accepte le report »."},
            {"id": "d", "text": "Il annule la version suivante",
             "explanation": "The next version is precisely where new requests are pushed, so it still exists."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Ce délai ne servira pas à ajouter des fonctionnalités, mais à stabiliser ce qui existe.",
        "key_line_en": "This extra time will not be used to add features, but to stabilise what already exists.",
        "vocabulary": [
            {"term": "un report", "gloss": "a postponement"},
            {"term": "un délai", "gloss": "a deadline, time allowed"},
            {"term": "une fonctionnalité", "gloss": "a feature"},
            {"term": "stabiliser", "gloss": "to stabilise, make reliable"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Analyse économique / Economic analysis",
        "topic": "Travail & emploi",
        "text": "La hausse du salaire minimum a-t-elle détruit des emplois ? Les études récentes penchent pour un effet faible, parfois nul.\nCe résultat ne vaut cependant pas garantie : il a été observé lors de hausses modérées, dans des économies en croissance. Rien ne dit qu'il se répéterait dans d'autres conditions.",
        "question_fr": "Quelle précaution l'auteur ajoute-t-il ?",
        "options": [
            {"id": "a", "text": "Les études citées sont peu nombreuses",
             "explanation": "Their number is never questioned; their scope of validity is."},
            {"id": "b", "text": "Le résultat dépend du contexte où il a été observé",
             "explanation": "Moderate rises, growing economies: « Rien ne dit qu'il se répéterait dans d'autres conditions »."},
            {"id": "c", "text": "La hausse du salaire minimum détruit des emplois",
             "explanation": "The studies find a weak or nil effect; the author does not contradict them."},
            {"id": "d", "text": "Les économistes sont divisés sur la question",
             "explanation": "The text reports a converging finding, not a disagreement between experts."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Rien ne dit qu'il se répéterait dans d'autres conditions.",
        "key_line_en": "There is nothing to say it would hold in other conditions.",
        "vocabulary": [
            {"term": "pencher pour", "gloss": "to lean towards"},
            {"term": "nul", "gloss": "nil, zero"},
            {"term": "valoir garantie", "gloss": "to amount to a guarantee"},
            {"term": "modéré", "gloss": "moderate"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "topic": "Environnement & nature",
        "text": "L'industrie du vêtement produit deux fois plus qu'il y a vingt ans, et nous gardons chaque pièce deux fois moins longtemps.\nLes campagnes de collecte donnent bonne conscience, mais elles traitent l'aval d'un problème qui se joue entièrement à l'amont : dans le rythme des collections.",
        "question_fr": "Que reproche l'auteur aux campagnes de collecte ?",
        "options": [
            {"id": "a", "text": "Elles coûtent trop cher aux collectivités",
             "explanation": "Cost is not discussed anywhere in the extract."},
            {"id": "b", "text": "Elles agissent sur les conséquences et non sur la cause",
             "explanation": "« elles traitent l'aval d'un problème qui se joue entièrement à l'amont » — downstream action, upstream cause."},
            {"id": "c", "text": "Elles récupèrent trop peu de vêtements",
             "explanation": "Their yield is never given; the criticism is about where they act, not how much they collect."},
            {"id": "d", "text": "Elles encouragent à garder ses vêtements trop longtemps",
             "explanation": "Keeping clothes longer is the behaviour the author would welcome, not a criticism."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Elles traitent l'aval d'un problème qui se joue entièrement à l'amont : dans le rythme des collections.",
        "key_line_en": "They address the downstream end of a problem that is decided entirely upstream: in the pace of the collections.",
        "vocabulary": [
            {"term": "l'aval / l'amont", "gloss": "downstream / upstream"},
            {"term": "se jouer", "gloss": "to be decided, played out"},
            {"term": "donner bonne conscience", "gloss": "to ease one's conscience"},
            {"term": "une collecte", "gloss": "a collection drive"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "topic": "Société, citoyenneté & administration",
        "text": "Nous confondons volontiers la vitesse et le mouvement. Une décision prise en trois minutes n'avance à rien si elle doit être défaite en trois mois.\nLa lenteur n'est pas l'ennemie de l'efficacité : elle en est parfois la condition, dès lors qu'elle sert à comprendre plutôt qu'à différer.",
        "question_fr": "Quelle nuance l'auteur apporte-t-il à l'éloge de la lenteur ?",
        "options": [
            {"id": "a", "text": "La lenteur vaut seulement si elle sert à comprendre",
             "explanation": "« dès lors qu'elle sert à comprendre plutôt qu'à différer » is a condition: slowness that merely postpones is not defended."},
            {"id": "b", "text": "La lenteur est toujours préférable à la vitesse",
             "explanation": "Too absolute. The author defends it only under a stated condition."},
            {"id": "c", "text": "Toute décision rapide est une mauvaise décision",
             "explanation": "The criticism targets decisions later undone, not speed as such."},
            {"id": "d", "text": "L'efficacité et la compréhension sont incompatibles",
             "explanation": "The reverse: understanding is presented as sometimes the condition of efficiency."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Elle en est parfois la condition, dès lors qu'elle sert à comprendre plutôt qu'à différer.",
        "key_line_en": "It is sometimes its condition, provided it serves to understand rather than to postpone.",
        "vocabulary": [
            {"term": "dès lors que", "gloss": "provided that, as soon as"},
            {"term": "différer", "gloss": "to postpone"},
            {"term": "défaire", "gloss": "to undo"},
            {"term": "confondre", "gloss": "to confuse (two things)"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "topic": "Société, citoyenneté & administration",
        "text": "La collectivité a publié, comme promis, l'intégralité de ses données : quatre-vingts fichiers, dans un format que trois logiciels seulement savent ouvrir, sans le moindre document expliquant ce que contient chaque colonne.\nLa transparence, décidément, ne se refuse rien.",
        "question_fr": "Que suggère la dernière phrase ?",
        "options": [
            {"id": "a", "text": "Que la collectivité a dépassé ses obligations",
             "explanation": "Read literally it says so — but the preceding details describe data nobody can actually use, which reverses the meaning."},
            {"id": "b", "text": "Que la publication est en réalité inexploitable",
             "explanation": "The ironic praise sits on top of an unusable release: rare formats, no documentation. The author means the opposite of what he writes."},
            {"id": "c", "text": "Que les données publiées sont confidentielles",
             "explanation": "Everything was published; the problem is usability, not secrecy."},
            {"id": "d", "text": "Que la transparence coûte trop cher",
             "explanation": "No cost appears in the text."},
        ],
        "correct_answer": "b",
        "key_line_fr": "La transparence, décidément, ne se refuse rien.",
        "key_line_en": "Transparency, clearly, spares no effort.",
        "vocabulary": [
            {"term": "l'intégralité", "gloss": "the entirety"},
            {"term": "décidément", "gloss": "clearly, really"},
            {"term": "ne se refuser rien", "gloss": "to deny oneself nothing"},
            {"term": "inexploitable", "gloss": "unusable"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "topic": "Travail & emploi",
        "text": "On annonce la fin du bureau depuis que le travail à distance s'est généralisé. L'observation dit autre chose : les entreprises réduisent les surfaces mais multiplient les lieux.\nCe n'est pas le bureau qui disparaît, c'est son unicité.",
        "question_fr": "Quelle évolution l'auteur décrit-il ?",
        "options": [
            {"id": "a", "text": "La disparition complète des bureaux",
             "explanation": "« Ce n'est pas le bureau qui disparaît » denies exactly this."},
            {"id": "b", "text": "Le retour au bureau unique d'avant",
             "explanation": "The opposite: what is ending is precisely the single office."},
            {"id": "c", "text": "Le passage d'un lieu unique à plusieurs lieux",
             "explanation": "« réduisent les surfaces mais multiplient les lieux », summed up as the end of the office's « unicité »."},
            {"id": "d", "text": "L'augmentation des surfaces de bureaux",
             "explanation": "Floor space is being reduced; only the number of sites grows."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ce n'est pas le bureau qui disparaît, c'est son unicité.",
        "key_line_en": "It is not the office that is disappearing, it is its singleness.",
        "vocabulary": [
            {"term": "l'unicité", "gloss": "singleness, being the only one"},
            {"term": "une surface", "gloss": "floor space"},
            {"term": "se généraliser", "gloss": "to become widespread"},
            {"term": "multiplier", "gloss": "to increase the number of"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "topic": "Loisirs, culture & médias",
        "text": "Il connaissait la ville par ses odeurs avant de la connaître par ses rues.\nPlus tard, quand on lui demanderait d'où il venait, il donnerait un nom, une région, une date — tout sauf ce qui était vrai : une boulangerie à six heures du matin, en hiver.",
        "question_fr": "Que suggère ce passage sur le rapport du personnage à son origine ?",
        "options": [
            {"id": "a", "text": "Il a oublié d'où il venait",
             "explanation": "He remembers it precisely — the bakery, the hour, the season. What he does is withhold it."},
            {"id": "b", "text": "Sa véritable origine échappe aux réponses attendues",
             "explanation": "Name, region and date are « tout sauf ce qui était vrai »: the real origin is a sensation the usual categories cannot carry."},
            {"id": "c", "text": "Il refuse de retourner dans sa ville",
             "explanation": "No return, and no refusal to return, appears in the passage."},
            {"id": "d", "text": "Il ment sur son lieu de naissance",
             "explanation": "The name and region he gives are not presented as false, merely as beside the point."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Tout sauf ce qui était vrai : une boulangerie à six heures du matin, en hiver.",
        "key_line_en": "Everything except what was true: a bakery at six in the morning, in winter.",
        "vocabulary": [
            {"term": "une odeur", "gloss": "a smell"},
            {"term": "tout sauf", "gloss": "everything except"},
            {"term": "d'où il venait", "gloss": "where he came from"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "topic": "Sciences & technologies",
        "text": "En nutrition, la plupart des travaux reposent sur des questionnaires déclaratifs : on demande aux participants ce qu'ils ont mangé.\nOr on se souvient mal, et l'on se souvient favorablement. L'erreur n'est pas aléatoire, elle est orientée — ce qui est autrement plus gênant.",
        "question_fr": "Pourquoi cette erreur est-elle particulièrement problématique ?",
        "options": [
            {"id": "a", "text": "Parce qu'elle penche systématiquement dans le même sens",
             "explanation": "« L'erreur n'est pas aléatoire, elle est orientée »: a biased error shifts results, whereas random noise would cancel out."},
            {"id": "b", "text": "Parce qu'elle concerne trop peu de participants",
             "explanation": "Sample size is never mentioned."},
            {"id": "c", "text": "Parce que les participants mentent délibérément",
             "explanation": "The text describes faulty and flattering recall, not deliberate lying."},
            {"id": "d", "text": "Parce que les questionnaires sont trop longs",
             "explanation": "Their length is never discussed, only what they can reliably capture."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'erreur n'est pas aléatoire, elle est orientée — ce qui est autrement plus gênant.",
        "key_line_en": "The error is not random, it is biased — which is far more troubling.",
        "vocabulary": [
            {"term": "déclaratif", "gloss": "self-reported"},
            {"term": "aléatoire", "gloss": "random"},
            {"term": "orienté", "gloss": "biased, skewed"},
            {"term": "autrement plus", "gloss": "far more"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Commentaire institutionnel / Institutional commentary",
        "topic": "Société, citoyenneté & administration",
        "text": "Le décret annonce une obligation, puis en confie l'application à des textes ultérieurs dont il ne fixe ni le contenu ni l'échéance.\nL'obligation existe donc, mais nul ne saurait dire à partir de quand ni en quoi elle consiste.",
        "question_fr": "Que souligne l'auteur au sujet de ce décret ?",
        "options": [
            {"id": "a", "text": "Il annule une obligation antérieure",
             "explanation": "It creates an obligation; nothing earlier is repealed."},
            {"id": "b", "text": "Il impose une obligation trop coûteuse",
             "explanation": "Cost is never mentioned; the objection is about content and timing."},
            {"id": "c", "text": "Il crée une obligation sans contenu ni date d'effet",
             "explanation": "Both are missing: « ni le contenu ni l'échéance », so the duty exists on paper alone."},
            {"id": "d", "text": "Il est plus strict que ce qui était annoncé",
             "explanation": "Its strictness cannot even be assessed, since what it requires is undefined."},
        ],
        "correct_answer": "c",
        "key_line_fr": "L'obligation existe donc, mais nul ne saurait dire à partir de quand ni en quoi elle consiste.",
        "key_line_en": "The obligation therefore exists, but nobody could say from when, or what it consists of.",
        "vocabulary": [
            {"term": "un décret", "gloss": "a decree"},
            {"term": "ultérieur", "gloss": "subsequent, later"},
            {"term": "une échéance", "gloss": "a deadline, due date"},
            {"term": "nul ne saurait", "gloss": "nobody could"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Analyse du monde du travail / Workplace analysis",
        "topic": "Travail & emploi",
        "text": "On mesure la charge de travail en heures, jamais en interruptions. C'est pourtant là que se joue l'épuisement : non dans la durée d'une tâche, mais dans le nombre de fois qu'il faut la recommencer.\nUne journée de sept heures hachées fatigue davantage que neuf heures continues.",
        "question_fr": "Quelle est la thèse de l'auteur sur l'épuisement au travail ?",
        "options": [
            {"id": "a", "text": "Il faudrait réduire la durée du travail",
             "explanation": "The text's own example shows nine continuous hours being less tiring than seven fragmented ones, which cuts against duration as the lever."},
            {"id": "b", "text": "La fragmentation fatigue plus que la durée",
             "explanation": "Exhaustion lies « dans le nombre de fois qu'il faut la recommencer », and the seven-versus-nine-hours example makes it explicit."},
            {"id": "c", "text": "Les interruptions sont impossibles à mesurer",
             "explanation": "He observes that they are not measured, not that they could not be."},
            {"id": "d", "text": "Les tâches longues devraient être découpées",
             "explanation": "The opposite of what the argument supports: cutting tasks up is precisely what tires people out."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une journée de sept heures hachées fatigue davantage que neuf heures continues.",
        "key_line_en": "A seven-hour day cut into pieces is more tiring than nine continuous hours.",
        "vocabulary": [
            {"term": "haché", "gloss": "chopped up, fragmented"},
            {"term": "l'épuisement", "gloss": "exhaustion, burnout"},
            {"term": "recommencer", "gloss": "to start again"},
            {"term": "se jouer", "gloss": "to be decided"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai sur la photographie / Essay on photography",
        "topic": "Loisirs, culture & médias",
        "text": "La photographie ne conserve pas le souvenir : elle le remplace. Ce dont nous nous souvenons d'une enfance abondamment photographiée, ce sont les photographies.\nElles n'ouvrent pas sur le passé, elles en tiennent lieu — et l'on prend cette substitution pour de la fidélité.",
        "question_fr": "Quelle est la thèse de l'auteur ?",
        "options": [
            {"id": "a", "text": "La photographie se substitue au souvenir qu'elle prétend garder",
             "explanation": "« elle le remplace », « elles en tiennent lieu », and we mistake this substitution for faithfulness."},
            {"id": "b", "text": "La photographie fixe fidèlement le passé",
             "explanation": "That belief is precisely what the last clause identifies as the error."},
            {"id": "c", "text": "Les souvenirs d'enfance sont peu fiables par nature",
             "explanation": "The unreliability described comes from the photographs, not from childhood memory as such."},
            {"id": "d", "text": "Il faudrait photographier davantage l'enfance",
             "explanation": "No recommendation is made; abundant photography is the situation being criticised."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Elles n'ouvrent pas sur le passé, elles en tiennent lieu.",
        "key_line_en": "They do not open onto the past, they stand in its place.",
        "vocabulary": [
            {"term": "tenir lieu de", "gloss": "to stand in for, take the place of"},
            {"term": "abondamment", "gloss": "abundantly"},
            {"term": "une substitution", "gloss": "a substitution"},
            {"term": "la fidélité", "gloss": "faithfulness, accuracy"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "topic": "Société, citoyenneté & administration",
        "text": "On reproche aux assemblées de mal représenter la société. Le reproche est juste, mais il vise souvent la mauvaise cible : ce n'est pas la composition des élus qui décide, c'est le calendrier qui les contraint.\nUne assemblée parfaitement représentative, sommée de trancher en huit jours, délibérerait aussi mal que la précédente.",
        "question_fr": "Où l'auteur situe-t-il le véritable problème ?",
        "options": [
            {"id": "a", "text": "Dans le manque de diversité des élus",
             "explanation": "He grants the criticism but calls it « la mauvaise cible »: composition is not what decides."},
            {"id": "b", "text": "Dans les contraintes de temps imposées à la délibération",
             "explanation": "« c'est le calendrier qui les contraint », proved by the thought experiment: even a perfect assembly rushed in eight days would deliberate badly."},
            {"id": "c", "text": "Dans l'incompétence des représentants",
             "explanation": "Competence is never raised; the argument holds even for an ideal assembly."},
            {"id": "d", "text": "Dans le désintérêt des citoyens",
             "explanation": "Citizens' engagement is not part of the argument."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une assemblée parfaitement représentative, sommée de trancher en huit jours, délibérerait aussi mal que la précédente.",
        "key_line_en": "A perfectly representative assembly, ordered to decide within a week, would deliberate just as badly as the last one.",
        "vocabulary": [
            {"term": "sommé de", "gloss": "ordered to, required to"},
            {"term": "trancher", "gloss": "to settle, decide"},
            {"term": "contraindre", "gloss": "to constrain"},
            {"term": "viser", "gloss": "to target, aim at"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Critique d'architecture / Architecture review",
        "topic": "Loisirs, culture & médias",
        "text": "Le bâtiment est irréprochable : proportions justes, matériaux nobles, lumière calculée. On l'admire comme on admire une démonstration.\nIl lui manque seulement ce qu'aucun plan ne prévoit — la trace de ceux qui l'habiteront, et le droit de le déformer.",
        "question_fr": "Que reproche le critique à ce bâtiment ?",
        "options": [
            {"id": "a", "text": "Ses matériaux et ses proportions sont mal choisis",
             "explanation": "Both are praised without reserve: « proportions justes, matériaux nobles »."},
            {"id": "b", "text": "Il est trop coûteux pour ses futurs habitants",
             "explanation": "No price and no occupants' means are mentioned."},
            {"id": "c", "text": "Il ne laisse aucune place à l'appropriation par ses habitants",
             "explanation": "What it lacks is « la trace de ceux qui l'habiteront, et le droit de le déformer » — room to be lived in and altered."},
            {"id": "d", "text": "Il manque de lumière naturelle",
             "explanation": "The light is described as « calculée », part of the building's technical success."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Il lui manque seulement ce qu'aucun plan ne prévoit — la trace de ceux qui l'habiteront, et le droit de le déformer.",
        "key_line_en": "It lacks only what no plan provides for — the mark of those who will live in it, and the right to distort it.",
        "vocabulary": [
            {"term": "irréprochable", "gloss": "faultless"},
            {"term": "noble (matériau)", "gloss": "high-quality, fine (material)"},
            {"term": "déformer", "gloss": "to distort, reshape"},
            {"term": "prévoir", "gloss": "to provide for, anticipate"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "topic": "Sciences & technologies",
        "text": "L'expert se distingue du profane moins par l'étendue de ce qu'il sait que par la précision de ce qu'il ignore.\nCelui qui ne peut pas dire où s'arrête sa compétence n'en a pas : il a des opinions, ce qui est une autre affaire.",
        "question_fr": "Quel critère définit l'expertise selon l'auteur ?",
        "options": [
            {"id": "a", "text": "La quantité de connaissances accumulées",
             "explanation": "« moins par l'étendue de ce qu'il sait » explicitly demotes breadth of knowledge."},
            {"id": "b", "text": "La capacité à délimiter sa propre compétence",
             "explanation": "Expertise is « la précision de ce qu'il ignore »: whoever cannot say where their competence stops does not have any."},
            {"id": "c", "text": "La reconnaissance par les autres spécialistes",
             "explanation": "Peer recognition plays no part in the definition given."},
            {"id": "d", "text": "La force des opinions que l'on défend",
             "explanation": "Opinions are set against expertise, as « une autre affaire »."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Celui qui ne peut pas dire où s'arrête sa compétence n'en a pas.",
        "key_line_en": "Anyone who cannot say where their competence ends does not have any.",
        "vocabulary": [
            {"term": "un profane", "gloss": "a layperson"},
            {"term": "l'étendue", "gloss": "the extent, breadth"},
            {"term": "ignorer", "gloss": "not to know"},
            {"term": "une autre affaire", "gloss": "a different matter"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "topic": "Société, citoyenneté & administration",
        "text": "On a installé des bancs sans dossier, séparés par des accoudoirs, devant la gare rénovée.\nLe mobilier ne dit rien, bien sûr ; il se contente d'empêcher. Il aura fallu beaucoup de réunions pour qu'une ville apprenne à refuser sans jamais l'écrire.",
        "question_fr": "Que dénonce l'auteur ?",
        "options": [
            {"id": "a", "text": "Le coût excessif de la rénovation de la gare",
             "explanation": "No budget or cost appears; the target is the design of the seating."},
            {"id": "b", "text": "Le manque de bancs devant la gare",
             "explanation": "Benches were installed. The objection is to how they were designed, not to their absence."},
            {"id": "c", "text": "Un refus d'accueil rendu invisible par le mobilier",
             "explanation": "Armrests and no backrest stop anyone lying down: « refuser sans jamais l'écrire » — exclusion enforced by objects rather than by a rule."},
            {"id": "d", "text": "La lenteur des décisions municipales",
             "explanation": "The many meetings are an ironic jab at the deliberateness of the choice, not a complaint about slowness."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Il aura fallu beaucoup de réunions pour qu'une ville apprenne à refuser sans jamais l'écrire.",
        "key_line_en": "It must have taken many meetings for a city to learn how to refuse without ever writing it down.",
        "vocabulary": [
            {"term": "un dossier (de banc)", "gloss": "a backrest"},
            {"term": "un accoudoir", "gloss": "an armrest"},
            {"term": "le mobilier (urbain)", "gloss": "(street) furniture"},
            {"term": "se contenter de", "gloss": "to do no more than"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai sur l'amitié / Essay on friendship",
        "topic": "Société, citoyenneté & administration",
        "text": "Le réseau a fait de l'ami une unité comptable. On les additionne désormais, ce qui aurait paru absurde à toute époque antérieure.\nL'amitié ne supporte pourtant pas le nombre : elle demande du temps, et le temps, lui, ne se multiplie pas.",
        "question_fr": "Sur quoi repose l'argument de l'auteur ?",
        "options": [
            {"id": "a", "text": "Sur le caractère non extensible du temps",
             "explanation": "Friendship demands time, « et le temps, lui, ne se multiplie pas » — the finite resource is what caps the number."},
            {"id": "b", "text": "Sur la mauvaise qualité des relations en ligne",
             "explanation": "Online relationships are not judged as inferior; what is criticised is counting them."},
            {"id": "c", "text": "Sur la nostalgie des époques antérieures",
             "explanation": "Earlier ages are cited to make the counting look absurd, not held up as better."},
            {"id": "d", "text": "Sur le fait que l'amitié serait devenue rare",
             "explanation": "Rarity is never claimed; the argument concerns arithmetic, not scarcity."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Elle demande du temps, et le temps, lui, ne se multiplie pas.",
        "key_line_en": "It requires time, and time, for its part, does not multiply.",
        "vocabulary": [
            {"term": "comptable", "gloss": "countable, accounting-related"},
            {"term": "additionner", "gloss": "to add up"},
            {"term": "antérieur", "gloss": "earlier, previous"},
            {"term": "supporter", "gloss": "to tolerate, withstand"},
        ],
    },
]

QUESTIONS = balance(_RAW)
