"""Compréhension écrite — Test 02.

Forty questions climbing A1 → C2. Distribution: A1 6, A2 7, B1 7, B2 7, C1 7,
C2 6. French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Horaires / Opening hours",
        "text": "PHARMACIE DU CENTRE\nOuverte de 9 h à 19 h du lundi au samedi.\nFermée le dimanche.\nPharmacie de garde : 12, rue Pasteur.",
        "question_fr": "Où aller le dimanche ?",
        "options": [
            {"id": "a", "text": "À la pharmacie du Centre",
             "explanation": "It is closed on Sundays — that is precisely why another address is given."},
            {"id": "b", "text": "Au 12, rue Pasteur",
             "explanation": "The « pharmacie de garde » is the duty chemist, and its address is given for exactly this situation."},
            {"id": "c", "text": "À l'hôpital",
             "explanation": "No hospital is mentioned on the notice."},
            {"id": "d", "text": "Chez le médecin",
             "explanation": "The notice is about pharmacies, not doctors."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Fermée le dimanche. Pharmacie de garde : 12, rue Pasteur.",
        "key_line_en": "Closed on Sundays. Duty chemist: 12, rue Pasteur.",
        "vocabulary": [
            {"term": "une pharmacie de garde", "gloss": "duty/on-call chemist"},
            {"term": "fermé", "gloss": "closed"},
            {"term": "du lundi au samedi", "gloss": "Monday to Saturday"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Mot de l'école / Note from school",
        "text": "Chers parents,\nJeudi, les enfants vont au musée. Départ à 9 h, retour à 16 h.\nPrévoir un pique-nique et un manteau.\nLa directrice",
        "question_fr": "Que doivent apporter les enfants ?",
        "options": [
            {"id": "a", "text": "De l'argent",
             "explanation": "No money is asked for; the trip's cost is not mentioned."},
            {"id": "b", "text": "Un livre",
             "explanation": "No book is requested anywhere in the note."},
            {"id": "c", "text": "Un repas et un manteau",
             "explanation": "« Prévoir un pique-nique et un manteau » — a packed lunch and a coat."},
            {"id": "d", "text": "Un cahier et un stylo",
             "explanation": "No school supplies are mentioned for this outing."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Prévoir un pique-nique et un manteau.",
        "key_line_en": "Bring a picnic lunch and a coat.",
        "vocabulary": [
            {"term": "prévoir", "gloss": "to bring, plan for"},
            {"term": "un manteau", "gloss": "a coat"},
            {"term": "le départ / le retour", "gloss": "departure / return"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Panneau / Sign",
        "text": "LAVERIE 24 H / 24\nMachine : 4 €. Séchoir : 1 € les 10 minutes.\nLessive en vente à l'accueil.\nNe pas laisser le linge sans surveillance.",
        "question_fr": "Combien coûte une machine ?",
        "options": [
            {"id": "a", "text": "1 €",
             "explanation": "€1 is the price of ten minutes in the dryer, not of a wash."},
            {"id": "b", "text": "10 €",
             "explanation": "10 is the number of dryer minutes, not a price."},
            {"id": "c", "text": "24 €",
             "explanation": "24 refers to the opening hours (24/7), not to a cost."},
            {"id": "d", "text": "4 €",
             "explanation": "« Machine : 4 € » gives the price directly."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Machine : 4 €. Séchoir : 1 € les 10 minutes.",
        "key_line_en": "Washing machine: €4. Dryer: €1 for 10 minutes.",
        "vocabulary": [
            {"term": "une laverie", "gloss": "a launderette"},
            {"term": "un séchoir", "gloss": "a dryer"},
            {"term": "la lessive", "gloss": "washing powder"},
            {"term": "le linge", "gloss": "laundry, washing"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "SMS",
        "text": "Coucou,\nJ'ai oublié mes clés chez toi hier soir. Tu es là ce midi ? Je passe les chercher.\nSami",
        "question_fr": "Que veut faire Sami ?",
        "options": [
            {"id": "a", "text": "Venir chercher ses clés",
             "explanation": "« Je passe les chercher » — he wants to come and pick up the keys he left behind."},
            {"id": "b", "text": "Déjeuner avec son ami",
             "explanation": "« ce midi » is a time, not a lunch invitation."},
            {"id": "c", "text": "Rendre des clés",
             "explanation": "The keys are his own and they are at the friend's place; he is collecting, not returning."},
            {"id": "d", "text": "Faire un double des clés",
             "explanation": "No copy or locksmith is mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "J'ai oublié mes clés chez toi hier soir. Je passe les chercher.",
        "key_line_en": "I left my keys at your place last night. I'll come and get them.",
        "vocabulary": [
            {"term": "oublier", "gloss": "to forget, leave behind"},
            {"term": "passer", "gloss": "to drop by"},
            {"term": "chercher", "gloss": "to fetch, collect"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Affichette / Small notice",
        "text": "WIFI GRATUIT\nRéseau : CAFE_PARIS\nMot de passe : bonjour2026\nDemandez le code à jour au comptoir.",
        "question_fr": "Que propose ce café ?",
        "options": [
            {"id": "a", "text": "Un ordinateur à louer",
             "explanation": "No computer is offered; only a network connection."},
            {"id": "b", "text": "Une connexion Internet sans payer",
             "explanation": "« WIFI GRATUIT » — free internet access, with the network name and password given."},
            {"id": "c", "text": "Des boissons gratuites",
             "explanation": "What is free is the wifi, not the drinks."},
            {"id": "d", "text": "Un abonnement mensuel",
             "explanation": "No subscription is sold; the access is free and immediate."},
        ],
        "correct_answer": "b",
        "key_line_fr": "WIFI GRATUIT. Réseau : CAFE_PARIS.",
        "key_line_en": "FREE WIFI. Network: CAFE_PARIS.",
        "vocabulary": [
            {"term": "gratuit", "gloss": "free of charge"},
            {"term": "un mot de passe", "gloss": "a password"},
            {"term": "le comptoir", "gloss": "the counter, bar"},
            {"term": "à jour", "gloss": "up to date, current"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Courriel / E-mail",
        "text": "Bonjour Claire,\nMerci beaucoup pour le cadeau, il me plaît énormément !\nÀ bientôt,\nInès",
        "question_fr": "Pourquoi Inès écrit-elle ?",
        "options": [
            {"id": "a", "text": "Pour demander un cadeau",
             "explanation": "The gift has already been received; nothing is being asked for."},
            {"id": "b", "text": "Pour s'excuser",
             "explanation": "There is no apology and nothing to apologise for."},
            {"id": "c", "text": "Pour inviter Claire",
             "explanation": "« À bientôt » is a sign-off, not an invitation."},
            {"id": "d", "text": "Pour remercier Claire",
             "explanation": "« Merci beaucoup pour le cadeau » is a thank-you message."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Merci beaucoup pour le cadeau, il me plaît énormément !",
        "key_line_en": "Thank you so much for the present, I really love it!",
        "vocabulary": [
            {"term": "un cadeau", "gloss": "a present"},
            {"term": "plaire à", "gloss": "to please, to be liked by"},
            {"term": "énormément", "gloss": "enormously, very much"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Petite annonce / Classified ad",
        "text": "COLOCATION\nChambre de 12 m² dans un appartement partagé à trois.\n380 € charges comprises, Internet inclus.\nNon-fumeur. Caution d'un mois demandée.\nDisponible immédiatement.",
        "question_fr": "Quelle condition l'annonce impose-t-elle ?",
        "options": [
            {"id": "a", "text": "Payer une caution",
             "explanation": "« Caution d'un mois demandée » — a one-month deposit is required."},
            {"id": "b", "text": "Payer Internet en supplément",
             "explanation": "« Internet inclus » — it is already in the €380."},
            {"id": "c", "text": "Attendre le mois prochain",
             "explanation": "« Disponible immédiatement » — the room is free straight away."},
            {"id": "d", "text": "Vivre seul dans l'appartement",
             "explanation": "It is a flat share for three people, so the tenant will not be alone."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Caution d'un mois demandée.",
        "key_line_en": "A one-month deposit is required.",
        "vocabulary": [
            {"term": "une caution", "gloss": "a deposit"},
            {"term": "la colocation", "gloss": "flat share"},
            {"term": "charges comprises", "gloss": "bills included"},
            {"term": "non-fumeur", "gloss": "non-smoker"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Règlement / Rules",
        "text": "MUSÉE DES BEAUX-ARTS\nLes photos sans flash sont autorisées.\nLes sacs de plus de 30 cm doivent être déposés au vestiaire.\nLa dernière entrée se fait 45 minutes avant la fermeture.",
        "question_fr": "Que dit le règlement à propos des photographies ?",
        "options": [
            {"id": "a", "text": "Elles sont totalement interdites",
             "explanation": "They are allowed; only the flash is not."},
            {"id": "b", "text": "Elles sont permises sans flash",
             "explanation": "« Les photos sans flash sont autorisées » states the rule and its single limit."},
            {"id": "c", "text": "Elles nécessitent une autorisation écrite",
             "explanation": "No permit or written approval is mentioned."},
            {"id": "d", "text": "Elles sont réservées à la dernière heure",
             "explanation": "The 45-minute rule concerns admission, not photography."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les photos sans flash sont autorisées.",
        "key_line_en": "Photographs without flash are permitted.",
        "vocabulary": [
            {"term": "autorisé", "gloss": "permitted"},
            {"term": "un vestiaire", "gloss": "a cloakroom"},
            {"term": "déposer", "gloss": "to leave, hand in"},
            {"term": "la fermeture", "gloss": "closing time"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Offre commerciale / Commercial offer",
        "text": "FORFAIT MOBILE 12 €/MOIS\nAppels et SMS illimités en France.\n20 Go d'Internet, dont 5 Go utilisables en Europe.\nSans engagement. Carte SIM : 10 € à l'activation.",
        "question_fr": "Que faut-il payer en plus des 12 € mensuels ?",
        "options": [
            {"id": "a", "text": "Les appels en France",
             "explanation": "Calls in France are unlimited and included."},
            {"id": "b", "text": "Un engagement de douze mois",
             "explanation": "« Sans engagement » — there is no contract period, and it would not be a payment anyway."},
            {"id": "c", "text": "La carte SIM au début",
             "explanation": "« Carte SIM : 10 € à l'activation » is a one-off charge on top of the monthly price."},
            {"id": "d", "text": "Les 5 Go utilisables en Europe",
             "explanation": "Those 5 GB are part of the 20 GB already included."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Sans engagement. Carte SIM : 10 € à l'activation.",
        "key_line_en": "No contract. SIM card: €10 on activation.",
        "vocabulary": [
            {"term": "un forfait", "gloss": "a plan, package"},
            {"term": "illimité", "gloss": "unlimited"},
            {"term": "sans engagement", "gloss": "no minimum contract"},
            {"term": "l'activation", "gloss": "activation"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Conditions / Terms",
        "text": "COURS DE CUISINE — ANNULATION\nAnnulation plus de 7 jours avant le cours : remboursement total.\nEntre 7 et 2 jours : avoir valable un an.\nMoins de 48 h : aucun remboursement.",
        "question_fr": "Que reçoit un client qui annule quatre jours avant ?",
        "options": [
            {"id": "a", "text": "Un remboursement complet",
             "explanation": "A full refund needs more than seven days' notice; four days falls in the middle band."},
            {"id": "b", "text": "Rien du tout",
             "explanation": "Nothing at all applies under 48 hours; four days is well outside that."},
            {"id": "c", "text": "La moitié du prix",
             "explanation": "No half refund exists in these terms."},
            {"id": "d", "text": "Un avoir utilisable pendant un an",
             "explanation": "Four days sits « entre 7 et 2 jours », which gives a credit note valid for one year."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Entre 7 et 2 jours : avoir valable un an.",
        "key_line_en": "Between 7 and 2 days: credit note valid for one year.",
        "vocabulary": [
            {"term": "un avoir", "gloss": "a credit note"},
            {"term": "valable", "gloss": "valid"},
            {"term": "une annulation", "gloss": "a cancellation"},
            {"term": "un remboursement", "gloss": "a refund"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Consigne / Instructions",
        "text": "CASIER À COLIS\nEntrez le code reçu par SMS.\nLa porte s'ouvre automatiquement : prenez votre colis et refermez.\nLes colis non retirés sous 3 jours sont renvoyés à l'expéditeur.",
        "question_fr": "Que se passe-t-il après trois jours ?",
        "options": [
            {"id": "a", "text": "Le colis repart chez l'expéditeur",
             "explanation": "« Les colis non retirés sous 3 jours sont renvoyés à l'expéditeur »."},
            {"id": "b", "text": "Le code est envoyé une seconde fois",
             "explanation": "No second code is promised; the deadline simply expires."},
            {"id": "c", "text": "Le colis est livré à domicile",
             "explanation": "The parcel goes back to the sender, not on to the address."},
            {"id": "d", "text": "Le casier reste ouvert",
             "explanation": "The instructions say to close the door after collecting."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les colis non retirés sous 3 jours sont renvoyés à l'expéditeur.",
        "key_line_en": "Parcels not collected within 3 days are returned to the sender.",
        "vocabulary": [
            {"term": "retirer", "gloss": "to collect, pick up"},
            {"term": "un expéditeur", "gloss": "a sender"},
            {"term": "renvoyer", "gloss": "to send back"},
            {"term": "un casier", "gloss": "a locker"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Carte de fidélité / Loyalty card",
        "text": "CINÉMA LUX — CARTE FIDÉLITÉ\nUne place achetée = 1 point.\n10 points = une séance offerte.\nCarte valable deux ans, non cumulable avec les tarifs réduits.",
        "question_fr": "Que faut-il pour obtenir une séance gratuite ?",
        "options": [
            {"id": "a", "text": "Deux ans d'abonnement",
             "explanation": "Two years is how long the card stays valid, not a condition for the free ticket."},
            {"id": "b", "text": "Un tarif réduit",
             "explanation": "The card cannot be combined with reduced rates, so this works against it."},
            {"id": "c", "text": "Acheter dix places",
             "explanation": "One ticket earns one point and « 10 points = une séance offerte »."},
            {"id": "d", "text": "Payer un supplément",
             "explanation": "No extra payment is involved; the free showing is earned with points."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une place achetée = 1 point. 10 points = une séance offerte.",
        "key_line_en": "One ticket bought = 1 point. 10 points = one free showing.",
        "vocabulary": [
            {"term": "une séance", "gloss": "a showing, screening"},
            {"term": "offert", "gloss": "free, given"},
            {"term": "cumulable", "gloss": "combinable"},
            {"term": "un tarif réduit", "gloss": "a reduced rate"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Message de forum / Forum post",
        "text": "Bonjour,\nJe donne un canapé deux places, en bon état, à récupérer avant samedi.\nIl faut venir le chercher soi-même : je n'ai pas de voiture et il est au 3e sans ascenseur.\nPremier arrivé, premier servi.",
        "question_fr": "Quelle difficulté cette annonce signale-t-elle ?",
        "options": [
            {"id": "a", "text": "Le canapé est abîmé",
             "explanation": "« en bon état » — it is in good condition."},
            {"id": "b", "text": "Il faut le transporter soi-même depuis le 3e étage",
             "explanation": "The owner has no car and the flat is on the third floor with no lift, so collection is the buyer's problem."},
            {"id": "c", "text": "Le canapé coûte cher",
             "explanation": "« Je donne » — it is free."},
            {"id": "d", "text": "Il faut attendre samedi",
             "explanation": "Saturday is a deadline to collect by, not a date to wait for."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Il faut venir le chercher soi-même : je n'ai pas de voiture et il est au 3e sans ascenseur.",
        "key_line_en": "You have to collect it yourself: I have no car and it's on the third floor with no lift.",
        "vocabulary": [
            {"term": "en bon état", "gloss": "in good condition"},
            {"term": "récupérer", "gloss": "to collect, pick up"},
            {"term": "un ascenseur", "gloss": "a lift"},
            {"term": "premier arrivé, premier servi", "gloss": "first come, first served"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Article de presse / Press article",
        "text": "Un samedi par mois, le Repair Café du quartier réunit des bénévoles qui réparent gratuitement grille-pain, lampes et vélos.\n« Nous ne réparons pas à la place des gens, précise le fondateur. Nous réparons avec eux. Beaucoup repartent surtout avec l'idée qu'ils peuvent le faire seuls. »",
        "question_fr": "Quel est l'objectif principal du Repair Café, selon son fondateur ?",
        "options": [
            {"id": "a", "text": "Vendre des appareils réparés",
             "explanation": "Nothing is sold; the repairs are free and the objects belong to their owners."},
            {"id": "b", "text": "Apprendre aux gens à réparer eux-mêmes",
             "explanation": "« Nous réparons avec eux » and people leave with the idea « qu'ils peuvent le faire seuls »."},
            {"id": "c", "text": "Employer des réparateurs professionnels",
             "explanation": "The helpers are « bénévoles » — volunteers, not employed professionals."},
            {"id": "d", "text": "Collecter les appareils en panne",
             "explanation": "Broken items are not collected; they are brought and taken home again."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nous ne réparons pas à la place des gens. Nous réparons avec eux.",
        "key_line_en": "We don't repair things for people. We repair them with them.",
        "vocabulary": [
            {"term": "un bénévole", "gloss": "a volunteer"},
            {"term": "à la place de", "gloss": "instead of, in place of"},
            {"term": "repartir", "gloss": "to leave again"},
            {"term": "préciser", "gloss": "to specify, make clear"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "text": "Le nombre de livres lus par habitant baisse légèrement, mais le temps consacré à la lecture, lui, augmente.\nL'explication tient au format : on lit davantage d'articles longs et de textes en ligne, moins de livres entiers.",
        "question_fr": "Comment expliquer ces résultats apparemment contradictoires ?",
        "options": [
            {"id": "a", "text": "Les gens lisent plus lentement qu'avant",
             "explanation": "Reading speed is never mentioned; the explanation given is about format."},
            {"id": "b", "text": "Les enquêtes sont mal conduites",
             "explanation": "The figures are not challenged; they are reconciled."},
            {"id": "c", "text": "On lit d'autres formats que le livre",
             "explanation": "« L'explication tient au format » — long articles and online texts replace whole books, so time rises while book counts fall."},
            {"id": "d", "text": "Les livres sont devenus plus courts",
             "explanation": "Book length is not discussed; what changed is what people read, not the books themselves."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On lit davantage d'articles longs et de textes en ligne, moins de livres entiers.",
        "key_line_en": "People read more long articles and online texts, and fewer whole books.",
        "vocabulary": [
            {"term": "tenir à", "gloss": "to be due to"},
            {"term": "consacrer à", "gloss": "to devote to"},
            {"term": "entier", "gloss": "whole, entire"},
            {"term": "légèrement", "gloss": "slightly"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Lettre de réclamation / Letter of complaint",
        "text": "Madame, Monsieur,\nJ'ai reçu ce matin une commande incomplète : sur les quatre articles payés, deux manquaient.\nJe ne conteste pas le retard, que votre site annonçait. Je demande simplement l'envoi des articles manquants, ou leur remboursement si vous ne les avez plus en stock.",
        "question_fr": "Sur quoi porte exactement la réclamation ?",
        "options": [
            {"id": "a", "text": "Sur le retard de livraison",
             "explanation": "« Je ne conteste pas le retard » — the delay is explicitly set aside."},
            {"id": "b", "text": "Sur la qualité des articles reçus",
             "explanation": "The items received are not criticised; the issue is the ones that never came."},
            {"id": "c", "text": "Sur le prix payé",
             "explanation": "The price is not disputed — only whether the goods paid for were delivered."},
            {"id": "d", "text": "Sur des articles absents de la commande",
             "explanation": "Two of four items were missing, and the request is to send or refund them."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Sur les quatre articles payés, deux manquaient.",
        "key_line_en": "Of the four items paid for, two were missing.",
        "vocabulary": [
            {"term": "manquer", "gloss": "to be missing"},
            {"term": "contester", "gloss": "to dispute"},
            {"term": "en stock", "gloss": "in stock"},
            {"term": "incomplet", "gloss": "incomplete"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Chronique santé / Health column",
        "text": "Les écrans ne détériorent pas la vue de façon permanente, contrairement à ce que l'on entend souvent.\nIls provoquent en revanche une fatigue bien réelle, parce qu'on cligne des yeux deux fois moins devant un écran. La règle des 20 minutes — regarder au loin vingt secondes — suffit le plus souvent.",
        "question_fr": "Que dit l'auteur sur l'effet des écrans ?",
        "options": [
            {"id": "a", "text": "Ils abîment la vue de manière définitive",
             "explanation": "The first sentence denies exactly this: no permanent damage."},
            {"id": "b", "text": "Ils fatiguent les yeux sans les abîmer durablement",
             "explanation": "Tiredness is « bien réelle », caused by reduced blinking, but the damage is not permanent."},
            {"id": "c", "text": "Ils n'ont aucun effet sur les yeux",
             "explanation": "Too strong: real fatigue is described, with a physical cause."},
            {"id": "d", "text": "Ils obligent à porter des lunettes",
             "explanation": "Glasses are never mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Ils provoquent en revanche une fatigue bien réelle, parce qu'on cligne des yeux deux fois moins devant un écran.",
        "key_line_en": "They do, however, cause genuine fatigue, because we blink half as often in front of a screen.",
        "vocabulary": [
            {"term": "cligner des yeux", "gloss": "to blink"},
            {"term": "en revanche", "gloss": "on the other hand"},
            {"term": "détériorer", "gloss": "to damage"},
            {"term": "au loin", "gloss": "into the distance"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Offre d'emploi / Job advert",
        "text": "Société de livraison recherche un chauffeur.\nPermis B depuis au moins trois ans exigé. Le véhicule est fourni.\nLa connaissance de la ville est un atout, mais un GPS est installé dans chaque camionnette.",
        "question_fr": "Quelle est la condition obligatoire pour ce poste ?",
        "options": [
            {"id": "a", "text": "Posséder son propre véhicule",
             "explanation": "« Le véhicule est fourni » — the company supplies it."},
            {"id": "b", "text": "Bien connaître la ville",
             "explanation": "« un atout » makes it desirable, and the GPS removes the necessity."},
            {"id": "c", "text": "Avoir le permis depuis trois ans",
             "explanation": "« Permis B depuis au moins trois ans exigé » — the only requirement marked « exigé »."},
            {"id": "d", "text": "Savoir utiliser un GPS",
             "explanation": "The GPS is provided as a convenience; no skill requirement is attached to it."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Permis B depuis au moins trois ans exigé.",
        "key_line_en": "A category B licence held for at least three years is required.",
        "vocabulary": [
            {"term": "exigé", "gloss": "required"},
            {"term": "un atout", "gloss": "an asset, advantage"},
            {"term": "fourni", "gloss": "supplied"},
            {"term": "une camionnette", "gloss": "a van"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Article municipal / Local news",
        "text": "Le marché du mercredi déménage place de la Liberté, le temps des travaux de la place centrale.\nLes commerçants craignaient de perdre leur clientèle ; après un mois, la fréquentation a légèrement augmenté, la nouvelle place étant mieux desservie par les bus.",
        "question_fr": "Quel a été l'effet du déménagement du marché ?",
        "options": [
            {"id": "a", "text": "Une hausse de la fréquentation",
             "explanation": "« la fréquentation a légèrement augmenté », helped by better bus links."},
            {"id": "b", "text": "Une baisse de la clientèle",
             "explanation": "That was the traders' fear, and the outcome contradicted it."},
            {"id": "c", "text": "La fermeture du marché",
             "explanation": "The market moved; it did not close."},
            {"id": "d", "text": "Un changement de jour",
             "explanation": "It remains the Wednesday market; only the place changed."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Après un mois, la fréquentation a légèrement augmenté, la nouvelle place étant mieux desservie par les bus.",
        "key_line_en": "After a month, footfall had risen slightly, the new square being better served by buses.",
        "vocabulary": [
            {"term": "déménager", "gloss": "to move (premises)"},
            {"term": "la clientèle", "gloss": "the customers"},
            {"term": "desservi", "gloss": "served (by transport)"},
            {"term": "craindre", "gloss": "to fear"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Appel aux donneurs / Call for donors",
        "text": "L'établissement du sang lance un appel : les réserves baissent chaque été, quand les donneurs partent en vacances alors que les besoins, eux, ne diminuent pas.\nUn don prend une heure, rendez-vous compris, et peut être fait tous les deux mois.",
        "question_fr": "Pourquoi les réserves baissent-elles en été ?",
        "options": [
            {"id": "a", "text": "Parce que les besoins augmentent fortement",
             "explanation": "Needs « ne diminuent pas » — they stay level; they are not said to rise."},
            {"id": "b", "text": "Parce que les dons sont limités à un par an",
             "explanation": "Donations are possible every two months, so the limit is not the cause."},
            {"id": "c", "text": "Parce que les donneurs sont absents",
             "explanation": "« les donneurs partent en vacances alors que les besoins […] ne diminuent pas » — supply falls while demand holds."},
            {"id": "d", "text": "Parce que les centres ferment l'été",
             "explanation": "No closure is mentioned; the appeal assumes donation remains possible."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les réserves baissent chaque été, quand les donneurs partent en vacances alors que les besoins, eux, ne diminuent pas.",
        "key_line_en": "Stocks fall every summer, when donors go on holiday while the needs, for their part, do not decrease.",
        "vocabulary": [
            {"term": "les réserves", "gloss": "stocks, reserves"},
            {"term": "un donneur", "gloss": "a donor"},
            {"term": "un don", "gloss": "a donation"},
            {"term": "diminuer", "gloss": "to decrease"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "text": "On présente le pourboire comme une récompense du bon service. C'est oublier qu'il varie surtout selon l'humeur du client, l'heure et la taille de l'addition.\nUne récompense qui dépend si peu de ce qu'elle récompense mérite un autre nom.",
        "question_fr": "Que soutient l'auteur au sujet du pourboire ?",
        "options": [
            {"id": "a", "text": "Il devrait être plus élevé",
             "explanation": "The amount is not the issue; the link between tip and service is."},
            {"id": "b", "text": "Il récompense mal ce qu'il prétend récompenser",
             "explanation": "It varies with mood, time and bill size — « une récompense qui dépend si peu de ce qu'elle récompense »."},
            {"id": "c", "text": "Il devrait être laissé à la discrétion du serveur",
             "explanation": "No alternative arrangement is proposed in the extract."},
            {"id": "d", "text": "Il reflète fidèlement la qualité du service",
             "explanation": "That is exactly the claim the author sets out to undo."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une récompense qui dépend si peu de ce qu'elle récompense mérite un autre nom.",
        "key_line_en": "A reward that depends so little on what it rewards deserves another name.",
        "vocabulary": [
            {"term": "un pourboire", "gloss": "a tip"},
            {"term": "une récompense", "gloss": "a reward"},
            {"term": "l'addition", "gloss": "the bill"},
            {"term": "mériter", "gloss": "to deserve"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "text": "Construire des résidences étudiantes ne résout le problème du logement que si elles sont proches des campus. Là où elles ont été bâties en périphérie, faute de terrain disponible, elles restent partiellement vides.\nLes étudiants préfèrent une chambre plus petite et plus chère à quarante minutes de trajet quotidien.",
        "question_fr": "Pourquoi certaines résidences restent-elles vides ?",
        "options": [
            {"id": "a", "text": "Parce qu'elles sont trop chères",
             "explanation": "Students accept a « plus chère » room when it is close, so price alone is not the obstacle."},
            {"id": "b", "text": "Parce que les chambres sont trop petites",
             "explanation": "They also accept « plus petite » — size is not the deciding factor either."},
            {"id": "c", "text": "Parce qu'il n'y a pas assez d'étudiants",
             "explanation": "The housing problem implies demand exceeds supply; numbers are not the issue."},
            {"id": "d", "text": "Parce qu'elles sont trop éloignées des campus",
             "explanation": "Those built « en périphérie » stay partly empty, and students trade size and price to avoid a 40-minute commute."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Les étudiants préfèrent une chambre plus petite et plus chère à quarante minutes de trajet quotidien.",
        "key_line_en": "Students prefer a smaller, dearer room to forty minutes of travel a day.",
        "vocabulary": [
            {"term": "la périphérie", "gloss": "the outskirts"},
            {"term": "faute de", "gloss": "for lack of"},
            {"term": "un trajet", "gloss": "a journey, commute"},
            {"term": "bâtir", "gloss": "to build"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Critique de théâtre / Theatre review",
        "text": "La mise en scène est inventive, le décor superbe, la troupe irréprochable. Trois heures durant, on ne s'ennuie pas une minute.\nOn se demande simplement, en sortant, ce que tout cela voulait dire.",
        "question_fr": "Quelle réserve le critique formule-t-il ?",
        "options": [
            {"id": "a", "text": "Le spectacle est trop long",
             "explanation": "Three hours pass without boredom, which defuses the length."},
            {"id": "b", "text": "Les comédiens manquent de talent",
             "explanation": "« la troupe irréprochable » — the company is beyond reproach."},
            {"id": "c", "text": "Le propos de la pièce reste obscur",
             "explanation": "Everything is admired except the meaning: « ce que tout cela voulait dire »."},
            {"id": "d", "text": "Le décor est trop simple",
             "explanation": "« le décor superbe » — the set is praised."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On se demande simplement, en sortant, ce que tout cela voulait dire.",
        "key_line_en": "You simply wonder, on the way out, what it was all meant to say.",
        "vocabulary": [
            {"term": "la mise en scène", "gloss": "the staging, direction"},
            {"term": "une troupe", "gloss": "a theatre company"},
            {"term": "irréprochable", "gloss": "faultless"},
            {"term": "le propos", "gloss": "the point, message"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "text": "Les montres qui mesurent le sommeil estiment, elles ne mesurent pas : elles déduisent les phases à partir des mouvements et du rythme cardiaque.\nLe risque est connu des spécialistes : à force de consulter son score, certains dormeurs s'inquiètent et dorment plus mal. L'outil crée alors le trouble qu'il prétend suivre.",
        "question_fr": "Quel paradoxe l'auteur relève-t-il ?",
        "options": [
            {"id": "a", "text": "L'appareil peut provoquer le problème qu'il mesure",
             "explanation": "Anxiety about the score worsens sleep: « L'outil crée alors le trouble qu'il prétend suivre »."},
            {"id": "b", "text": "Les montres sont trop chères pour ce qu'elles font",
             "explanation": "Price is never mentioned."},
            {"id": "c", "text": "Les phases de sommeil n'existent pas",
             "explanation": "They exist; the point is that the watch infers rather than measures them."},
            {"id": "d", "text": "Les spécialistes ignorent ce risque",
             "explanation": "The opposite: « Le risque est connu des spécialistes »."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'outil crée alors le trouble qu'il prétend suivre.",
        "key_line_en": "The device then creates the very disorder it claims to track.",
        "vocabulary": [
            {"term": "déduire", "gloss": "to infer"},
            {"term": "à force de", "gloss": "through constantly"},
            {"term": "un trouble", "gloss": "a disorder"},
            {"term": "prétendre", "gloss": "to claim"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "text": "Bonjour,\nNous avons reçu quarante candidatures pour le poste, dont une dizaine d'excellentes. Je préfère prévenir : nous n'en retiendrons qu'une, et le choix se jouera sur des détails.\nMerci de répondre à tous les candidats reçus en entretien, y compris ceux que nous ne prendrons pas.",
        "question_fr": "Que demande l'auteur du message ?",
        "options": [
            {"id": "a", "text": "De recruter plusieurs candidats",
             "explanation": "« nous n'en retiendrons qu'une » — only one will be taken on."},
            {"id": "b", "text": "De réduire le nombre d'entretiens",
             "explanation": "No change to the interview process is requested."},
            {"id": "c", "text": "De relancer les candidats non retenus",
             "explanation": "They are to be answered, not chased — « relancer » would mean following up for a reply."},
            {"id": "d", "text": "De répondre aussi aux candidats refusés",
             "explanation": "« y compris ceux que nous ne prendrons pas » is the explicit instruction."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Merci de répondre à tous les candidats reçus en entretien, y compris ceux que nous ne prendrons pas.",
        "key_line_en": "Please reply to every candidate we interviewed, including those we will not be hiring.",
        "vocabulary": [
            {"term": "une candidature", "gloss": "an application"},
            {"term": "retenir", "gloss": "to select, keep"},
            {"term": "se jouer sur", "gloss": "to come down to"},
            {"term": "un entretien", "gloss": "an interview"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Analyse économique / Economic analysis",
        "text": "La région se félicite des emplois créés par le tourisme. Le chiffre est exact, mais il faudrait l'accompagner d'un second : sept sur dix de ces postes durent moins de six mois.\nCompter des emplois sans compter leur durée revient à confondre l'activité et la stabilité.",
        "question_fr": "Que reproche l'auteur à cette présentation des chiffres ?",
        "options": [
            {"id": "a", "text": "Elle exagère le nombre d'emplois créés",
             "explanation": "« Le chiffre est exact » — the count itself is not disputed."},
            {"id": "b", "text": "Elle ignore la durée de ces emplois",
             "explanation": "Seven in ten last under six months, and counting jobs without their duration « confond l'activité et la stabilité »."},
            {"id": "c", "text": "Elle sous-estime l'apport du tourisme",
             "explanation": "The author is qualifying the benefit, not arguing it is understated."},
            {"id": "d", "text": "Elle repose sur des données anciennes",
             "explanation": "The age of the data is never questioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Compter des emplois sans compter leur durée revient à confondre l'activité et la stabilité.",
        "key_line_en": "Counting jobs without counting how long they last amounts to confusing activity with stability.",
        "vocabulary": [
            {"term": "se féliciter de", "gloss": "to congratulate oneself on"},
            {"term": "revenir à", "gloss": "to amount to"},
            {"term": "confondre", "gloss": "to confuse (two things)"},
            {"term": "la durée", "gloss": "the duration"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "text": "On demande aux habitants d'économiser l'eau, et ils le font : la consommation domestique baisse depuis dix ans.\nDans le même temps, un cinquième de l'eau potable se perd dans des canalisations percées. Tant que ce chiffre ne bougera pas, les efforts individuels resteront symboliques.",
        "question_fr": "Quelle est la position de l'auteur ?",
        "options": [
            {"id": "a", "text": "Les habitants ne font pas assez d'efforts",
             "explanation": "They are credited: consumption has been falling for ten years."},
            {"id": "b", "text": "L'eau potable n'est pas menacée",
             "explanation": "A fifth of it is lost, which is presented as a serious problem."},
            {"id": "c", "text": "Les fuites du réseau annulent l'effet des économies",
             "explanation": "« Tant que ce chiffre ne bougera pas, les efforts individuels resteront symboliques » — the leaks dwarf household savings."},
            {"id": "d", "text": "Il faut augmenter le prix de l'eau",
             "explanation": "No pricing measure is proposed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Tant que ce chiffre ne bougera pas, les efforts individuels resteront symboliques.",
        "key_line_en": "As long as that figure does not move, individual efforts will remain symbolic.",
        "vocabulary": [
            {"term": "une canalisation", "gloss": "a pipe"},
            {"term": "percé", "gloss": "leaking, holed"},
            {"term": "l'eau potable", "gloss": "drinking water"},
            {"term": "tant que", "gloss": "as long as"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "text": "Une carte utile est une carte fausse. Elle efface, simplifie, redresse — et c'est à ce prix qu'elle nous conduit quelque part.\nCelui qui exigerait d'elle une exactitude complète obtiendrait le territoire lui-même, c'est-à-dire rien qui puisse tenir dans une poche.",
        "question_fr": "Quelle idée l'auteur défend-il ?",
        "options": [
            {"id": "a", "text": "Les cartes devraient être plus précises",
             "explanation": "The argument runs the other way: complete accuracy would destroy the map's usefulness."},
            {"id": "b", "text": "L'utilité d'une carte tient à ce qu'elle omet",
             "explanation": "It erases and simplifies, « et c'est à ce prix qu'elle nous conduit quelque part »."},
            {"id": "c", "text": "Les cartes numériques ont remplacé les cartes papier",
             "explanation": "No comparison of formats appears in the text."},
            {"id": "d", "text": "Il vaut mieux se déplacer sans carte",
             "explanation": "The map is defended as useful, not dismissed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Elle efface, simplifie, redresse — et c'est à ce prix qu'elle nous conduit quelque part.",
        "key_line_en": "It erases, simplifies, straightens — and that is the price at which it takes us somewhere.",
        "vocabulary": [
            {"term": "à ce prix", "gloss": "at that cost, only in this way"},
            {"term": "redresser", "gloss": "to straighten"},
            {"term": "exiger de", "gloss": "to demand from"},
            {"term": "l'exactitude", "gloss": "accuracy"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "text": "Le service client a été « modernisé » : un assistant automatique répond désormais en trois secondes, contre onze minutes d'attente auparavant.\nIl ne résout rien, mais il le fait vite. Le délai moyen de traitement, lui, a doublé — on ne saurait tout avoir.",
        "question_fr": "Que critique l'auteur dans cette modernisation ?",
        "options": [
            {"id": "a", "text": "Elle améliore un indicateur en dégradant le service",
             "explanation": "Answering time fell, but resolution time doubled: « Il ne résout rien, mais il le fait vite »."},
            {"id": "b", "text": "Elle a allongé le temps d'attente",
             "explanation": "Waiting time dropped from eleven minutes to three seconds; that part genuinely improved."},
            {"id": "c", "text": "Elle a supprimé tous les conseillers",
             "explanation": "No redundancies or staff removals are mentioned."},
            {"id": "d", "text": "Elle coûte plus cher qu'avant",
             "explanation": "No cost figure appears in the text."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Il ne résout rien, mais il le fait vite.",
        "key_line_en": "It solves nothing, but it does so quickly.",
        "vocabulary": [
            {"term": "le traitement", "gloss": "handling, processing"},
            {"term": "un délai", "gloss": "a time, delay"},
            {"term": "on ne saurait", "gloss": "one cannot"},
            {"term": "auparavant", "gloss": "previously"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "text": "La disparition des espèces est annoncée à chaque nouveau moyen de paiement, et pourtant elles circulent encore.\nCe qui change n'est pas leur volume mais leur fonction : on ne paie plus en liquide, on y a recours quand tout le reste échoue. La monnaie devient un filet plutôt qu'un outil.",
        "question_fr": "Quelle évolution du liquide l'auteur décrit-il ?",
        "options": [
            {"id": "a", "text": "Il disparaît complètement de la circulation",
             "explanation": "« elles circulent encore » — cash is still around; only its role has shifted."},
            {"id": "b", "text": "Son volume augmente fortement",
             "explanation": "« Ce qui change n'est pas leur volume » — volume is explicitly not the change."},
            {"id": "c", "text": "Il devient un recours de secours plutôt qu'un moyen courant",
             "explanation": "« on y a recours quand tout le reste échoue », summed up as « un filet plutôt qu'un outil »."},
            {"id": "d", "text": "Il redevient le moyen de paiement principal",
             "explanation": "The opposite: « on ne paie plus en liquide » in ordinary use."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La monnaie devient un filet plutôt qu'un outil.",
        "key_line_en": "Cash is becoming a safety net rather than a tool.",
        "vocabulary": [
            {"term": "les espèces / le liquide", "gloss": "cash"},
            {"term": "avoir recours à", "gloss": "to resort to"},
            {"term": "un filet", "gloss": "a net, safety net"},
            {"term": "échouer", "gloss": "to fail"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "text": "Sa mère rangeait la maison chaque dimanche, non parce qu'elle était sale, mais parce que ranger l'occupait.\nIl comprit bien plus tard qu'on peut passer une vie entière à mettre de l'ordre dans ce qui n'en manquait pas, pour ne pas regarder ce qui en manquait vraiment.",
        "question_fr": "Que comprend le personnage à propos de sa mère ?",
        "options": [
            {"id": "a", "text": "Qu'elle tenait beaucoup à la propreté",
             "explanation": "« non parce qu'elle était sale » removes cleanliness as the motive."},
            {"id": "b", "text": "Que le rangement lui servait à éviter autre chose",
             "explanation": "Tidying what needed no tidying served « pour ne pas regarder ce qui en manquait vraiment »."},
            {"id": "c", "text": "Qu'elle s'ennuyait le dimanche",
             "explanation": "Being occupied is a means here, not a cure for boredom; the last sentence names avoidance."},
            {"id": "d", "text": "Qu'elle attendait de la visite",
             "explanation": "No visitors are mentioned anywhere."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On peut passer une vie entière à mettre de l'ordre dans ce qui n'en manquait pas, pour ne pas regarder ce qui en manquait vraiment.",
        "key_line_en": "One can spend a whole life putting order into what did not lack it, so as not to look at what truly did.",
        "vocabulary": [
            {"term": "ranger", "gloss": "to tidy up"},
            {"term": "mettre de l'ordre", "gloss": "to put in order"},
            {"term": "manquer de", "gloss": "to lack"},
            {"term": "occuper", "gloss": "to keep busy"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "text": "L'effet placebo n'est pas une illusion à écarter : il est un effet, mesurable et reproductible.\nC'est précisément pour cela qu'un essai sérieux le neutralise. On ne cherche pas à savoir si un traitement agit, mais s'il agit au-delà de ce que produirait n'importe quoi d'administré avec conviction.",
        "question_fr": "Pourquoi les essais neutralisent-ils l'effet placebo ?",
        "options": [
            {"id": "a", "text": "Parce qu'il n'existe pas réellement",
             "explanation": "The first sentence insists the opposite: it is measurable and reproducible."},
            {"id": "b", "text": "Parce qu'il fausse les mesures de laboratoire",
             "explanation": "The issue is not measurement error but what the trial is trying to establish."},
            {"id": "c", "text": "Parce qu'il est dangereux pour les patients",
             "explanation": "No harm is attributed to it."},
            {"id": "d", "text": "Pour isoler ce que le traitement ajoute",
             "explanation": "The question is whether a treatment works « au-delà de ce que produirait n'importe quoi d'administré avec conviction »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "On ne cherche pas à savoir si un traitement agit, mais s'il agit au-delà de ce que produirait n'importe quoi d'administré avec conviction.",
        "key_line_en": "The question is not whether a treatment works, but whether it works beyond what anything given with conviction would produce.",
        "vocabulary": [
            {"term": "écarter", "gloss": "to dismiss, set aside"},
            {"term": "un essai", "gloss": "a trial"},
            {"term": "neutraliser", "gloss": "to control for, neutralise"},
            {"term": "au-delà de", "gloss": "beyond"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Commentaire institutionnel / Institutional commentary",
        "text": "La charte adoptée par la profession énonce de beaux principes et prévoit un comité chargé d'en contrôler l'application.\nCe comité est composé des signataires, se réunit à leur initiative et ne publie rien. On appellera cela de l'autorégulation, faute d'un mot plus exact.",
        "question_fr": "Que suggère l'auteur à propos de ce comité ?",
        "options": [
            {"id": "a", "text": "Il n'exerce aucun contrôle véritable",
             "explanation": "Made of the signatories, meeting when they choose, publishing nothing — the ironic « faute d'un mot plus exact » seals the point."},
            {"id": "b", "text": "Il applique la charte trop strictement",
             "explanation": "Nothing suggests strictness; the description points to the absence of scrutiny."},
            {"id": "c", "text": "Il devrait publier ses principes",
             "explanation": "The principles are already stated in the charter; what is missing is any account of enforcement."},
            {"id": "d", "text": "Il remplace utilement une régulation publique",
             "explanation": "The closing irony withholds exactly that endorsement."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce comité est composé des signataires, se réunit à leur initiative et ne publie rien.",
        "key_line_en": "This committee is made up of the signatories, meets when they choose, and publishes nothing.",
        "vocabulary": [
            {"term": "une charte", "gloss": "a charter"},
            {"term": "énoncer", "gloss": "to set out, state"},
            {"term": "un signataire", "gloss": "a signatory"},
            {"term": "l'autorégulation", "gloss": "self-regulation"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Analyse du monde du travail / Workplace analysis",
        "text": "Le courriel a été adopté pour éviter des réunions ; il en a créé la version écrite et permanente.\nCe n'est pas l'outil qu'il faudrait blâmer : une organisation qui n'a pas décidé qui décide produira toujours de la circulation à la place de la décision.",
        "question_fr": "Où l'auteur situe-t-il la cause du problème ?",
        "options": [
            {"id": "a", "text": "Dans le courriel lui-même",
             "explanation": "« Ce n'est pas l'outil qu'il faudrait blâmer » — the tool is explicitly exonerated."},
            {"id": "b", "text": "Dans le nombre excessif de réunions",
             "explanation": "Meetings are the comparison, not the diagnosis; e-mail reproduced them rather than caused them."},
            {"id": "c", "text": "Dans l'absence de règles de décision claires",
             "explanation": "« une organisation qui n'a pas décidé qui décide produira toujours de la circulation à la place de la décision »."},
            {"id": "d", "text": "Dans la formation insuffisante des salariés",
             "explanation": "Training is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une organisation qui n'a pas décidé qui décide produira toujours de la circulation à la place de la décision.",
        "key_line_en": "An organisation that has not decided who decides will always produce traffic instead of decisions.",
        "vocabulary": [
            {"term": "blâmer", "gloss": "to blame"},
            {"term": "la circulation", "gloss": "flow, traffic (of messages)"},
            {"term": "à la place de", "gloss": "instead of"},
            {"term": "permanent", "gloss": "permanent, ongoing"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai sur les noms / Essay on names",
        "text": "Nommer, c'est déjà trancher. Le mot que l'on choisit pour un phénomène décide de ceux qui s'en occuperont : appelez-le crise, et vous convoquez des experts ; appelez-le injustice, et vous convoquez des juges.\nLe débat sur les mots n'est pas un préliminaire au débat de fond : il en est la première manche.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Le choix des mots oriente déjà le traitement du problème",
             "explanation": "The word summons a profession, and « le débat sur les mots […] en est la première manche » — naming is part of the substantive fight."},
            {"id": "b", "text": "Il faudrait s'entendre sur les mots avant de débattre",
             "explanation": "The text refuses to treat wording as a preliminary; it is already the argument."},
            {"id": "c", "text": "Les experts sont plus utiles que les juges",
             "explanation": "Neither is preferred; they illustrate what different names bring about."},
            {"id": "d", "text": "Les débats sur le vocabulaire font perdre du temps",
             "explanation": "The opposite: they are given decisive weight."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le débat sur les mots n'est pas un préliminaire au débat de fond : il en est la première manche.",
        "key_line_en": "The argument over words is not a preliminary to the real argument: it is its first round.",
        "vocabulary": [
            {"term": "trancher", "gloss": "to settle, decide"},
            {"term": "convoquer", "gloss": "to summon, call in"},
            {"term": "une manche", "gloss": "a round (of a contest)"},
            {"term": "de fond", "gloss": "substantive"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "text": "Le chiffre a ceci de commode qu'il paraît clore la discussion. On oublie qu'il a fallu, en amont, décider ce que l'on comptait, et donc ce que l'on ne comptait pas.\nToute statistique est une opinion qui a réussi à se faire oublier comme telle.",
        "question_fr": "Quelle est la thèse de l'auteur sur les statistiques ?",
        "options": [
            {"id": "a", "text": "Les statistiques sont volontairement falsifiées",
             "explanation": "No accusation of fraud is made; the point concerns choices made before counting."},
            {"id": "b", "text": "Elles portent des choix devenus invisibles",
             "explanation": "Deciding what to count is deciding what not to count — « une opinion qui a réussi à se faire oublier comme telle »."},
            {"id": "c", "text": "Il faudrait renoncer aux données chiffrées",
             "explanation": "No such renunciation is proposed; the author asks that the choices be seen."},
            {"id": "d", "text": "Les chiffres mettent fin aux discussions inutiles",
             "explanation": "That appearance (« il paraît clore la discussion ») is precisely what the text dismantles."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Toute statistique est une opinion qui a réussi à se faire oublier comme telle.",
        "key_line_en": "Every statistic is an opinion that has managed to be forgotten as one.",
        "vocabulary": [
            {"term": "commode", "gloss": "convenient"},
            {"term": "clore", "gloss": "to close, end"},
            {"term": "en amont", "gloss": "upstream, beforehand"},
            {"term": "comme telle", "gloss": "as such"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Critique de danse / Dance review",
        "text": "La chorégraphie exige des interprètes une précision d'horloger, qu'ils atteignent sans faillir.\nIl leur manque pourtant cette hésitation infime qui distingue un corps d'un mécanisme — et sans laquelle la virtuosité n'émeut personne.",
        "question_fr": "Que reproche le critique aux interprètes ?",
        "options": [
            {"id": "a", "text": "Leur manque de technique",
             "explanation": "Their precision is described as flawless: « qu'ils atteignent sans faillir »."},
            {"id": "b", "text": "La brièveté du spectacle",
             "explanation": "Length is never mentioned."},
            {"id": "c", "text": "Une perfection qui supprime toute émotion",
             "explanation": "The missing « hésitation infime » is what separates a body from a mechanism, « sans laquelle la virtuosité n'émeut personne »."},
            {"id": "d", "text": "Le choix de la chorégraphie",
             "explanation": "The choreography's demands are stated neutrally; the reservation concerns what the dancing lacks, not the work chosen."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Il leur manque pourtant cette hésitation infime qui distingue un corps d'un mécanisme.",
        "key_line_en": "Yet they lack that minute hesitation which distinguishes a body from a mechanism.",
        "vocabulary": [
            {"term": "sans faillir", "gloss": "without fail"},
            {"term": "infime", "gloss": "minute, tiny"},
            {"term": "la virtuosité", "gloss": "virtuosity"},
            {"term": "émouvoir", "gloss": "to move (emotionally)"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "text": "Un modèle qui prévoit tout ne prévoit rien : à force d'ajouter des variables pour rattraper chaque écart, on finit par décrire le passé au lieu d'anticiper l'avenir.\nLa valeur d'un modèle se mesure à ce qu'il refuse d'expliquer.",
        "question_fr": "Quel critère l'auteur propose-t-il pour juger un modèle ?",
        "options": [
            {"id": "a", "text": "Sa capacité à tout expliquer",
             "explanation": "Explaining everything is presented as the failure mode: it describes the past instead of predicting."},
            {"id": "b", "text": "Le nombre de variables qu'il contient",
             "explanation": "Adding variables is exactly what degrades the model in this argument."},
            {"id": "c", "text": "Sa capacité à décrire fidèlement le passé",
             "explanation": "That is the trap: fitting the past is what over-specified models do instead of forecasting."},
            {"id": "d", "text": "Ce qu'il laisse volontairement de côté",
             "explanation": "« La valeur d'un modèle se mesure à ce qu'il refuse d'expliquer »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "La valeur d'un modèle se mesure à ce qu'il refuse d'expliquer.",
        "key_line_en": "A model's value is measured by what it refuses to explain.",
        "vocabulary": [
            {"term": "rattraper", "gloss": "to catch up with, make good"},
            {"term": "un écart", "gloss": "a discrepancy, gap"},
            {"term": "anticiper", "gloss": "to anticipate"},
            {"term": "à force de", "gloss": "through constantly"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "text": "On a éclairé la rue toute la nuit pour rassurer, et l'on s'étonne que plus personne n'y lève les yeux.\nUne ville qui supprime ses ombres supprime aussi ce qu'elles rendaient visible : le ciel, et l'heure qu'il indique.",
        "question_fr": "Que déplore l'auteur ?",
        "options": [
            {"id": "a", "text": "L'insécurité persistante des rues",
             "explanation": "Safety is the stated motive for the lighting, not what the author laments."},
            {"id": "b", "text": "Le coût de l'éclairage public",
             "explanation": "No cost appears in the text."},
            {"id": "c", "text": "Le manque d'éclairage dans certains quartiers",
             "explanation": "The complaint is about too much light, not too little."},
            {"id": "d", "text": "La perte du ciel nocturne comme repère",
             "explanation": "Removing the shadows removes what they made visible: « le ciel, et l'heure qu'il indique »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Une ville qui supprime ses ombres supprime aussi ce qu'elles rendaient visible : le ciel, et l'heure qu'il indique.",
        "key_line_en": "A city that removes its shadows also removes what they made visible: the sky, and the hour it tells.",
        "vocabulary": [
            {"term": "une ombre", "gloss": "a shadow"},
            {"term": "rassurer", "gloss": "to reassure"},
            {"term": "s'étonner", "gloss": "to be surprised"},
            {"term": "un repère", "gloss": "a reference point"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai sur l'attente / Essay on waiting",
        "text": "Nous avons supprimé l'attente partout où nous l'avons pu, sans remarquer qu'elle ne servait pas seulement à patienter.\nElle donnait sa forme au désir : ce qui s'obtient à l'instant se désire mal, et finit par ne plus se désirer du tout.",
        "question_fr": "Que perd-on, selon l'auteur, en supprimant l'attente ?",
        "options": [
            {"id": "a", "text": "Le désir lui-même",
             "explanation": "Waiting « donnait sa forme au désir », and what is instantly obtained « finit par ne plus se désirer du tout »."},
            {"id": "b", "text": "Du temps utile",
             "explanation": "Removing waiting saves time; the loss described is of a different order."},
            {"id": "c", "text": "La patience comme vertu",
             "explanation": "The text explicitly says waiting served for more than patience — that is the idea it moves beyond."},
            {"id": "d", "text": "La qualité des objets obtenus",
             "explanation": "The objects are not judged; what changes is our relation to them."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce qui s'obtient à l'instant se désire mal, et finit par ne plus se désirer du tout.",
        "key_line_en": "What is obtained instantly is poorly desired, and ends up not being desired at all.",
        "vocabulary": [
            {"term": "patienter", "gloss": "to wait patiently"},
            {"term": "donner sa forme à", "gloss": "to give shape to"},
            {"term": "à l'instant", "gloss": "instantly"},
            {"term": "remarquer", "gloss": "to notice"},
        ],
    },
]

QUESTIONS = balance(_RAW)
