"""Compréhension écrite — Test 06.

Forty questions climbing A1 → C2. Profile A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Avis / Notice",
        "topic": "Vie quotidienne & logement",
        "text": "AVIS AUX RÉSIDENTS\nL'eau sera coupée jeudi de 8 h à 12 h.\nPensez à remplir une bouteille la veille.",
        "question_fr": "Que doivent faire les résidents avant jeudi ?",
        "options": [
            {"id": "a", "text": "Préparer de l'eau",
             "explanation": "« Pensez à remplir une bouteille la veille » — fill a bottle the day before."},
            {"id": "b", "text": "Quitter l'immeuble",
             "explanation": "Nobody is asked to leave; only the water is affected."},
            {"id": "c", "text": "Appeler le plombier",
             "explanation": "The cut is planned; no call is requested."},
            {"id": "d", "text": "Fermer leurs robinets",
             "explanation": "Closing taps is not mentioned on the notice."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Pensez à remplir une bouteille la veille.",
        "key_line_en": "Remember to fill a bottle the day before.",
        "vocabulary": [
            {"term": "couper l'eau", "gloss": "to cut off the water"},
            {"term": "la veille", "gloss": "the day before"},
            {"term": "remplir", "gloss": "to fill"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Panneau / Sign",
        "topic": "Transports & voyages",
        "text": "HORODATEUR\nPayez et placez le ticket derrière le pare-brise.\nStationnement payant de 9 h à 18 h.\nGratuit le dimanche.",
        "question_fr": "Où faut-il mettre le ticket ?",
        "options": [
            {"id": "a", "text": "Dans l'horodateur",
             "explanation": "The machine issues the ticket; it is not where the ticket goes."},
            {"id": "b", "text": "Derrière le pare-brise",
             "explanation": "« placez le ticket derrière le pare-brise » says exactly where."},
            {"id": "c", "text": "Sur la porte",
             "explanation": "No door is mentioned."},
            {"id": "d", "text": "Il ne faut pas de ticket",
             "explanation": "A ticket is required between 9 a.m. and 6 p.m."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Payez et placez le ticket derrière le pare-brise.",
        "key_line_en": "Pay and place the ticket behind the windscreen.",
        "vocabulary": [
            {"term": "un horodateur", "gloss": "a parking meter"},
            {"term": "un pare-brise", "gloss": "a windscreen"},
            {"term": "le stationnement", "gloss": "parking"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Menu / Canteen menu",
        "topic": "Alimentation & consommation",
        "text": "MENU DU JOUR\nSoupe de légumes\nPoulet et riz\nFruit de saison\nMenu végétarien sur demande.",
        "question_fr": "Que peut demander une personne végétarienne ?",
        "options": [
            {"id": "a", "text": "Du poulet",
             "explanation": "Chicken is meat, which is what a vegetarian menu replaces."},
            {"id": "b", "text": "Rien, il n'y a pas de choix",
             "explanation": "There is a choice: « Menu végétarien sur demande »."},
            {"id": "c", "text": "Un autre menu",
             "explanation": "A vegetarian menu is available on request."},
            {"id": "d", "text": "Un dessert supplémentaire",
             "explanation": "No extra dessert is offered."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Menu végétarien sur demande.",
        "key_line_en": "Vegetarian menu available on request.",
        "vocabulary": [
            {"term": "sur demande", "gloss": "on request"},
            {"term": "de saison", "gloss": "seasonal"},
            {"term": "un légume", "gloss": "a vegetable"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "SMS",
        "topic": "Santé & bien-être",
        "text": "Rappel : votre rendez-vous chez le dentiste est lundi 14 mars à 11 h.\nPour annuler, répondez STOP avant dimanche.",
        "question_fr": "Comment annuler le rendez-vous ?",
        "options": [
            {"id": "a", "text": "Téléphoner lundi",
             "explanation": "Monday is the appointment itself, and the method given is a reply."},
            {"id": "b", "text": "Venir au cabinet",
             "explanation": "Coming in is not how the message says to cancel."},
            {"id": "c", "text": "Écrire une lettre",
             "explanation": "No letter is mentioned."},
            {"id": "d", "text": "Répondre STOP avant dimanche",
             "explanation": "« Pour annuler, répondez STOP avant dimanche »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Pour annuler, répondez STOP avant dimanche.",
        "key_line_en": "To cancel, reply STOP before Sunday.",
        "vocabulary": [
            {"term": "un rappel", "gloss": "a reminder"},
            {"term": "annuler", "gloss": "to cancel"},
            {"term": "répondre", "gloss": "to reply"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Horaires / Opening hours",
        "topic": "Loisirs, culture & médias",
        "text": "BIBLIOTHÈQUE — HORAIRES D'ÉTÉ\nDu 1er juillet au 31 août.\nMardi au vendredi : 14 h – 18 h.\nFermée le samedi et le lundi.",
        "question_fr": "Quand la bibliothèque est-elle ouverte en été ?",
        "options": [
            {"id": "a", "text": "Le matin",
             "explanation": "The hours run from 2 p.m. to 6 p.m., so afternoons only."},
            {"id": "b", "text": "Le samedi",
             "explanation": "« Fermée le samedi et le lundi »."},
            {"id": "c", "text": "L'après-midi, du mardi au vendredi",
             "explanation": "« Mardi au vendredi : 14 h – 18 h »."},
            {"id": "d", "text": "Tous les jours",
             "explanation": "Saturday and Monday are closed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Mardi au vendredi : 14 h – 18 h.",
        "key_line_en": "Tuesday to Friday: 2 p.m. – 6 p.m.",
        "vocabulary": [
            {"term": "les horaires", "gloss": "opening hours"},
            {"term": "l'été", "gloss": "summer"},
            {"term": "fermé", "gloss": "closed"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Mot / Note",
        "topic": "Études & formation",
        "text": "Chers étudiants,\nL'examen de mardi aura lieu salle 105, et non salle 12.\nApportez une pièce d'identité.\nMerci.",
        "question_fr": "Qu'est-ce qui change ?",
        "options": [
            {"id": "a", "text": "La salle de l'examen",
             "explanation": "« salle 105, et non salle 12 » — the room has changed."},
            {"id": "b", "text": "Le jour de l'examen",
             "explanation": "It is still on Tuesday."},
            {"id": "c", "text": "L'heure de l'examen",
             "explanation": "No time is given at all."},
            {"id": "d", "text": "Le sujet de l'examen",
             "explanation": "The subject is never mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'examen de mardi aura lieu salle 105, et non salle 12.",
        "key_line_en": "Tuesday's exam will be in room 105, not room 12.",
        "vocabulary": [
            {"term": "avoir lieu", "gloss": "to take place"},
            {"term": "une salle", "gloss": "a room"},
            {"term": "une pièce d'identité", "gloss": "an ID document"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Petite annonce / Classified ad",
        "topic": "Travail & emploi",
        "text": "STAGE — COMMUNICATION\nDurée : trois mois, à partir de janvier.\nConvention de stage obligatoire : le candidat doit être inscrit dans un établissement.\nIndemnité mensuelle de 600 €. Télétravail possible un jour par semaine.",
        "question_fr": "Qui peut postuler à ce stage ?",
        "options": [
            {"id": "a", "text": "Toute personne cherchant un emploi",
             "explanation": "A student agreement is required, which a jobseeker cannot provide."},
            {"id": "b", "text": "Une personne inscrite dans une école",
             "explanation": "« le candidat doit être inscrit dans un établissement » to obtain the convention."},
            {"id": "c", "text": "Uniquement les personnes en télétravail",
             "explanation": "Remote work is an option once hired, not a condition."},
            {"id": "d", "text": "Les diplômés depuis trois mois",
             "explanation": "Three months is the length of the placement, not a graduation condition."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Convention de stage obligatoire : le candidat doit être inscrit dans un établissement.",
        "key_line_en": "A placement agreement is compulsory: the candidate must be enrolled at an institution.",
        "vocabulary": [
            {"term": "une convention de stage", "gloss": "a placement agreement"},
            {"term": "une indemnité", "gloss": "an allowance"},
            {"term": "inscrit", "gloss": "enrolled"},
            {"term": "postuler", "gloss": "to apply"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Note du syndic / Building management notice",
        "topic": "Vie quotidienne & logement",
        "text": "CHAUFFAGE COLLECTIF\nLa mise en route est prévue le 15 octobre.\nSi un radiateur ne chauffe pas, signalez-le avant le 30 octobre : une seule intervention groupée sera organisée.\nPassé cette date, les frais seront à la charge du propriétaire.",
        "question_fr": "Que se passe-t-il après le 30 octobre ?",
        "options": [
            {"id": "a", "text": "Le chauffage est arrêté",
             "explanation": "The heating starts on 15 October; no shutdown is announced."},
            {"id": "b", "text": "Les radiateurs sont remplacés",
             "explanation": "Replacement is never mentioned, only repair."},
            {"id": "c", "text": "Le propriétaire paie l'intervention",
             "explanation": "« Passé cette date, les frais seront à la charge du propriétaire »."},
            {"id": "d", "text": "Il n'est plus possible de signaler un problème",
             "explanation": "Reporting stays possible; what changes is who pays."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Passé cette date, les frais seront à la charge du propriétaire.",
        "key_line_en": "After that date, the cost will be borne by the owner.",
        "vocabulary": [
            {"term": "la mise en route", "gloss": "the start-up"},
            {"term": "signaler", "gloss": "to report"},
            {"term": "à la charge de", "gloss": "at the expense of"},
            {"term": "groupé", "gloss": "combined, grouped"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Consigne / Instructions",
        "topic": "Sciences & technologies",
        "text": "IMPRIMANTE PARTAGÉE\nEnvoyez votre document depuis votre poste, puis passez votre badge sur l'appareil.\nL'impression ne démarre qu'après le badge : les documents non imprimés sont effacés au bout de deux heures.",
        "question_fr": "Pourquoi faut-il passer son badge ?",
        "options": [
            {"id": "a", "text": "Pour lancer l'impression",
             "explanation": "« L'impression ne démarre qu'après le badge » — the badge triggers the print."},
            {"id": "b", "text": "Pour ouvrir la porte du bureau",
             "explanation": "No door or access control is mentioned here."},
            {"id": "c", "text": "Pour payer les copies",
             "explanation": "No charge appears in the instructions."},
            {"id": "d", "text": "Pour effacer les documents",
             "explanation": "Unprinted documents are deleted automatically after two hours."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'impression ne démarre qu'après le badge.",
        "key_line_en": "Printing only starts once the badge has been swiped.",
        "vocabulary": [
            {"term": "un poste", "gloss": "a workstation"},
            {"term": "passer son badge", "gloss": "to swipe one's badge"},
            {"term": "démarrer", "gloss": "to start"},
            {"term": "effacer", "gloss": "to delete"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Conditions / Terms",
        "topic": "Transports & voyages",
        "text": "RETARD DE TRAIN — INDEMNISATION\nÀ partir de 30 minutes de retard : 25 % du prix du billet.\nÀ partir de 2 heures : 50 %.\nLa demande se fait en ligne, dans les 60 jours suivant le voyage.",
        "question_fr": "Que reçoit un voyageur retardé de 45 minutes ?",
        "options": [
            {"id": "a", "text": "Rien",
             "explanation": "Compensation starts at 30 minutes, and 45 is above that."},
            {"id": "b", "text": "Le remboursement complet",
             "explanation": "No band gives 100 %; the maximum listed is 50 %."},
            {"id": "c", "text": "50 % du prix",
             "explanation": "50 % applies from two hours onwards."},
            {"id": "d", "text": "25 % du prix",
             "explanation": "45 minutes falls in the first band, « À partir de 30 minutes […] 25 % »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "À partir de 30 minutes de retard : 25 % du prix du billet.",
        "key_line_en": "From 30 minutes' delay: 25 % of the ticket price.",
        "vocabulary": [
            {"term": "une indemnisation", "gloss": "compensation"},
            {"term": "un retard", "gloss": "a delay"},
            {"term": "une demande", "gloss": "a claim, request"},
            {"term": "suivant", "gloss": "following"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Affichage restaurant / Restaurant notice",
        "topic": "Alimentation & consommation",
        "text": "ALLERGÈNES\nLa liste complète des allergènes est disponible à l'accueil.\nNos plats sont préparés dans une cuisine qui utilise gluten, œufs et fruits à coque.\nSignalez toute allergie au moment de la commande.",
        "question_fr": "Que doit faire un client allergique ?",
        "options": [
            {"id": "a", "text": "Prévenir lorsqu'il commande",
             "explanation": "« Signalez toute allergie au moment de la commande »."},
            {"id": "b", "text": "Apporter son repas",
             "explanation": "Nothing suggests bringing food."},
            {"id": "c", "text": "Choisir un plat sans gluten",
             "explanation": "The notice warns that the kitchen handles gluten; it does not offer a guaranteed dish."},
            {"id": "d", "text": "Demander la liste après le repas",
             "explanation": "The list is available at reception, and allergies must be flagged when ordering."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Signalez toute allergie au moment de la commande.",
        "key_line_en": "Please report any allergy when ordering.",
        "vocabulary": [
            {"term": "un allergène", "gloss": "an allergen"},
            {"term": "des fruits à coque", "gloss": "nuts"},
            {"term": "signaler", "gloss": "to report, flag"},
            {"term": "une commande", "gloss": "an order"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Règlement / Rules",
        "topic": "Loisirs, culture & médias",
        "text": "PISCINE — LIGNES D'EAU\nLigne 1 : nage lente. Ligne 2 : nage rapide.\nLigne 3 réservée aux cours, de 18 h à 20 h.\nLe bonnet de bain est obligatoire pour tous.",
        "question_fr": "Que doit porter chaque nageur ?",
        "options": [
            {"id": "a", "text": "Des lunettes",
             "explanation": "Goggles are never mentioned."},
            {"id": "b", "text": "Un bonnet de bain",
             "explanation": "« Le bonnet de bain est obligatoire pour tous »."},
            {"id": "c", "text": "Rien de particulier",
             "explanation": "One item is compulsory for everyone."},
            {"id": "d", "text": "Un bracelet de ligne",
             "explanation": "No wristband exists in these rules."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Le bonnet de bain est obligatoire pour tous.",
        "key_line_en": "A swimming cap is compulsory for everyone.",
        "vocabulary": [
            {"term": "un bonnet de bain", "gloss": "a swimming cap"},
            {"term": "une ligne d'eau", "gloss": "a swimming lane"},
            {"term": "réservé à", "gloss": "reserved for"},
            {"term": "la nage", "gloss": "swimming"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information administrative / Administrative notice",
        "topic": "Société, citoyenneté & administration",
        "text": "CARTE D'IDENTITÉ\nLe dépôt du dossier se fait uniquement sur rendez-vous.\nLe délai actuel est de six semaines entre le dépôt et la remise du titre.\nLa présence du demandeur est obligatoire aux deux étapes.",
        "question_fr": "Combien de fois faut-il se déplacer ?",
        "options": [
            {"id": "a", "text": "Une seule fois",
             "explanation": "Presence is required at both the deposit and the collection."},
            {"id": "b", "text": "Deux fois",
             "explanation": "« La présence du demandeur est obligatoire aux deux étapes » — deposit and handover."},
            {"id": "c", "text": "Six fois",
             "explanation": "Six is the number of weeks' waiting, not of visits."},
            {"id": "d", "text": "Aucune, tout se fait en ligne",
             "explanation": "An appointment and in-person presence are required."},
        ],
        "correct_answer": "b",
        "key_line_fr": "La présence du demandeur est obligatoire aux deux étapes.",
        "key_line_en": "The applicant must be present at both stages.",
        "vocabulary": [
            {"term": "un dépôt", "gloss": "a submission"},
            {"term": "la remise", "gloss": "the handover"},
            {"term": "un titre", "gloss": "a document, ID"},
            {"term": "un demandeur", "gloss": "an applicant"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article de presse / Press article",
        "topic": "Environnement & nature",
        "text": "La cantine scolaire a supprimé les barquettes en plastique au profit de bacs en inox.\n« L'investissement a été lourd, admet la responsable, mais nous le rentabilisons en quatre ans. Ce que nous n'avions pas prévu, c'est que les enfants trouvent que ça sent meilleur. »",
        "question_fr": "Quel effet la responsable n'avait-elle pas anticipé ?",
        "options": [
            {"id": "a", "text": "Le coût élevé du matériel",
             "explanation": "The cost was known and planned for over four years."},
            {"id": "b", "text": "La réaction des enfants",
             "explanation": "« Ce que nous n'avions pas prévu, c'est que les enfants trouvent que ça sent meilleur »."},
            {"id": "c", "text": "La durée d'amortissement",
             "explanation": "Four years is presented as a calculation already made."},
            {"id": "d", "text": "La difficulté du nettoyage",
             "explanation": "Cleaning is never mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Ce que nous n'avions pas prévu, c'est que les enfants trouvent que ça sent meilleur.",
        "key_line_en": "What we had not expected is that the children think it smells better.",
        "vocabulary": [
            {"term": "une barquette", "gloss": "a food tray"},
            {"term": "rentabiliser", "gloss": "to recoup, make pay for itself"},
            {"term": "au profit de", "gloss": "in favour of"},
            {"term": "prévoir", "gloss": "to foresee"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "topic": "Travail & emploi",
        "text": "Après un an de semaine de quatre jours, l'entreprise publie ses chiffres : chiffre d'affaires stable, absences en baisse d'un tiers.\nLes salariés soulignent cependant que les journées sont devenues plus denses, et que les pauses ont pratiquement disparu.",
        "question_fr": "Quelle réserve les salariés expriment-ils ?",
        "options": [
            {"id": "a", "text": "Le chiffre d'affaires a baissé",
             "explanation": "Turnover is reported as stable."},
            {"id": "b", "text": "Les absences ont augmenté",
             "explanation": "They fell by a third."},
            {"id": "c", "text": "Le travail est plus concentré qu'avant",
             "explanation": "« les journées sont devenues plus denses, et […] les pauses ont pratiquement disparu »."},
            {"id": "d", "text": "Ils souhaitent revenir à cinq jours",
             "explanation": "No wish to go back is expressed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les journées sont devenues plus denses, et les pauses ont pratiquement disparu.",
        "key_line_en": "The days have become more intense, and breaks have all but disappeared.",
        "vocabulary": [
            {"term": "le chiffre d'affaires", "gloss": "turnover"},
            {"term": "dense", "gloss": "intense, packed"},
            {"term": "une pause", "gloss": "a break"},
            {"term": "souligner", "gloss": "to point out"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Présentation de dispositif / Scheme description",
        "topic": "Études & formation",
        "text": "Le tutorat met en relation un étudiant de première année et un étudiant plus avancé.\nLe tuteur n'est pas là pour donner des cours : il explique comment travailler, où trouver l'information et à qui s'adresser. Deux heures par mois suffisent, à condition qu'elles soient régulières.",
        "question_fr": "Quel est le rôle du tuteur ?",
        "options": [
            {"id": "a", "text": "Enseigner le contenu des cours",
             "explanation": "« Le tuteur n'est pas là pour donner des cours » — that is explicitly excluded."},
            {"id": "b", "text": "Corriger les examens",
             "explanation": "Marking is never mentioned."},
            {"id": "c", "text": "Aider à s'organiser et à s'orienter",
             "explanation": "He explains « comment travailler, où trouver l'information et à qui s'adresser »."},
            {"id": "d", "text": "Remplacer l'enseignant",
             "explanation": "The scheme sits alongside teaching, not in place of it."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Il explique comment travailler, où trouver l'information et à qui s'adresser.",
        "key_line_en": "He explains how to work, where to find information and who to ask.",
        "vocabulary": [
            {"term": "le tutorat", "gloss": "mentoring, tutoring"},
            {"term": "mettre en relation", "gloss": "to put in touch"},
            {"term": "s'adresser à", "gloss": "to go to, ask"},
            {"term": "régulier", "gloss": "regular"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Information santé / Health information",
        "topic": "Santé & bien-être",
        "text": "Les pharmaciens peuvent désormais vacciner contre la grippe sans ordonnance.\nLa mesure vise les personnes qui renoncent faute de temps : la vaccination prend dix minutes et ne nécessite aucun rendez-vous. Les publics fragiles restent suivis par leur médecin.",
        "question_fr": "Quel problème cette mesure cherche-t-elle à résoudre ?",
        "options": [
            {"id": "a", "text": "Le manque de vaccins disponibles",
             "explanation": "Supply is never mentioned; access is."},
            {"id": "b", "text": "Le renoncement par manque de temps",
             "explanation": "« La mesure vise les personnes qui renoncent faute de temps » — no appointment, ten minutes."},
            {"id": "c", "text": "Le coût de la vaccination",
             "explanation": "No price is discussed."},
            {"id": "d", "text": "Le manque de médecins pour les publics fragiles",
             "explanation": "Vulnerable groups stay with their doctor, which is a limit of the measure, not its aim."},
        ],
        "correct_answer": "b",
        "key_line_fr": "La mesure vise les personnes qui renoncent faute de temps.",
        "key_line_en": "The measure targets people who give up for lack of time.",
        "vocabulary": [
            {"term": "une ordonnance", "gloss": "a prescription"},
            {"term": "renoncer", "gloss": "to give up"},
            {"term": "viser", "gloss": "to target"},
            {"term": "fragile", "gloss": "vulnerable"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article municipal / Local news",
        "topic": "Transports & voyages",
        "text": "Une voie réservée au covoiturage a été créée sur l'autoroute d'accès à la ville.\nLes contrôles montrent qu'un quart des véhicules qui l'empruntent transportent une seule personne. La commune envisage des caméras plutôt que d'augmenter le montant de l'amende.",
        "question_fr": "Que prévoit la commune ?",
        "options": [
            {"id": "a", "text": "Supprimer la voie réservée",
             "explanation": "Removal is not among the options considered."},
            {"id": "b", "text": "Augmenter le montant de l'amende",
             "explanation": "« plutôt que d'augmenter le montant de l'amende » — that is the option set aside."},
            {"id": "c", "text": "Renforcer la surveillance",
             "explanation": "« La commune envisage des caméras » — better detection rather than a higher fine."},
            {"id": "d", "text": "Ouvrir la voie à tous les véhicules",
             "explanation": "That would abolish the scheme, which is not proposed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La commune envisage des caméras plutôt que d'augmenter le montant de l'amende.",
        "key_line_en": "The council is considering cameras rather than raising the fine.",
        "vocabulary": [
            {"term": "le covoiturage", "gloss": "car-sharing"},
            {"term": "emprunter (une voie)", "gloss": "to use (a lane)"},
            {"term": "une amende", "gloss": "a fine"},
            {"term": "envisager", "gloss": "to consider"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Reportage / Report",
        "topic": "Alimentation & consommation",
        "text": "La cantine s'approvisionne désormais auprès de producteurs situés à moins de cent kilomètres.\n« Le prix de revient a augmenté de huit pour cent, reconnaît le gestionnaire. Nous l'avons compensé en servant moins de viande, pas en augmentant le tarif payé par les familles. »",
        "question_fr": "Comment la hausse des coûts a-t-elle été absorbée ?",
        "options": [
            {"id": "a", "text": "En augmentant le prix des repas",
             "explanation": "« pas en augmentant le tarif payé par les familles »."},
            {"id": "b", "text": "En réduisant la part de viande",
             "explanation": "« Nous l'avons compensé en servant moins de viande »."},
            {"id": "c", "text": "En réduisant le nombre de repas",
             "explanation": "The number of meals is never mentioned."},
            {"id": "d", "text": "En changeant de fournisseurs",
             "explanation": "Changing suppliers is what caused the rise in the first place."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nous l'avons compensé en servant moins de viande, pas en augmentant le tarif payé par les familles.",
        "key_line_en": "We offset it by serving less meat, not by raising the price paid by families.",
        "vocabulary": [
            {"term": "s'approvisionner", "gloss": "to source supplies"},
            {"term": "le prix de revient", "gloss": "the cost price"},
            {"term": "compenser", "gloss": "to offset"},
            {"term": "un gestionnaire", "gloss": "a manager, administrator"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Information municipale / Council information",
        "topic": "Société, citoyenneté & administration",
        "text": "Les habitants peuvent proposer des projets financés par le budget participatif.\nSeuls les projets d'investissement sont recevables : la ville peut financer un terrain de jeu, pas les salaires de ceux qui l'animeront.\nLe vote a lieu en novembre.",
        "question_fr": "Quel type de projet peut être proposé ?",
        "options": [
            {"id": "a", "text": "Un projet créant des emplois permanents",
             "explanation": "Salaries fall outside investment spending: « pas les salaires »."},
            {"id": "b", "text": "N'importe quel projet",
             "explanation": "« Seuls les projets d'investissement sont recevables »."},
            {"id": "c", "text": "Un projet réservé aux associations",
             "explanation": "Any resident may propose; no such restriction exists."},
            {"id": "d", "text": "Un projet d'équipement",
             "explanation": "A playground is given as the example of what qualifies."},
        ],
        "correct_answer": "d",
        "key_line_fr": "La ville peut financer un terrain de jeu, pas les salaires de ceux qui l'animeront.",
        "key_line_en": "The city can fund a playground, not the wages of those who will run it.",
        "vocabulary": [
            {"term": "recevable", "gloss": "admissible, eligible"},
            {"term": "un investissement", "gloss": "capital spending"},
            {"term": "animer", "gloss": "to run, lead"},
            {"term": "un budget participatif", "gloss": "a participatory budget"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "topic": "Société, citoyenneté & administration",
        "text": "On juge la bibliothèque au nombre de livres empruntés, ce qui revient à juger une place publique au nombre de bancs occupés.\nOn y vient aussi pour travailler au chaud, imprimer un dossier ou n'être dérangé par personne. Ces usages ne laissent aucune trace, et ce sont eux qui font le lieu.",
        "question_fr": "Que défend l'auteur ?",
        "options": [
            {"id": "a", "text": "L'utilité de la bibliothèque dépasse ce qu'on en mesure",
             "explanation": "Working in the warm or being left alone « ne laissent aucune trace, et ce sont eux qui font le lieu »."},
            {"id": "b", "text": "Il faut augmenter le nombre de prêts",
             "explanation": "Loans are the metric he considers too narrow, not a target to raise."},
            {"id": "c", "text": "Les bibliothèques coûtent trop cher",
             "explanation": "No budget question is raised."},
            {"id": "d", "text": "Il faudrait fermer les places publiques",
             "explanation": "The square is an analogy, not a subject."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ces usages ne laissent aucune trace, et ce sont eux qui font le lieu.",
        "key_line_en": "These uses leave no record, and they are what makes the place.",
        "vocabulary": [
            {"term": "un emprunt", "gloss": "a loan (of a book)"},
            {"term": "revenir à", "gloss": "to amount to"},
            {"term": "un usage", "gloss": "a use, practice"},
            {"term": "déranger", "gloss": "to disturb"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "topic": "Loisirs, culture & médias",
        "text": "Le podcast a rendu la parole longue de nouveau écoutable, à un moment où l'on annonçait la fin de l'attention.\nSon secret n'est pas la durée mais l'accompagnement : on l'écoute en marchant, en cuisinant, en conduisant. Il n'a pas gagné du temps sur les autres médias, il en a trouvé là où personne n'en cherchait.",
        "question_fr": "Comment l'auteur explique-t-il le succès du podcast ?",
        "options": [
            {"id": "a", "text": "Il propose des contenus plus courts",
             "explanation": "The opposite: it made long-form speech listenable again."},
            {"id": "b", "text": "Il occupe des moments jusque-là inutilisés",
             "explanation": "« il en a trouvé là où personne n'en cherchait » — walking, cooking, driving."},
            {"id": "c", "text": "Il remplace la radio traditionnelle",
             "explanation": "No substitution for other media is claimed — the reverse is stated."},
            {"id": "d", "text": "Il demande une attention totale",
             "explanation": "It is listened to while doing something else."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Il n'a pas gagné du temps sur les autres médias, il en a trouvé là où personne n'en cherchait.",
        "key_line_en": "It did not take time from other media, it found time where nobody was looking for any.",
        "vocabulary": [
            {"term": "la parole longue", "gloss": "long-form speech"},
            {"term": "l'accompagnement", "gloss": "being a companion activity"},
            {"term": "gagner du temps sur", "gloss": "to take time from"},
            {"term": "annoncer", "gloss": "to predict, announce"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "topic": "Sciences & technologies",
        "text": "Recycler une batterie coûte aujourd'hui plus cher que d'extraire le métal neuf, ce qui explique les faibles taux observés.\nCe rapport s'inversera lorsque les gisements les plus accessibles seront épuisés. La question n'est donc pas technique : la filière existe, elle attend seulement d'être rentable.",
        "question_fr": "Pourquoi recycle-t-on peu de batteries ?",
        "options": [
            {"id": "a", "text": "Parce qu'on ne sait pas le faire",
             "explanation": "« La question n'est donc pas technique : la filière existe »."},
            {"id": "b", "text": "Parce que les métaux sont rares",
             "explanation": "They are still accessible enough to be cheaper to mine — the scarcity comes later."},
            {"id": "c", "text": "Parce que ce n'est pas encore rentable",
             "explanation": "Recycling costs more than new extraction, and « elle attend seulement d'être rentable »."},
            {"id": "d", "text": "Parce que les batteries durent trop longtemps",
             "explanation": "Battery lifespan is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La filière existe, elle attend seulement d'être rentable.",
        "key_line_en": "The industry exists, it is only waiting to become profitable.",
        "vocabulary": [
            {"term": "un gisement", "gloss": "a deposit (of ore)"},
            {"term": "épuisé", "gloss": "exhausted"},
            {"term": "une filière", "gloss": "an industry, supply chain"},
            {"term": "rentable", "gloss": "profitable"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "topic": "Environnement & nature",
        "text": "Les toitures végétalisées retiennent l'eau de pluie et rafraîchissent les étages supérieurs.\nElles exigent en revanche une structure capable de porter le poids du substrat gorgé d'eau, ce que la plupart des bâtiments anciens ne permettent pas sans travaux lourds.",
        "question_fr": "Quelle limite l'article signale-t-il ?",
        "options": [
            {"id": "a", "text": "Elles consomment trop d'eau",
             "explanation": "They retain rainwater rather than consuming supply."},
            {"id": "b", "text": "Elles ne rafraîchissent pas les bâtiments",
             "explanation": "Cooling of the upper floors is listed as a benefit."},
            {"id": "c", "text": "Elles sont interdites sur les bâtiments anciens",
             "explanation": "No ban exists; the obstacle is structural and financial."},
            {"id": "d", "text": "Peu de bâtiments anciens peuvent en supporter le poids",
             "explanation": "The saturated substrate needs a structure « que la plupart des bâtiments anciens ne permettent pas sans travaux lourds »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Elles exigent une structure capable de porter le poids du substrat gorgé d'eau.",
        "key_line_en": "They require a structure able to bear the weight of the water-logged substrate.",
        "vocabulary": [
            {"term": "une toiture", "gloss": "a roof"},
            {"term": "retenir", "gloss": "to hold back, retain"},
            {"term": "gorgé d'eau", "gloss": "waterlogged"},
            {"term": "des travaux lourds", "gloss": "major works"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "topic": "Travail & emploi",
        "text": "Bonjour,\nJe propose de supprimer la réunion hebdomadaire de suivi et de la remplacer par un compte rendu écrit le vendredi.\nNous nous verrons une fois par mois, mais pour arbitrer, pas pour nous informer. Informer par oral coûte huit heures de présence chaque mois.",
        "question_fr": "Quelle distinction l'auteur établit-il ?",
        "options": [
            {"id": "a", "text": "Entre réunions courtes et réunions longues",
             "explanation": "Duration is a consequence here, not the criterion."},
            {"id": "b", "text": "Entre se réunir pour informer et pour décider",
             "explanation": "Monthly meetings « pour arbitrer, pas pour nous informer »; information moves to writing."},
            {"id": "c", "text": "Entre travail sur site et à distance",
             "explanation": "Remote work is not mentioned."},
            {"id": "d", "text": "Entre comptes rendus oraux et écrits",
             "explanation": "That is the means adopted, not the distinction the reform rests on."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nous nous verrons une fois par mois, mais pour arbitrer, pas pour nous informer.",
        "key_line_en": "We will meet once a month, but to decide, not to inform each other.",
        "vocabulary": [
            {"term": "un compte rendu", "gloss": "a report, minutes"},
            {"term": "arbitrer", "gloss": "to decide between options"},
            {"term": "hebdomadaire", "gloss": "weekly"},
            {"term": "le suivi", "gloss": "follow-up, monitoring"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Analyse économique / Economic analysis",
        "topic": "Alimentation & consommation",
        "text": "Le bio coûte plus cher, et l'écart se réduit peu.\nUne partie s'explique par des rendements inférieurs, une autre par des volumes trop faibles pour amortir la logistique. Le premier facteur est agronomique et durable ; le second disparaîtrait si la demande augmentait.",
        "question_fr": "Que distingue l'auteur dans l'écart de prix ?",
        "options": [
            {"id": "a", "text": "Une part structurelle et une part liée aux volumes",
             "explanation": "Lower yields are « agronomique et durable »; the logistics share « disparaîtrait si la demande augmentait »."},
            {"id": "b", "text": "Une part due aux taxes et une part due aux marges",
             "explanation": "Neither taxes nor margins are mentioned."},
            {"id": "c", "text": "Une part française et une part importée",
             "explanation": "No geographical breakdown appears."},
            {"id": "d", "text": "Une part qui disparaîtra entièrement",
             "explanation": "Only the second factor could disappear; the first is described as lasting."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le premier facteur est agronomique et durable ; le second disparaîtrait si la demande augmentait.",
        "key_line_en": "The first factor is agronomic and lasting; the second would vanish if demand grew.",
        "vocabulary": [
            {"term": "un rendement", "gloss": "a yield"},
            {"term": "amortir", "gloss": "to spread, absorb (a cost)"},
            {"term": "durable", "gloss": "lasting"},
            {"term": "un écart", "gloss": "a gap"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article santé / Health article",
        "topic": "Santé & bien-être",
        "text": "Élargir un dépistage semble toujours souhaitable, et pourtant chaque élargissement a un coût invisible.\nDétecter des anomalies qui n'auraient jamais évolué conduit à traiter des personnes que la maladie n'aurait pas atteintes. Le bénéfice net dépend donc du seuil, non du principe.",
        "question_fr": "Pourquoi élargir un dépistage n'est-il pas toujours bénéfique ?",
        "options": [
            {"id": "a", "text": "Parce que les tests sont peu fiables",
             "explanation": "Reliability is not questioned; the anomalies found are real but harmless."},
            {"id": "b", "text": "Parce qu'on traite des personnes qui n'en avaient pas besoin",
             "explanation": "Detecting anomalies « qui n'auraient jamais évolué » leads to treating people the disease would never have reached."},
            {"id": "c", "text": "Parce que les patients refusent le dépistage",
             "explanation": "Patient refusal is not discussed."},
            {"id": "d", "text": "Parce que le dépistage précoce est inutile",
             "explanation": "The principle is not rejected: « Le bénéfice net dépend du seuil, non du principe »."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Le bénéfice net dépend donc du seuil, non du principe.",
        "key_line_en": "The net benefit therefore depends on the threshold, not on the principle.",
        "vocabulary": [
            {"term": "un dépistage", "gloss": "a screening programme"},
            {"term": "évoluer", "gloss": "to progress (of a condition)"},
            {"term": "un seuil", "gloss": "a threshold"},
            {"term": "élargir", "gloss": "to widen"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "topic": "Sciences & technologies",
        "text": "Mesurer modifie ce qui est mesuré, et pas seulement en physique.\nDès qu'un indicateur devient un objectif, il cesse de renseigner : on optimise le chiffre, non la chose. Ce n'est pas une dérive, c'est la conséquence prévisible de toute récompense attachée à une mesure.",
        "question_fr": "Quelle est la thèse de l'auteur ?",
        "options": [
            {"id": "a", "text": "Un indicateur devenu objectif perd sa valeur informative",
             "explanation": "« Dès qu'un indicateur devient un objectif, il cesse de renseigner : on optimise le chiffre, non la chose »."},
            {"id": "b", "text": "Les mesures sont généralement falsifiées",
             "explanation": "No fraud is alleged; the effect is described as predictable, not dishonest."},
            {"id": "c", "text": "Il faudrait renoncer à toute mesure",
             "explanation": "No such renunciation is proposed."},
            {"id": "d", "text": "Le phénomène ne concerne que la physique",
             "explanation": "« et pas seulement en physique » extends it explicitly."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Dès qu'un indicateur devient un objectif, il cesse de renseigner.",
        "key_line_en": "As soon as an indicator becomes a target, it stops being informative.",
        "vocabulary": [
            {"term": "renseigner", "gloss": "to be informative"},
            {"term": "une dérive", "gloss": "a drift, aberration"},
            {"term": "prévisible", "gloss": "predictable"},
            {"term": "optimiser", "gloss": "to optimise"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "topic": "Société, citoyenneté & administration",
        "text": "Le document stratégique fait quatre-vingts pages et se lit sans difficulté : chaque phrase est claire, aucune n'engage.\nOn y « accompagnera les transitions » et l'on « renforcera les synergies ». À la dernière page, on ignore toujours ce qui sera fait, par qui, et avant quand.",
        "question_fr": "Que reproche l'auteur à ce document ?",
        "options": [
            {"id": "a", "text": "Son style trop technique",
             "explanation": "It reads easily and every sentence is clear — clarity is not the problem."},
            {"id": "b", "text": "Sa longueur excessive",
             "explanation": "Eighty pages is a symptom; the objection is that none of them commits to anything."},
            {"id": "c", "text": "Son absence d'engagement concret",
             "explanation": "« aucune n'engage » and, at the end, no what, no who, no when."},
            {"id": "d", "text": "Ses erreurs factuelles",
             "explanation": "No factual claim is disputed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On ignore toujours ce qui sera fait, par qui, et avant quand.",
        "key_line_en": "You still do not know what will be done, by whom, or by when.",
        "vocabulary": [
            {"term": "engager", "gloss": "to commit, bind"},
            {"term": "une synergie", "gloss": "a synergy"},
            {"term": "accompagner", "gloss": "to support, accompany"},
            {"term": "ignorer", "gloss": "not to know"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "topic": "Travail & emploi",
        "text": "Les intitulés de poste changent plus vite que les métiers qu'ils désignent.\nUn « responsable de l'expérience client » fait souvent ce qu'un chef de rayon faisait hier. Renommer donne le sentiment d'avoir transformé une organisation sans avoir déplacé la moindre décision.",
        "question_fr": "Que dénonce l'auteur ?",
        "options": [
            {"id": "a", "text": "La disparition des anciens métiers",
             "explanation": "The jobs persist; only their names change."},
            {"id": "b", "text": "Un changement de vocabulaire pris pour une réforme",
             "explanation": "« Renommer donne le sentiment d'avoir transformé une organisation sans avoir déplacé la moindre décision »."},
            {"id": "c", "text": "La complexité des organigrammes",
             "explanation": "Org charts are not discussed."},
            {"id": "d", "text": "Le manque de formation des responsables",
             "explanation": "Training is never mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Renommer donne le sentiment d'avoir transformé une organisation sans avoir déplacé la moindre décision.",
        "key_line_en": "Renaming gives the feeling of having transformed an organisation without moving a single decision.",
        "vocabulary": [
            {"term": "un intitulé de poste", "gloss": "a job title"},
            {"term": "désigner", "gloss": "to denote"},
            {"term": "un chef de rayon", "gloss": "a department manager"},
            {"term": "déplacer", "gloss": "to move, shift"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "topic": "Loisirs, culture & médias",
        "text": "Il avait appris la langue en six mois et la parlait mieux que ses collègues nés ici.\nCe qui lui manquait n'était pas un mot mais un souvenir : les chansons qu'on fredonne sans y penser, et qui font qu'une phrase, chez les autres, en appelle une autre.",
        "question_fr": "Que lui manque-t-il malgré sa maîtrise de la langue ?",
        "options": [
            {"id": "a", "text": "Du vocabulaire technique",
             "explanation": "« Ce qui lui manquait n'était pas un mot » — vocabulary is not the gap."},
            {"id": "b", "text": "La confiance pour s'exprimer",
             "explanation": "He speaks better than native colleagues; confidence is not raised."},
            {"id": "c", "text": "Un fonds culturel commun",
             "explanation": "The songs hummed without thinking, which make one phrase call up another — shared memory, not language."},
            {"id": "d", "text": "Un accent correct",
             "explanation": "Accent is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ce qui lui manquait n'était pas un mot mais un souvenir.",
        "key_line_en": "What he lacked was not a word but a memory.",
        "vocabulary": [
            {"term": "fredonner", "gloss": "to hum"},
            {"term": "en appeler une autre", "gloss": "to call up another"},
            {"term": "manquer à", "gloss": "to be lacking to"},
            {"term": "sans y penser", "gloss": "without thinking about it"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "topic": "Environnement & nature",
        "text": "Laisser une parcelle évoluer sans intervention produit d'abord un appauvrissement apparent : quelques espèces dominent et occupent l'espace.\nCe stade décourage souvent les gestionnaires, qui interviennent trop tôt. La diversité revient, mais après dix ou quinze ans — au-delà de la durée de la plupart des programmes.",
        "question_fr": "Pourquoi ces expériences échouent-elles souvent ?",
        "options": [
            {"id": "a", "text": "Parce que la diversité ne revient jamais",
             "explanation": "It does return, but « après dix ou quinze ans »."},
            {"id": "b", "text": "Parce qu'on les interrompt avant le résultat",
             "explanation": "The impoverished stage discourages managers « qui interviennent trop tôt », and programmes end before the recovery."},
            {"id": "c", "text": "Parce que les espèces dominantes sont invasives",
             "explanation": "No invasive species are mentioned; dominance here is a stage, not a pathology."},
            {"id": "d", "text": "Parce que les parcelles sont trop petites",
             "explanation": "Plot size is never discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "La diversité revient, mais après dix ou quinze ans — au-delà de la durée de la plupart des programmes.",
        "key_line_en": "Diversity does return, but after ten or fifteen years — beyond the length of most programmes.",
        "vocabulary": [
            {"term": "une parcelle", "gloss": "a plot"},
            {"term": "un appauvrissement", "gloss": "an impoverishment"},
            {"term": "un gestionnaire", "gloss": "a manager, warden"},
            {"term": "au-delà de", "gloss": "beyond"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Commentaire institutionnel / Institutional commentary",
        "topic": "Société, citoyenneté & administration",
        "text": "La loi crée un droit nouveau et en confie l'exercice à une autorité qu'elle ne dote d'aucun moyen supplémentaire.\nLe droit existe donc, opposable en théorie, inexerçable en pratique — situation dont le législateur ne peut ignorer qu'elle produit surtout du contentieux.",
        "question_fr": "Quelle conséquence l'auteur anticipe-t-il ?",
        "options": [
            {"id": "a", "text": "Une multiplication des recours",
             "explanation": "A right that is « opposable en théorie, inexerçable en pratique » « produit surtout du contentieux »."},
            {"id": "b", "text": "Une application rapide de la loi",
             "explanation": "The authority has no extra means, which makes swift application unlikely."},
            {"id": "c", "text": "L'abrogation du droit créé",
             "explanation": "No repeal is envisaged."},
            {"id": "d", "text": "Une baisse du nombre de litiges",
             "explanation": "The opposite of what « contentieux » announces."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le droit existe donc, opposable en théorie, inexerçable en pratique.",
        "key_line_en": "So the right exists, enforceable in theory, unexercisable in practice.",
        "vocabulary": [
            {"term": "doter de", "gloss": "to provide with"},
            {"term": "opposable", "gloss": "enforceable"},
            {"term": "le contentieux", "gloss": "litigation"},
            {"term": "l'exercice (d'un droit)", "gloss": "the exercise (of a right)"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse urbaine / Urban analysis",
        "topic": "Vie quotidienne & logement",
        "text": "Le commerce de rez-de-chaussée ne disparaît pas seulement à cause d'Internet.\nIl disparaît parce qu'un local vide rapporte parfois davantage, en attente d'un repreneur solvable, qu'un loyer modeste versé par un artisan. La vacance n'est pas toujours un échec : elle est parfois un calcul.",
        "question_fr": "Quelle explication l'auteur ajoute-t-il ?",
        "options": [
            {"id": "a", "text": "Les artisans ne veulent plus de locaux en rez-de-chaussée",
             "explanation": "The craftsman is willing but pays a modest rent; the refusal comes from the owner's side."},
            {"id": "b", "text": "Internet est la seule cause du phénomène",
             "explanation": "« pas seulement à cause d'Internet » — the point is to add a cause."},
            {"id": "c", "text": "Laisser un local vide peut être rentable",
             "explanation": "« La vacance n'est pas toujours un échec : elle est parfois un calcul »."},
            {"id": "d", "text": "Les loyers commerciaux ont baissé",
             "explanation": "No fall in rents is described."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La vacance n'est pas toujours un échec : elle est parfois un calcul.",
        "key_line_en": "Vacancy is not always a failure: it is sometimes a calculation.",
        "vocabulary": [
            {"term": "un local", "gloss": "a commercial unit"},
            {"term": "un repreneur", "gloss": "a buyer, taker"},
            {"term": "solvable", "gloss": "creditworthy"},
            {"term": "la vacance", "gloss": "vacancy"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la musique / Essay on music",
        "topic": "Loisirs, culture & médias",
        "text": "Le silence n'interrompt pas la musique, il en fait partie ; c'est lui qui donne à la note précédente sa durée et à la suivante son poids.\nUn interprète se juge moins à ce qu'il joue qu'à ce qu'il consent à ne pas jouer.",
        "question_fr": "Quelle conception l'auteur défend-il ?",
        "options": [
            {"id": "a", "text": "Le silence est un élément constitutif de la musique",
             "explanation": "It gives the previous note its length and the next its weight, and the performer is judged on it."},
            {"id": "b", "text": "Les interprètes jouent trop de notes",
             "explanation": "No such general complaint is made; a criterion is proposed."},
            {"id": "c", "text": "La musique moderne abuse du silence",
             "explanation": "No period or style is singled out."},
            {"id": "d", "text": "Le silence rend la musique inaudible",
             "explanation": "The reverse: it is what makes the notes legible."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Un interprète se juge moins à ce qu'il joue qu'à ce qu'il consent à ne pas jouer.",
        "key_line_en": "A performer is judged less by what they play than by what they agree not to play.",
        "vocabulary": [
            {"term": "consentir à", "gloss": "to agree to"},
            {"term": "le poids", "gloss": "the weight"},
            {"term": "un interprète", "gloss": "a performer"},
            {"term": "constitutif", "gloss": "constitutive, essential"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "topic": "Société, citoyenneté & administration",
        "text": "On reproche aux gouvernants de ne pas tenir leurs promesses ; on devrait leur reprocher d'en faire de tenables.\nUne promesse que l'on peut tenir seul n'engage à rien : elle décrit ce qui allait arriver. Promettre sérieusement, c'est s'exposer à dépendre des autres.",
        "question_fr": "Quel renversement l'auteur opère-t-il ?",
        "options": [
            {"id": "a", "text": "Le problème n'est pas de ne pas tenir, c'est de ne promettre que le sûr",
             "explanation": "A promise one can keep alone « décrit ce qui allait arriver »; a serious promise means depending on others."},
            {"id": "b", "text": "Les promesses politiques sont toutes mensongères",
             "explanation": "No accusation of lying is made."},
            {"id": "c", "text": "Il faudrait renoncer à promettre",
             "explanation": "Serious promising is defended, not abandoned."},
            {"id": "d", "text": "Les électeurs demandent trop aux gouvernants",
             "explanation": "Voters' demands are not discussed."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Promettre sérieusement, c'est s'exposer à dépendre des autres.",
        "key_line_en": "To promise seriously is to expose oneself to depending on others.",
        "vocabulary": [
            {"term": "tenir une promesse", "gloss": "to keep a promise"},
            {"term": "tenable", "gloss": "keepable"},
            {"term": "s'exposer à", "gloss": "to lay oneself open to"},
            {"term": "un gouvernant", "gloss": "a person in government"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Critique littéraire / Literary review",
        "topic": "Loisirs, culture & médias",
        "text": "Le recueil rassemble trente ans de poèmes, et l'ordre chronologique lui rend un mauvais service : on y suit une maîtrise qui s'installe, et l'on regrette la maladresse des débuts.\nCe que l'auteur a gagné en sûreté, il l'a perdu en surprise ; c'est peut-être le prix ordinaire du métier.",
        "question_fr": "Que constate le critique ?",
        "options": [
            {"id": "a", "text": "Les derniers poèmes sont techniquement faibles",
             "explanation": "Late mastery is acknowledged: what is lost is surprise, not craft."},
            {"id": "b", "text": "La maîtrise acquise a coûté la surprise",
             "explanation": "« Ce que l'auteur a gagné en sûreté, il l'a perdu en surprise »."},
            {"id": "c", "text": "Le recueil est trop court",
             "explanation": "It gathers thirty years of work; length is not the issue."},
            {"id": "d", "text": "L'ordre chronologique met en valeur l'ensemble",
             "explanation": "« l'ordre chronologique lui rend un mauvais service » — it works against the book."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Ce que l'auteur a gagné en sûreté, il l'a perdu en surprise.",
        "key_line_en": "What the author gained in assurance, he lost in surprise.",
        "vocabulary": [
            {"term": "un recueil", "gloss": "a collection"},
            {"term": "la maladresse", "gloss": "clumsiness"},
            {"term": "la sûreté", "gloss": "assurance, sureness"},
            {"term": "rendre un mauvais service", "gloss": "to do a disservice"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "topic": "Sciences & technologies",
        "text": "Une mesure sans marge d'erreur n'est pas plus précise, elle est moins honnête.\nDonner un chiffre seul, c'est laisser croire qu'il n'a pas d'épaisseur ; l'accompagner d'un intervalle, c'est indiquer où le savoir s'arrête. La précision affichée est souvent inversement proportionnelle à la précision réelle.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Les intervalles de confiance compliquent inutilement",
             "explanation": "They are what makes a figure honest, not a needless complication."},
            {"id": "b", "text": "Il faudrait cesser de publier des chiffres",
             "explanation": "Figures are fine; they should carry their uncertainty."},
            {"id": "c", "text": "Afficher une marge d'erreur est un gage d'honnêteté",
             "explanation": "The interval « indique où le savoir s'arrête », and bare figures suggest a thickness they do not have."},
            {"id": "d", "text": "Les mesures scientifiques sont rarement exactes",
             "explanation": "Accuracy in general is not the subject; how uncertainty is reported is."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La précision affichée est souvent inversement proportionnelle à la précision réelle.",
        "key_line_en": "Displayed precision is often inversely proportional to real precision.",
        "vocabulary": [
            {"term": "une marge d'erreur", "gloss": "a margin of error"},
            {"term": "l'épaisseur", "gloss": "thickness, depth"},
            {"term": "un intervalle", "gloss": "an interval, range"},
            {"term": "inversement proportionnel", "gloss": "inversely proportional"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "topic": "Vie quotidienne & logement",
        "text": "On a supprimé les balcons pour gagner des mètres carrés habitables, et l'on a supprimé du même coup le seul endroit d'où l'on regardait la rue sans y descendre.\nUn immeuble sans balcons ne surveille rien : ses habitants n'ont plus de raison, ni de moyen, de savoir ce qui s'y passe.",
        "question_fr": "Que perd-on, selon l'auteur, en supprimant les balcons ?",
        "options": [
            {"id": "a", "text": "De la surface habitable",
             "explanation": "Removing them gains floor space — that is the reason given for doing it."},
            {"id": "b", "text": "Un regard des habitants sur la rue",
             "explanation": "The balcony was « le seul endroit d'où l'on regardait la rue sans y descendre »; without it the building watches nothing."},
            {"id": "c", "text": "La lumière naturelle des appartements",
             "explanation": "Light is never mentioned."},
            {"id": "d", "text": "La valeur des logements",
             "explanation": "No price effect is discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un immeuble sans balcons ne surveille rien.",
        "key_line_en": "A building without balconies watches over nothing.",
        "vocabulary": [
            {"term": "du même coup", "gloss": "at the same stroke"},
            {"term": "habitable", "gloss": "liveable, usable (floor area)"},
            {"term": "surveiller", "gloss": "to watch over"},
            {"term": "y descendre", "gloss": "to go down into it"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la gratitude / Essay on gratitude",
        "topic": "Société, citoyenneté & administration",
        "text": "Un service rendu crée une dette que la reconnaissance n'éteint pas ; elle l'entretient, et c'est heureux.\nUne société où chacun rembourserait exactement ce qu'il doit n'aurait plus rien à échanger : le lien tient à ce qui reste dû, non à ce qui a été rendu.",
        "question_fr": "Quel rôle l'auteur attribue-t-il à la dette morale ?",
        "options": [
            {"id": "a", "text": "Elle empêche les relations d'être égalitaires",
             "explanation": "Inequality is not the concern; the outstanding debt is presented as what binds people."},
            {"id": "b", "text": "Elle devrait être remboursée rapidement",
             "explanation": "Exact repayment is exactly what would leave nothing to exchange."},
            {"id": "c", "text": "Elle est le fondement du lien social",
             "explanation": "« le lien tient à ce qui reste dû, non à ce qui a été rendu »."},
            {"id": "d", "text": "Elle disparaît avec la reconnaissance",
             "explanation": "Gratitude « ne l'éteint pas ; elle l'entretient » — it keeps the debt alive."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le lien tient à ce qui reste dû, non à ce qui a été rendu.",
        "key_line_en": "The bond holds by what remains owed, not by what has been repaid.",
        "vocabulary": [
            {"term": "éteindre (une dette)", "gloss": "to discharge (a debt)"},
            {"term": "entretenir", "gloss": "to keep alive, maintain"},
            {"term": "la reconnaissance", "gloss": "gratitude"},
            {"term": "rester dû", "gloss": "to remain owed"},
        ],
    },
]

QUESTIONS = balance(_RAW)
