"""Compréhension écrite — Test 10.

Forty questions climbing A1 → C2. Profile A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Mot / Note",
        "topic": "Vie quotidienne & logement",
        "text": "Léo,\nLe plombier vient demain matin entre 8 h et 10 h.\nTu peux rester à la maison ?\nJe travaille, je ne peux pas.\nMaman",
        "question_fr": "Que demande la mère à Léo ?",
        "options": [
            {"id": "a", "text": "D'appeler le plombier",
             "explanation": "The appointment is already arranged."},
            {"id": "b", "text": "De rester chez lui demain matin",
             "explanation": "« Tu peux rester à la maison ? » because she is working."},
            {"id": "c", "text": "D'aller au travail avec elle",
             "explanation": "She is going to work; he is asked to stay in."},
            {"id": "d", "text": "De réparer quelque chose",
             "explanation": "The plumber does the repair."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Tu peux rester à la maison ? Je travaille, je ne peux pas.",
        "key_line_en": "Can you stay home? I'm working, I can't.",
        "vocabulary": [
            {"term": "un plombier", "gloss": "a plumber"},
            {"term": "rester", "gloss": "to stay"},
            {"term": "demain matin", "gloss": "tomorrow morning"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Panneau / Sign",
        "topic": "Transports & voyages",
        "text": "QUAI B\nTrains vers Marseille et Nice.\nAttention à la marche en descendant du train.\nNe pas dépasser la ligne jaune.",
        "question_fr": "Que ne faut-il pas faire sur le quai ?",
        "options": [
            {"id": "a", "text": "Descendre du train",
             "explanation": "Getting off is expected; the sign only warns about the step."},
            {"id": "b", "text": "Aller à Marseille",
             "explanation": "Marseille is a destination served from this platform."},
            {"id": "c", "text": "Dépasser la ligne jaune",
             "explanation": "« Ne pas dépasser la ligne jaune »."},
            {"id": "d", "text": "Attendre le train",
             "explanation": "Waiting is what the platform is for."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ne pas dépasser la ligne jaune.",
        "key_line_en": "Do not cross the yellow line.",
        "vocabulary": [
            {"term": "un quai", "gloss": "a platform"},
            {"term": "dépasser", "gloss": "to go beyond, cross"},
            {"term": "une marche", "gloss": "a step"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Affichette / Small notice",
        "topic": "Alimentation & consommation",
        "text": "PAIN FRAIS\nLivré deux fois par jour : 7 h et 16 h.\nLe pain de la veille est vendu à moitié prix.\nFermé le mercredi.",
        "question_fr": "Combien coûte le pain de la veille ?",
        "options": [
            {"id": "a", "text": "Le prix normal",
             "explanation": "Day-old bread is sold at half price."},
            {"id": "b", "text": "Deux fois plus cher",
             "explanation": "Twice refers to the daily deliveries, not a price."},
            {"id": "c", "text": "Il n'est pas vendu",
             "explanation": "It is sold, at a reduced price."},
            {"id": "d", "text": "La moitié du prix",
             "explanation": "« Le pain de la veille est vendu à moitié prix »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Le pain de la veille est vendu à moitié prix.",
        "key_line_en": "Yesterday's bread is sold at half price.",
        "vocabulary": [
            {"term": "frais", "gloss": "fresh"},
            {"term": "la veille", "gloss": "the day before"},
            {"term": "à moitié prix", "gloss": "at half price"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "SMS",
        "topic": "Santé & bien-être",
        "text": "Bonjour,\nVos lunettes sont prêtes.\nVous pouvez venir les chercher du lundi au samedi, avant 18 h.\nOptique Central",
        "question_fr": "Que doit faire le client ?",
        "options": [
            {"id": "a", "text": "Venir chercher ses lunettes",
             "explanation": "« Vous pouvez venir les chercher du lundi au samedi »."},
            {"id": "b", "text": "Commander des lunettes",
             "explanation": "They are already made and waiting."},
            {"id": "c", "text": "Prendre rendez-vous",
             "explanation": "No appointment is needed within the opening times."},
            {"id": "d", "text": "Attendre lundi",
             "explanation": "Monday to Saturday is the whole window, not a wait."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Vos lunettes sont prêtes. Vous pouvez venir les chercher.",
        "key_line_en": "Your glasses are ready. You can come and collect them.",
        "vocabulary": [
            {"term": "des lunettes", "gloss": "glasses"},
            {"term": "prêt", "gloss": "ready"},
            {"term": "chercher", "gloss": "to collect"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Affiche / Poster",
        "topic": "Loisirs, culture & médias",
        "text": "CINÉMA — SÉANCES DU JOUR\n14 h : film pour enfants\n18 h : comédie\n21 h : film en version originale\nTarif unique : 7 €.",
        "question_fr": "Combien coûte une place ?",
        "options": [
            {"id": "a", "text": "14 €",
             "explanation": "14 h is a showing time."},
            {"id": "b", "text": "7 €",
             "explanation": "« Tarif unique : 7 € » — the same price for every showing."},
            {"id": "c", "text": "21 €",
             "explanation": "21 h is the evening showing time."},
            {"id": "d", "text": "Cela dépend du film",
             "explanation": "« Tarif unique » means one price for all."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Tarif unique : 7 €.",
        "key_line_en": "Single price: €7.",
        "vocabulary": [
            {"term": "une séance", "gloss": "a showing"},
            {"term": "un tarif unique", "gloss": "a single price"},
            {"term": "en version originale", "gloss": "in the original language"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Panneau / Notice",
        "topic": "Société, citoyenneté & administration",
        "text": "BUREAU DE VOTE\nOuvert de 8 h à 19 h.\nApportez votre carte d'identité.\nLa carte d'électeur n'est pas obligatoire.",
        "question_fr": "Que faut-il apporter pour voter ?",
        "options": [
            {"id": "a", "text": "La carte d'électeur",
             "explanation": "« La carte d'électeur n'est pas obligatoire »."},
            {"id": "b", "text": "Rien",
             "explanation": "One document is required."},
            {"id": "c", "text": "Une carte d'identité",
             "explanation": "« Apportez votre carte d'identité »."},
            {"id": "d", "text": "Une photo",
             "explanation": "No photograph is asked for."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Apportez votre carte d'identité.",
        "key_line_en": "Bring your identity card.",
        "vocabulary": [
            {"term": "un bureau de vote", "gloss": "a polling station"},
            {"term": "une carte d'électeur", "gloss": "a voter registration card"},
            {"term": "obligatoire", "gloss": "compulsory"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Offre d'emploi / Job advert",
        "topic": "Travail & emploi",
        "text": "ANIMATEUR (H/F) — CENTRE DE LOISIRS\nJuillet et août, du lundi au vendredi.\nLe BAFA est exigé ; une expérience avec des enfants de 6 à 11 ans est un plus.\nRepas fournis, transport non remboursé.",
        "question_fr": "Qu'est-ce qui est obligatoire pour ce poste ?",
        "options": [
            {"id": "a", "text": "Le diplôme BAFA",
             "explanation": "« Le BAFA est exigé » — it is the one requirement."},
            {"id": "b", "text": "Une expérience avec les 6-11 ans",
             "explanation": "« un plus » makes it desirable, not required."},
            {"id": "c", "text": "Avoir un véhicule",
             "explanation": "Travel is unreimbursed, but no vehicle is demanded."},
            {"id": "d", "text": "Travailler le week-end",
             "explanation": "The job runs Monday to Friday."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le BAFA est exigé ; une expérience avec des enfants de 6 à 11 ans est un plus.",
        "key_line_en": "The BAFA qualification is required; experience with 6–11 year-olds is a bonus.",
        "vocabulary": [
            {"term": "un animateur", "gloss": "a youth activity leader"},
            {"term": "exigé", "gloss": "required"},
            {"term": "un plus", "gloss": "an asset"},
            {"term": "fourni", "gloss": "provided"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information scolaire / School information",
        "topic": "Études & formation",
        "text": "INSCRIPTION EN LIGNE\nLes inscriptions sont ouvertes du 2 au 30 mai.\nUn seul vœu peut être modifié après validation, et une seule fois.\nAucune inscription n'est acceptée après la date limite, quel qu'en soit le motif.",
        "question_fr": "Que peut-on faire après avoir validé son inscription ?",
        "options": [
            {"id": "a", "text": "Tout changer librement",
             "explanation": "Only one choice may be changed, and only once."},
            {"id": "b", "text": "Modifier un vœu, une seule fois",
             "explanation": "« Un seul vœu peut être modifié après validation, et une seule fois »."},
            {"id": "c", "text": "S'inscrire en juin",
             "explanation": "« Aucune inscription n'est acceptée après la date limite »."},
            {"id": "d", "text": "Rien du tout",
             "explanation": "One modification remains possible."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un seul vœu peut être modifié après validation, et une seule fois.",
        "key_line_en": "Only one choice may be changed after validation, and only once.",
        "vocabulary": [
            {"term": "un vœu", "gloss": "a choice, preference"},
            {"term": "la validation", "gloss": "confirmation"},
            {"term": "une date limite", "gloss": "a deadline"},
            {"term": "un motif", "gloss": "a reason"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Courrier / Letter",
        "topic": "Vie quotidienne & logement",
        "text": "Madame, Monsieur,\nLe loyer sera révisé au 1er janvier, selon l'indice publié en octobre.\nLa hausse sera de 2,1 %, soit 15 € par mois.\nAucune démarche n'est nécessaire de votre part.",
        "question_fr": "Que doit faire le locataire ?",
        "options": [
            {"id": "a", "text": "Payer 15 € en une fois",
             "explanation": "The €15 is a monthly increase, not a lump sum."},
            {"id": "b", "text": "Contester la hausse",
             "explanation": "No dispute procedure is mentioned."},
            {"id": "c", "text": "Signer un nouveau bail",
             "explanation": "No new contract is required."},
            {"id": "d", "text": "Rien",
             "explanation": "« Aucune démarche n'est nécessaire de votre part »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Aucune démarche n'est nécessaire de votre part.",
        "key_line_en": "No action is required on your part.",
        "vocabulary": [
            {"term": "réviser", "gloss": "to adjust, review"},
            {"term": "un indice", "gloss": "an index"},
            {"term": "une hausse", "gloss": "an increase"},
            {"term": "une démarche", "gloss": "a step, formality"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Consigne / Instructions",
        "topic": "Sciences & technologies",
        "text": "RÉINITIALISER SON MOT DE PASSE\nCliquez sur « mot de passe oublié » et saisissez votre adresse.\nUn lien valable trente minutes vous est envoyé.\nPassé ce délai, la demande doit être refaite.",
        "question_fr": "Que se passe-t-il après trente minutes ?",
        "options": [
            {"id": "a", "text": "Il faut recommencer la demande",
             "explanation": "« Passé ce délai, la demande doit être refaite »."},
            {"id": "b", "text": "Le compte est bloqué",
             "explanation": "No blocking is mentioned."},
            {"id": "c", "text": "Un second lien est envoyé",
             "explanation": "Nothing is sent automatically; the user must start again."},
            {"id": "d", "text": "Le mot de passe est supprimé",
             "explanation": "The old password is unaffected; only the link expires."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Un lien valable trente minutes vous est envoyé. Passé ce délai, la demande doit être refaite.",
        "key_line_en": "A link valid for thirty minutes is sent to you. After that, the request must be made again.",
        "vocabulary": [
            {"term": "réinitialiser", "gloss": "to reset"},
            {"term": "saisir", "gloss": "to enter, type in"},
            {"term": "valable", "gloss": "valid"},
            {"term": "refaire", "gloss": "to do again"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information municipale / Council notice",
        "topic": "Environnement & nature",
        "text": "COMPOSTEUR DE QUARTIER\nOuvert à tous les habitants, sans inscription.\nOn y dépose épluchures, marc de café et coquilles d'œufs.\nNi viande, ni poisson, ni produits laitiers : ils attirent les animaux.",
        "question_fr": "Que ne peut-on pas mettre dans le composteur ?",
        "options": [
            {"id": "a", "text": "Des épluchures",
             "explanation": "Peelings are explicitly accepted."},
            {"id": "b", "text": "Du marc de café",
             "explanation": "Coffee grounds are on the accepted list."},
            {"id": "c", "text": "Des coquilles d'œufs",
             "explanation": "Eggshells are accepted."},
            {"id": "d", "text": "Des produits laitiers",
             "explanation": "« Ni viande, ni poisson, ni produits laitiers »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Ni viande, ni poisson, ni produits laitiers : ils attirent les animaux.",
        "key_line_en": "No meat, fish or dairy: they attract animals.",
        "vocabulary": [
            {"term": "une épluchure", "gloss": "a peeling"},
            {"term": "le marc de café", "gloss": "coffee grounds"},
            {"term": "une coquille", "gloss": "a shell"},
            {"term": "un produit laitier", "gloss": "a dairy product"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Conditions / Terms",
        "topic": "Alimentation & consommation",
        "text": "CARTE CANTINE\nLe rechargement se fait en ligne ou à l'accueil.\nUn solde négatif bloque l'accès au self dès le lendemain.\nUn message d'alerte est envoyé quand le solde passe sous 10 €.",
        "question_fr": "Quand reçoit-on un message d'alerte ?",
        "options": [
            {"id": "a", "text": "Quand le solde est négatif",
             "explanation": "A negative balance blocks access; the alert comes earlier."},
            {"id": "b", "text": "Quand il reste moins de 10 €",
             "explanation": "« Un message d'alerte est envoyé quand le solde passe sous 10 € »."},
            {"id": "c", "text": "Le lendemain du blocage",
             "explanation": "The next day is when blocking takes effect, not when the alert is sent."},
            {"id": "d", "text": "À chaque rechargement",
             "explanation": "Top-ups do not trigger the alert."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un message d'alerte est envoyé quand le solde passe sous 10 €.",
        "key_line_en": "An alert is sent when the balance drops below €10.",
        "vocabulary": [
            {"term": "un rechargement", "gloss": "a top-up"},
            {"term": "un solde", "gloss": "a balance"},
            {"term": "le self", "gloss": "the self-service canteen"},
            {"term": "bloquer", "gloss": "to block"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information voyageurs / Passenger information",
        "topic": "Transports & voyages",
        "text": "GRÈVE — TRAFIC PERTURBÉ\nUn train sur trois circule jeudi.\nLes billets sont échangeables sans frais jusqu'au 30 du mois.\nLes réservations pour vendredi ne sont pas concernées.",
        "question_fr": "Quels billets peuvent être échangés sans frais ?",
        "options": [
            {"id": "a", "text": "Ceux de vendredi",
             "explanation": "« Les réservations pour vendredi ne sont pas concernées »."},
            {"id": "b", "text": "Ceux du 30 du mois",
             "explanation": "The 30th is the deadline for exchanging, not the travel date."},
            {"id": "c", "text": "Ceux concernés par la grève de jeudi",
             "explanation": "The strike disrupts Thursday, and those tickets can be exchanged free until the 30th."},
            {"id": "d", "text": "Tous les billets du mois",
             "explanation": "Friday is expressly excluded."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les billets sont échangeables sans frais jusqu'au 30 du mois.",
        "key_line_en": "Tickets can be exchanged free of charge until the 30th of the month.",
        "vocabulary": [
            {"term": "une grève", "gloss": "a strike"},
            {"term": "perturbé", "gloss": "disrupted"},
            {"term": "échangeable", "gloss": "exchangeable"},
            {"term": "concerné", "gloss": "affected"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Chronique santé / Health column",
        "topic": "Santé & bien-être",
        "text": "Les compléments alimentaires se vendent de mieux en mieux, sans que les carences aient augmenté.\nChez une personne qui mange varié, une vitamine prise en excès est éliminée par les reins : on produit surtout une urine coûteuse. Les carences réelles, elles, se diagnostiquent.",
        "question_fr": "Que dit l'auteur des compléments pris sans carence ?",
        "options": [
            {"id": "a", "text": "Ils sont dangereux pour les reins",
             "explanation": "The kidneys eliminate the excess; no damage is claimed."},
            {"id": "b", "text": "Ils sont sans effet et coûteux",
             "explanation": "« on produit surtout une urine coûteuse » — the surplus is simply excreted."},
            {"id": "c", "text": "Ils remplacent une alimentation variée",
             "explanation": "The varied diet is the premise, not what they replace."},
            {"id": "d", "text": "Ils préviennent les carences",
             "explanation": "Real deficiencies « se diagnostiquent » — they are a medical matter, not a retail one."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une vitamine prise en excès est éliminée par les reins : on produit surtout une urine coûteuse.",
        "key_line_en": "A vitamin taken in excess is eliminated by the kidneys: what you mainly produce is expensive urine.",
        "vocabulary": [
            {"term": "une carence", "gloss": "a deficiency"},
            {"term": "un rein", "gloss": "a kidney"},
            {"term": "éliminer", "gloss": "to excrete, remove"},
            {"term": "diagnostiquer", "gloss": "to diagnose"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "topic": "Travail & emploi",
        "text": "Un tiers des démissions interviennent dans les six premiers mois.\nLes personnes interrogées ne mettent pas en cause le travail lui-même, mais l'écart entre ce qui leur avait été décrit en entretien et ce qu'elles ont trouvé.",
        "question_fr": "Quelle cause de démission l'enquête met-elle en avant ?",
        "options": [
            {"id": "a", "text": "La difficulté des tâches confiées",
             "explanation": "« ne mettent pas en cause le travail lui-même »."},
            {"id": "b", "text": "Le salaire proposé",
             "explanation": "Pay is not mentioned."},
            {"id": "c", "text": "La différence entre la promesse et la réalité",
             "explanation": "« l'écart entre ce qui leur avait été décrit en entretien et ce qu'elles ont trouvé »."},
            {"id": "d", "text": "La durée de la période d'essai",
             "explanation": "The probation period is not discussed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "L'écart entre ce qui leur avait été décrit en entretien et ce qu'elles ont trouvé.",
        "key_line_en": "The gap between what they were told at interview and what they found.",
        "vocabulary": [
            {"term": "une démission", "gloss": "a resignation"},
            {"term": "mettre en cause", "gloss": "to blame"},
            {"term": "un écart", "gloss": "a gap"},
            {"term": "un entretien", "gloss": "an interview"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Présentation de dispositif / Scheme description",
        "topic": "Études & formation",
        "text": "L'école propose des devoirs faits sur place, après les cours.\nLe principe est simple : l'élève repart sans travail à la maison. Les enseignants observent surtout un effet inattendu — les familles qui ne pouvaient pas aider ne sont plus mises en difficulté chaque soir.",
        "question_fr": "Quel effet les enseignants soulignent-ils ?",
        "options": [
            {"id": "a", "text": "Les élèves travaillent plus longtemps",
             "explanation": "The homework moves to school; the total is not said to grow."},
            {"id": "b", "text": "Les notes ont augmenté",
             "explanation": "Marks are not mentioned."},
            {"id": "c", "text": "Les familles ne sont plus en difficulté le soir",
             "explanation": "« les familles qui ne pouvaient pas aider ne sont plus mises en difficulté chaque soir »."},
            {"id": "d", "text": "Les enseignants travaillent moins",
             "explanation": "Supervising the sessions is extra work, not less."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les familles qui ne pouvaient pas aider ne sont plus mises en difficulté chaque soir.",
        "key_line_en": "Families who could not help are no longer put in difficulty every evening.",
        "vocabulary": [
            {"term": "sur place", "gloss": "on site"},
            {"term": "repartir", "gloss": "to leave, go home"},
            {"term": "inattendu", "gloss": "unexpected"},
            {"term": "mettre en difficulté", "gloss": "to put in a difficult position"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article culturel / Culture article",
        "topic": "Loisirs, culture & médias",
        "text": "La bibliothèque prête désormais des objets : perceuses, machines à coudre, appareils à raclette.\n« Un objet utilisé trois fois par an n'a pas besoin d'être acheté, explique la responsable. Nous prêtons des livres depuis un siècle ; le principe est le même. »",
        "question_fr": "Comment la responsable justifie-t-elle ce service ?",
        "options": [
            {"id": "a", "text": "Par la rareté des objets prêtés",
             "explanation": "The point is rare use, not rare objects."},
            {"id": "b", "text": "Par la logique du prêt déjà appliquée aux livres",
             "explanation": "« Nous prêtons des livres depuis un siècle ; le principe est le même »."},
            {"id": "c", "text": "Par le manque de place des habitants",
             "explanation": "Storage space is not mentioned."},
            {"id": "d", "text": "Par la baisse du nombre de lecteurs",
             "explanation": "Readership is never discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un objet utilisé trois fois par an n'a pas besoin d'être acheté.",
        "key_line_en": "An object used three times a year does not need to be bought.",
        "vocabulary": [
            {"term": "une perceuse", "gloss": "a drill"},
            {"term": "une machine à coudre", "gloss": "a sewing machine"},
            {"term": "prêter", "gloss": "to lend"},
            {"term": "un principe", "gloss": "a principle"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Reportage / Report",
        "topic": "Environnement & nature",
        "text": "Le village a remplacé l'éclairage public par des lampes qui s'éteignent entre minuit et cinq heures.\nLes habitants craignaient les cambriolages : les chiffres n'ont pas bougé. En revanche, les insectes nocturnes sont revenus, et la facture d'électricité a baissé de moitié.",
        "question_fr": "Quel effet redouté ne s'est pas produit ?",
        "options": [
            {"id": "a", "text": "Le retour des insectes",
             "explanation": "That happened, and it is presented as welcome."},
            {"id": "b", "text": "La hausse des cambriolages",
             "explanation": "« Les habitants craignaient les cambriolages : les chiffres n'ont pas bougé »."},
            {"id": "c", "text": "La hausse de la facture",
             "explanation": "The bill halved."},
            {"id": "d", "text": "La panne de l'éclairage",
             "explanation": "The lights are switched off deliberately, not broken."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les habitants craignaient les cambriolages : les chiffres n'ont pas bougé.",
        "key_line_en": "Residents feared burglaries: the figures did not move.",
        "vocabulary": [
            {"term": "un cambriolage", "gloss": "a burglary"},
            {"term": "s'éteindre", "gloss": "to switch off"},
            {"term": "nocturne", "gloss": "nocturnal"},
            {"term": "une facture", "gloss": "a bill"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Information administrative / Administrative notice",
        "topic": "Société, citoyenneté & administration",
        "text": "Une association peut être créée par deux personnes au minimum.\nLa déclaration en préfecture est gratuite ; seule la publication au Journal officiel est payante, et elle est indispensable pour ouvrir un compte bancaire.\nLes statuts peuvent être modifiés à tout moment.",
        "question_fr": "Quelle démarche est payante ?",
        "options": [
            {"id": "a", "text": "La déclaration en préfecture",
             "explanation": "« La déclaration en préfecture est gratuite »."},
            {"id": "b", "text": "La modification des statuts",
             "explanation": "No charge is attached to changing the statutes."},
            {"id": "c", "text": "La publication au Journal officiel",
             "explanation": "« seule la publication au Journal officiel est payante »."},
            {"id": "d", "text": "L'ouverture du compte bancaire",
             "explanation": "The bank account requires the publication; its own cost is not mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Seule la publication au Journal officiel est payante.",
        "key_line_en": "Only publication in the Journal officiel has to be paid for.",
        "vocabulary": [
            {"term": "une préfecture", "gloss": "a prefecture (local state office)"},
            {"term": "des statuts", "gloss": "articles of association"},
            {"term": "payant", "gloss": "chargeable"},
            {"term": "indispensable", "gloss": "essential"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article consommation / Consumer article",
        "topic": "Alimentation & consommation",
        "text": "Les rayons placent les produits les plus rentables à hauteur des yeux, et ceux des enfants à hauteur des leurs.\nCe n'est pas un secret, et pourtant la connaissance de cette règle ne change presque rien aux achats : savoir qu'on est influencé ne suffit pas à ne pas l'être.",
        "question_fr": "Quelle est la conclusion de l'auteur ?",
        "options": [
            {"id": "a", "text": "L'information du consommateur ne suffit pas",
             "explanation": "« savoir qu'on est influencé ne suffit pas à ne pas l'être »."},
            {"id": "b", "text": "Les magasins cachent leurs méthodes",
             "explanation": "« Ce n'est pas un secret »."},
            {"id": "c", "text": "Les enfants choisissent les produits",
             "explanation": "Products are placed at their eye level, which is a technique, not a conclusion."},
            {"id": "d", "text": "Les consommateurs achètent moins qu'avant",
             "explanation": "Purchase volumes are not discussed."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Savoir qu'on est influencé ne suffit pas à ne pas l'être.",
        "key_line_en": "Knowing you are being influenced is not enough to stop you being influenced.",
        "vocabulary": [
            {"term": "un rayon", "gloss": "an aisle, shelf"},
            {"term": "rentable", "gloss": "profitable"},
            {"term": "à hauteur des yeux", "gloss": "at eye level"},
            {"term": "influencer", "gloss": "to influence"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "topic": "Société, citoyenneté & administration",
        "text": "On confond la liberté d'expression et l'obligation d'être diffusé.\nLa première interdit qu'on empêche quelqu'un de parler ; elle n'oblige personne à lui fournir une tribune, ni un public. Refuser de publier n'est pas censurer : c'est éditer, ce qui est l'exact contraire de se taire.",
        "question_fr": "Quelle distinction l'auteur établit-il ?",
        "options": [
            {"id": "a", "text": "Entre parler librement et être publié",
             "explanation": "Freedom forbids silencing but « n'oblige personne à lui fournir une tribune »; refusing to publish is editing."},
            {"id": "b", "text": "Entre censure publique et censure privée",
             "explanation": "The text denies that refusing to publish is censorship at all."},
            {"id": "c", "text": "Entre opinions vraies et fausses",
             "explanation": "The content of the opinions is never assessed."},
            {"id": "d", "text": "Entre journalistes et citoyens",
             "explanation": "No such professional distinction is drawn."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Refuser de publier n'est pas censurer : c'est éditer.",
        "key_line_en": "Refusing to publish is not censorship: it is editing.",
        "vocabulary": [
            {"term": "une tribune", "gloss": "a platform"},
            {"term": "diffuser", "gloss": "to broadcast, distribute"},
            {"term": "censurer", "gloss": "to censor"},
            {"term": "éditer", "gloss": "to edit, publish selectively"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "topic": "Loisirs, culture & médias",
        "text": "Les salles de sport vendent des abonnements annuels à des gens qui viennent trois semaines.\nLe modèle ne repose pas sur la fréquentation mais sur son absence : une salle où tous les abonnés viendraient serait immédiatement saturée. On vend une intention, et l'on facture l'abandon.",
        "question_fr": "Sur quoi repose le modèle décrit ?",
        "options": [
            {"id": "a", "text": "Sur la fidélité des adhérents",
             "explanation": "The business depends on members not turning up."},
            {"id": "b", "text": "Sur le fait que la plupart ne viennent pas",
             "explanation": "« On vend une intention, et l'on facture l'abandon » — full attendance would saturate the gym."},
            {"id": "c", "text": "Sur le prix élevé des abonnements",
             "explanation": "Price level is not the mechanism described."},
            {"id": "d", "text": "Sur la qualité des équipements",
             "explanation": "Facilities are never mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On vend une intention, et l'on facture l'abandon.",
        "key_line_en": "They sell an intention and bill you for giving up.",
        "vocabulary": [
            {"term": "un abonnement", "gloss": "a membership"},
            {"term": "la fréquentation", "gloss": "attendance"},
            {"term": "saturé", "gloss": "overcrowded"},
            {"term": "l'abandon", "gloss": "giving up"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "topic": "Sciences & technologies",
        "text": "Le cerveau ne distingue pas bien une action réalisée d'une action longuement imaginée : les mêmes zones s'activent.\nCe n'est pas une bonne nouvelle pour la motivation. Planifier procure une partie de la satisfaction attendue de l'exécution, et cette avance sur récompense diminue l'envie de faire.",
        "question_fr": "Pourquoi planifier peut-il nuire à l'action ?",
        "options": [
            {"id": "a", "text": "Parce que le plan est souvent irréaliste",
             "explanation": "The realism of plans is not discussed."},
            {"id": "b", "text": "Parce que cela prend trop de temps",
             "explanation": "Time spent planning is not the mechanism given."},
            {"id": "c", "text": "Parce qu'on obtient une partie de la satisfaction à l'avance",
             "explanation": "« cette avance sur récompense diminue l'envie de faire »."},
            {"id": "d", "text": "Parce que le cerveau oublie les plans",
             "explanation": "Memory is not the issue; the shared brain activation is."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Cette avance sur récompense diminue l'envie de faire.",
        "key_line_en": "This advance on the reward reduces the desire to act.",
        "vocabulary": [
            {"term": "s'activer", "gloss": "to be activated"},
            {"term": "une récompense", "gloss": "a reward"},
            {"term": "l'exécution", "gloss": "carrying out"},
            {"term": "diminuer", "gloss": "to reduce"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "topic": "Travail & emploi",
        "text": "Bonjour,\nJe reviens sur votre demande de recruter un profil senior.\nCe n'est pas le niveau qui nous manque, c'est le temps de l'accompagner : les deux derniers arrivés ont attendu six semaines un accès aux outils. Recrutons quand nous serons prêts à accueillir.",
        "question_fr": "Pourquoi l'auteur diffère-t-il le recrutement ?",
        "options": [
            {"id": "a", "text": "Parce que le budget est insuffisant",
             "explanation": "Money is not mentioned."},
            {"id": "b", "text": "Parce que l'équipe ne peut pas intégrer un nouvel arrivant",
             "explanation": "Six weeks to get tool access: « Recrutons quand nous serons prêts à accueillir »."},
            {"id": "c", "text": "Parce que le profil demandé est trop expérimenté",
             "explanation": "« Ce n'est pas le niveau qui nous manque » — seniority is not the objection."},
            {"id": "d", "text": "Parce que les candidats manquent",
             "explanation": "Candidate supply is not discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Ce n'est pas le niveau qui nous manque, c'est le temps de l'accompagner.",
        "key_line_en": "It is not the seniority we lack, it is the time to support them.",
        "vocabulary": [
            {"term": "un profil", "gloss": "a candidate profile"},
            {"term": "accompagner", "gloss": "to support, onboard"},
            {"term": "un accès", "gloss": "access"},
            {"term": "accueillir", "gloss": "to take in, welcome"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article société / Society article",
        "topic": "Vie quotidienne & logement",
        "text": "Les résidences fermées se multiplient, vendues comme des îlots de tranquillité.\nElles produisent pourtant l'inquiétude qu'elles prétendent traiter : à mesure que l'on se protège de la rue, la rue devient ce dont il faut se protéger. La clôture ne répond pas à la peur, elle la confirme.",
        "question_fr": "Quel mécanisme l'auteur décrit-il ?",
        "options": [
            {"id": "a", "text": "La protection entretient la peur qu'elle vise",
             "explanation": "« La clôture ne répond pas à la peur, elle la confirme »."},
            {"id": "b", "text": "Les résidences fermées réduisent la délinquance",
             "explanation": "No crime figures are given; the argument is about perception."},
            {"id": "c", "text": "Les habitants quittent ces résidences",
             "explanation": "Departures are not mentioned; the residences are multiplying."},
            {"id": "d", "text": "La rue est réellement plus dangereuse",
             "explanation": "The street becomes what must be feared, which is a shift in perception, not a measured danger."},
        ],
        "correct_answer": "a",
        "key_line_fr": "La clôture ne répond pas à la peur, elle la confirme.",
        "key_line_en": "The fence does not answer the fear, it confirms it.",
        "vocabulary": [
            {"term": "un îlot", "gloss": "an island, pocket"},
            {"term": "une clôture", "gloss": "a fence, enclosure"},
            {"term": "prétendre", "gloss": "to claim"},
            {"term": "à mesure que", "gloss": "as, in proportion as"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "topic": "Environnement & nature",
        "text": "Les campagnes invitent à éteindre ses appareils en veille, ce qui économise environ dix pour cent d'une facture.\nLe geste est bon ; le message l'est moins, car il laisse croire que l'effort domestique est du même ordre que celui de l'industrie. Comparer les deux, c'est déjà se tromper d'échelle.",
        "question_fr": "Que reproche l'auteur à ces campagnes ?",
        "options": [
            {"id": "a", "text": "Le geste proposé est inutile",
             "explanation": "« Le geste est bon » — it saves around ten per cent."},
            {"id": "b", "text": "Elles suggèrent une équivalence trompeuse",
             "explanation": "The message implies household effort is « du même ordre » as industry's: « se tromper d'échelle »."},
            {"id": "c", "text": "Elles s'adressent aux entreprises",
             "explanation": "They address households; industry is the missing term."},
            {"id": "d", "text": "Elles exagèrent l'économie réalisée",
             "explanation": "The ten per cent figure is not contested."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Comparer les deux, c'est déjà se tromper d'échelle.",
        "key_line_en": "Comparing the two is already to mistake the scale.",
        "vocabulary": [
            {"term": "en veille", "gloss": "on standby"},
            {"term": "du même ordre", "gloss": "of the same order"},
            {"term": "une échelle", "gloss": "a scale"},
            {"term": "se tromper de", "gloss": "to get the wrong…"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Analyse économique / Economic analysis",
        "topic": "Transports & voyages",
        "text": "Élargir une autoroute réduit les embouteillages pendant environ trois ans.\nPassé ce délai, le trafic revient à son niveau antérieur : une route plus fluide rend la voiture plus attractive, et de nouveaux conducteurs apparaissent. On appelle cela le trafic induit, et il est documenté depuis quarante ans.",
        "question_fr": "Pourquoi les embouteillages réapparaissent-ils ?",
        "options": [
            {"id": "a", "text": "Parce que la population augmente",
             "explanation": "Population growth is not the mechanism cited; induced demand is."},
            {"id": "b", "text": "Parce que les travaux sont mal faits",
             "explanation": "The works achieve their effect — for three years."},
            {"id": "c", "text": "Parce que la route attire de nouveaux conducteurs",
             "explanation": "« une route plus fluide rend la voiture plus attractive » — the induced-traffic effect."},
            {"id": "d", "text": "Parce que les transports publics disparaissent",
             "explanation": "Public transport is not mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une route plus fluide rend la voiture plus attractive, et de nouveaux conducteurs apparaissent.",
        "key_line_en": "A freer-flowing road makes the car more attractive, and new drivers appear.",
        "vocabulary": [
            {"term": "un embouteillage", "gloss": "a traffic jam"},
            {"term": "fluide", "gloss": "free-flowing"},
            {"term": "induit", "gloss": "induced"},
            {"term": "antérieur", "gloss": "previous"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "topic": "Sciences & technologies",
        "text": "Une prédiction publiée agit sur ce qu'elle annonce, et cesse par là d'être une simple description.\nAnnoncer une pénurie la déclenche ; annoncer un effondrement le retarde, parce qu'on s'y prépare. Prévoir en public, c'est intervenir en se donnant l'air d'observer.",
        "question_fr": "Quelle est la thèse de l'auteur ?",
        "options": [
            {"id": "a", "text": "Les prédictions publiques modifient ce qu'elles annoncent",
             "explanation": "« Prévoir en public, c'est intervenir en se donnant l'air d'observer », illustrated in both directions."},
            {"id": "b", "text": "Les prédictions sont généralement fausses",
             "explanation": "Their accuracy is not the subject; their effect is."},
            {"id": "c", "text": "Il ne faut jamais publier de prévisions",
             "explanation": "No prohibition is proposed."},
            {"id": "d", "text": "Les pénuries sont inévitables",
             "explanation": "The shortage is an example of the mechanism, not a fatality."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Prévoir en public, c'est intervenir en se donnant l'air d'observer.",
        "key_line_en": "To forecast publicly is to intervene while appearing to observe.",
        "vocabulary": [
            {"term": "une pénurie", "gloss": "a shortage"},
            {"term": "déclencher", "gloss": "to trigger"},
            {"term": "un effondrement", "gloss": "a collapse"},
            {"term": "se donner l'air de", "gloss": "to give the appearance of"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "topic": "Société, citoyenneté & administration",
        "text": "On a créé un comité chargé d'évaluer l'efficacité des comités.\nIl s'est réuni quatre fois, a produit un rapport de soixante pages et recommande la création d'un observatoire. Nul ne saurait mieux démontrer l'utilité de la méthode qu'en l'appliquant à elle-même.",
        "question_fr": "Que suggère la dernière phrase ?",
        "options": [
            {"id": "a", "text": "Que la méthode a fait ses preuves",
             "explanation": "Read literally — but the committee's only output is another body, which undercuts it."},
            {"id": "b", "text": "Que la méthode se disqualifie elle-même",
             "explanation": "A committee on committees producing a new observatory demonstrates precisely the problem it was to assess."},
            {"id": "c", "text": "Que le rapport est trop court",
             "explanation": "Sixty pages is offered as excess, not shortage."},
            {"id": "d", "text": "Qu'il faut créer un observatoire",
             "explanation": "That is the recommendation the irony targets."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nul ne saurait mieux démontrer l'utilité de la méthode qu'en l'appliquant à elle-même.",
        "key_line_en": "No one could better demonstrate the method's usefulness than by applying it to itself.",
        "vocabulary": [
            {"term": "un comité", "gloss": "a committee"},
            {"term": "un observatoire", "gloss": "a monitoring body"},
            {"term": "nul ne saurait", "gloss": "nobody could"},
            {"term": "démontrer", "gloss": "to demonstrate"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "topic": "Travail & emploi",
        "text": "On oppose le travail et le loisir comme s'ils se partageaient la journée.\nCe découpage suppose une frontière que les métiers de service ont depuis longtemps perdue : répondre à un message le dimanche n'est ni du travail au sens du contrat, ni du repos au sens du corps.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Le travail occupe désormais toute la journée",
             "explanation": "The claim is not about quantity but about a boundary that no longer holds."},
            {"id": "b", "text": "La frontière entre travail et repos s'est brouillée",
             "explanation": "Answering a message on Sunday is « ni du travail au sens du contrat, ni du repos au sens du corps »."},
            {"id": "c", "text": "Les loisirs ont disparu",
             "explanation": "Leisure is not said to vanish, only to lose its clean boundary."},
            {"id": "d", "text": "Les contrats doivent être réécrits",
             "explanation": "No remedy is proposed in the extract."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Répondre à un message le dimanche n'est ni du travail au sens du contrat, ni du repos au sens du corps.",
        "key_line_en": "Answering a message on Sunday is neither work in the contractual sense nor rest in the bodily sense.",
        "vocabulary": [
            {"term": "un découpage", "gloss": "a division"},
            {"term": "une frontière", "gloss": "a boundary"},
            {"term": "au sens de", "gloss": "in the sense of"},
            {"term": "le repos", "gloss": "rest"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "topic": "Loisirs, culture & médias",
        "text": "Elle avait toujours dit qu'elle partirait, et elle était restée.\nCe n'était pas un renoncement : à force de l'annoncer, le départ était devenu une manière d'habiter là, une porte qu'il suffisait de savoir ouverte pour n'avoir plus besoin de la franchir.",
        "question_fr": "Quel rôle jouait le projet de départ ?",
        "options": [
            {"id": "a", "text": "Il l'empêchait de s'installer",
             "explanation": "The opposite: it « était devenu une manière d'habiter là »."},
            {"id": "b", "text": "Il rendait sa présence supportable",
             "explanation": "A door one needs only to know is open, without going through it."},
            {"id": "c", "text": "Il montrait qu'elle avait échoué",
             "explanation": "« Ce n'était pas un renoncement » — failure is expressly denied."},
            {"id": "d", "text": "Il préparait un déménagement proche",
             "explanation": "She stayed, and the departure was never meant to happen."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une porte qu'il suffisait de savoir ouverte pour n'avoir plus besoin de la franchir.",
        "key_line_en": "A door you only needed to know was open in order never to need to walk through it.",
        "vocabulary": [
            {"term": "un renoncement", "gloss": "a giving-up"},
            {"term": "à force de", "gloss": "through constantly"},
            {"term": "franchir", "gloss": "to cross, go through"},
            {"term": "habiter", "gloss": "to live in, inhabit"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse urbaine / Urban analysis",
        "topic": "Vie quotidienne & logement",
        "text": "Un logement se juge à sa surface, jamais à ses seuils.\nOn compte les mètres carrés, on ne compte pas les endroits où l'on peut fermer une porte. Deux pièces qui s'isolent valent mieux, pour deux personnes qui vivent ensemble, que trente mètres carrés ouverts.",
        "question_fr": "Que défend l'auteur ?",
        "options": [
            {"id": "a", "text": "Les grands logements ouverts sont préférables",
             "explanation": "The comparison ends the other way for two people sharing."},
            {"id": "b", "text": "La possibilité de s'isoler compte plus que la surface",
             "explanation": "« Deux pièces qui s'isolent valent mieux […] que trente mètres carrés ouverts »."},
            {"id": "c", "text": "Les mètres carrés sont mal mesurés",
             "explanation": "Measurement accuracy is not at issue; what is counted is."},
            {"id": "d", "text": "Il faut construire plus de pièces",
             "explanation": "No building prescription is given; a criterion of judgement is."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On compte les mètres carrés, on ne compte pas les endroits où l'on peut fermer une porte.",
        "key_line_en": "We count the square metres; we do not count the places where a door can be closed.",
        "vocabulary": [
            {"term": "un seuil", "gloss": "a threshold"},
            {"term": "s'isoler", "gloss": "to have privacy, be apart"},
            {"term": "valoir mieux", "gloss": "to be worth more"},
            {"term": "ouvert", "gloss": "open-plan"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "topic": "Environnement & nature",
        "text": "Restaurer un milieu ne consiste pas à le ramener à un état antérieur, qui n'est jamais identifiable avec certitude.\nOn choisit une référence, et ce choix est une décision politique déguisée en constat écologique : dire à quelle date la nature était « normale », c'est décider ce qu'on veut retrouver.",
        "question_fr": "Que met en évidence l'auteur ?",
        "options": [
            {"id": "a", "text": "La restauration écologique est impossible",
             "explanation": "It is possible; what is contested is that the reference is purely factual."},
            {"id": "b", "text": "Le choix de l'état de référence est un choix de valeurs",
             "explanation": "« ce choix est une décision politique déguisée en constat écologique »."},
            {"id": "c", "text": "Les milieux anciens étaient plus riches",
             "explanation": "No such comparison is made."},
            {"id": "d", "text": "Les scientifiques manquent de données",
             "explanation": "The difficulty is conceptual, not a shortage of data."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Dire à quelle date la nature était « normale », c'est décider ce qu'on veut retrouver.",
        "key_line_en": "Saying at what date nature was “normal” is deciding what we want to get back.",
        "vocabulary": [
            {"term": "restaurer", "gloss": "to restore"},
            {"term": "une référence", "gloss": "a baseline"},
            {"term": "déguisé en", "gloss": "disguised as"},
            {"term": "un constat", "gloss": "an observation, finding"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Commentaire institutionnel / Institutional commentary",
        "topic": "Études & formation",
        "text": "La réforme confie aux établissements le soin de définir leurs propres critères d'évaluation.\nL'autonomie est réelle ; la comparabilité disparaît. On ne pourra plus dire qu'un diplôme vaut le même diplôme ailleurs, ce qui était pourtant sa fonction première.",
        "question_fr": "Quelle conséquence l'auteur souligne-t-il ?",
        "options": [
            {"id": "a", "text": "Les diplômes ne seront plus comparables entre établissements",
             "explanation": "« On ne pourra plus dire qu'un diplôme vaut le même diplôme ailleurs »."},
            {"id": "b", "text": "L'autonomie annoncée est fictive",
             "explanation": "« L'autonomie est réelle » — that part is granted."},
            {"id": "c", "text": "Les évaluations deviendront plus strictes",
             "explanation": "Strictness is not predicted, only divergence."},
            {"id": "d", "text": "Les établissements perdront leur liberté",
             "explanation": "They gain it; the cost falls elsewhere."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'autonomie est réelle ; la comparabilité disparaît.",
        "key_line_en": "The autonomy is real; comparability disappears.",
        "vocabulary": [
            {"term": "confier", "gloss": "to entrust"},
            {"term": "un critère", "gloss": "a criterion"},
            {"term": "la comparabilité", "gloss": "comparability"},
            {"term": "valoir", "gloss": "to be worth"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur l'art / Essay on art",
        "topic": "Loisirs, culture & médias",
        "text": "Une œuvre qu'on explique entièrement cesse d'être une œuvre : elle devient un exemple.\nCe qui résiste au commentaire n'est pas un défaut de clarté, c'est ce qui oblige à revenir. On ne relit pas ce que l'on a compris ; on relit ce qui n'a pas fini de se laisser comprendre.",
        "question_fr": "Que défend l'auteur ?",
        "options": [
            {"id": "a", "text": "Les œuvres devraient être plus accessibles",
             "explanation": "Full explicability is precisely what empties the work."},
            {"id": "b", "text": "Le commentaire est inutile",
             "explanation": "Commentary is not rejected; what matters is what resists it."},
            {"id": "c", "text": "Ce qui résiste à l'explication fait revenir le lecteur",
             "explanation": "« On relit ce qui n'a pas fini de se laisser comprendre »."},
            {"id": "d", "text": "Les œuvres obscures sont les meilleures",
             "explanation": "Resistance is not obscurity: « ce n'est pas un défaut de clarté »."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On ne relit pas ce que l'on a compris ; on relit ce qui n'a pas fini de se laisser comprendre.",
        "key_line_en": "We do not re-read what we have understood; we re-read what has not finished letting itself be understood.",
        "vocabulary": [
            {"term": "résister à", "gloss": "to resist"},
            {"term": "un défaut", "gloss": "a flaw"},
            {"term": "relire", "gloss": "to re-read"},
            {"term": "se laisser comprendre", "gloss": "to let oneself be understood"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "topic": "Société, citoyenneté & administration",
        "text": "Une majorité qui gouverne sans opposition ne gouverne pas mieux : elle gouverne sans savoir.\nL'opposition ne sert pas à empêcher, elle sert à révéler ce que la majorité n'aurait pas vu — et ce service, elle le rend même quand elle a tort.",
        "question_fr": "Quel rôle l'auteur attribue-t-il à l'opposition ?",
        "options": [
            {"id": "a", "text": "Bloquer les décisions du gouvernement",
             "explanation": "« L'opposition ne sert pas à empêcher » — obstruction is explicitly not its function."},
            {"id": "b", "text": "Faire apparaître ce que la majorité ignore",
             "explanation": "« révéler ce que la majorité n'aurait pas vu — et ce service, elle le rend même quand elle a tort »."},
            {"id": "c", "text": "Remplacer la majorité",
             "explanation": "Alternation in power is not the subject."},
            {"id": "d", "text": "Rendre les débats plus courts",
             "explanation": "Debate length is not discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Ce service, elle le rend même quand elle a tort.",
        "key_line_en": "It renders that service even when it is wrong.",
        "vocabulary": [
            {"term": "une majorité", "gloss": "a majority"},
            {"term": "empêcher", "gloss": "to prevent"},
            {"term": "révéler", "gloss": "to reveal"},
            {"term": "rendre un service", "gloss": "to do a service"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "topic": "Sciences & technologies",
        "text": "Simplifier un phénomène pour l'enseigner produit une dette qu'il faudra rembourser plus tard.\nLe modèle faux mais commode s'installe si bien qu'il résiste ensuite au modèle juste : on n'apprend pas sur une page blanche, on apprend contre ce qu'on croyait savoir.",
        "question_fr": "Quelle difficulté l'auteur décrit-il ?",
        "options": [
            {"id": "a", "text": "Les élèves oublient trop vite",
             "explanation": "The problem is the opposite: the simplified model is retained too well."},
            {"id": "b", "text": "Les modèles simplifiés gênent l'apprentissage ultérieur",
             "explanation": "« il résiste ensuite au modèle juste »; « on apprend contre ce qu'on croyait savoir »."},
            {"id": "c", "text": "Les enseignants simplifient trop peu",
             "explanation": "Simplification is what creates the debt."},
            {"id": "d", "text": "Les modèles justes sont inaccessibles",
             "explanation": "They are reachable, but must displace an established belief."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On n'apprend pas sur une page blanche, on apprend contre ce qu'on croyait savoir.",
        "key_line_en": "We do not learn on a blank page; we learn against what we thought we knew.",
        "vocabulary": [
            {"term": "une dette", "gloss": "a debt"},
            {"term": "commode", "gloss": "convenient"},
            {"term": "s'installer", "gloss": "to take hold"},
            {"term": "résister à", "gloss": "to resist"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "topic": "Vie quotidienne & logement",
        "text": "Le café du coin a fermé, et le quartier n'a rien perdu qui se compte.\nIl a perdu l'endroit où l'on pouvait entrer sans motif, rester sans consommer beaucoup, et repartir sans avoir rien fait. Ces lieux ne figurent dans aucun bilan, faute d'une ligne où les inscrire.",
        "question_fr": "Que regrette l'auteur ?",
        "options": [
            {"id": "a", "text": "Un lieu dont la valeur échappe aux comptes",
             "explanation": "Entering without a reason, staying without spending: « Ces lieux ne figurent dans aucun bilan »."},
            {"id": "b", "text": "La disparition d'un commerce rentable",
             "explanation": "Profitability is not mentioned; the loss is explicitly not one that counts."},
            {"id": "c", "text": "La hausse des prix du quartier",
             "explanation": "No price change is described."},
            {"id": "d", "text": "Le manque de cafés dans la ville",
             "explanation": "The subject is one particular kind of place, not a supply shortage."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ces lieux ne figurent dans aucun bilan, faute d'une ligne où les inscrire.",
        "key_line_en": "Such places appear in no balance sheet, for want of a line to enter them on.",
        "vocabulary": [
            {"term": "un motif", "gloss": "a reason"},
            {"term": "consommer", "gloss": "to buy (in a café)"},
            {"term": "un bilan", "gloss": "a balance sheet"},
            {"term": "inscrire", "gloss": "to record, enter"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Critique de traduction / Translation review",
        "topic": "Loisirs, culture & médias",
        "text": "La nouvelle traduction corrige les erreurs de l'ancienne et perd ce qui la rendait lisible.\nL'exactitude a remplacé le rythme, comme si l'un pouvait tenir sans l'autre. On lit désormais un texte juste que personne n'entend.",
        "question_fr": "Que reproche le critique à cette traduction ?",
        "options": [
            {"id": "a", "text": "Elle contient des erreurs de sens",
             "explanation": "It corrects the old version's errors: accuracy is its achievement."},
            {"id": "b", "text": "Elle est trop libre par rapport à l'original",
             "explanation": "The complaint is excessive literal accuracy, not freedom."},
            {"id": "c", "text": "Elle a sacrifié le rythme à l'exactitude",
             "explanation": "« On lit désormais un texte juste que personne n'entend »."},
            {"id": "d", "text": "Elle reprend l'ancienne traduction",
             "explanation": "It departs from it, which is the whole point."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On lit désormais un texte juste que personne n'entend.",
        "key_line_en": "What we now read is an accurate text that nobody hears.",
        "vocabulary": [
            {"term": "l'exactitude", "gloss": "accuracy"},
            {"term": "lisible", "gloss": "readable"},
            {"term": "le rythme", "gloss": "rhythm"},
            {"term": "entendre", "gloss": "to hear"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la règle / Essay on rules",
        "topic": "Société, citoyenneté & administration",
        "text": "Toute règle suppose quelqu'un pour juger des cas qu'elle n'avait pas prévus, et c'est là qu'elle se révèle.\nUne règle bien écrite ne supprime pas le jugement : elle indique dans quel esprit juger. Celles qui prétendent s'en passer produisent des décisions absurdes appliquées avec rigueur.",
        "question_fr": "Quelle conception de la règle l'auteur défend-il ?",
        "options": [
            {"id": "a", "text": "Une règle doit prévoir tous les cas possibles",
             "explanation": "Rules claiming to dispense with judgement produce « des décisions absurdes appliquées avec rigueur »."},
            {"id": "b", "text": "Une règle doit guider le jugement sans le remplacer",
             "explanation": "« elle indique dans quel esprit juger »."},
            {"id": "c", "text": "Les règles devraient être supprimées",
             "explanation": "Well-written rules are defended."},
            {"id": "d", "text": "Le jugement individuel doit primer sur la règle",
             "explanation": "The two are presented as complementary, not ranked."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une règle bien écrite ne supprime pas le jugement : elle indique dans quel esprit juger.",
        "key_line_en": "A well-written rule does not remove judgement: it indicates in what spirit to judge.",
        "vocabulary": [
            {"term": "prévoir", "gloss": "to anticipate, provide for"},
            {"term": "se passer de", "gloss": "to do without"},
            {"term": "la rigueur", "gloss": "strictness"},
            {"term": "un esprit", "gloss": "a spirit, intent"},
        ],
    },
]

QUESTIONS = balance(_RAW)
