"""Compréhension écrite — Test 03.

Forty questions climbing A1 → C2. Profile A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Avis d'immeuble / Building notice",
        "topic": "Vie quotidienne & logement",
        "text": "AVIS\nDes travaux auront lieu dans la cour mardi et mercredi, de 8 h à 17 h.\nMerci de ne pas garer vos vélos sous les fenêtres.",
        "question_fr": "Que demande cet avis aux habitants ?",
        "options": [
            {"id": "a", "text": "De ne pas laisser leurs vélos dans la cour",
             "explanation": "« Merci de ne pas garer vos vélos sous les fenêtres » is the one instruction given."},
            {"id": "b", "text": "De rester chez eux mardi",
             "explanation": "Nobody is asked to stay in; only the bikes are mentioned."},
            {"id": "c", "text": "De fermer leurs fenêtres",
             "explanation": "The windows locate where the bikes must not be, not an action to perform."},
            {"id": "d", "text": "De payer les travaux",
             "explanation": "No cost or contribution appears on the notice."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Merci de ne pas garer vos vélos sous les fenêtres.",
        "key_line_en": "Please do not park your bikes under the windows.",
        "vocabulary": [
            {"term": "des travaux", "gloss": "building works"},
            {"term": "une cour", "gloss": "a courtyard"},
            {"term": "garer", "gloss": "to park"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Information transport / Transport information",
        "topic": "Transports & voyages",
        "text": "ARRÊT DÉPLACÉ\nL'arrêt « Mairie » est déplacé 100 mètres plus loin, devant la poste.\nDu 4 au 20 avril.",
        "question_fr": "Où se trouve l'arrêt maintenant ?",
        "options": [
            {"id": "a", "text": "À la mairie",
             "explanation": "« Mairie » is the stop's name; the stop itself has moved away from it."},
            {"id": "b", "text": "Devant la poste",
             "explanation": "« déplacé 100 mètres plus loin, devant la poste » gives the new location."},
            {"id": "c", "text": "À 100 mètres de la poste",
             "explanation": "The 100 metres measure the move, and the arrival point is the post office itself."},
            {"id": "d", "text": "Il n'y a plus d'arrêt",
             "explanation": "The stop still exists; it has only been moved."},
        ],
        "correct_answer": "b",
        "key_line_fr": "L'arrêt « Mairie » est déplacé 100 mètres plus loin, devant la poste.",
        "key_line_en": "The “Mairie” stop is moved 100 metres further on, in front of the post office.",
        "vocabulary": [
            {"term": "un arrêt", "gloss": "a stop"},
            {"term": "déplacer", "gloss": "to move"},
            {"term": "plus loin", "gloss": "further on"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Panneau de marché / Market sign",
        "topic": "Alimentation & consommation",
        "text": "MARCHÉ DE SAINT-JEAN\nMardi et samedi matin, de 7 h à 13 h.\nProduits de la région.",
        "question_fr": "Quand a lieu le marché ?",
        "options": [
            {"id": "a", "text": "Tous les jours",
             "explanation": "Only two days are listed: Tuesday and Saturday."},
            {"id": "b", "text": "Le samedi après-midi",
             "explanation": "The market runs in the morning and closes at 1 p.m."},
            {"id": "c", "text": "Le mardi et le samedi matin",
             "explanation": "« Mardi et samedi matin, de 7 h à 13 h » states both days and the time."},
            {"id": "d", "text": "Le mardi seulement",
             "explanation": "Saturday is listed too."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Mardi et samedi matin, de 7 h à 13 h.",
        "key_line_en": "Tuesday and Saturday morning, from 7 a.m. to 1 p.m.",
        "vocabulary": [
            {"term": "un marché", "gloss": "a market"},
            {"term": "la région", "gloss": "the local area"},
            {"term": "avoir lieu", "gloss": "to take place"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Mot du cabinet médical / Doctor's note",
        "topic": "Santé & bien-être",
        "text": "Le docteur Lemaire est absent du 10 au 17 mai.\nEn cas d'urgence, appelez le 15.\nLes rendez-vous sont reportés après le 17.",
        "question_fr": "Que faire en cas d'urgence pendant cette période ?",
        "options": [
            {"id": "a", "text": "Attendre le 17 mai",
             "explanation": "Waiting applies to ordinary appointments, not to emergencies."},
            {"id": "b", "text": "Aller au cabinet",
             "explanation": "The doctor is away, so the surgery is not the answer."},
            {"id": "c", "text": "Prendre un rendez-vous",
             "explanation": "Appointments are being postponed, which does not help an emergency."},
            {"id": "d", "text": "Téléphoner au 15",
             "explanation": "« En cas d'urgence, appelez le 15 » gives the emergency number directly."},
        ],
        "correct_answer": "d",
        "key_line_fr": "En cas d'urgence, appelez le 15.",
        "key_line_en": "In an emergency, call 15.",
        "vocabulary": [
            {"term": "une urgence", "gloss": "an emergency"},
            {"term": "absent", "gloss": "away"},
            {"term": "reporter", "gloss": "to postpone"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Carte de bibliothèque / Library card",
        "topic": "Études & formation",
        "text": "BIBLIOTHÈQUE UNIVERSITAIRE\nCarte gratuite pour les étudiants.\nPrésentez votre carte d'étudiant et une photo.\nInscription au bureau 2.",
        "question_fr": "Que faut-il apporter pour s'inscrire ?",
        "options": [
            {"id": "a", "text": "De l'argent",
             "explanation": "« Carte gratuite pour les étudiants » — there is nothing to pay."},
            {"id": "b", "text": "Une carte d'étudiant et une photo",
             "explanation": "« Présentez votre carte d'étudiant et une photo » lists exactly these two items."},
            {"id": "c", "text": "Un livre",
             "explanation": "No book is required to join."},
            {"id": "d", "text": "Une lettre du professeur",
             "explanation": "No letter or recommendation is mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Présentez votre carte d'étudiant et une photo.",
        "key_line_en": "Show your student card and a photograph.",
        "vocabulary": [
            {"term": "gratuit", "gloss": "free"},
            {"term": "présenter", "gloss": "to show"},
            {"term": "une inscription", "gloss": "registration"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Affiche de concert / Concert poster",
        "topic": "Loisirs, culture & médias",
        "text": "CONCERT DE JAZZ\nSamedi 18 juin, 20 h 30, parc municipal.\nEntrée libre.\nEn cas de pluie, le concert est annulé.",
        "question_fr": "Combien coûte l'entrée ?",
        "options": [
            {"id": "a", "text": "18 euros",
             "explanation": "18 is the date of the concert, not a price."},
            {"id": "b", "text": "20 euros",
             "explanation": "20 h 30 is the start time; there is no price in the poster."},
            {"id": "c", "text": "Rien",
             "explanation": "« Entrée libre » means admission is free."},
            {"id": "d", "text": "Le prix n'est pas indiqué",
             "explanation": "It is indicated — « Entrée libre » is the price information."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Entrée libre.",
        "key_line_en": "Free admission.",
        "vocabulary": [
            {"term": "entrée libre", "gloss": "free admission"},
            {"term": "la pluie", "gloss": "rain"},
            {"term": "annulé", "gloss": "cancelled"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Offre d'emploi / Job advert",
        "topic": "Travail & emploi",
        "text": "Boulangerie recherche un vendeur (H/F) à mi-temps.\nHoraires : 6 h – 12 h, du mercredi au dimanche.\nLe candidat doit habiter à proximité, aucun transport ne circule à cette heure.",
        "question_fr": "Pourquoi faut-il habiter près de la boulangerie ?",
        "options": [
            {"id": "a", "text": "Parce que les transports ne fonctionnent pas si tôt",
             "explanation": "« aucun transport ne circule à cette heure » — nothing runs at 6 a.m., so the employee must be able to get there without it."},
            {"id": "b", "text": "Parce que le poste est à mi-temps",
             "explanation": "Part-time hours say nothing about where someone lives."},
            {"id": "c", "text": "Parce qu'il faut travailler le dimanche",
             "explanation": "Sunday work is a condition of the job, not a reason to live nearby."},
            {"id": "d", "text": "Parce que le salaire est bas",
             "explanation": "No pay figure is given in the advert."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le candidat doit habiter à proximité, aucun transport ne circule à cette heure.",
        "key_line_en": "The candidate must live nearby; no transport runs at that hour.",
        "vocabulary": [
            {"term": "à mi-temps", "gloss": "part-time"},
            {"term": "à proximité", "gloss": "nearby"},
            {"term": "circuler", "gloss": "to run (of transport)"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Courriel d'agence / Agency e-mail",
        "topic": "Vie quotidienne & logement",
        "text": "Madame,\nLa visite de l'appartement est fixée jeudi à 17 h.\nMerci d'apporter vos trois derniers bulletins de salaire et une pièce d'identité.\nSans ces documents, le dossier ne pourra pas être étudié.",
        "question_fr": "Que se passe-t-il si les documents manquent ?",
        "options": [
            {"id": "a", "text": "La visite est annulée",
             "explanation": "The viewing still takes place; it is the application that cannot proceed."},
            {"id": "b", "text": "Le loyer augmente",
             "explanation": "No rent or price is mentioned."},
            {"id": "c", "text": "La candidature ne sera pas examinée",
             "explanation": "« Sans ces documents, le dossier ne pourra pas être étudié »."},
            {"id": "d", "text": "Il faut revenir vendredi",
             "explanation": "No second date is offered."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Sans ces documents, le dossier ne pourra pas être étudié.",
        "key_line_en": "Without these documents, the application cannot be considered.",
        "vocabulary": [
            {"term": "un bulletin de salaire", "gloss": "a payslip"},
            {"term": "un dossier", "gloss": "an application file"},
            {"term": "étudier un dossier", "gloss": "to consider an application"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Courrier de santé / Health letter",
        "topic": "Santé & bien-être",
        "text": "Madame, Monsieur,\nVous êtes invité(e) à un dépistage gratuit, sans rendez-vous, du 2 au 6 octobre.\nL'examen dure dix minutes. Munissez-vous de votre carte d'assurance maladie.\nCette invitation est personnelle et ne peut être transmise.",
        "question_fr": "Comment se déroule ce dépistage ?",
        "options": [
            {"id": "a", "text": "Il faut réserver à l'avance",
             "explanation": "« sans rendez-vous » — no booking is needed."},
            {"id": "b", "text": "Il faut payer sur place",
             "explanation": "The screening is « gratuit »."},
            {"id": "c", "text": "On peut y envoyer un proche",
             "explanation": "« Cette invitation est personnelle et ne peut être transmise »."},
            {"id": "d", "text": "On vient librement avec sa carte d'assurance",
             "explanation": "No appointment, ten minutes, and one document to bring: the health insurance card."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Un dépistage gratuit, sans rendez-vous […]. Munissez-vous de votre carte d'assurance maladie.",
        "key_line_en": "A free screening, no appointment needed […]. Bring your health insurance card.",
        "vocabulary": [
            {"term": "un dépistage", "gloss": "a screening test"},
            {"term": "sans rendez-vous", "gloss": "no appointment needed"},
            {"term": "se munir de", "gloss": "to bring"},
            {"term": "transmettre", "gloss": "to pass on"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Règlement de parking / Car park rules",
        "topic": "Transports & voyages",
        "text": "PARKING DE LA GARE\nLes trente premières minutes sont gratuites.\nEnsuite : 2 € par heure commencée, 18 € maximum par jour.\nLe ticket doit être payé à la borne avant de rejoindre son véhicule.",
        "question_fr": "Que paie un conducteur resté vingt minutes ?",
        "options": [
            {"id": "a", "text": "Rien",
             "explanation": "Twenty minutes falls inside the free first half-hour."},
            {"id": "b", "text": "2 euros",
             "explanation": "Charging starts only after the first thirty minutes."},
            {"id": "c", "text": "18 euros",
             "explanation": "€18 is the daily maximum, not a short-stay price."},
            {"id": "d", "text": "2 € par heure commencée",
             "explanation": "That rate applies from the thirty-first minute onwards."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les trente premières minutes sont gratuites.",
        "key_line_en": "The first thirty minutes are free.",
        "vocabulary": [
            {"term": "une heure commencée", "gloss": "each hour started"},
            {"term": "une borne", "gloss": "a payment terminal"},
            {"term": "rejoindre", "gloss": "to go back to"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Conditions de livraison / Delivery terms",
        "topic": "Alimentation & consommation",
        "text": "LIVRAISON DE COURSES\nGratuite à partir de 60 € d'achat, sinon 5 €.\nCréneaux de deux heures, à choisir au moment de la commande.\nLes produits frais sont livrés dans un sac isotherme, à rendre à la livraison suivante.",
        "question_fr": "Que doit faire le client du sac isotherme ?",
        "options": [
            {"id": "a", "text": "Le payer 5 €",
             "explanation": "The €5 is the delivery charge under €60, not the bag."},
            {"id": "b", "text": "Le garder",
             "explanation": "It is to be given back, not kept."},
            {"id": "c", "text": "Le rendre la fois suivante",
             "explanation": "« à rendre à la livraison suivante » states it directly."},
            {"id": "d", "text": "Le choisir à la commande",
             "explanation": "What is chosen at order time is the two-hour delivery slot."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les produits frais sont livrés dans un sac isotherme, à rendre à la livraison suivante.",
        "key_line_en": "Fresh items are delivered in a cool bag, to be returned at the next delivery.",
        "vocabulary": [
            {"term": "un créneau", "gloss": "a time slot"},
            {"term": "isotherme", "gloss": "insulated, cool (bag)"},
            {"term": "rendre", "gloss": "to give back"},
            {"term": "à partir de", "gloss": "from (an amount)"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Message d'application / App message",
        "topic": "Sciences & technologies",
        "text": "MISE À JOUR DISPONIBLE\nCette version corrige plusieurs erreurs et améliore la batterie.\nL'installation dure environ cinq minutes ; l'application sera indisponible pendant ce temps.\nVos données sont conservées.",
        "question_fr": "Que se passe-t-il pendant l'installation ?",
        "options": [
            {"id": "a", "text": "Les données sont effacées",
             "explanation": "« Vos données sont conservées » — nothing is lost."},
            {"id": "b", "text": "L'application ne fonctionne pas",
             "explanation": "« l'application sera indisponible pendant ce temps » — it is unavailable for about five minutes."},
            {"id": "c", "text": "La batterie se décharge",
             "explanation": "Battery life is what the update improves, not a side effect of installing it."},
            {"id": "d", "text": "Il faut redémarrer le téléphone",
             "explanation": "No restart is mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "L'application sera indisponible pendant ce temps.",
        "key_line_en": "The app will be unavailable during that time.",
        "vocabulary": [
            {"term": "une mise à jour", "gloss": "an update"},
            {"term": "indisponible", "gloss": "unavailable"},
            {"term": "conserver", "gloss": "to keep"},
            {"term": "corriger", "gloss": "to fix"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Annonce de club / Club announcement",
        "topic": "Loisirs, culture & médias",
        "text": "CLUB DE NATATION\nInscriptions ouvertes jusqu'au 15 septembre.\nDeux séances d'essai gratuites avant de s'engager.\nCertificat médical obligatoire pour la saison complète.",
        "question_fr": "Quand le certificat médical est-il nécessaire ?",
        "options": [
            {"id": "a", "text": "Dès la première séance d'essai",
             "explanation": "The trial sessions are free and come « avant de s'engager », before the season commitment."},
            {"id": "b", "text": "Jamais",
             "explanation": "It is described as « obligatoire » for the full season."},
            {"id": "c", "text": "Après le 15 septembre",
             "explanation": "15 September is the registration deadline, not a certificate date."},
            {"id": "d", "text": "Pour s'inscrire à la saison complète",
             "explanation": "« Certificat médical obligatoire pour la saison complète » ties it to the full membership."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Certificat médical obligatoire pour la saison complète.",
        "key_line_en": "A medical certificate is compulsory for the full season.",
        "vocabulary": [
            {"term": "une séance d'essai", "gloss": "a trial session"},
            {"term": "s'engager", "gloss": "to commit"},
            {"term": "un certificat médical", "gloss": "a medical certificate"},
        ],
    },
]

QUESTIONS = balance(_RAW)
