"""Compréhension écrite — Test 04.

Forty questions climbing A1 → C2. Profile A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "SMS",
        "topic": "Transports & voyages",
        "text": "Bonjour,\nVotre taxi arrive dans 5 minutes.\nVoiture grise, plaque AB-123-CD.\nLe chauffeur vous attend devant le numéro 8.",
        "question_fr": "Où le chauffeur attend-il ?",
        "options": [
            {"id": "a", "text": "Devant le numéro 8",
             "explanation": "« Le chauffeur vous attend devant le numéro 8 » gives the place directly."},
            {"id": "b", "text": "Dans cinq minutes",
             "explanation": "That is a time, not a place."},
            {"id": "c", "text": "À la gare",
             "explanation": "No station is mentioned."},
            {"id": "d", "text": "Devant le numéro 123",
             "explanation": "123 is part of the number plate, not an address."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le chauffeur vous attend devant le numéro 8.",
        "key_line_en": "The driver is waiting for you outside number 8.",
        "vocabulary": [
            {"term": "un chauffeur", "gloss": "a driver"},
            {"term": "une plaque", "gloss": "a number plate"},
            {"term": "attendre", "gloss": "to wait for"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Étiquette / Label",
        "topic": "Alimentation & consommation",
        "text": "YAOURT NATURE\nÀ conserver entre 2 °C et 6 °C.\nÀ consommer avant le 12/09.\nAprès ouverture : 48 heures.",
        "question_fr": "Où faut-il garder ce produit ?",
        "options": [
            {"id": "a", "text": "Au congélateur",
             "explanation": "2 to 6 °C is fridge temperature, well above freezing."},
            {"id": "b", "text": "Dans un placard",
             "explanation": "A cupboard is at room temperature, far above 6 °C."},
            {"id": "c", "text": "Au réfrigérateur",
             "explanation": "« À conserver entre 2 °C et 6 °C » is the fridge range."},
            {"id": "d", "text": "À la fenêtre",
             "explanation": "No cold temperature is guaranteed there."},
        ],
        "correct_answer": "c",
        "key_line_fr": "À conserver entre 2 °C et 6 °C.",
        "key_line_en": "Keep between 2 °C and 6 °C.",
        "vocabulary": [
            {"term": "conserver", "gloss": "to keep, store"},
            {"term": "à consommer avant", "gloss": "use by"},
            {"term": "après ouverture", "gloss": "once opened"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Panneau / Sign",
        "topic": "Vie quotidienne & logement",
        "text": "ATTENTION\nPeinture fraîche.\nNe pas toucher le mur.\nMerci de votre compréhension.",
        "question_fr": "Que ne faut-il pas faire ?",
        "options": [
            {"id": "a", "text": "Entrer dans la pièce",
             "explanation": "Entry is not forbidden; only touching is."},
            {"id": "b", "text": "Toucher le mur",
             "explanation": "« Ne pas toucher le mur » is the single instruction."},
            {"id": "c", "text": "Prendre des photos",
             "explanation": "Photography is not mentioned."},
            {"id": "d", "text": "Parler fort",
             "explanation": "Noise is not mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Peinture fraîche. Ne pas toucher le mur.",
        "key_line_en": "Wet paint. Do not touch the wall.",
        "vocabulary": [
            {"term": "la peinture", "gloss": "paint"},
            {"term": "frais / fraîche", "gloss": "fresh, wet"},
            {"term": "toucher", "gloss": "to touch"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Courriel / E-mail",
        "topic": "Études & formation",
        "text": "Bonjour,\nLe cours de français de lundi est annulé.\nIl est remplacé par un cours mercredi, à la même heure.\nBonne journée,\nLe secrétariat",
        "question_fr": "Quand aura lieu le cours ?",
        "options": [
            {"id": "a", "text": "Lundi",
             "explanation": "The Monday class is the one that has been cancelled."},
            {"id": "b", "text": "Il n'y aura pas de cours",
             "explanation": "There is a class; it has been moved, not dropped."},
            {"id": "c", "text": "À une autre heure",
             "explanation": "« à la même heure » — the time is unchanged."},
            {"id": "d", "text": "Mercredi",
             "explanation": "« Il est remplacé par un cours mercredi »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Il est remplacé par un cours mercredi, à la même heure.",
        "key_line_en": "It is replaced by a class on Wednesday, at the same time.",
        "vocabulary": [
            {"term": "annulé", "gloss": "cancelled"},
            {"term": "remplacer", "gloss": "to replace"},
            {"term": "le secrétariat", "gloss": "the school office"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Affiche / Notice",
        "topic": "Santé & bien-être",
        "text": "SALLE D'ATTENTE\nMerci d'éteindre votre téléphone.\nLes enfants restent avec un adulte.\nLe médecin vous appelle par votre nom.",
        "question_fr": "Que demande-t-on aux patients ?",
        "options": [
            {"id": "a", "text": "De ne pas utiliser leur téléphone",
             "explanation": "« Merci d'éteindre votre téléphone » — phones must be switched off."},
            {"id": "b", "text": "D'appeler le médecin",
             "explanation": "It is the doctor who calls the patients."},
            {"id": "c", "text": "De laisser les enfants seuls",
             "explanation": "The opposite: children stay with an adult."},
            {"id": "d", "text": "D'écrire leur nom",
             "explanation": "Nobody is asked to write anything."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Merci d'éteindre votre téléphone.",
        "key_line_en": "Please switch off your phone.",
        "vocabulary": [
            {"term": "une salle d'attente", "gloss": "a waiting room"},
            {"term": "éteindre", "gloss": "to switch off"},
            {"term": "appeler", "gloss": "to call"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Mot / Note",
        "topic": "Loisirs, culture & médias",
        "text": "Salut,\nJe te laisse les clés du studio pour ta répétition.\nMerci de fermer la fenêtre en partant.\nÀ vendredi !\nKarim",
        "question_fr": "Que doit faire la personne en partant ?",
        "options": [
            {"id": "a", "text": "Laisser les clés",
             "explanation": "Karim is the one leaving the keys, for the other person to use."},
            {"id": "b", "text": "Téléphoner à Karim",
             "explanation": "No call is requested."},
            {"id": "c", "text": "Venir vendredi",
             "explanation": "« À vendredi » is a goodbye, not the instruction for leaving the studio."},
            {"id": "d", "text": "Fermer la fenêtre",
             "explanation": "« Merci de fermer la fenêtre en partant » is the request."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Merci de fermer la fenêtre en partant.",
        "key_line_en": "Please close the window when you leave.",
        "vocabulary": [
            {"term": "une répétition", "gloss": "a rehearsal"},
            {"term": "en partant", "gloss": "when leaving"},
            {"term": "fermer", "gloss": "to close"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Petite annonce / Classified ad",
        "topic": "Travail & emploi",
        "text": "GARDE D'ENFANTS\nFamille cherche une personne pour garder deux enfants (4 et 7 ans).\nLundi, mardi et jeudi, de 16 h 30 à 19 h.\nExpérience avec les enfants demandée. Références exigées.",
        "question_fr": "Quelle condition la famille pose-t-elle ?",
        "options": [
            {"id": "a", "text": "Être disponible tous les jours",
             "explanation": "Only three days are listed: Monday, Tuesday and Thursday."},
            {"id": "b", "text": "Fournir des références",
             "explanation": "« Références exigées » — references are required."},
            {"id": "c", "text": "Avoir moins de 25 ans",
             "explanation": "No age condition appears."},
            {"id": "d", "text": "Habiter chez la famille",
             "explanation": "The hours are afternoons only; living in is never mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Expérience avec les enfants demandée. Références exigées.",
        "key_line_en": "Experience with children required. References essential.",
        "vocabulary": [
            {"term": "la garde d'enfants", "gloss": "childcare"},
            {"term": "des références", "gloss": "references"},
            {"term": "exigé", "gloss": "required"},
            {"term": "disponible", "gloss": "available"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Règlement / Rules",
        "topic": "Vie quotidienne & logement",
        "text": "RÈGLEMENT DE L'IMMEUBLE\nLes travaux bruyants sont autorisés de 9 h à 12 h et de 14 h à 19 h, sauf le dimanche.\nLes poubelles sont sorties la veille au soir.\nLe local à vélos est réservé aux résidents.",
        "question_fr": "Quand peut-on faire des travaux bruyants ?",
        "options": [
            {"id": "a", "text": "Tous les jours de 9 h à 19 h",
             "explanation": "Two things are wrong: there is a midday break, and Sunday is excluded."},
            {"id": "b", "text": "Le dimanche matin",
             "explanation": "« sauf le dimanche » — Sunday is excluded entirely."},
            {"id": "c", "text": "En semaine, sauf entre midi et 14 h",
             "explanation": "The two windows are 9–12 and 14–19, on every day except Sunday."},
            {"id": "d", "text": "À n'importe quelle heure",
             "explanation": "Precise hours are set by the rules."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les travaux bruyants sont autorisés de 9 h à 12 h et de 14 h à 19 h, sauf le dimanche.",
        "key_line_en": "Noisy work is allowed from 9 to 12 and from 2 to 7, except on Sundays.",
        "vocabulary": [
            {"term": "bruyant", "gloss": "noisy"},
            {"term": "sauf", "gloss": "except"},
            {"term": "la veille", "gloss": "the day before"},
            {"term": "un local", "gloss": "a room, storage area"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Consigne / Instructions",
        "topic": "Santé & bien-être",
        "text": "AVANT L'EXAMEN\nRestez à jeun pendant douze heures : ni nourriture, ni boisson sucrée.\nL'eau est autorisée.\nApportez votre ordonnance et la liste de vos médicaments.",
        "question_fr": "Que peut-on prendre avant l'examen ?",
        "options": [
            {"id": "a", "text": "Un café sucré",
             "explanation": "Sweetened drinks are excluded by « ni boisson sucrée »."},
            {"id": "b", "text": "Un petit-déjeuner léger",
             "explanation": "« à jeun » means no food at all for twelve hours."},
            {"id": "c", "text": "De l'eau",
             "explanation": "« L'eau est autorisée » is the one exception."},
            {"id": "d", "text": "Rien du tout",
             "explanation": "Water is explicitly permitted."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Restez à jeun pendant douze heures […]. L'eau est autorisée.",
        "key_line_en": "Fast for twelve hours […]. Water is allowed.",
        "vocabulary": [
            {"term": "à jeun", "gloss": "fasting, on an empty stomach"},
            {"term": "une ordonnance", "gloss": "a prescription"},
            {"term": "sucré", "gloss": "sweetened"},
            {"term": "la nourriture", "gloss": "food"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information voyage / Travel information",
        "topic": "Transports & voyages",
        "text": "BAGAGES EN CABINE\nUn bagage de 55 x 40 x 20 cm maximum, 10 kg.\nUn petit sac supplémentaire est accepté sous le siège.\nTout bagage plus grand sera mis en soute, avec un supplément de 45 €.",
        "question_fr": "Que se passe-t-il si le bagage est trop grand ?",
        "options": [
            {"id": "a", "text": "Il est refusé à l'embarquement",
             "explanation": "It is not refused; it goes in the hold for a fee."},
            {"id": "b", "text": "Il faut payer 45 € et le mettre en soute",
             "explanation": "« sera mis en soute, avec un supplément de 45 € »."},
            {"id": "c", "text": "Il faut le porter sous le siège",
             "explanation": "Under the seat is where the extra small bag goes, not an oversized case."},
            {"id": "d", "text": "Il est pesé une seconde fois",
             "explanation": "No second weighing is mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Tout bagage plus grand sera mis en soute, avec un supplément de 45 €.",
        "key_line_en": "Any larger bag will be placed in the hold, with a €45 surcharge.",
        "vocabulary": [
            {"term": "en cabine", "gloss": "in the cabin"},
            {"term": "la soute", "gloss": "the hold"},
            {"term": "un supplément", "gloss": "a surcharge"},
            {"term": "un siège", "gloss": "a seat"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Annonce / Announcement",
        "topic": "Loisirs, culture & médias",
        "text": "VISITE GUIDÉE DU VIEUX QUARTIER\nDépart tous les samedis à 10 h, devant la fontaine.\nDurée : 1 h 30. Tarif : 8 €, gratuit pour les moins de 12 ans.\nLa visite se fait par tous les temps : prévoyez une tenue adaptée.",
        "question_fr": "Que se passe-t-il s'il pleut ?",
        "options": [
            {"id": "a", "text": "La visite est annulée",
             "explanation": "« La visite se fait par tous les temps » — it goes ahead in any weather."},
            {"id": "b", "text": "La visite est remboursée",
             "explanation": "No refund is mentioned."},
            {"id": "c", "text": "La visite a lieu quand même",
             "explanation": "It runs whatever the weather, which is why suitable clothing is advised."},
            {"id": "d", "text": "La visite est plus courte",
             "explanation": "The duration is fixed at an hour and a half."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La visite se fait par tous les temps : prévoyez une tenue adaptée.",
        "key_line_en": "The tour runs in all weathers: dress accordingly.",
        "vocabulary": [
            {"term": "par tous les temps", "gloss": "in all weathers"},
            {"term": "une tenue", "gloss": "an outfit, clothing"},
            {"term": "la durée", "gloss": "the length"},
            {"term": "un tarif", "gloss": "a price, rate"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Message d'information / Service message",
        "topic": "Sciences & technologies",
        "text": "Votre mot de passe expire dans trois jours.\nLe nouveau mot de passe doit contenir au moins dix caractères, dont un chiffre et une majuscule.\nIl ne peut pas reprendre l'un de vos trois derniers mots de passe.",
        "question_fr": "Que doit contenir le nouveau mot de passe ?",
        "options": [
            {"id": "a", "text": "Trois caractères au minimum",
             "explanation": "Three refers to the days left and to the old passwords, not to a length."},
            {"id": "b", "text": "Uniquement des lettres",
             "explanation": "A digit is required, so letters alone are not enough."},
            {"id": "c", "text": "L'un des anciens mots de passe",
             "explanation": "The last three are explicitly forbidden."},
            {"id": "d", "text": "Dix caractères, un chiffre et une majuscule",
             "explanation": "« au moins dix caractères, dont un chiffre et une majuscule » lists all three conditions."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Au moins dix caractères, dont un chiffre et une majuscule.",
        "key_line_en": "At least ten characters, including one digit and one capital letter.",
        "vocabulary": [
            {"term": "expirer", "gloss": "to expire"},
            {"term": "un chiffre", "gloss": "a digit"},
            {"term": "une majuscule", "gloss": "a capital letter"},
            {"term": "reprendre", "gloss": "to reuse"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Message de forum / Forum post",
        "topic": "Environnement & nature",
        "text": "Bonjour,\nNous organisons un ramassage de déchets sur la plage samedi à 9 h.\nGants et sacs fournis. Prévoyez de bonnes chaussures.\nInutile de s'inscrire : venez à l'heure que vous voulez, on reste jusqu'à midi.",
        "question_fr": "Comment participer à cette action ?",
        "options": [
            {"id": "a", "text": "Venir sans s'inscrire",
             "explanation": "« Inutile de s'inscrire : venez à l'heure que vous voulez » — just turn up."},
            {"id": "b", "text": "S'inscrire avant samedi",
             "explanation": "Registration is explicitly unnecessary."},
            {"id": "c", "text": "Apporter des gants et des sacs",
             "explanation": "« Gants et sacs fournis » — those are provided."},
            {"id": "d", "text": "Arriver obligatoirement à 9 h",
             "explanation": "9 a.m. is the start, but people may come at any time until noon."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Inutile de s'inscrire : venez à l'heure que vous voulez.",
        "key_line_en": "No need to sign up: come whenever you like.",
        "vocabulary": [
            {"term": "un ramassage", "gloss": "a collection, pick-up"},
            {"term": "les déchets", "gloss": "litter, waste"},
            {"term": "fourni", "gloss": "provided"},
            {"term": "inutile de", "gloss": "no need to"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article de presse / Press article",
        "topic": "Vie quotidienne & logement",
        "text": "La commune loue depuis un an des logements à loyer réduit aux jeunes actifs, à condition qu'ils y restent au moins deux ans.\n« Nous ne cherchons pas à loger vite, explique l'élu, mais à retenir des gens qui repartaient dès qu'ils trouvaient un emploi ailleurs. »",
        "question_fr": "Quel est l'objectif de cette mesure ?",
        "options": [
            {"id": "a", "text": "Loger le plus de personnes possible",
             "explanation": "« Nous ne cherchons pas à loger vite » — volume is explicitly not the aim."},
            {"id": "b", "text": "Faire rester les jeunes dans la commune",
             "explanation": "The two-year condition serves « à retenir des gens qui repartaient »."},
            {"id": "c", "text": "Augmenter les recettes de la commune",
             "explanation": "The rents are reduced, so income is not the point."},
            {"id": "d", "text": "Construire de nouveaux logements",
             "explanation": "The scheme lets existing homes; no building programme is mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nous ne cherchons pas à loger vite, mais à retenir des gens qui repartaient.",
        "key_line_en": "We are not trying to house people quickly, but to keep people who were leaving.",
        "vocabulary": [
            {"term": "un loyer", "gloss": "a rent"},
            {"term": "retenir", "gloss": "to keep, hold on to"},
            {"term": "un élu", "gloss": "an elected official"},
            {"term": "repartir", "gloss": "to leave again"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "topic": "Alimentation & consommation",
        "text": "Neuf personnes sur dix déclarent vouloir réduire leur gaspillage alimentaire.\nDans les faits, la quantité jetée n'a pas bougé depuis cinq ans. L'écart s'explique surtout par les achats en promotion : on achète en quantité ce qu'on ne consommera pas.",
        "question_fr": "Comment l'enquête explique-t-elle le gaspillage ?",
        "options": [
            {"id": "a", "text": "Par le manque d'intérêt des consommateurs",
             "explanation": "Nine in ten say they want to cut waste, so intent is not what is missing."},
            {"id": "b", "text": "Par le prix élevé des aliments",
             "explanation": "Price is only mentioned through promotions, which encourage buying, not through cost."},
            {"id": "c", "text": "Par les achats en grande quantité",
             "explanation": "« on achète en quantité ce qu'on ne consommera pas » — promotions drive the excess."},
            {"id": "d", "text": "Par les dates limites trop courtes",
             "explanation": "Use-by dates are never discussed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On achète en quantité ce qu'on ne consommera pas.",
        "key_line_en": "People buy in quantity what they will not eat.",
        "vocabulary": [
            {"term": "le gaspillage", "gloss": "waste"},
            {"term": "dans les faits", "gloss": "in practice"},
            {"term": "jeter", "gloss": "to throw away"},
            {"term": "une promotion", "gloss": "a special offer"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Lettre de réclamation / Letter of complaint",
        "topic": "Travail & emploi",
        "text": "Madame,\nMon contrat prévoit trente-cinq heures hebdomadaires. Depuis trois mois, je dépasse régulièrement quarante heures, sans que ces heures apparaissent sur mes bulletins.\nJe ne demande pas de compensation financière immédiate, mais que ces heures soient enfin comptabilisées.",
        "question_fr": "Que demande cette salariée ?",
        "options": [
            {"id": "a", "text": "Une augmentation de salaire",
             "explanation": "« Je ne demande pas de compensation financière immédiate » — pay is not the request."},
            {"id": "b", "text": "Une réduction de son temps de travail",
             "explanation": "She asks for the hours to be recorded, not for fewer of them."},
            {"id": "c", "text": "Un changement de contrat",
             "explanation": "The contract is cited as the reference, not as something to rewrite."},
            {"id": "d", "text": "Que ses heures supplémentaires soient enregistrées",
             "explanation": "« que ces heures soient enfin comptabilisées » is the explicit request."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Je ne demande pas de compensation financière immédiate, mais que ces heures soient enfin comptabilisées.",
        "key_line_en": "I am not asking for immediate financial compensation, but for these hours finally to be recorded.",
        "vocabulary": [
            {"term": "hebdomadaire", "gloss": "weekly"},
            {"term": "dépasser", "gloss": "to exceed"},
            {"term": "un bulletin (de paie)", "gloss": "a payslip"},
            {"term": "comptabiliser", "gloss": "to record, count"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Chronique santé / Health column",
        "topic": "Santé & bien-être",
        "text": "Boire deux litres d'eau par jour est une règle commode, mais approximative.\nLes besoins varient selon la température, l'activité et l'alimentation : une part importante de l'eau vient des aliments. La soif reste le meilleur indicateur pour un adulte en bonne santé.",
        "question_fr": "Que conseille l'auteur ?",
        "options": [
            {"id": "a", "text": "De se fier à sa soif",
             "explanation": "« La soif reste le meilleur indicateur pour un adulte en bonne santé »."},
            {"id": "b", "text": "De boire exactement deux litres",
             "explanation": "The rule is called « commode, mais approximative » — convenient, not exact."},
            {"id": "c", "text": "De boire moins en été",
             "explanation": "Higher temperature raises needs, so the advice would run the other way."},
            {"id": "d", "text": "De ne compter que les boissons",
             "explanation": "The text says a large share of water comes from food."},
        ],
        "correct_answer": "a",
        "key_line_fr": "La soif reste le meilleur indicateur pour un adulte en bonne santé.",
        "key_line_en": "Thirst remains the best guide for a healthy adult.",
        "vocabulary": [
            {"term": "commode", "gloss": "convenient"},
            {"term": "approximatif", "gloss": "rough, approximate"},
            {"term": "la soif", "gloss": "thirst"},
            {"term": "un indicateur", "gloss": "an indicator, guide"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Offre de formation / Training offer",
        "topic": "Études & formation",
        "text": "Cette formation en informatique s'adresse à des personnes sans diplôme dans le domaine.\nAucune connaissance préalable n'est nécessaire ; en revanche, il faut être disponible six mois à plein temps.\nLa sélection se fait sur un entretien de motivation, pas sur le dossier scolaire.",
        "question_fr": "Sur quoi repose la sélection des candidats ?",
        "options": [
            {"id": "a", "text": "Sur les résultats scolaires",
             "explanation": "« pas sur le dossier scolaire » — school records are explicitly excluded."},
            {"id": "b", "text": "Sur les connaissances en informatique",
             "explanation": "« Aucune connaissance préalable n'est nécessaire »."},
            {"id": "c", "text": "Sur un entretien",
             "explanation": "« La sélection se fait sur un entretien de motivation »."},
            {"id": "d", "text": "Sur le diplôme obtenu",
             "explanation": "The course is aimed precisely at people without a qualification in the field."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La sélection se fait sur un entretien de motivation, pas sur le dossier scolaire.",
        "key_line_en": "Selection is by motivation interview, not on school records.",
        "vocabulary": [
            {"term": "préalable", "gloss": "prior"},
            {"term": "à plein temps", "gloss": "full-time"},
            {"term": "un dossier scolaire", "gloss": "a school record"},
            {"term": "en revanche", "gloss": "on the other hand"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article municipal / Local news",
        "topic": "Société, citoyenneté & administration",
        "text": "La mairie a ouvert un guichet unique pour les démarches administratives.\nLe temps d'attente moyen est passé de quarante à quinze minutes. Les agents soulignent toutefois que les dossiers complexes prennent désormais plus longtemps, faute d'un interlocuteur spécialisé.",
        "question_fr": "Quelle limite les agents signalent-ils ?",
        "options": [
            {"id": "a", "text": "Les dossiers difficiles sont moins bien traités",
             "explanation": "Complex files now take longer, « faute d'un interlocuteur spécialisé »."},
            {"id": "b", "text": "Le temps d'attente a augmenté",
             "explanation": "It fell from forty minutes to fifteen."},
            {"id": "c", "text": "Le guichet est trop petit",
             "explanation": "The premises are never mentioned."},
            {"id": "d", "text": "Les agents sont trop nombreux",
             "explanation": "The shortage described is of specialists, not a surplus of staff."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les dossiers complexes prennent désormais plus longtemps, faute d'un interlocuteur spécialisé.",
        "key_line_en": "Complex cases now take longer, for want of a specialist contact.",
        "vocabulary": [
            {"term": "un guichet unique", "gloss": "a one-stop desk"},
            {"term": "une démarche", "gloss": "a procedure, formality"},
            {"term": "un interlocuteur", "gloss": "a contact person"},
            {"term": "faute de", "gloss": "for want of"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Reportage / Report",
        "topic": "Environnement & nature",
        "text": "Le refuge accueille chaque hiver des oiseaux blessés, puis les relâche au printemps.\nLes bénévoles évitent soigneusement de leur parler et de les nourrir à la main : un oiseau qui s'habitue aux humains ne survit pas longtemps une fois relâché.",
        "question_fr": "Pourquoi les bénévoles limitent-ils le contact avec les oiseaux ?",
        "options": [
            {"id": "a", "text": "Pour éviter de se faire blesser",
             "explanation": "The risk described is to the birds, not to the volunteers."},
            {"id": "b", "text": "Parce que les oiseaux mangent seuls",
             "explanation": "They are fed; only hand-feeding is avoided, and for a stated reason."},
            {"id": "c", "text": "Pour préserver leurs chances de survie",
             "explanation": "« un oiseau qui s'habitue aux humains ne survit pas longtemps une fois relâché »."},
            {"id": "d", "text": "Pour respecter le règlement du refuge",
             "explanation": "No rule is cited; the justification given is biological."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Un oiseau qui s'habitue aux humains ne survit pas longtemps une fois relâché.",
        "key_line_en": "A bird that gets used to humans does not survive long once released.",
        "vocabulary": [
            {"term": "un refuge", "gloss": "a sanctuary"},
            {"term": "relâcher", "gloss": "to release"},
            {"term": "s'habituer à", "gloss": "to get used to"},
            {"term": "soigneusement", "gloss": "carefully"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "topic": "Études & formation",
        "text": "On juge une école à ses résultats au baccalauréat, ce qui revient à juger un hôpital au nombre de ses patients guéris sans regarder ceux qu'il admet.\nUn établissement qui fait progresser des élèves fragiles mérite davantage qu'un autre qui sélectionne les meilleurs et n'y ajoute rien.",
        "question_fr": "Que propose l'auteur de mesurer ?",
        "options": [
            {"id": "a", "text": "Le nombre d'élèves reçus au baccalauréat",
             "explanation": "That is exactly the measure he criticises as incomplete."},
            {"id": "b", "text": "Le progrès accompli par les élèves",
             "explanation": "The hospital analogy asks what the school adds: making fragile pupils progress counts for more than selecting strong ones."},
            {"id": "c", "text": "La sélection à l'entrée",
             "explanation": "Selection is what inflates the misleading figure, not the proposed measure."},
            {"id": "d", "text": "Le nombre d'enseignants par classe",
             "explanation": "Staffing is never mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un établissement qui fait progresser des élèves fragiles mérite davantage qu'un autre qui sélectionne les meilleurs et n'y ajoute rien.",
        "key_line_en": "A school that helps struggling pupils progress deserves more credit than one that selects the best and adds nothing.",
        "vocabulary": [
            {"term": "revenir à", "gloss": "to amount to"},
            {"term": "guérir", "gloss": "to cure"},
            {"term": "admettre", "gloss": "to admit, take in"},
            {"term": "fragile", "gloss": "struggling, vulnerable"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "topic": "Transports & voyages",
        "text": "Les trains de nuit reviennent, portés par le souci du climat. Leur équation économique reste pourtant fragile : une rame transporte peu de voyageurs et immobilise du matériel toute la journée.\nSans subvention, la ligne ferme ; avec subvention, on lui reproche de coûter cher.",
        "question_fr": "Quelle difficulté l'auteur décrit-il ?",
        "options": [
            {"id": "a", "text": "Les voyageurs boudent les trains de nuit",
             "explanation": "Demand is not the issue described; the constraint is the economics of the rolling stock."},
            {"id": "b", "text": "Ces trains polluent plus que l'avion",
             "explanation": "Climate concern is what is bringing them back, not an objection to them."},
            {"id": "c", "text": "Le modèle ne tient ni avec ni sans aide publique",
             "explanation": "« Sans subvention, la ligne ferme ; avec subvention, on lui reproche de coûter cher » — both options are criticised."},
            {"id": "d", "text": "Le matériel roulant est trop récent",
             "explanation": "The problem is that the stock sits idle by day, not its age."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Sans subvention, la ligne ferme ; avec subvention, on lui reproche de coûter cher.",
        "key_line_en": "Without a subsidy the line closes; with one, it is criticised for being expensive.",
        "vocabulary": [
            {"term": "une rame", "gloss": "a train set"},
            {"term": "immobiliser", "gloss": "to tie up, keep idle"},
            {"term": "une subvention", "gloss": "a subsidy"},
            {"term": "porté par", "gloss": "driven by"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Critique d'exposition / Exhibition review",
        "topic": "Loisirs, culture & médias",
        "text": "L'exposition rassemble des œuvres rarement montrées, et l'on mesure la chance qu'il y a à les voir réunies.\nLe parcours, en revanche, impose un sens de visite si strict qu'on ne peut revenir sur ses pas : difficile de comparer deux toiles que tout invite à rapprocher.",
        "question_fr": "Que reproche le critique à cette exposition ?",
        "options": [
            {"id": "a", "text": "Le choix des œuvres présentées",
             "explanation": "The selection is praised as a rare opportunity."},
            {"id": "b", "text": "L'organisation imposée du parcours",
             "explanation": "The one-way route prevents going back, so paintings that beg to be compared cannot be."},
            {"id": "c", "text": "Le prix trop élevé de l'entrée",
             "explanation": "No admission price is mentioned."},
            {"id": "d", "text": "Le manque d'explications sur les toiles",
             "explanation": "Labels and commentary are never discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Le parcours impose un sens de visite si strict qu'on ne peut revenir sur ses pas.",
        "key_line_en": "The route imposes so strict an order of visit that you cannot retrace your steps.",
        "vocabulary": [
            {"term": "un parcours", "gloss": "a route, itinerary"},
            {"term": "revenir sur ses pas", "gloss": "to retrace one's steps"},
            {"term": "rapprocher", "gloss": "to bring together, compare"},
            {"term": "une toile", "gloss": "a canvas, painting"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "topic": "Sciences & technologies",
        "text": "On présente souvent le cerveau comme un ordinateur, image commode et trompeuse.\nUn ordinateur sépare la mémoire du calcul ; le cerveau ne les distingue pas : se souvenir y modifie ce dont on se souvient. La comparaison éclaire une machine et masque un organe.",
        "question_fr": "Pourquoi l'auteur juge-t-il la comparaison trompeuse ?",
        "options": [
            {"id": "a", "text": "Parce que le cerveau est plus rapide",
             "explanation": "Speed is not part of the argument."},
            {"id": "b", "text": "Parce que les ordinateurs sont trop récents",
             "explanation": "The age of the technology is irrelevant to the objection."},
            {"id": "c", "text": "Parce que le souvenir y transforme ce qui est stocké",
             "explanation": "The brain does not separate memory from processing: « se souvenir y modifie ce dont on se souvient »."},
            {"id": "d", "text": "Parce que le cerveau ne calcule pas",
             "explanation": "It is not said not to compute — the point is that computing and remembering are not separate in it."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le cerveau ne les distingue pas : se souvenir y modifie ce dont on se souvient.",
        "key_line_en": "The brain does not separate them: remembering alters what is remembered.",
        "vocabulary": [
            {"term": "commode", "gloss": "convenient"},
            {"term": "trompeur", "gloss": "misleading"},
            {"term": "masquer", "gloss": "to hide, obscure"},
            {"term": "un organe", "gloss": "an organ"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "topic": "Travail & emploi",
        "text": "Bonjour à tous,\nÀ compter de lundi, les messages envoyés après 19 h seront livrés le lendemain matin.\nIl ne s'agit pas d'interdire de travailler tard : chacun garde sa liberté. Il s'agit d'éviter qu'un message envoyé à 22 h en produise trois autres avant minuit.",
        "question_fr": "Quel est le but de cette mesure ?",
        "options": [
            {"id": "a", "text": "Interdire le travail en soirée",
             "explanation": "« Il ne s'agit pas d'interdire de travailler tard : chacun garde sa liberté »."},
            {"id": "b", "text": "Réduire le nombre total de messages",
             "explanation": "Volume as such is not the target; the chain reaction at night is."},
            {"id": "c", "text": "Surveiller les horaires des salariés",
             "explanation": "No monitoring is introduced; delivery is simply deferred."},
            {"id": "d", "text": "Empêcher qu'un message tardif en déclenche d'autres",
             "explanation": "« éviter qu'un message envoyé à 22 h en produise trois autres avant minuit »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Il s'agit d'éviter qu'un message envoyé à 22 h en produise trois autres avant minuit.",
        "key_line_en": "The aim is to stop one message sent at 10 p.m. producing three more before midnight.",
        "vocabulary": [
            {"term": "à compter de", "gloss": "as from"},
            {"term": "livrer", "gloss": "to deliver"},
            {"term": "le lendemain", "gloss": "the next day"},
            {"term": "il s'agit de", "gloss": "the point is to"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Analyse économique / Economic analysis",
        "topic": "Alimentation & consommation",
        "text": "Le prix payé au producteur représente en moyenne un cinquième du prix en rayon.\nLe reste se répartit entre transformation, transport et distribution, dont les marges sont connues. Ce n'est donc pas l'agriculteur qui fixe le prix du panier, ni lui qui en profite quand il monte.",
        "question_fr": "Que conclut l'auteur ?",
        "options": [
            {"id": "a", "text": "Les agriculteurs ne bénéficient pas des hausses de prix",
             "explanation": "They take a fifth and set nothing: « ni lui qui en profite quand il monte »."},
            {"id": "b", "text": "Les prix en magasin sont trop bas",
             "explanation": "The level of shelf prices is not judged; their distribution is."},
            {"id": "c", "text": "La distribution travaille à perte",
             "explanation": "Its margins are described as known, not as negative."},
            {"id": "d", "text": "Les consommateurs paient au juste prix",
             "explanation": "No verdict on fairness to consumers is offered."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce n'est donc pas l'agriculteur qui fixe le prix du panier, ni lui qui en profite quand il monte.",
        "key_line_en": "So it is not the farmer who sets the price of the basket, nor the farmer who gains when it rises.",
        "vocabulary": [
            {"term": "en rayon", "gloss": "on the shelf"},
            {"term": "une marge", "gloss": "a margin"},
            {"term": "se répartir", "gloss": "to be shared out"},
            {"term": "fixer un prix", "gloss": "to set a price"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article société / Society article",
        "topic": "Société, citoyenneté & administration",
        "text": "Dématérialiser les démarches a fait gagner du temps à la majorité et a exclu une minorité.\nCe n'est pas un mauvais calcul, c'est un calcul incomplet : on a compté les heures économisées par ceux qui savent faire, jamais celles perdues par ceux qui renoncent.",
        "question_fr": "Que reproche l'auteur à cette évaluation ?",
        "options": [
            {"id": "a", "text": "Elle ignore ceux qui abandonnent leurs démarches",
             "explanation": "Hours saved were counted, « jamais celles perdues par ceux qui renoncent »."},
            {"id": "b", "text": "Elle surestime le temps gagné",
             "explanation": "The time saved is not disputed; what is missing is the other side of the ledger."},
            {"id": "c", "text": "Elle conclut que la réforme est mauvaise",
             "explanation": "« Ce n'est pas un mauvais calcul » — the author does not condemn the reform itself."},
            {"id": "d", "text": "Elle repose sur trop peu de données",
             "explanation": "The volume of data is not questioned; its scope is."},
        ],
        "correct_answer": "a",
        "key_line_fr": "On a compté les heures économisées par ceux qui savent faire, jamais celles perdues par ceux qui renoncent.",
        "key_line_en": "The hours saved by those who can manage were counted, never those lost by those who give up.",
        "vocabulary": [
            {"term": "dématérialiser", "gloss": "to move online"},
            {"term": "exclure", "gloss": "to exclude"},
            {"term": "renoncer", "gloss": "to give up"},
            {"term": "incomplet", "gloss": "incomplete"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "topic": "Société, citoyenneté & administration",
        "text": "La simplicité coûte cher. Il est facile d'écrire une règle longue, difficile d'en écrire une courte qui tienne.\nAussi préfère-t-on ajouter des exceptions plutôt que reprendre le principe : chacune paraît raisonnable, et leur somme rend le texte illisible à ceux qu'il concerne.",
        "question_fr": "Comment l'auteur explique-t-il la complexité des règles ?",
        "options": [
            {"id": "a", "text": "Par l'incompétence de ceux qui les rédigent",
             "explanation": "No incompetence is alleged; the pressure described is structural, and simplicity is called genuinely hard."},
            {"id": "b", "text": "Par l'accumulation d'exceptions raisonnables une à une",
             "explanation": "Each seems sensible on its own, « et leur somme rend le texte illisible »."},
            {"id": "c", "text": "Par le manque de temps des législateurs",
             "explanation": "Time pressure is never mentioned."},
            {"id": "d", "text": "Par la volonté de tromper les citoyens",
             "explanation": "No intent to deceive is attributed to anyone."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Chacune paraît raisonnable, et leur somme rend le texte illisible à ceux qu'il concerne.",
        "key_line_en": "Each one looks reasonable, and together they make the text unreadable to the people it applies to.",
        "vocabulary": [
            {"term": "tenir", "gloss": "to hold up, stand"},
            {"term": "reprendre", "gloss": "to rework, revisit"},
            {"term": "une exception", "gloss": "an exception"},
            {"term": "illisible", "gloss": "unreadable"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "topic": "Travail & emploi",
        "text": "La direction a supprimé les évaluations annuelles, jugées anxiogènes, et les a remplacées par des « points de progression » trimestriels.\nOn passe donc d'un entretien redouté par an à quatre, ce qui constitue, à n'en pas douter, une nette amélioration du bien-être.",
        "question_fr": "Que suggère l'auteur ?",
        "options": [
            {"id": "a", "text": "Que la réforme aggrave ce qu'elle voulait résoudre",
             "explanation": "One dreaded interview a year became four; the closing praise is ironic."},
            {"id": "b", "text": "Que les évaluations annuelles étaient utiles",
             "explanation": "He does not defend the old system either — his target is the swap."},
            {"id": "c", "text": "Que le bien-être des salariés s'est amélioré",
             "explanation": "Read literally, yes; but « à n'en pas douter » sits on a fact that contradicts it."},
            {"id": "d", "text": "Que les entretiens devraient être supprimés",
             "explanation": "No such proposal is made."},
        ],
        "correct_answer": "a",
        "key_line_fr": "On passe donc d'un entretien redouté par an à quatre.",
        "key_line_en": "So we go from one dreaded interview a year to four.",
        "vocabulary": [
            {"term": "anxiogène", "gloss": "anxiety-inducing"},
            {"term": "redouter", "gloss": "to dread"},
            {"term": "à n'en pas douter", "gloss": "doubtless"},
            {"term": "trimestriel", "gloss": "quarterly"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "topic": "Vie quotidienne & logement",
        "text": "On construit des logements de plus en plus petits pour des ménages de plus en plus réduits, et l'on croit répondre à la demande.\nOn oublie qu'un ménage change : le studio qui convient à vingt-cinq ans ne convient plus à trente-cinq, et le parc, lui, reste tel qu'on l'a bâti.",
        "question_fr": "Quelle objection l'auteur formule-t-il ?",
        "options": [
            {"id": "a", "text": "Les logements construits sont trop chers",
             "explanation": "Price is never mentioned."},
            {"id": "b", "text": "Les ménages ne se réduisent pas réellement",
             "explanation": "The trend is granted; what is contested is treating it as fixed."},
            {"id": "c", "text": "Les logements se dégradent trop vite",
             "explanation": "Building quality and ageing are not discussed."},
            {"id": "d", "text": "On bâtit pour un instantané, alors que les besoins évoluent",
             "explanation": "The studio that suits at 25 does not at 35, « et le parc, lui, reste tel qu'on l'a bâti »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Le studio qui convient à vingt-cinq ans ne convient plus à trente-cinq, et le parc, lui, reste tel qu'on l'a bâti.",
        "key_line_en": "The studio that suits at twenty-five no longer suits at thirty-five, and the housing stock stays as it was built.",
        "vocabulary": [
            {"term": "un ménage", "gloss": "a household"},
            {"term": "le parc (immobilier)", "gloss": "the housing stock"},
            {"term": "convenir", "gloss": "to suit"},
            {"term": "bâtir", "gloss": "to build"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "topic": "Loisirs, culture & médias",
        "text": "Elle avait gardé la maison telle qu'il l'avait laissée, persuadée d'honorer sa mémoire.\nCe qu'elle honorait, en vérité, c'était l'idée qu'il pourrait revenir et ne rien trouver de changé — et cette idée, elle ne l'aurait avouée à personne, pas même à elle.",
        "question_fr": "Que révèle ce passage ?",
        "options": [
            {"id": "a", "text": "Qu'elle attend un retour qu'elle ne s'avoue pas",
             "explanation": "What she honours is « l'idée qu'il pourrait revenir », an idea she would not admit even to herself."},
            {"id": "b", "text": "Qu'elle veut vendre la maison",
             "explanation": "Nothing about selling appears."},
            {"id": "c", "text": "Qu'elle a oublié le disparu",
             "explanation": "The whole passage is organised around him."},
            {"id": "d", "text": "Qu'elle honore réellement sa mémoire",
             "explanation": "« Ce qu'elle honorait, en vérité » corrects exactly this first reading."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Cette idée, elle ne l'aurait avouée à personne, pas même à elle.",
        "key_line_en": "That thought she would have admitted to no one, not even to herself.",
        "vocabulary": [
            {"term": "honorer", "gloss": "to honour"},
            {"term": "en vérité", "gloss": "in truth"},
            {"term": "avouer", "gloss": "to admit"},
            {"term": "persuadé", "gloss": "convinced"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "topic": "Sciences & technologies",
        "text": "Un résultat qui ne se reproduit pas n'est pas nécessairement faux : il peut n'avoir jamais été assez décrit pour être refait.\nLes revues exigent désormais les protocoles complets, non par méfiance envers les auteurs, mais parce qu'une méthode qu'on ne peut pas suivre ne se distingue en rien d'une méthode qui n'existe pas.",
        "question_fr": "Pourquoi les revues exigent-elles des protocoles complets ?",
        "options": [
            {"id": "a", "text": "Parce qu'elles soupçonnent les auteurs de fraude",
             "explanation": "« non par méfiance envers les auteurs » rules this out explicitly."},
            {"id": "b", "text": "Pour que les travaux puissent être refaits",
             "explanation": "A method nobody can follow « ne se distingue en rien d'une méthode qui n'existe pas »."},
            {"id": "c", "text": "Parce que les résultats sont souvent faux",
             "explanation": "The text says non-reproduction does not prove falsity."},
            {"id": "d", "text": "Pour raccourcir les articles publiés",
             "explanation": "Full protocols make articles longer, not shorter."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une méthode qu'on ne peut pas suivre ne se distingue en rien d'une méthode qui n'existe pas.",
        "key_line_en": "A method that cannot be followed is indistinguishable from a method that does not exist.",
        "vocabulary": [
            {"term": "se reproduire", "gloss": "to be reproduced"},
            {"term": "la méfiance", "gloss": "mistrust"},
            {"term": "un protocole", "gloss": "a protocol, method"},
            {"term": "se distinguer de", "gloss": "to differ from"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Commentaire institutionnel / Institutional commentary",
        "topic": "Santé & bien-être",
        "text": "Le plan annonce un objectif chiffré — réduire les délais de rendez-vous de moitié — sans indiquer par quels moyens.\nUn objectif sans moyen n'est pas un engagement : c'est un souhait auquel on a donné la forme d'un chiffre.",
        "question_fr": "Que reproche l'auteur à ce plan ?",
        "options": [
            {"id": "a", "text": "Son objectif est trop ambitieux",
             "explanation": "The level of ambition is not questioned; the absence of means is."},
            {"id": "b", "text": "Il ne fixe aucun objectif précis",
             "explanation": "It does fix one, and a quantified one at that."},
            {"id": "c", "text": "Il énonce une cible sans dire comment l'atteindre",
             "explanation": "« Un objectif sans moyen n'est pas un engagement : c'est un souhait auquel on a donné la forme d'un chiffre »."},
            {"id": "d", "text": "Il concerne trop peu de patients",
             "explanation": "The scope of the plan is not discussed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Un objectif sans moyen n'est pas un engagement : c'est un souhait auquel on a donné la forme d'un chiffre.",
        "key_line_en": "A target without means is not a commitment: it is a wish given the shape of a number.",
        "vocabulary": [
            {"term": "chiffré", "gloss": "quantified"},
            {"term": "un délai", "gloss": "a waiting time"},
            {"term": "un engagement", "gloss": "a commitment"},
            {"term": "un souhait", "gloss": "a wish"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse environnementale / Environmental analysis",
        "topic": "Environnement & nature",
        "text": "Planter des arbres est devenu le geste écologique par excellence, parce qu'il se photographie bien.\nUne forêt plantée met quarante ans à stocker ce qu'une forêt ancienne détruite libère en une saison. Protéger ce qui existe n'a pas la même valeur symbolique, ni la même urgence apparente.",
        "question_fr": "Quelle est la thèse de l'auteur ?",
        "options": [
            {"id": "a", "text": "Il faut planter davantage d'arbres",
             "explanation": "Planting is presented as the visible gesture that displaces the more urgent one."},
            {"id": "b", "text": "Les forêts anciennes stockent peu de carbone",
             "explanation": "The reverse: destroying one releases in a season what a plantation takes forty years to store."},
            {"id": "c", "text": "La protection de l'existant est plus efficace mais moins visible",
             "explanation": "The time asymmetry makes protection more urgent, yet it lacks « la même valeur symbolique »."},
            {"id": "d", "text": "La photographie nuit à l'écologie",
             "explanation": "Photogenic appeal explains the preference; it is not itself the harm."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une forêt plantée met quarante ans à stocker ce qu'une forêt ancienne détruite libère en une saison.",
        "key_line_en": "A planted forest takes forty years to store what a destroyed old forest releases in one season.",
        "vocabulary": [
            {"term": "par excellence", "gloss": "par excellence, the definitive"},
            {"term": "stocker", "gloss": "to store"},
            {"term": "libérer", "gloss": "to release"},
            {"term": "apparent", "gloss": "apparent, seeming"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la lecture / Essay on reading",
        "topic": "Loisirs, culture & médias",
        "text": "Un livre difficile ne demande pas plus d'intelligence, il demande plus de patience — c'est-à-dire l'acceptation de ne pas comprendre tout de suite.\nNotre époque n'a pas perdu la faculté de lire ; elle a perdu le goût de rester un moment dans l'obscurité sans conclure.",
        "question_fr": "Que défend l'auteur ?",
        "options": [
            {"id": "a", "text": "Que les livres difficiles sont réservés à quelques-uns",
             "explanation": "The opposite: what they require is patience, not exceptional intelligence."},
            {"id": "b", "text": "Que la difficulté demande une tolérance à l'incompréhension",
             "explanation": "« l'acceptation de ne pas comprendre tout de suite », lost as « le goût de rester […] dans l'obscurité sans conclure »."},
            {"id": "c", "text": "Que nous lisons moins bien qu'avant",
             "explanation": "« Notre époque n'a pas perdu la faculté de lire » — the skill is intact."},
            {"id": "d", "text": "Qu'il faut écrire des livres plus clairs",
             "explanation": "No recommendation to authors is made."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Elle a perdu le goût de rester un moment dans l'obscurité sans conclure.",
        "key_line_en": "It has lost the taste for staying a while in the dark without concluding.",
        "vocabulary": [
            {"term": "une faculté", "gloss": "a capacity, faculty"},
            {"term": "l'obscurité", "gloss": "darkness, obscurity"},
            {"term": "conclure", "gloss": "to conclude"},
            {"term": "le goût de", "gloss": "the taste for"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "topic": "Société, citoyenneté & administration",
        "text": "On confond volontiers l'égalité et l'identité de traitement. Servir le même repas à tous n'est équitable que si tous ont la même faim.\nUne règle uniforme appliquée à des situations inégales ne corrige pas l'écart : elle le reconduit, avec la bonne conscience en plus.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Il faut supprimer toutes les règles communes",
             "explanation": "No abolition is proposed; what is criticised is applying one rule blindly."},
            {"id": "b", "text": "L'égalité de traitement suffit à l'équité",
             "explanation": "The meal analogy is built to deny exactly this."},
            {"id": "c", "text": "Traiter identiquement des situations inégales perpétue l'écart",
             "explanation": "« elle le reconduit, avec la bonne conscience en plus »."},
            {"id": "d", "text": "Les inégalités sont impossibles à mesurer",
             "explanation": "Measurement is not discussed anywhere."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une règle uniforme appliquée à des situations inégales ne corrige pas l'écart : elle le reconduit.",
        "key_line_en": "A uniform rule applied to unequal situations does not correct the gap: it perpetuates it.",
        "vocabulary": [
            {"term": "équitable", "gloss": "fair, equitable"},
            {"term": "reconduire", "gloss": "to renew, carry forward"},
            {"term": "la bonne conscience", "gloss": "a clear conscience"},
            {"term": "uniforme", "gloss": "uniform"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Critique de cinéma / Film review",
        "topic": "Loisirs, culture & médias",
        "text": "Le film explique ses personnages à mesure qu'il les montre, comme s'il craignait qu'on lui échappe.\nOn sort en ayant tout compris et rien deviné, ce qui est la seule manière de sortir d'un film sans l'emporter avec soi.",
        "question_fr": "Que reproche le critique au film ?",
        "options": [
            {"id": "a", "text": "Il ne laisse rien à interpréter au spectateur",
             "explanation": "Everything is explained as it is shown: « tout compris et rien deviné », so nothing stays with the viewer."},
            {"id": "b", "text": "Ses personnages sont incompréhensibles",
             "explanation": "They are over-explained, not obscure."},
            {"id": "c", "text": "L'histoire est trop longue",
             "explanation": "Length is not discussed."},
            {"id": "d", "text": "Le film manque d'explications",
             "explanation": "The exact opposite of what the review describes."},
        ],
        "correct_answer": "a",
        "key_line_fr": "On sort en ayant tout compris et rien deviné.",
        "key_line_en": "You leave having understood everything and guessed nothing.",
        "vocabulary": [
            {"term": "à mesure que", "gloss": "as, at the same time as"},
            {"term": "échapper à", "gloss": "to escape, elude"},
            {"term": "deviner", "gloss": "to guess, work out"},
            {"term": "emporter", "gloss": "to take away with one"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "topic": "Sciences & technologies",
        "text": "Une objection sérieuse ne consiste pas à montrer qu'une thèse est fausse, mais à indiquer sous quelles conditions elle cesserait d'être vraie.\nLa première ferme la discussion, la seconde l'organise. C'est pourquoi les meilleurs contradicteurs rendent leurs adversaires plus précis.",
        "question_fr": "Pourquoi la seconde forme d'objection est-elle supérieure ?",
        "options": [
            {"id": "a", "text": "Parce qu'elle est plus polie",
             "explanation": "Tone is not what the argument turns on."},
            {"id": "b", "text": "Parce qu'elle évite le conflit",
             "explanation": "It organises disagreement rather than avoiding it."},
            {"id": "c", "text": "Parce qu'elle est plus rapide à formuler",
             "explanation": "Ease of formulation is never mentioned."},
            {"id": "d", "text": "Parce qu'elle oblige à préciser la thèse",
             "explanation": "It opens discussion rather than closing it: « les meilleurs contradicteurs rendent leurs adversaires plus précis »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Les meilleurs contradicteurs rendent leurs adversaires plus précis.",
        "key_line_en": "The best opponents make their adversaries more precise.",
        "vocabulary": [
            {"term": "une thèse", "gloss": "a claim, thesis"},
            {"term": "cesser de", "gloss": "to stop being"},
            {"term": "un contradicteur", "gloss": "an opponent in debate"},
            {"term": "organiser", "gloss": "to structure"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "topic": "Transports & voyages",
        "text": "On a mesuré le temps de trajet, jamais ce qu'il contient. Vingt minutes debout dans un couloir bondé et vingt minutes assis près d'une fenêtre portent le même nom et ne sont pas la même chose.\nCe que l'usager appelle un mauvais réseau, l'ingénieur le lit comme une durée conforme.",
        "question_fr": "Quel écart l'auteur décrit-il ?",
        "options": [
            {"id": "a", "text": "Entre la durée mesurée et l'expérience vécue",
             "explanation": "Twenty minutes standing and twenty seated « portent le même nom et ne sont pas la même chose »; the engineer sees a conforming duration where the user feels a bad network."},
            {"id": "b", "text": "Entre les trajets courts et les trajets longs",
             "explanation": "Both examples last twenty minutes; length is held constant on purpose."},
            {"id": "c", "text": "Entre les usagers et les conducteurs",
             "explanation": "The contrast is between users and engineers, and it is about measurement."},
            {"id": "d", "text": "Entre les réseaux anciens et récents",
             "explanation": "No comparison of eras appears."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce que l'usager appelle un mauvais réseau, l'ingénieur le lit comme une durée conforme.",
        "key_line_en": "What the passenger calls a bad network, the engineer reads as a compliant journey time.",
        "vocabulary": [
            {"term": "bondé", "gloss": "packed, crowded"},
            {"term": "conforme", "gloss": "compliant, within target"},
            {"term": "un usager", "gloss": "a user, passenger"},
            {"term": "porter le même nom", "gloss": "to go by the same name"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur l'habitude / Essay on habit",
        "topic": "Vie quotidienne & logement",
        "text": "L'habitude a mauvaise presse : on lui reproche d'endormir. C'est confondre son coût et son office.\nEn déchargeant l'attention de ce qui doit être refait chaque jour, elle libère précisément la part d'esprit sans laquelle rien de neuf ne serait pensé. Ce qui nous répète nous rend disponibles.",
        "question_fr": "Quelle réhabilitation l'auteur propose-t-il ?",
        "options": [
            {"id": "a", "text": "L'habitude libère l'esprit pour autre chose",
             "explanation": "By offloading what must be redone daily, it frees « la part d'esprit sans laquelle rien de neuf ne serait pensé »."},
            {"id": "b", "text": "L'habitude est sans inconvénient",
             "explanation": "The text distinguishes its « coût » from its « office » — the cost is granted."},
            {"id": "c", "text": "L'habitude remplace la réflexion",
             "explanation": "It makes reflection possible rather than substituting for it."},
            {"id": "d", "text": "L'habitude endort l'attention",
             "explanation": "That is the received criticism the essay sets out to correct."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce qui nous répète nous rend disponibles.",
        "key_line_en": "What repeats us makes us available.",
        "vocabulary": [
            {"term": "avoir mauvaise presse", "gloss": "to have a bad reputation"},
            {"term": "l'office", "gloss": "the function, role"},
            {"term": "décharger", "gloss": "to relieve, unburden"},
            {"term": "disponible", "gloss": "available, free"},
        ],
    },
]

QUESTIONS = balance(_RAW)
