"""Compréhension écrite — Test 07.

Forty questions climbing A1 → C2. Profile A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Mot / Note",
        "topic": "Vie quotidienne & logement",
        "text": "Bonjour,\nJe suis passé pour relever le compteur d'eau. Personne n'était là.\nMerci de m'appeler au 06 12 34 56 78.\nLe technicien",
        "question_fr": "Pourquoi le technicien laisse-t-il ce mot ?",
        "options": [
            {"id": "a", "text": "Pour donner le montant de la facture",
             "explanation": "No amount or bill is mentioned."},
            {"id": "b", "text": "Parce qu'il n'a pas pu entrer",
             "explanation": "« Personne n'était là » — he came to read the meter and found nobody in, so he asks to be called."},
            {"id": "c", "text": "Pour annoncer une coupure d'eau",
             "explanation": "No cut is announced; he came to take a reading."},
            {"id": "d", "text": "Pour proposer un abonnement",
             "explanation": "Nothing is being sold."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Je suis passé pour relever le compteur d'eau. Personne n'était là.",
        "key_line_en": "I came to read the water meter. Nobody was in.",
        "vocabulary": [
            {"term": "relever un compteur", "gloss": "to read a meter"},
            {"term": "passer", "gloss": "to call round"},
            {"term": "personne", "gloss": "nobody"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Étiquette de prix / Price label",
        "topic": "Alimentation & consommation",
        "text": "POMMES\n2,50 € le kilo\nPromotion : 2 kilos pour 4 €\nOrigine : France",
        "question_fr": "Combien coûtent deux kilos de pommes ?",
        "options": [
            {"id": "a", "text": "2,50 €",
             "explanation": "That is the price of one kilo."},
            {"id": "b", "text": "5 €",
             "explanation": "That would be two kilos at full price; the offer is cheaper."},
            {"id": "c", "text": "4 €",
             "explanation": "« Promotion : 2 kilos pour 4 € »."},
            {"id": "d", "text": "2 €",
             "explanation": "2 is the number of kilos, not a price."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Promotion : 2 kilos pour 4 €.",
        "key_line_en": "Special offer: 2 kilos for €4.",
        "vocabulary": [
            {"term": "une promotion", "gloss": "a special offer"},
            {"term": "l'origine", "gloss": "country of origin"},
            {"term": "le kilo", "gloss": "the kilo"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Annonce sonore / Announcement",
        "topic": "Transports & voyages",
        "text": "Le train à destination de Lille partira voie 7, et non voie 4.\nDépart à 14 h 20.\nNous vous remercions de votre compréhension.",
        "question_fr": "Quel est le changement annoncé ?",
        "options": [
            {"id": "a", "text": "La voie de départ",
             "explanation": "« voie 7, et non voie 4 » — the platform has changed."},
            {"id": "b", "text": "L'heure du départ",
             "explanation": "The time is given once, with no change: 14 h 20."},
            {"id": "c", "text": "La destination",
             "explanation": "The train still goes to Lille."},
            {"id": "d", "text": "Le prix du billet",
             "explanation": "No price is mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le train à destination de Lille partira voie 7, et non voie 4.",
        "key_line_en": "The train to Lille will leave from platform 7, not platform 4.",
        "vocabulary": [
            {"term": "une voie", "gloss": "a platform, track"},
            {"term": "à destination de", "gloss": "bound for"},
            {"term": "le départ", "gloss": "departure"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Affiche / Poster",
        "topic": "Loisirs, culture & médias",
        "text": "FÊTE DU QUARTIER\nDimanche 12 juin, de 11 h à 18 h.\nJeux pour les enfants, musique, repas partagé.\nApportez un plat à partager !",
        "question_fr": "Que demande-t-on aux participants ?",
        "options": [
            {"id": "a", "text": "De payer l'entrée",
             "explanation": "No admission charge is mentioned."},
            {"id": "b", "text": "De s'inscrire",
             "explanation": "No registration is asked for."},
            {"id": "c", "text": "De venir avec un instrument",
             "explanation": "There is music, but nobody is asked to bring an instrument."},
            {"id": "d", "text": "D'apporter à manger",
             "explanation": "« Apportez un plat à partager ! »"},
        ],
        "correct_answer": "d",
        "key_line_fr": "Apportez un plat à partager !",
        "key_line_en": "Bring a dish to share!",
        "vocabulary": [
            {"term": "un plat", "gloss": "a dish"},
            {"term": "partager", "gloss": "to share"},
            {"term": "un quartier", "gloss": "a neighbourhood"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Consigne / Instruction",
        "topic": "Santé & bien-être",
        "text": "PHARMACIE\nUne personne à la fois au comptoir.\nMerci de garder vos distances.\nLes ordonnances peuvent être déposées le matin et récupérées l'après-midi.",
        "question_fr": "Quand peut-on récupérer une ordonnance ?",
        "options": [
            {"id": "a", "text": "L'après-midi",
             "explanation": "« déposées le matin et récupérées l'après-midi »."},
            {"id": "b", "text": "Le matin",
             "explanation": "The morning is when prescriptions are handed in."},
            {"id": "c", "text": "À tout moment",
             "explanation": "The notice sets two distinct times."},
            {"id": "d", "text": "Le lendemain",
             "explanation": "No next-day arrangement is mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les ordonnances peuvent être déposées le matin et récupérées l'après-midi.",
        "key_line_en": "Prescriptions can be handed in during the morning and collected in the afternoon.",
        "vocabulary": [
            {"term": "un comptoir", "gloss": "a counter"},
            {"term": "déposer", "gloss": "to hand in"},
            {"term": "récupérer", "gloss": "to collect"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Panneau / Sign",
        "topic": "Société, citoyenneté & administration",
        "text": "MAIRIE\nOuverte du lundi au vendredi, de 8 h 30 à 16 h.\nFermée entre 12 h et 13 h 30.\nService des passeports : sur rendez-vous.",
        "question_fr": "Que faut-il pour le service des passeports ?",
        "options": [
            {"id": "a", "text": "Venir avant midi",
             "explanation": "The midday closure applies to the whole town hall, and passports need an appointment anyway."},
            {"id": "b", "text": "Un rendez-vous",
             "explanation": "« Service des passeports : sur rendez-vous »."},
            {"id": "c", "text": "Une photo d'identité",
             "explanation": "No document requirement is listed on this sign."},
            {"id": "d", "text": "Rien de particulier",
             "explanation": "An appointment is specifically required."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Service des passeports : sur rendez-vous.",
        "key_line_en": "Passport service: by appointment only.",
        "vocabulary": [
            {"term": "sur rendez-vous", "gloss": "by appointment"},
            {"term": "la mairie", "gloss": "the town hall"},
            {"term": "fermé", "gloss": "closed"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Offre d'emploi / Job advert",
        "topic": "Travail & emploi",
        "text": "AIDE À DOMICILE (H/F)\nInterventions chez des personnes âgées, dans un rayon de dix kilomètres.\nLe permis de conduire et un véhicule sont indispensables : les frais de déplacement sont remboursés.\nTemps partiel, évolutif vers un temps plein.",
        "question_fr": "Quelle est la condition indispensable ?",
        "options": [
            {"id": "a", "text": "Accepter un temps plein",
             "explanation": "The post starts part-time and may grow; full time is not required."},
            {"id": "b", "text": "Avoir une expérience du métier",
             "explanation": "No experience requirement appears."},
            {"id": "c", "text": "Habiter à dix kilomètres",
             "explanation": "Ten kilometres is the radius of the visits, not a residence rule."},
            {"id": "d", "text": "Avoir le permis et une voiture",
             "explanation": "« Le permis de conduire et un véhicule sont indispensables »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Le permis de conduire et un véhicule sont indispensables.",
        "key_line_en": "A driving licence and a vehicle are essential.",
        "vocabulary": [
            {"term": "une aide à domicile", "gloss": "a home carer"},
            {"term": "un rayon", "gloss": "a radius"},
            {"term": "les frais de déplacement", "gloss": "travel expenses"},
            {"term": "évolutif", "gloss": "with scope to develop"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information scolaire / School information",
        "topic": "Études & formation",
        "text": "SORTIE SCOLAIRE\nLes élèves de 3e visiteront le musée jeudi.\nLe départ se fait du collège à 8 h : les retardataires ne seront pas attendus.\nAutorisation parentale à rendre avant mardi soir.",
        "question_fr": "Que se passe-t-il si un élève arrive en retard ?",
        "options": [
            {"id": "a", "text": "Il part avec un autre groupe",
             "explanation": "No second group exists."},
            {"id": "b", "text": "Il rejoint le musée seul",
             "explanation": "Nothing of the kind is offered."},
            {"id": "c", "text": "Le car ne l'attend pas",
             "explanation": "« les retardataires ne seront pas attendus »."},
            {"id": "d", "text": "Il doit rendre une autorisation",
             "explanation": "The parental form is due Tuesday, unrelated to lateness on the day."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Les retardataires ne seront pas attendus.",
        "key_line_en": "Latecomers will not be waited for.",
        "vocabulary": [
            {"term": "un retardataire", "gloss": "a latecomer"},
            {"term": "une autorisation parentale", "gloss": "a parental consent form"},
            {"term": "rendre", "gloss": "to hand in"},
            {"term": "une sortie scolaire", "gloss": "a school trip"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Message de service / Service message",
        "topic": "Sciences & technologies",
        "text": "Votre commande a été expédiée.\nElle sera livrée entre le 4 et le 6 mai, sans signature.\nSi vous êtes absent, le colis sera déposé chez le gardien.\nSuivez votre livraison avec le numéro indiqué dans le courriel.",
        "question_fr": "Que se passe-t-il en cas d'absence ?",
        "options": [
            {"id": "a", "text": "Le colis est laissé chez le gardien",
             "explanation": "« Si vous êtes absent, le colis sera déposé chez le gardien »."},
            {"id": "b", "text": "Le colis repart à l'expéditeur",
             "explanation": "No return is mentioned; a fallback delivery point is given."},
            {"id": "c", "text": "Il faut signer plus tard",
             "explanation": "The delivery is « sans signature » — no signature at all."},
            {"id": "d", "text": "La livraison est annulée",
             "explanation": "It goes ahead, just to the caretaker."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Si vous êtes absent, le colis sera déposé chez le gardien.",
        "key_line_en": "If you are out, the parcel will be left with the caretaker.",
        "vocabulary": [
            {"term": "expédier", "gloss": "to dispatch"},
            {"term": "un gardien", "gloss": "a caretaker, concierge"},
            {"term": "une livraison", "gloss": "a delivery"},
            {"term": "suivre", "gloss": "to track"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Petite annonce / Classified ad",
        "topic": "Vie quotidienne & logement",
        "text": "ÉCHANGE DE MAISON\nJe propose ma maison en Bretagne (4 personnes, jardin) contre un appartement à Paris, deux semaines en août.\nPas d'argent échangé : chacun paie ses propres charges.\nNon-fumeurs, sans animaux.",
        "question_fr": "Comment fonctionne cet échange ?",
        "options": [
            {"id": "a", "text": "Chacun paie un loyer à l'autre",
             "explanation": "« Pas d'argent échangé » — nothing is paid between them."},
            {"id": "b", "text": "Personne ne paie rien",
             "explanation": "Each still pays their own bills."},
            {"id": "c", "text": "Chacun règle ses propres frais",
             "explanation": "« chacun paie ses propres charges » — no rent, but own utilities."},
            {"id": "d", "text": "L'un des deux paie la différence",
             "explanation": "No balancing payment is mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Pas d'argent échangé : chacun paie ses propres charges.",
        "key_line_en": "No money changes hands: each pays their own bills.",
        "vocabulary": [
            {"term": "un échange", "gloss": "a swap"},
            {"term": "les charges", "gloss": "utility bills"},
            {"term": "propre", "gloss": "own"},
            {"term": "un animal", "gloss": "a pet, animal"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Conditions / Terms",
        "topic": "Transports & voyages",
        "text": "LOCATION DE VOITURE\nLe véhicule est fourni avec le plein ; il doit être rendu plein.\nÀ défaut, le carburant manquant est facturé, majoré de 25 € de frais de service.\nLe conducteur doit avoir plus de 21 ans et le permis depuis un an.",
        "question_fr": "Que paie un client qui rend la voiture sans faire le plein ?",
        "options": [
            {"id": "a", "text": "Seulement le carburant manquant",
             "explanation": "A service fee is added on top."},
            {"id": "b", "text": "Rien, le plein est compris",
             "explanation": "The car is given full and must come back full."},
            {"id": "c", "text": "Seulement 25 €",
             "explanation": "The €25 comes in addition to the missing fuel."},
            {"id": "d", "text": "Le carburant et 25 € de frais",
             "explanation": "« le carburant manquant est facturé, majoré de 25 € de frais de service »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Le carburant manquant est facturé, majoré de 25 € de frais de service.",
        "key_line_en": "The missing fuel is charged for, plus a €25 service fee.",
        "vocabulary": [
            {"term": "le plein", "gloss": "a full tank"},
            {"term": "à défaut", "gloss": "failing that"},
            {"term": "majoré de", "gloss": "increased by"},
            {"term": "le carburant", "gloss": "fuel"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Affichage magasin / Shop notice",
        "topic": "Alimentation & consommation",
        "text": "RETOUR ET ÉCHANGE\nLes produits frais ne sont ni repris ni échangés.\nLes autres articles peuvent être rapportés sous quinze jours, avec le ticket de caisse.\nL'échange se fait au prix payé, non au prix du jour.",
        "question_fr": "Quels produits ne peuvent pas être rapportés ?",
        "options": [
            {"id": "a", "text": "Ceux achetés il y a moins de quinze jours",
             "explanation": "Fifteen days is the window in which returns are allowed."},
            {"id": "b", "text": "Les produits frais",
             "explanation": "« Les produits frais ne sont ni repris ni échangés »."},
            {"id": "c", "text": "Ceux dont le prix a changé",
             "explanation": "A price change only affects the value of the exchange, not the right to return."},
            {"id": "d", "text": "Ceux payés en espèces",
             "explanation": "The means of payment is never mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les produits frais ne sont ni repris ni échangés.",
        "key_line_en": "Fresh products can be neither returned nor exchanged.",
        "vocabulary": [
            {"term": "reprendre", "gloss": "to take back"},
            {"term": "un ticket de caisse", "gloss": "a receipt"},
            {"term": "rapporter", "gloss": "to bring back"},
            {"term": "le prix du jour", "gloss": "today's price"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information municipale / Council notice",
        "topic": "Environnement & nature",
        "text": "DÉCHETTERIE\nOuverte du mardi au samedi, de 9 h à 17 h.\nAccès réservé aux habitants de la commune, sur présentation d'un justificatif de domicile.\nLes déchets doivent être triés avant l'arrivée : aucun tri n'est possible sur place.",
        "question_fr": "Que faut-il faire avant de venir ?",
        "options": [
            {"id": "a", "text": "Trier ses déchets",
             "explanation": "« Les déchets doivent être triés avant l'arrivée : aucun tri n'est possible sur place »."},
            {"id": "b", "text": "Prendre rendez-vous",
             "explanation": "No appointment is required; only opening hours apply."},
            {"id": "c", "text": "Payer une contribution",
             "explanation": "No charge is mentioned."},
            {"id": "d", "text": "Demander une autorisation",
             "explanation": "Proof of address is enough; no permit is issued."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les déchets doivent être triés avant l'arrivée : aucun tri n'est possible sur place.",
        "key_line_en": "Waste must be sorted before you arrive: no sorting is possible on site.",
        "vocabulary": [
            {"term": "une déchetterie", "gloss": "a recycling centre"},
            {"term": "un justificatif de domicile", "gloss": "proof of address"},
            {"term": "trier", "gloss": "to sort"},
            {"term": "sur place", "gloss": "on site"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Chronique santé / Health column",
        "topic": "Santé & bien-être",
        "text": "Le petit-déjeuner n'est pas le repas le plus important de la journée : cette formule vient d'une campagne publicitaire des années trente.\nCe qui compte est la régularité des repas, quel que soit leur nombre. Sauter le petit-déjeuner ne pose problème que si l'on compense par des grignotages.",
        "question_fr": "Que retient l'auteur comme facteur important ?",
        "options": [
            {"id": "a", "text": "La régularité des repas",
             "explanation": "« Ce qui compte est la régularité des repas, quel que soit leur nombre »."},
            {"id": "b", "text": "La prise d'un petit-déjeuner",
             "explanation": "Its special status is presented as an advertising invention."},
            {"id": "c", "text": "Le nombre de repas quotidiens",
             "explanation": "« quel que soit leur nombre » — the number is explicitly set aside."},
            {"id": "d", "text": "La suppression des grignotages",
             "explanation": "Snacking matters only as a consequence of skipping, not as the main factor."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce qui compte est la régularité des repas, quel que soit leur nombre.",
        "key_line_en": "What matters is the regularity of meals, whatever their number.",
        "vocabulary": [
            {"term": "sauter un repas", "gloss": "to skip a meal"},
            {"term": "le grignotage", "gloss": "snacking"},
            {"term": "compenser", "gloss": "to make up for"},
            {"term": "quel que soit", "gloss": "whatever"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "topic": "Travail & emploi",
        "text": "Un salarié sur trois déclare avoir refusé une promotion au moins une fois.\nLe motif le plus cité n'est pas le salaire, jugé satisfaisant, mais la crainte de perdre le contact avec le métier au profit de tâches de gestion.",
        "question_fr": "Pourquoi ces salariés refusent-ils une promotion ?",
        "options": [
            {"id": "a", "text": "Parce que le salaire proposé est insuffisant",
             "explanation": "Pay is described as satisfactory and explicitly not the main reason."},
            {"id": "b", "text": "Parce qu'ils manquent de compétences",
             "explanation": "Competence is never raised."},
            {"id": "c", "text": "Parce qu'ils craignent de quitter leur métier",
             "explanation": "« la crainte de perdre le contact avec le métier au profit de tâches de gestion »."},
            {"id": "d", "text": "Parce qu'ils veulent changer d'entreprise",
             "explanation": "Leaving is not mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La crainte de perdre le contact avec le métier au profit de tâches de gestion.",
        "key_line_en": "The fear of losing touch with the job itself in favour of management tasks.",
        "vocabulary": [
            {"term": "une promotion", "gloss": "a promotion"},
            {"term": "une crainte", "gloss": "a fear"},
            {"term": "au profit de", "gloss": "in favour of"},
            {"term": "la gestion", "gloss": "management, administration"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Présentation de dispositif / Scheme description",
        "topic": "Études & formation",
        "text": "L'établissement prête un ordinateur portable aux élèves qui n'en ont pas.\nLe prêt court sur toute l'année scolaire et l'appareil se rend en juin. Les familles ne paient rien, mais s'engagent à signaler toute panne dans la semaine : un appareil immobilisé prive un élève, pas l'établissement.",
        "question_fr": "À quoi les familles s'engagent-elles ?",
        "options": [
            {"id": "a", "text": "À payer les réparations",
             "explanation": "« Les familles ne paient rien »."},
            {"id": "b", "text": "À rendre l'appareil chaque trimestre",
             "explanation": "The loan runs the whole year, with return in June."},
            {"id": "c", "text": "À acheter l'ordinateur en fin d'année",
             "explanation": "The device is returned, not bought."},
            {"id": "d", "text": "À signaler rapidement une panne",
             "explanation": "« s'engagent à signaler toute panne dans la semaine »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Un appareil immobilisé prive un élève, pas l'établissement.",
        "key_line_en": "A device out of action deprives a pupil, not the school.",
        "vocabulary": [
            {"term": "un prêt", "gloss": "a loan"},
            {"term": "une panne", "gloss": "a breakdown, fault"},
            {"term": "immobilisé", "gloss": "out of action"},
            {"term": "priver", "gloss": "to deprive"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article culturel / Culture article",
        "topic": "Loisirs, culture & médias",
        "text": "Le cinéma de quartier a rouvert grâce à une souscription auprès des habitants.\nSa programmation reste modeste : deux films par semaine, choisis par une commission de bénévoles. « Nous ne concurrençons pas les grandes salles, explique la présidente. Nous montrons ce qu'elles ne montrent plus. »",
        "question_fr": "Comment la présidente définit-elle le rôle du cinéma ?",
        "options": [
            {"id": "a", "text": "Attirer le public des grandes salles",
             "explanation": "« Nous ne concurrençons pas les grandes salles » — competition is disclaimed."},
            {"id": "b", "text": "Proposer ce que les autres ne diffusent pas",
             "explanation": "« Nous montrons ce qu'elles ne montrent plus »."},
            {"id": "c", "text": "Programmer le plus de films possible",
             "explanation": "Two films a week is described as deliberately modest."},
            {"id": "d", "text": "Former des bénévoles au cinéma",
             "explanation": "Volunteers choose the films; training them is not the purpose."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nous ne concurrençons pas les grandes salles. Nous montrons ce qu'elles ne montrent plus.",
        "key_line_en": "We are not competing with the big cinemas. We show what they no longer show.",
        "vocabulary": [
            {"term": "une souscription", "gloss": "a public subscription"},
            {"term": "la programmation", "gloss": "the programme, listings"},
            {"term": "concurrencer", "gloss": "to compete with"},
            {"term": "une commission", "gloss": "a committee"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Reportage / Report",
        "topic": "Environnement & nature",
        "text": "La rivière a retrouvé ses poissons cinq ans après la destruction d'un ancien barrage.\nLes pêcheurs, d'abord opposés au projet, reconnaissent aujourd'hui l'erreur : ils craignaient de perdre un plan d'eau, ils ont gagné un cours d'eau vivant.",
        "question_fr": "Quelle a été l'évolution des pêcheurs ?",
        "options": [
            {"id": "a", "text": "Ils s'opposent toujours au projet",
             "explanation": "« reconnaissent aujourd'hui l'erreur » marks a change of mind."},
            {"id": "b", "text": "Ils ont perdu leur lieu de pêche",
             "explanation": "They lost a lake but gained a living river with fish."},
            {"id": "c", "text": "Ils ont changé d'avis après avoir vu le résultat",
             "explanation": "Initially opposed, they now admit they were wrong."},
            {"id": "d", "text": "Ils demandent la reconstruction du barrage",
             "explanation": "Nothing suggests they want it back."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ils craignaient de perdre un plan d'eau, ils ont gagné un cours d'eau vivant.",
        "key_line_en": "They feared losing a stretch of still water; they gained a living river.",
        "vocabulary": [
            {"term": "un barrage", "gloss": "a dam"},
            {"term": "un plan d'eau", "gloss": "a body of still water"},
            {"term": "un cours d'eau", "gloss": "a watercourse"},
            {"term": "reconnaître", "gloss": "to acknowledge"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Information administrative / Administrative notice",
        "topic": "Société, citoyenneté & administration",
        "text": "Un service d'écrivain public est ouvert le mercredi, gratuitement.\nIl ne donne pas de conseil juridique : il aide à comprendre un courrier, à rédiger une réponse et à réunir les pièces demandées.\nAucune condition de ressources n'est exigée.",
        "question_fr": "Que ne fait pas ce service ?",
        "options": [
            {"id": "a", "text": "Aider à rédiger une lettre",
             "explanation": "That is precisely part of what it does."},
            {"id": "b", "text": "Donner un avis juridique",
             "explanation": "« Il ne donne pas de conseil juridique »."},
            {"id": "c", "text": "Recevoir sans condition de revenus",
             "explanation": "It does receive everyone: « Aucune condition de ressources n'est exigée »."},
            {"id": "d", "text": "Expliquer un courrier reçu",
             "explanation": "Explaining letters is listed among its tasks."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Il ne donne pas de conseil juridique.",
        "key_line_en": "It does not give legal advice.",
        "vocabulary": [
            {"term": "un écrivain public", "gloss": "a public letter-writer"},
            {"term": "rédiger", "gloss": "to draft, write"},
            {"term": "une pièce", "gloss": "a document"},
            {"term": "des ressources", "gloss": "income, means"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article consommation / Consumer article",
        "topic": "Alimentation & consommation",
        "text": "Les magasins de vrac se multiplient, mais un tiers ferme dans les deux ans.\nLe modèle suppose un client régulier qui apporte ses contenants ; or beaucoup viennent une fois par curiosité et ne reviennent pas. La fidélité, ici, compte davantage que la fréquentation.",
        "question_fr": "Pourquoi ces magasins ferment-ils ?",
        "options": [
            {"id": "a", "text": "Parce qu'ils reçoivent trop peu de visiteurs",
             "explanation": "Visitors come; the problem is that they do not come back — « La fidélité […] compte davantage que la fréquentation »."},
            {"id": "b", "text": "Parce que les clients ne reviennent pas",
             "explanation": "Many come once out of curiosity, and the model needs regulars with their own containers."},
            {"id": "c", "text": "Parce que les produits sont trop chers",
             "explanation": "Price is never mentioned."},
            {"id": "d", "text": "Parce que les contenants sont interdits",
             "explanation": "Bringing containers is exactly how the shops work."},
        ],
        "correct_answer": "b",
        "key_line_fr": "La fidélité, ici, compte davantage que la fréquentation.",
        "key_line_en": "Loyalty here matters more than footfall.",
        "vocabulary": [
            {"term": "le vrac", "gloss": "loose, unpackaged goods"},
            {"term": "un contenant", "gloss": "a container"},
            {"term": "la fidélité", "gloss": "customer loyalty"},
            {"term": "la fréquentation", "gloss": "footfall"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "topic": "Travail & emploi",
        "text": "On vante l'autonomie accordée aux équipes, et l'on oublie qu'elle n'a de sens qu'accompagnée des moyens correspondants.\nDonner à quelqu'un la responsabilité d'un résultat sans lui donner la maîtrise de ce qui le produit, ce n'est pas de l'autonomie : c'est un transfert de risque.",
        "question_fr": "Que dénonce l'auteur ?",
        "options": [
            {"id": "a", "text": "Une autonomie sans les moyens correspondants",
             "explanation": "Responsibility without control over the means « n'est pas de l'autonomie : c'est un transfert de risque »."},
            {"id": "b", "text": "L'excès de contrôle hiérarchique",
             "explanation": "The complaint is the opposite: control is withheld from those held responsible."},
            {"id": "c", "text": "Le manque de responsabilités confiées",
             "explanation": "Responsibility is precisely what is being handed over."},
            {"id": "d", "text": "La lenteur des décisions collectives",
             "explanation": "Decision speed is never discussed."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce n'est pas de l'autonomie : c'est un transfert de risque.",
        "key_line_en": "That is not autonomy: it is a transfer of risk.",
        "vocabulary": [
            {"term": "vanter", "gloss": "to praise, extol"},
            {"term": "la maîtrise", "gloss": "control"},
            {"term": "un transfert", "gloss": "a transfer"},
            {"term": "correspondant", "gloss": "corresponding"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "topic": "Société, citoyenneté & administration",
        "text": "Les guichets ferment, remplacés par des sites qui fonctionnent bien pour qui sait s'en servir.\nLe problème n'est pas le numérique en soi : c'est qu'on a supprimé l'alternative avant de vérifier que le remplacement convenait à tous. On a changé de canal, pas de public.",
        "question_fr": "Quelle erreur l'auteur identifie-t-il ?",
        "options": [
            {"id": "a", "text": "Avoir choisi des sites mal conçus",
             "explanation": "The sites work well for those who can use them."},
            {"id": "b", "text": "Avoir fermé l'ancien canal trop tôt",
             "explanation": "« on a supprimé l'alternative avant de vérifier que le remplacement convenait à tous »."},
            {"id": "c", "text": "Avoir gardé trop de guichets",
             "explanation": "Counters are closing, not proliferating."},
            {"id": "d", "text": "Avoir formé les usagers trop tard",
             "explanation": "Training is not mentioned; the sequencing of the closure is."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On a changé de canal, pas de public.",
        "key_line_en": "The channel changed, the public did not.",
        "vocabulary": [
            {"term": "un guichet", "gloss": "a service counter"},
            {"term": "une alternative", "gloss": "an alternative"},
            {"term": "convenir à", "gloss": "to suit"},
            {"term": "un canal", "gloss": "a channel"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Critique de série / Series review",
        "topic": "Loisirs, culture & médias",
        "text": "La série tient huit épisodes sur une intrigue qui en supporterait quatre.\nLes scénaristes le savent, et compensent par des rebondissements dont aucun ne modifie la situation. On avance beaucoup et l'on ne va nulle part.",
        "question_fr": "Que reproche le critique à cette série ?",
        "options": [
            {"id": "a", "text": "Un rythme trop rapide",
             "explanation": "The problem is the reverse: a thin plot stretched over too many episodes."},
            {"id": "b", "text": "Des acteurs peu convaincants",
             "explanation": "The cast is not discussed."},
            {"id": "c", "text": "Une intrigue étirée par des péripéties inutiles",
             "explanation": "Twists « dont aucun ne modifie la situation »: « On avance beaucoup et l'on ne va nulle part »."},
            {"id": "d", "text": "Une fin incompréhensible",
             "explanation": "The ending is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On avance beaucoup et l'on ne va nulle part.",
        "key_line_en": "There is a lot of movement and no progress.",
        "vocabulary": [
            {"term": "une intrigue", "gloss": "a plot"},
            {"term": "un rebondissement", "gloss": "a twist"},
            {"term": "supporter", "gloss": "to sustain, bear"},
            {"term": "un scénariste", "gloss": "a screenwriter"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "topic": "Sciences & technologies",
        "text": "Les mots de passe complexes imposés par les entreprises produisent souvent l'effet inverse de celui recherché.\nContraint de changer tous les trois mois, l'utilisateur adopte une variante prévisible ou l'écrit quelque part. La sécurité gagnée sur le papier se perd dans l'usage.",
        "question_fr": "Pourquoi ces règles sont-elles contre-productives ?",
        "options": [
            {"id": "a", "text": "Parce que les mots de passe sont trop courts",
             "explanation": "They are complex; length is not the issue."},
            {"id": "b", "text": "Parce que les systèmes sont mal protégés",
             "explanation": "Technical protection is not discussed; user behaviour is."},
            {"id": "c", "text": "Parce que les utilisateurs contournent la contrainte",
             "explanation": "Predictable variants or written-down passwords: « La sécurité gagnée sur le papier se perd dans l'usage »."},
            {"id": "d", "text": "Parce que les changements sont trop rares",
             "explanation": "Changes every three months are what create the problem."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La sécurité gagnée sur le papier se perd dans l'usage.",
        "key_line_en": "The security gained on paper is lost in practice.",
        "vocabulary": [
            {"term": "contraint de", "gloss": "forced to"},
            {"term": "une variante", "gloss": "a variant"},
            {"term": "prévisible", "gloss": "predictable"},
            {"term": "l'usage", "gloss": "actual use"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "topic": "Environnement & nature",
        "text": "Le zéro déchet est présenté comme un objectif individuel, ce qui en fait un exercice épuisant et culpabilisant.\nUn ménage attentif réduit ses déchets de moitié ; l'autre moitié dépend d'emballages qu'il n'a pas choisis. Exiger la perfection de chacun revient à excuser ceux qui produisent le problème.",
        "question_fr": "Quelle est la position de l'auteur ?",
        "options": [
            {"id": "a", "text": "Les efforts individuels sont inutiles",
             "explanation": "They halve household waste, which the text credits."},
            {"id": "b", "text": "Il faut viser la perfection individuelle",
             "explanation": "Demanding perfection is precisely what is criticised."},
            {"id": "c", "text": "La responsabilité doit être partagée avec les producteurs",
             "explanation": "Half the waste comes from packaging households did not choose, and blaming individuals « revient à excuser ceux qui produisent le problème »."},
            {"id": "d", "text": "Les emballages sont déjà bien conçus",
             "explanation": "They are the unaddressed half of the problem."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Exiger la perfection de chacun revient à excuser ceux qui produisent le problème.",
        "key_line_en": "Demanding perfection from individuals amounts to excusing those who create the problem.",
        "vocabulary": [
            {"term": "culpabilisant", "gloss": "guilt-inducing"},
            {"term": "un ménage", "gloss": "a household"},
            {"term": "un emballage", "gloss": "packaging"},
            {"term": "exiger", "gloss": "to demand"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "topic": "Vie quotidienne & logement",
        "text": "Madame,\nVotre demande de travaux est recevable, mais elle porte sur une partie commune : elle relève donc de l'assemblée générale, non du syndic.\nJe l'inscris à l'ordre du jour de juin. D'ici là, aucune intervention ne peut être engagée, même à vos frais.",
        "question_fr": "Pourquoi la demande ne peut-elle pas être traitée tout de suite ?",
        "options": [
            {"id": "a", "text": "Parce qu'elle est irrecevable",
             "explanation": "« Votre demande de travaux est recevable » — admissibility is not the issue."},
            {"id": "b", "text": "Parce qu'elle coûte trop cher",
             "explanation": "Cost is not discussed; the resident even offers to pay."},
            {"id": "c", "text": "Parce que le syndic est absent",
             "explanation": "The syndic replies; the matter is simply outside his powers."},
            {"id": "d", "text": "Parce qu'elle doit être votée en assemblée",
             "explanation": "It concerns a common area and « relève de l'assemblée générale, non du syndic »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Elle relève donc de l'assemblée générale, non du syndic.",
        "key_line_en": "It is therefore a matter for the general meeting, not for the managing agent.",
        "vocabulary": [
            {"term": "recevable", "gloss": "admissible"},
            {"term": "une partie commune", "gloss": "a communal area"},
            {"term": "relever de", "gloss": "to be a matter for"},
            {"term": "l'ordre du jour", "gloss": "the agenda"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Analyse économique / Economic analysis",
        "topic": "Transports & voyages",
        "text": "Les compagnies affichent des billets très bas, puis facturent le bagage, le siège et l'embarquement prioritaire.\nCette décomposition n'est pas seulement commerciale : elle rend la comparaison entre compagnies presque impossible, ce qui protège les prix bien mieux qu'une entente.",
        "question_fr": "Quel effet l'auteur attribue-t-il à cette pratique ?",
        "options": [
            {"id": "a", "text": "Elle empêche les voyageurs de comparer les offres",
             "explanation": "Unbundling makes comparison nearly impossible, « ce qui protège les prix bien mieux qu'une entente »."},
            {"id": "b", "text": "Elle fait baisser durablement les prix",
             "explanation": "The opposite: it shelters prices from competition."},
            {"id": "c", "text": "Elle résulte d'un accord entre compagnies",
             "explanation": "It works better « qu'une entente » — an explicit contrast with collusion."},
            {"id": "d", "text": "Elle simplifie la vente des billets",
             "explanation": "It multiplies the components rather than simplifying."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Elle rend la comparaison entre compagnies presque impossible, ce qui protège les prix bien mieux qu'une entente.",
        "key_line_en": "It makes comparison between airlines almost impossible, which protects prices far better than collusion would.",
        "vocabulary": [
            {"term": "facturer", "gloss": "to charge for"},
            {"term": "une décomposition", "gloss": "an unbundling"},
            {"term": "une entente", "gloss": "a cartel, collusion"},
            {"term": "l'embarquement", "gloss": "boarding"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "topic": "Société, citoyenneté & administration",
        "text": "Une règle que l'on n'applique jamais fait plus de dégâts qu'une règle absente.\nElle laisse subsister la possibilité de l'appliquer un jour, à quelqu'un, pour une raison qui ne sera pas celle qu'elle énonce. L'arbitraire ne naît pas de l'absence de loi, mais de son application intermittente.",
        "question_fr": "Quel danger l'auteur identifie-t-il ?",
        "options": [
            {"id": "a", "text": "L'absence totale de règles",
             "explanation": "« L'arbitraire ne naît pas de l'absence de loi » — that is expressly not the danger."},
            {"id": "b", "text": "Une règle appliquée de façon sélective",
             "explanation": "Its dormancy allows enforcement one day « pour une raison qui ne sera pas celle qu'elle énonce »."},
            {"id": "c", "text": "L'excès de règles nouvelles",
             "explanation": "The number of rules is not at issue."},
            {"id": "d", "text": "La complexité du texte des lois",
             "explanation": "Legibility is not discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "L'arbitraire ne naît pas de l'absence de loi, mais de son application intermittente.",
        "key_line_en": "Arbitrariness is born not of the absence of law, but of its intermittent enforcement.",
        "vocabulary": [
            {"term": "l'arbitraire", "gloss": "arbitrariness"},
            {"term": "subsister", "gloss": "to remain, persist"},
            {"term": "énoncer", "gloss": "to state"},
            {"term": "intermittent", "gloss": "intermittent"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "topic": "Sciences & technologies",
        "text": "Les études qui ne trouvent rien sont rarement publiées, et cette asymétrie déforme la littérature entière.\nSi vingt équipes cherchent un effet et qu'une seule en trouve un, c'est cette dernière qu'on lira. Le hasard, répété assez souvent, finit par ressembler à une découverte.",
        "question_fr": "Quel biais l'auteur décrit-il ?",
        "options": [
            {"id": "a", "text": "Les chercheurs falsifient leurs données",
             "explanation": "No fraud is alleged; chance plus selective publication suffices."},
            {"id": "b", "text": "Les études sont trop peu nombreuses",
             "explanation": "Twenty teams are searching; the problem is which result gets published."},
            {"id": "c", "text": "Seuls les résultats positifs sont publiés",
             "explanation": "« Les études qui ne trouvent rien sont rarement publiées », so the one chance finding is the one read."},
            {"id": "d", "text": "Les revues manquent de relecteurs",
             "explanation": "Peer review capacity is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le hasard, répété assez souvent, finit par ressembler à une découverte.",
        "key_line_en": "Chance, repeated often enough, ends up looking like a discovery.",
        "vocabulary": [
            {"term": "une asymétrie", "gloss": "an asymmetry"},
            {"term": "déformer", "gloss": "to distort"},
            {"term": "le hasard", "gloss": "chance"},
            {"term": "une découverte", "gloss": "a discovery"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "topic": "Travail & emploi",
        "text": "On prédit la fin du salariat depuis vingt ans, et sa part reste stable.\nCe qui change n'est pas le statut mais la frontière : on est salarié d'une entreprise dont on ne rencontre plus les clients, et l'on répond à des consignes produites par un logiciel. Le contrat tient ; la relation, elle, s'est vidée.",
        "question_fr": "Quelle évolution l'auteur observe-t-il ?",
        "options": [
            {"id": "a", "text": "Le salariat disparaît rapidement",
             "explanation": "« sa part reste stable » — the share of salaried work is not falling."},
            {"id": "b", "text": "Le contrat de travail a été modifié",
             "explanation": "« Le contrat tient » — the legal form is intact."},
            {"id": "c", "text": "Le statut demeure mais la relation se dégrade",
             "explanation": "« Le contrat tient ; la relation, elle, s'est vidée » — instructions from software, clients never met."},
            {"id": "d", "text": "Les salariés changent plus souvent d'entreprise",
             "explanation": "Job mobility is not discussed."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le contrat tient ; la relation, elle, s'est vidée.",
        "key_line_en": "The contract holds; the relationship, for its part, has been hollowed out.",
        "vocabulary": [
            {"term": "le salariat", "gloss": "salaried employment"},
            {"term": "une frontière", "gloss": "a boundary"},
            {"term": "une consigne", "gloss": "an instruction"},
            {"term": "se vider", "gloss": "to be emptied out"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "topic": "Loisirs, culture & médias",
        "text": "Chaque été, il revenait au village et trouvait tout plus petit.\nIl mit longtemps à comprendre que ce n'était pas le village qui avait rétréci, ni lui qui avait grandi : c'était le souvenir qui, chaque hiver, reprenait un peu d'espace.",
        "question_fr": "Qu'est-ce qui explique cette impression, dans le passage ?",
        "options": [
            {"id": "a", "text": "Le village a réellement changé",
             "explanation": "« ce n'était pas le village qui avait rétréci » — the place is not what moved."},
            {"id": "b", "text": "Le souvenir a grandi entre deux visites",
             "explanation": "« c'était le souvenir qui, chaque hiver, reprenait un peu d'espace » — memory expands, so the place seems to shrink."},
            {"id": "c", "text": "Il a grandi physiquement",
             "explanation": "Explicitly ruled out: « ni lui qui avait grandi »."},
            {"id": "d", "text": "Il ne reconnaît plus les lieux",
             "explanation": "He recognises them; they simply feel smaller."},
        ],
        "correct_answer": "b",
        "key_line_fr": "C'était le souvenir qui, chaque hiver, reprenait un peu d'espace.",
        "key_line_en": "It was the memory that, each winter, took back a little more room.",
        "vocabulary": [
            {"term": "rétrécir", "gloss": "to shrink"},
            {"term": "mettre longtemps à", "gloss": "to take a long time to"},
            {"term": "reprendre", "gloss": "to take back"},
            {"term": "un souvenir", "gloss": "a memory"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse urbaine / Urban analysis",
        "topic": "Vie quotidienne & logement",
        "text": "On mesure l'accessibilité d'un quartier en minutes de trajet, ce qui suppose que tout le monde marche à la même vitesse.\nPour un parent avec une poussette ou une personne âgée, huit cents mètres sans banc ni ombre ne sont pas huit cents mètres : ce sont deux arrêts et un renoncement.",
        "question_fr": "Quelle critique l'auteur formule-t-il ?",
        "options": [
            {"id": "a", "text": "Les distances annoncées sont fausses",
             "explanation": "The distance is accurate; what it means differs from person to person."},
            {"id": "b", "text": "Les quartiers manquent de transports",
             "explanation": "The subject is walking, and what the route offers along the way."},
            {"id": "c", "text": "La mesure ignore les conditions du trajet",
             "explanation": "Eight hundred metres « sans banc ni ombre » are not the same for everyone: « deux arrêts et un renoncement »."},
            {"id": "d", "text": "Les habitants marchent trop lentement",
             "explanation": "No fault is attributed to the walkers."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Huit cents mètres sans banc ni ombre ne sont pas huit cents mètres : ce sont deux arrêts et un renoncement.",
        "key_line_en": "Eight hundred metres with no bench and no shade are not eight hundred metres: they are two stops and a giving-up.",
        "vocabulary": [
            {"term": "l'accessibilité", "gloss": "accessibility"},
            {"term": "une poussette", "gloss": "a pushchair"},
            {"term": "l'ombre", "gloss": "shade"},
            {"term": "un renoncement", "gloss": "a giving-up"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "topic": "Société, citoyenneté & administration",
        "text": "La plateforme a mis en place un service de réclamation exemplaire : un formulaire en six étapes, un accusé de réception immédiat, un numéro de dossier.\nAucune de ces étapes ne prévoit qu'un humain lise la réclamation, mais il faut reconnaître que le suivi est irréprochable.",
        "question_fr": "Que met en évidence l'auteur ?",
        "options": [
            {"id": "a", "text": "Un processus soigné qui ne traite rien",
             "explanation": "Six steps, acknowledgement and case number, yet « aucune de ces étapes ne prévoit qu'un humain lise la réclamation »."},
            {"id": "b", "text": "Un service client efficace et rapide",
             "explanation": "Speed of acknowledgement is not resolution, which the middle sentence denies."},
            {"id": "c", "text": "Un formulaire trop compliqué à remplir",
             "explanation": "Its length is a symptom; the point is that nobody reads the result."},
            {"id": "d", "text": "Un manque de suivi des dossiers",
             "explanation": "Tracking is the one thing that works — ironically."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Aucune de ces étapes ne prévoit qu'un humain lise la réclamation.",
        "key_line_en": "None of these steps provides for a human being to read the complaint.",
        "vocabulary": [
            {"term": "une réclamation", "gloss": "a complaint"},
            {"term": "un accusé de réception", "gloss": "an acknowledgement of receipt"},
            {"term": "le suivi", "gloss": "tracking, follow-up"},
            {"term": "irréprochable", "gloss": "faultless"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article environnement / Environmental article",
        "topic": "Environnement & nature",
        "text": "Compenser ses émissions en finançant des arbres revient à payer aujourd'hui pour un stockage qui n'aura lieu que dans trente ans, s'il a lieu.\nOn échange une certitude contre une promesse, et l'on inscrit l'opération comme si les deux se valaient.",
        "question_fr": "Que reproche l'auteur à la compensation carbone ?",
        "options": [
            {"id": "a", "text": "Elle coûte trop cher aux entreprises",
             "explanation": "Cost is not the objection; the accounting is."},
            {"id": "b", "text": "Elle traite comme équivalents une émission certaine et un stockage incertain",
             "explanation": "« On échange une certitude contre une promesse, et l'on inscrit l'opération comme si les deux se valaient »."},
            {"id": "c", "text": "Elle empêche de planter des arbres",
             "explanation": "It funds planting; the doubt is about timing and certainty."},
            {"id": "d", "text": "Elle est interdite dans la plupart des pays",
             "explanation": "No legal status is discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On échange une certitude contre une promesse, et l'on inscrit l'opération comme si les deux se valaient.",
        "key_line_en": "A certainty is traded for a promise, and the transaction is booked as if the two were equal.",
        "vocabulary": [
            {"term": "compenser", "gloss": "to offset"},
            {"term": "le stockage", "gloss": "storage, sequestration"},
            {"term": "inscrire", "gloss": "to record, book"},
            {"term": "se valoir", "gloss": "to be worth the same"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la conversation / Essay on conversation",
        "topic": "Loisirs, culture & médias",
        "text": "Une conversation réussie ne se reconnaît pas à l'accord obtenu, mais à ce que chacun en emporte qu'il n'avait pas apporté.\nCelui qui sort d'un échange exactement tel qu'il y est entré n'a pas parlé : il a émis.",
        "question_fr": "Quel critère l'auteur retient-il ?",
        "options": [
            {"id": "a", "text": "Le fait d'avoir convaincu l'autre",
             "explanation": "Agreement is explicitly not the mark of success."},
            {"id": "b", "text": "La durée de l'échange",
             "explanation": "Length is never mentioned."},
            {"id": "c", "text": "Ce que chacun en repart avec de nouveau",
             "explanation": "« ce que chacun en emporte qu'il n'avait pas apporté »; otherwise one has merely broadcast."},
            {"id": "d", "text": "La politesse des interlocuteurs",
             "explanation": "Manners play no part in the criterion given."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Celui qui sort d'un échange exactement tel qu'il y est entré n'a pas parlé : il a émis.",
        "key_line_en": "Anyone who leaves an exchange exactly as they entered it has not spoken: they have broadcast.",
        "vocabulary": [
            {"term": "emporter", "gloss": "to take away"},
            {"term": "un échange", "gloss": "an exchange"},
            {"term": "émettre", "gloss": "to broadcast, emit"},
            {"term": "se reconnaître à", "gloss": "to be recognised by"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "topic": "Société, citoyenneté & administration",
        "text": "L'urgence est le meilleur argument dont dispose un pouvoir : elle dispense de convaincre.\nOn ne débat pas d'une décision qu'il faut prendre avant ce soir ; on l'approuve ou l'on gêne. Aussi le premier travail politique consiste-t-il souvent à établir qu'il y a urgence.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Les décisions urgentes sont généralement mauvaises",
             "explanation": "Their quality is not assessed; what is analysed is how urgency suspends debate."},
            {"id": "b", "text": "L'urgence est parfois construite pour éviter le débat",
             "explanation": "It « dispense de convaincre », and « le premier travail politique consiste souvent à établir qu'il y a urgence »."},
            {"id": "c", "text": "Il faut agir plus vite en politique",
             "explanation": "The essay is a warning about speed, not a call for it."},
            {"id": "d", "text": "Les citoyens refusent de débattre",
             "explanation": "The refusal described comes from the framing, not from citizens."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Le premier travail politique consiste souvent à établir qu'il y a urgence.",
        "key_line_en": "The first political task is often to establish that there is an emergency.",
        "vocabulary": [
            {"term": "dispenser de", "gloss": "to exempt from"},
            {"term": "gêner", "gloss": "to obstruct, be in the way"},
            {"term": "approuver", "gloss": "to approve"},
            {"term": "l'urgence", "gloss": "urgency, emergency"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "topic": "Sciences & technologies",
        "text": "Comprendre n'est pas retenir. On retient une formule, on comprend ce qu'elle interdit.\nCelui qui sait résoudre l'exercice et ne voit pas quel résultat serait absurde possède une procédure, non une connaissance — et la procédure le lâchera au premier cas qu'on n'aura pas prévu.",
        "question_fr": "Comment l'auteur distingue-t-il comprendre et retenir ?",
        "options": [
            {"id": "a", "text": "Comprendre suppose de voir ce qui est exclu",
             "explanation": "« on comprend ce qu'elle interdit »; without seeing which result would be absurd, one holds only a procedure."},
            {"id": "b", "text": "Retenir demande plus d'efforts que comprendre",
             "explanation": "Effort is not the criterion offered."},
            {"id": "c", "text": "Comprendre consiste à résoudre l'exercice",
             "explanation": "Solving it is exactly what the merely procedural student can do."},
            {"id": "d", "text": "Les deux reviennent au même",
             "explanation": "The essay's whole purpose is to separate them."},
        ],
        "correct_answer": "a",
        "key_line_fr": "On retient une formule, on comprend ce qu'elle interdit.",
        "key_line_en": "You memorise a formula; you understand what it rules out.",
        "vocabulary": [
            {"term": "retenir", "gloss": "to memorise"},
            {"term": "interdire", "gloss": "to rule out, forbid"},
            {"term": "lâcher", "gloss": "to let down, give way"},
            {"term": "une procédure", "gloss": "a procedure"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Critique de photographie / Photography review",
        "topic": "Loisirs, culture & médias",
        "text": "Les images de la série sont irréprochables : cadrage, lumière, instant.\nIl leur manque ce léger défaut par lequel une photographie avoue avoir été prise par quelqu'un. À force d'être parfaites, elles ne témoignent plus de rien : elles illustrent.",
        "question_fr": "Que reproche le critique à ces photographies ?",
        "options": [
            {"id": "a", "text": "Leur perfection efface la présence du photographe",
             "explanation": "They lack the flaw « par lequel une photographie avoue avoir été prise par quelqu'un »; they illustrate rather than testify."},
            {"id": "b", "text": "Leur cadrage est maladroit",
             "explanation": "Framing is listed among their faultless qualities."},
            {"id": "c", "text": "Elles sont trop peu nombreuses",
             "explanation": "The size of the series is not discussed."},
            {"id": "d", "text": "Elles témoignent trop directement",
             "explanation": "The complaint is that they no longer bear witness at all."},
        ],
        "correct_answer": "a",
        "key_line_fr": "À force d'être parfaites, elles ne témoignent plus de rien : elles illustrent.",
        "key_line_en": "By dint of being perfect, they no longer bear witness to anything: they illustrate.",
        "vocabulary": [
            {"term": "un cadrage", "gloss": "framing"},
            {"term": "avouer", "gloss": "to confess, admit"},
            {"term": "témoigner de", "gloss": "to bear witness to"},
            {"term": "illustrer", "gloss": "to illustrate"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "topic": "Vie quotidienne & logement",
        "text": "On a repeint la façade et remplacé les boîtes aux lettres, mais l'escalier reste celui où l'on ne croise personne.\nUn immeuble ne devient un lieu que le jour où quelqu'un y attend quelqu'un. Jusque-là, c'est une adresse.",
        "question_fr": "Quelle distinction l'auteur établit-il ?",
        "options": [
            {"id": "a", "text": "Entre bâtiments anciens et rénovés",
             "explanation": "The renovation happened and changed nothing that matters here."},
            {"id": "b", "text": "Entre une adresse et un lieu habité socialement",
             "explanation": "« Un immeuble ne devient un lieu que le jour où quelqu'un y attend quelqu'un. Jusque-là, c'est une adresse »."},
            {"id": "c", "text": "Entre propriétaires et locataires",
             "explanation": "Tenure is never mentioned."},
            {"id": "d", "text": "Entre façade et intérieur",
             "explanation": "Both are described; the contrast drawn is about human presence."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un immeuble ne devient un lieu que le jour où quelqu'un y attend quelqu'un.",
        "key_line_en": "A building becomes a place only on the day someone is waiting there for someone.",
        "vocabulary": [
            {"term": "une façade", "gloss": "a façade"},
            {"term": "une boîte aux lettres", "gloss": "a letterbox"},
            {"term": "croiser", "gloss": "to run into"},
            {"term": "jusque-là", "gloss": "until then"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la traduction du droit / Essay on legal language",
        "topic": "Société, citoyenneté & administration",
        "text": "Rendre une loi lisible n'est pas la simplifier : c'est déplacer la difficulté du lecteur vers le rédacteur.\nUn texte obscur fait payer sa complexité à des milliers de personnes ; un texte clair la fait payer une fois, à celui qui l'écrit. Le calcul devrait être vite fait.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Les lois claires sont nécessairement plus courtes",
             "explanation": "Length is not the criterion; where the effort falls is."},
            {"id": "b", "text": "La clarté déplace l'effort vers celui qui rédige",
             "explanation": "Obscurity charges its complexity to thousands of readers; clarity charges it once, to the drafter."},
            {"id": "c", "text": "Les lecteurs devraient être mieux formés",
             "explanation": "The remedy proposed is on the writing side, not the reading side."},
            {"id": "d", "text": "Simplifier une loi la rend moins précise",
             "explanation": "The text distinguishes making legible from simplifying, and does not claim any loss of precision."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un texte obscur fait payer sa complexité à des milliers de personnes ; un texte clair la fait payer une fois, à celui qui l'écrit.",
        "key_line_en": "An obscure text charges its complexity to thousands of people; a clear one charges it once, to whoever wrote it.",
        "vocabulary": [
            {"term": "lisible", "gloss": "legible, readable"},
            {"term": "un rédacteur", "gloss": "a drafter, writer"},
            {"term": "obscur", "gloss": "obscure"},
            {"term": "faire payer", "gloss": "to charge"},
        ],
    },
]

QUESTIONS = balance(_RAW)
