"""Compréhension écrite — Test 09.

Forty questions climbing A1 → C2. Profile A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Mot / Note",
        "topic": "Vie quotidienne & logement",
        "text": "Bonjour,\nJe pars en vacances du 3 au 17 août.\nPouvez-vous arroser mes plantes une fois par semaine ?\nLes clés sont chez la gardienne.\nMme Diallo",
        "question_fr": "Que demande Mme Diallo ?",
        "options": [
            {"id": "a", "text": "De garder son chat",
             "explanation": "No animal is mentioned."},
            {"id": "b", "text": "D'arroser ses plantes",
             "explanation": "« Pouvez-vous arroser mes plantes une fois par semaine ? »"},
            {"id": "c", "text": "De garder ses clés",
             "explanation": "The keys are already with the caretaker; that is information, not the request."},
            {"id": "d", "text": "De partir en vacances avec elle",
             "explanation": "No invitation is made."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Pouvez-vous arroser mes plantes une fois par semaine ?",
        "key_line_en": "Could you water my plants once a week?",
        "vocabulary": [
            {"term": "arroser", "gloss": "to water"},
            {"term": "une gardienne", "gloss": "a caretaker"},
            {"term": "une fois par semaine", "gloss": "once a week"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Étiquette / Label",
        "topic": "Alimentation & consommation",
        "text": "JUS D'ORANGE\n100 % pur jus, sans sucre ajouté.\nÀ boire dans les 3 jours après ouverture.\nBien agiter avant de servir.",
        "question_fr": "Que faut-il faire avant de servir ?",
        "options": [
            {"id": "a", "text": "Ajouter du sucre",
             "explanation": "The juice has no added sugar and none is asked for."},
            {"id": "b", "text": "Attendre trois jours",
             "explanation": "Three days is the limit for drinking it, not a waiting time."},
            {"id": "c", "text": "Agiter la bouteille",
             "explanation": "« Bien agiter avant de servir »."},
            {"id": "d", "text": "Faire chauffer",
             "explanation": "Heating is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Bien agiter avant de servir.",
        "key_line_en": "Shake well before serving.",
        "vocabulary": [
            {"term": "agiter", "gloss": "to shake"},
            {"term": "sans sucre ajouté", "gloss": "no added sugar"},
            {"term": "après ouverture", "gloss": "once opened"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Affiche / Notice",
        "topic": "Santé & bien-être",
        "text": "CABINET MÉDICAL\nLe docteur reçoit sur rendez-vous.\nPour une urgence, appelez avant 9 h.\nLes résultats d'analyses sont envoyés par courriel.",
        "question_fr": "Comment reçoit-on ses résultats d'analyses ?",
        "options": [
            {"id": "a", "text": "Par courriel",
             "explanation": "« Les résultats d'analyses sont envoyés par courriel »."},
            {"id": "b", "text": "Au cabinet",
             "explanation": "The surgery is where consultations happen, by appointment."},
            {"id": "c", "text": "Par téléphone avant 9 h",
             "explanation": "The 9 a.m. call is for emergencies."},
            {"id": "d", "text": "Par courrier",
             "explanation": "Post is not mentioned; the notice specifies e-mail."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les résultats d'analyses sont envoyés par courriel.",
        "key_line_en": "Test results are sent by e-mail.",
        "vocabulary": [
            {"term": "recevoir", "gloss": "to see (patients)"},
            {"term": "des analyses", "gloss": "medical tests"},
            {"term": "un courriel", "gloss": "an e-mail"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Billet / Ticket",
        "topic": "Transports & voyages",
        "text": "BUS — LIGNE 22\nBillet valable 1 heure.\nCorrespondances comprises.\nÀ composter à la montée.",
        "question_fr": "Combien de temps le billet est-il valable ?",
        "options": [
            {"id": "a", "text": "22 minutes",
             "explanation": "22 is the bus line number."},
            {"id": "b", "text": "Toute la journée",
             "explanation": "The ticket lasts one hour."},
            {"id": "c", "text": "Un seul trajet",
             "explanation": "Connections are included within the hour."},
            {"id": "d", "text": "Une heure",
             "explanation": "« Billet valable 1 heure »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Billet valable 1 heure. Correspondances comprises.",
        "key_line_en": "Ticket valid for 1 hour. Connections included.",
        "vocabulary": [
            {"term": "valable", "gloss": "valid"},
            {"term": "une correspondance", "gloss": "a connection"},
            {"term": "composter", "gloss": "to validate (a ticket)"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Message / Message",
        "topic": "Études & formation",
        "text": "Bonjour Madame,\nJe suis malade et je ne peux pas venir au cours aujourd'hui.\nPouvez-vous m'envoyer les exercices ?\nMerci beaucoup,\nSofia",
        "question_fr": "Que demande Sofia ?",
        "options": [
            {"id": "a", "text": "Un rendez-vous",
             "explanation": "No meeting is requested."},
            {"id": "b", "text": "Les exercices du cours",
             "explanation": "« Pouvez-vous m'envoyer les exercices ? »"},
            {"id": "c", "text": "Un certificat médical",
             "explanation": "She reports being ill but asks for nothing of the kind."},
            {"id": "d", "text": "De changer l'heure du cours",
             "explanation": "The class time is not discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Pouvez-vous m'envoyer les exercices ?",
        "key_line_en": "Could you send me the exercises?",
        "vocabulary": [
            {"term": "malade", "gloss": "ill"},
            {"term": "un exercice", "gloss": "an exercise"},
            {"term": "envoyer", "gloss": "to send"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Programme / Programme",
        "topic": "Loisirs, culture & médias",
        "text": "MÉDIATHÈQUE — MERCREDI\n10 h : lecture pour les enfants (3-6 ans)\n15 h : atelier jeux de société\n17 h : rencontre avec un auteur\nEntrée libre.",
        "question_fr": "Que peut-on faire à 15 h ?",
        "options": [
            {"id": "a", "text": "Écouter une lecture",
             "explanation": "The story reading is at 10 a.m."},
            {"id": "b", "text": "Rencontrer un auteur",
             "explanation": "The author event is at 5 p.m."},
            {"id": "c", "text": "Jouer à des jeux de société",
             "explanation": "« 15 h : atelier jeux de société »."},
            {"id": "d", "text": "Emprunter des livres",
             "explanation": "Borrowing is not part of this programme."},
        ],
        "correct_answer": "c",
        "key_line_fr": "15 h : atelier jeux de société.",
        "key_line_en": "3 p.m.: board games workshop.",
        "vocabulary": [
            {"term": "un jeu de société", "gloss": "a board game"},
            {"term": "une rencontre", "gloss": "a meeting, event"},
            {"term": "entrée libre", "gloss": "free admission"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Offre d'emploi / Job advert",
        "topic": "Travail & emploi",
        "text": "LIBRAIRIE — VENDEUR (H/F)\nCDD de trois mois, renouvelable.\nTravail un samedi sur deux, jour de repos le lundi.\nLe goût de la lecture est plus important que l'expérience : une formation interne est assurée.",
        "question_fr": "Qu'est-ce qui compte le plus pour ce poste ?",
        "options": [
            {"id": "a", "text": "L'expérience en librairie",
             "explanation": "« Le goût de la lecture est plus important que l'expérience »."},
            {"id": "b", "text": "La disponibilité le lundi",
             "explanation": "Monday is the day off, not a requirement."},
            {"id": "c", "text": "Un diplôme en littérature",
             "explanation": "No qualification is mentioned."},
            {"id": "d", "text": "L'intérêt pour les livres",
             "explanation": "Reading is what the advert ranks above experience, with training provided."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Le goût de la lecture est plus important que l'expérience.",
        "key_line_en": "A love of reading matters more than experience.",
        "vocabulary": [
            {"term": "un CDD", "gloss": "a fixed-term contract"},
            {"term": "renouvelable", "gloss": "renewable"},
            {"term": "le goût de", "gloss": "a taste for"},
            {"term": "assuré", "gloss": "provided"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Courrier administratif / Official letter",
        "topic": "Société, citoyenneté & administration",
        "text": "Madame,\nVotre demande d'aide au logement a été acceptée à compter du 1er mars.\nLe versement est effectué le 5 de chaque mois, directement au propriétaire.\nTout changement de situation doit être signalé sous quinze jours.",
        "question_fr": "Qui reçoit l'argent de l'aide ?",
        "options": [
            {"id": "a", "text": "Le propriétaire",
             "explanation": "« Le versement est effectué […] directement au propriétaire »."},
            {"id": "b", "text": "La locataire",
             "explanation": "The payment bypasses her and goes to the landlord."},
            {"id": "c", "text": "La mairie",
             "explanation": "The council plays no part in the payment described."},
            {"id": "d", "text": "Personne avant le 1er mars",
             "explanation": "1 March is the start date, not an answer to who is paid."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le versement est effectué le 5 de chaque mois, directement au propriétaire.",
        "key_line_en": "Payment is made on the 5th of each month, directly to the landlord.",
        "vocabulary": [
            {"term": "un versement", "gloss": "a payment"},
            {"term": "à compter de", "gloss": "as from"},
            {"term": "signaler", "gloss": "to report"},
            {"term": "un propriétaire", "gloss": "a landlord, owner"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Règlement / Rules",
        "topic": "Vie quotidienne & logement",
        "text": "LOCAL À VÉLOS\nAccès réservé aux résidents, avec un badge personnel.\nChaque vélo doit porter une étiquette au nom du propriétaire.\nLes vélos sans étiquette seront retirés après un mois.",
        "question_fr": "Que risque un vélo sans étiquette ?",
        "options": [
            {"id": "a", "text": "Une amende pour le propriétaire",
             "explanation": "No fine is mentioned."},
            {"id": "b", "text": "D'être enlevé du local",
             "explanation": "« Les vélos sans étiquette seront retirés après un mois »."},
            {"id": "c", "text": "De perdre l'accès au badge",
             "explanation": "The badge belongs to the resident, not to the bike."},
            {"id": "d", "text": "Rien de particulier",
             "explanation": "A specific consequence is stated."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les vélos sans étiquette seront retirés après un mois.",
        "key_line_en": "Bicycles without a label will be removed after one month.",
        "vocabulary": [
            {"term": "une étiquette", "gloss": "a label, tag"},
            {"term": "retirer", "gloss": "to remove"},
            {"term": "un badge", "gloss": "a pass, badge"},
            {"term": "réservé à", "gloss": "reserved for"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Message de service / Service message",
        "topic": "Sciences & technologies",
        "text": "MAINTENANCE\nLe site sera indisponible dimanche de 2 h à 6 h.\nLes commandes passées avant samedi minuit seront traitées normalement.\nAucune donnée ne sera perdue.",
        "question_fr": "Que deviennent les commandes passées vendredi ?",
        "options": [
            {"id": "a", "text": "Elles seront annulées",
             "explanation": "Nothing is cancelled and no data is lost."},
            {"id": "b", "text": "Elles seront traitées normalement",
             "explanation": "Friday is before Saturday midnight: « Les commandes passées avant samedi minuit seront traitées normalement »."},
            {"id": "c", "text": "Elles devront être repassées dimanche",
             "explanation": "No reordering is required."},
            {"id": "d", "text": "Elles seront traitées après six heures",
             "explanation": "They are handled normally, not deferred past the maintenance window."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les commandes passées avant samedi minuit seront traitées normalement.",
        "key_line_en": "Orders placed before midnight on Saturday will be processed as usual.",
        "vocabulary": [
            {"term": "indisponible", "gloss": "unavailable"},
            {"term": "traiter", "gloss": "to process"},
            {"term": "une commande", "gloss": "an order"},
            {"term": "une donnée", "gloss": "a piece of data"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information municipale / Council notice",
        "topic": "Environnement & nature",
        "text": "COLLECTE DES ENCOMBRANTS\nUn ramassage par mois, sur inscription en ligne.\nLes objets doivent être sortis la veille au soir, sans gêner le passage.\nLes gravats et les produits dangereux ne sont pas acceptés.",
        "question_fr": "Que faut-il faire avant le ramassage ?",
        "options": [
            {"id": "a", "text": "S'inscrire et sortir les objets la veille",
             "explanation": "Registration is online, and items go out « la veille au soir »."},
            {"id": "b", "text": "Apporter les objets à la déchetterie",
             "explanation": "The collection comes to the street; nothing is taken elsewhere."},
            {"id": "c", "text": "Payer une contribution",
             "explanation": "No charge is mentioned."},
            {"id": "d", "text": "Trier les gravats",
             "explanation": "Rubble is refused entirely, not sorted."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Un ramassage par mois, sur inscription en ligne. Les objets doivent être sortis la veille au soir.",
        "key_line_en": "One collection a month, booked online. Items must be put out the evening before.",
        "vocabulary": [
            {"term": "les encombrants", "gloss": "bulky waste"},
            {"term": "un ramassage", "gloss": "a collection"},
            {"term": "des gravats", "gloss": "rubble"},
            {"term": "gêner", "gloss": "to obstruct"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Affichage marché / Market notice",
        "topic": "Alimentation & consommation",
        "text": "VENTE DIRECTE À LA FERME\nOuvert le vendredi de 15 h à 19 h et le samedi matin.\nPaiement en espèces ou par carte à partir de 10 €.\nApportez vos contenants pour les œufs et le fromage.",
        "question_fr": "Quand peut-on payer par carte ?",
        "options": [
            {"id": "a", "text": "Le samedi uniquement",
             "explanation": "The card rule depends on the amount, not the day."},
            {"id": "b", "text": "Toujours",
             "explanation": "A minimum applies."},
            {"id": "c", "text": "À partir de 10 €",
             "explanation": "« Paiement en espèces ou par carte à partir de 10 € »."},
            {"id": "d", "text": "Jamais",
             "explanation": "Card payment is possible above the minimum."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Paiement en espèces ou par carte à partir de 10 €.",
        "key_line_en": "Payment in cash, or by card for €10 and above.",
        "vocabulary": [
            {"term": "la vente directe", "gloss": "direct sale"},
            {"term": "en espèces", "gloss": "in cash"},
            {"term": "un contenant", "gloss": "a container"},
            {"term": "à partir de", "gloss": "from (an amount)"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Conditions / Terms",
        "topic": "Transports & voyages",
        "text": "VÉLOS EN LIBRE-SERVICE\nLes trente premières minutes sont incluses dans l'abonnement.\nAu-delà : 1 € par demi-heure entamée.\nLe vélo doit être rendu à une station ; tout stationnement libre est facturé 20 €.",
        "question_fr": "Que se passe-t-il si le vélo n'est pas rendu à une station ?",
        "options": [
            {"id": "a", "text": "L'abonnement est suspendu",
             "explanation": "Suspension is not mentioned; a charge is."},
            {"id": "b", "text": "On paie 1 € de plus",
             "explanation": "€1 is the half-hour overtime rate, not the parking penalty."},
            {"id": "c", "text": "Rien, c'est autorisé",
             "explanation": "Free parking is explicitly billed."},
            {"id": "d", "text": "On paie 20 €",
             "explanation": "« tout stationnement libre est facturé 20 € »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Tout stationnement libre est facturé 20 €.",
        "key_line_en": "Any free-floating parking is charged at €20.",
        "vocabulary": [
            {"term": "en libre-service", "gloss": "self-service"},
            {"term": "entamé", "gloss": "started"},
            {"term": "au-delà", "gloss": "beyond that"},
            {"term": "facturer", "gloss": "to charge"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Chronique santé / Health column",
        "topic": "Santé & bien-être",
        "text": "Faire dix mille pas par jour n'a rien d'un seuil médical : le chiffre vient d'une campagne publicitaire japonaise des années soixante.\nLes bénéfices apparaissent bien avant, dès quatre mille pas, et augmentent ensuite lentement. Un objectif inatteignable décourage plus qu'il ne motive.",
        "question_fr": "Que reproche l'auteur au chiffre de dix mille pas ?",
        "options": [
            {"id": "a", "text": "Il est trop bas pour être utile",
             "explanation": "The benefits appear well below it, so the figure is high rather than low."},
            {"id": "b", "text": "Il n'a pas d'origine scientifique et décourage",
             "explanation": "It comes from an advertising campaign, and « Un objectif inatteignable décourage plus qu'il ne motive »."},
            {"id": "c", "text": "Il ne concerne que les sportifs",
             "explanation": "No such restriction is suggested."},
            {"id": "d", "text": "Il est impossible à mesurer",
             "explanation": "Measurement is not the issue; the threshold's basis is."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un objectif inatteignable décourage plus qu'il ne motive.",
        "key_line_en": "An unreachable target discourages more than it motivates.",
        "vocabulary": [
            {"term": "un seuil", "gloss": "a threshold"},
            {"term": "un bénéfice", "gloss": "a benefit"},
            {"term": "inatteignable", "gloss": "unattainable"},
            {"term": "décourager", "gloss": "to discourage"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "topic": "Travail & emploi",
        "text": "Les salariés interrogés placent la reconnaissance devant l'augmentation, mais l'ordre s'inverse chez ceux dont le salaire est le plus bas.\nL'étude en tire une conclusion prudente : la reconnaissance compte partout, elle ne remplace nulle part un revenu suffisant.",
        "question_fr": "Que conclut l'étude ?",
        "options": [
            {"id": "a", "text": "La reconnaissance ne compte pas pour les bas salaires",
             "explanation": "« la reconnaissance compte partout » — the order changes, not its value."},
            {"id": "b", "text": "L'augmentation est toujours prioritaire",
             "explanation": "Most respondents put recognition first; only the lowest-paid reverse it."},
            {"id": "c", "text": "La reconnaissance ne compense pas un salaire insuffisant",
             "explanation": "« elle ne remplace nulle part un revenu suffisant »."},
            {"id": "d", "text": "Les salariés sont satisfaits de leur rémunération",
             "explanation": "Satisfaction with pay is not reported."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La reconnaissance compte partout, elle ne remplace nulle part un revenu suffisant.",
        "key_line_en": "Recognition counts everywhere; nowhere does it replace an adequate income.",
        "vocabulary": [
            {"term": "la reconnaissance", "gloss": "recognition"},
            {"term": "s'inverser", "gloss": "to be reversed"},
            {"term": "prudent", "gloss": "cautious"},
            {"term": "un revenu", "gloss": "an income"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Présentation de dispositif / Scheme description",
        "topic": "Études & formation",
        "text": "Les élèves de terminale peuvent passer une journée en cours à l'université avant de choisir leur orientation.\nL'objectif n'est pas de convaincre : beaucoup repartent en ayant écarté une filière, et c'est considéré comme une réussite du dispositif.",
        "question_fr": "Comment le dispositif définit-il sa réussite ?",
        "options": [
            {"id": "a", "text": "Par le nombre d'inscriptions obtenues",
             "explanation": "« L'objectif n'est pas de convaincre » — recruitment is not the aim."},
            {"id": "b", "text": "Par la satisfaction des enseignants",
             "explanation": "Teachers' views are not mentioned."},
            {"id": "c", "text": "Par le fait d'écarter une orientation",
             "explanation": "Ruling out a course is explicitly « considéré comme une réussite du dispositif »."},
            {"id": "d", "text": "Par la durée de la visite",
             "explanation": "One day is the format, not a measure of success."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Beaucoup repartent en ayant écarté une filière, et c'est considéré comme une réussite.",
        "key_line_en": "Many leave having ruled a course out, and that counts as a success.",
        "vocabulary": [
            {"term": "la terminale", "gloss": "the final year of school"},
            {"term": "l'orientation", "gloss": "course/career choice"},
            {"term": "écarter", "gloss": "to rule out"},
            {"term": "une filière", "gloss": "a course of study"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article culturel / Culture article",
        "topic": "Loisirs, culture & médias",
        "text": "Le musée a supprimé ses audioguides au profit d'un livret papier de huit pages.\n« Les visiteurs restaient plus longtemps avec l'audioguide, mais ils regardaient moins les œuvres, explique la conservatrice. Ils écoutaient le musée au lieu de le voir. »",
        "question_fr": "Pourquoi le musée a-t-il changé de support ?",
        "options": [
            {"id": "a", "text": "Parce que les audioguides coûtaient trop cher",
             "explanation": "Cost is not mentioned."},
            {"id": "b", "text": "Parce que les visiteurs restaient moins longtemps",
             "explanation": "They stayed longer with the audioguide — that was not the problem."},
            {"id": "c", "text": "Parce que le livret est plus complet",
             "explanation": "Eight pages is shorter, not fuller."},
            {"id": "d", "text": "Parce que l'audioguide détournait le regard des œuvres",
             "explanation": "« Ils écoutaient le musée au lieu de le voir »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Ils écoutaient le musée au lieu de le voir.",
        "key_line_en": "They were listening to the museum instead of looking at it.",
        "vocabulary": [
            {"term": "un audioguide", "gloss": "an audio guide"},
            {"term": "un livret", "gloss": "a booklet"},
            {"term": "une conservatrice", "gloss": "a curator"},
            {"term": "au profit de", "gloss": "in favour of"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Reportage / Report",
        "topic": "Environnement & nature",
        "text": "La commune a installé des nichoirs pour attirer les mésanges, grandes consommatrices de chenilles.\nDeux ans plus tard, les traitements contre les chenilles ont été divisés par trois. « Nous n'avons rien inventé, précise le technicien : nous avons seulement cessé de couper les haies au printemps. »",
        "question_fr": "Qu'est-ce qui a surtout permis ce résultat, selon le technicien ?",
        "options": [
            {"id": "a", "text": "L'arrêt de la taille des haies au printemps",
             "explanation": "« Nous n'avons rien inventé […] nous avons seulement cessé de couper les haies au printemps »."},
            {"id": "b", "text": "L'installation des nichoirs seule",
             "explanation": "The nest boxes are mentioned, but the technician credits the hedges."},
            {"id": "c", "text": "L'augmentation des traitements chimiques",
             "explanation": "Treatments fell by two thirds."},
            {"id": "d", "text": "L'arrivée d'une nouvelle espèce",
             "explanation": "The tits are local birds encouraged to stay, not a newly introduced species."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Nous avons seulement cessé de couper les haies au printemps.",
        "key_line_en": "We simply stopped cutting the hedges in spring.",
        "vocabulary": [
            {"term": "un nichoir", "gloss": "a nest box"},
            {"term": "une chenille", "gloss": "a caterpillar"},
            {"term": "une haie", "gloss": "a hedge"},
            {"term": "un traitement", "gloss": "a (pesticide) treatment"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Information administrative / Administrative notice",
        "topic": "Société, citoyenneté & administration",
        "text": "Le recensement se déroule du 15 janvier au 20 février.\nUn agent se présente à votre domicile avec une carte officielle ; il ne demande jamais de coordonnées bancaires.\nLa réponse est obligatoire, mais les données restent anonymes et servent uniquement aux statistiques.",
        "question_fr": "Quel comportement doit alerter un habitant ?",
        "options": [
            {"id": "a", "text": "Un agent qui présente une carte",
             "explanation": "That is exactly what a genuine agent does."},
            {"id": "b", "text": "Un agent qui demande des informations bancaires",
             "explanation": "« il ne demande jamais de coordonnées bancaires »."},
            {"id": "c", "text": "Un agent qui vient en février",
             "explanation": "The census runs until 20 February."},
            {"id": "d", "text": "Un agent qui pose des questions personnelles",
             "explanation": "Personal questions are the purpose; the answers stay anonymous."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Il ne demande jamais de coordonnées bancaires.",
        "key_line_en": "They never ask for bank details.",
        "vocabulary": [
            {"term": "un recensement", "gloss": "a census"},
            {"term": "des coordonnées bancaires", "gloss": "bank details"},
            {"term": "anonyme", "gloss": "anonymous"},
            {"term": "se présenter", "gloss": "to come, introduce oneself"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article de presse / Press article",
        "topic": "Vie quotidienne & logement",
        "text": "Un immeuble du centre a installé une laverie commune au rez-de-chaussée, financée par la copropriété.\nL'économie d'eau est réelle, mais ce n'est pas ce que citent les habitants : ils parlent surtout des vingt minutes d'attente pendant lesquelles on finit par se parler.",
        "question_fr": "Quel effet les habitants mettent-ils en avant ?",
        "options": [
            {"id": "a", "text": "L'économie d'eau réalisée",
             "explanation": "It is real but « ce n'est pas ce que citent les habitants »."},
            {"id": "b", "text": "Les rencontres entre voisins",
             "explanation": "They talk about the twenty minutes' wait « pendant lesquelles on finit par se parler »."},
            {"id": "c", "text": "La baisse des charges",
             "explanation": "No effect on service charges is described."},
            {"id": "d", "text": "Le gain de place dans les appartements",
             "explanation": "Space is not mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Ils parlent surtout des vingt minutes d'attente pendant lesquelles on finit par se parler.",
        "key_line_en": "They talk mostly about the twenty minutes' wait in which people end up talking to each other.",
        "vocabulary": [
            {"term": "une laverie", "gloss": "a laundry room"},
            {"term": "la copropriété", "gloss": "the owners' association"},
            {"term": "citer", "gloss": "to mention"},
            {"term": "finir par", "gloss": "to end up"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "topic": "Société, citoyenneté & administration",
        "text": "On oppose volontiers les experts et les citoyens, comme si les uns détenaient les faits et les autres les valeurs.\nLa réalité est moins commode : les experts arbitrent constamment entre des risques, ce qui est un jugement ; et les citoyens raisonnent sur des données, ce qui suppose des faits.",
        "question_fr": "Que conteste l'auteur ?",
        "options": [
            {"id": "a", "text": "La compétence des experts",
             "explanation": "Their competence is not in question; the division of labour attributed to them is."},
            {"id": "b", "text": "Une séparation nette entre faits et valeurs",
             "explanation": "Experts arbitrate risks (a judgement) and citizens reason on data (facts), so the neat split fails."},
            {"id": "c", "text": "La participation des citoyens",
             "explanation": "Citizens are credited with reasoning, not disqualified."},
            {"id": "d", "text": "L'existence de données fiables",
             "explanation": "Data reliability is never questioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les experts arbitrent constamment entre des risques, ce qui est un jugement.",
        "key_line_en": "Experts constantly arbitrate between risks, which is a judgement.",
        "vocabulary": [
            {"term": "détenir", "gloss": "to hold, possess"},
            {"term": "arbitrer", "gloss": "to weigh, decide between"},
            {"term": "commode", "gloss": "convenient"},
            {"term": "supposer", "gloss": "to presuppose"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "topic": "Loisirs, culture & médias",
        "text": "Le direct a repris le dessus sur la vidéo à la demande, contre toute attente.\nCe n'est pas le contenu qui l'explique, souvent médiocre, mais la simultanéité : savoir que des milliers de personnes regardent au même moment transforme un programme en événement.",
        "question_fr": "Qu'est-ce qui explique le retour du direct ?",
        "options": [
            {"id": "a", "text": "La qualité des programmes diffusés",
             "explanation": "The content is described as « souvent médiocre »."},
            {"id": "b", "text": "Le prix des abonnements",
             "explanation": "No price comparison appears."},
            {"id": "c", "text": "Le fait de regarder en même temps que d'autres",
             "explanation": "« la simultanéité […] transforme un programme en événement »."},
            {"id": "d", "text": "La disparition de la vidéo à la demande",
             "explanation": "On-demand still exists; live has simply regained ground."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Savoir que des milliers de personnes regardent au même moment transforme un programme en événement.",
        "key_line_en": "Knowing that thousands are watching at the same moment turns a programme into an event.",
        "vocabulary": [
            {"term": "le direct", "gloss": "live broadcasting"},
            {"term": "reprendre le dessus", "gloss": "to regain the upper hand"},
            {"term": "la simultanéité", "gloss": "simultaneity"},
            {"term": "médiocre", "gloss": "mediocre"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "topic": "Sciences & technologies",
        "text": "On oppose souvent le naturel au chimique, alors que tout ce qui existe est chimique.\nLa question utile n'est pas l'origine d'une molécule mais sa dose et son usage : une plante peut être toxique, une substance de laboratoire parfaitement inoffensive. Le mot « naturel » ne dit rien du risque.",
        "question_fr": "Quelle idée l'auteur veut-il corriger ?",
        "options": [
            {"id": "a", "text": "Que le naturel serait par principe sans danger",
             "explanation": "« Le mot “naturel” ne dit rien du risque »; a plant can be toxic and a lab substance harmless."},
            {"id": "b", "text": "Que les produits de laboratoire sont sûrs",
             "explanation": "Safety is said to depend on dose and use, not on origin — in either direction."},
            {"id": "c", "text": "Que la chimie est dangereuse",
             "explanation": "The point is that everything is chemical, so the category carries no verdict."},
            {"id": "d", "text": "Que les doses sont mal mesurées",
             "explanation": "Measurement is not questioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "La question utile n'est pas l'origine d'une molécule mais sa dose et son usage.",
        "key_line_en": "The useful question is not a molecule's origin but its dose and its use.",
        "vocabulary": [
            {"term": "une dose", "gloss": "a dose"},
            {"term": "inoffensif", "gloss": "harmless"},
            {"term": "toxique", "gloss": "toxic"},
            {"term": "un usage", "gloss": "a use"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "topic": "Travail & emploi",
        "text": "Bonjour,\nJe refuse le projet tel qu'il est présenté, et je veux être claire sur la raison : ce n'est pas le budget, c'est le calendrier.\nLivrer en septembre suppose de figer les besoins en juin, alors que le client change encore d'avis chaque semaine. Décalons, ou acceptons de livrer autre chose.",
        "question_fr": "Sur quoi porte le refus ?",
        "options": [
            {"id": "a", "text": "Sur le montant demandé",
             "explanation": "« ce n'est pas le budget » — money is explicitly excluded."},
            {"id": "b", "text": "Sur la qualité de l'équipe",
             "explanation": "The team is never discussed."},
            {"id": "c", "text": "Sur le calendrier proposé",
             "explanation": "Delivering in September means freezing requirements in June, which the client's indecision makes impossible."},
            {"id": "d", "text": "Sur le choix du client",
             "explanation": "The client's behaviour is a constraint cited, not the object of the refusal."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ce n'est pas le budget, c'est le calendrier.",
        "key_line_en": "It is not the budget, it is the schedule.",
        "vocabulary": [
            {"term": "figer", "gloss": "to freeze, fix"},
            {"term": "un besoin", "gloss": "a requirement"},
            {"term": "décaler", "gloss": "to shift, postpone"},
            {"term": "livrer", "gloss": "to deliver"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Analyse économique / Economic analysis",
        "topic": "Alimentation & consommation",
        "text": "Un produit vendu à perte attire des clients qui achètent le reste au prix fort : c'est le principe du produit d'appel.\nLe consommateur croit profiter d'une bonne affaire, et il en profite réellement — à condition de n'acheter que celui-là, ce que presque personne ne fait.",
        "question_fr": "Quelle est la position de l'auteur ?",
        "options": [
            {"id": "a", "text": "Le produit d'appel est une arnaque",
             "explanation": "The saving is genuine — « il en profite réellement » — under a condition."},
            {"id": "b", "text": "La bonne affaire n'est réelle que si l'on s'y limite",
             "explanation": "« à condition de n'acheter que celui-là, ce que presque personne ne fait »."},
            {"id": "c", "text": "Les magasins perdent de l'argent",
             "explanation": "The loss on one item is recouped on the rest of the basket."},
            {"id": "d", "text": "Les consommateurs ne sont jamais gagnants",
             "explanation": "They can be, if they buy only the loss-leader."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Il en profite réellement — à condition de n'acheter que celui-là, ce que presque personne ne fait.",
        "key_line_en": "They really do benefit — provided they buy only that one, which almost nobody does.",
        "vocabulary": [
            {"term": "à perte", "gloss": "at a loss"},
            {"term": "un produit d'appel", "gloss": "a loss-leader"},
            {"term": "au prix fort", "gloss": "at full price"},
            {"term": "une bonne affaire", "gloss": "a bargain"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "topic": "Environnement & nature",
        "text": "La rénovation thermique est présentée comme rentable, ce qu'elle est — sur vingt ans.\nOr le propriétaire qui paie les travaux n'est pas toujours celui qui paiera les factures, ni celui qui habitera encore là dans vingt ans. Le calcul est juste ; c'est la personne qui ne l'est pas.",
        "question_fr": "Quel obstacle l'auteur identifie-t-il ?",
        "options": [
            {"id": "a", "text": "Les travaux ne sont pas rentables",
             "explanation": "« ce qu'elle est — sur vingt ans » — profitability is granted."},
            {"id": "b", "text": "Les calculs sont mal faits",
             "explanation": "« Le calcul est juste »."},
            {"id": "c", "text": "Celui qui paie n'est pas celui qui en profite",
             "explanation": "« c'est la personne qui ne l'est pas » — the owner paying is not the one collecting the savings."},
            {"id": "d", "text": "Les locataires refusent les travaux",
             "explanation": "No refusal by tenants is described."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le calcul est juste ; c'est la personne qui ne l'est pas.",
        "key_line_en": "The calculation is right; it is the person who is not.",
        "vocabulary": [
            {"term": "rentable", "gloss": "profitable"},
            {"term": "une facture", "gloss": "a bill"},
            {"term": "juste", "gloss": "correct"},
            {"term": "la rénovation thermique", "gloss": "energy-efficiency renovation"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article société / Society article",
        "topic": "Transports & voyages",
        "text": "Les zones à faibles émissions écartent des centres-villes les véhicules les plus anciens, donc les moins chers.\nL'objectif sanitaire est réel et documenté. Il n'empêche : une politique qui améliore l'air respiré par ceux qui restent, en éloignant ceux qui partent, mérite au moins d'être nommée ainsi.",
        "question_fr": "Quelle réserve l'auteur formule-t-il ?",
        "options": [
            {"id": "a", "text": "La mesure n'améliore pas la qualité de l'air",
             "explanation": "« L'objectif sanitaire est réel et documenté »."},
            {"id": "b", "text": "La mesure a un effet social qu'il faut reconnaître",
             "explanation": "It improves the air « pour ceux qui restent, en éloignant ceux qui partent » — and that should be named."},
            {"id": "c", "text": "Les véhicules anciens polluent peu",
             "explanation": "Their emissions are the reason for the restriction, and are not contested."},
            {"id": "d", "text": "La mesure devrait être supprimée",
             "explanation": "No abolition is called for; honest naming is."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une politique qui améliore l'air respiré par ceux qui restent, en éloignant ceux qui partent, mérite au moins d'être nommée ainsi.",
        "key_line_en": "A policy that improves the air breathed by those who stay, by pushing out those who leave, deserves at least to be named as such.",
        "vocabulary": [
            {"term": "écarter", "gloss": "to keep out, exclude"},
            {"term": "sanitaire", "gloss": "health-related"},
            {"term": "il n'empêche", "gloss": "even so"},
            {"term": "éloigner", "gloss": "to push away"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "topic": "Sciences & technologies",
        "text": "Automatiser une tâche ne la supprime pas : cela la déplace vers celui qui doit surveiller la machine.\nSurveiller est pourtant le travail le plus ingrat qui soit, car il exige une attention continue pour un événement rare. L'humain y échoue, non par négligence, mais par construction.",
        "question_fr": "Pourquoi la surveillance est-elle un mauvais rôle pour l'humain ?",
        "options": [
            {"id": "a", "text": "Parce qu'elle demande une vigilance constante pour presque rien",
             "explanation": "« une attention continue pour un événement rare », où l'humain échoue « par construction »."},
            {"id": "b", "text": "Parce que les machines sont peu fiables",
             "explanation": "Machine reliability is not questioned; the rarity of failure is the difficulty."},
            {"id": "c", "text": "Parce que les opérateurs sont mal formés",
             "explanation": "« non par négligence » — the failure is structural, not a skills gap."},
            {"id": "d", "text": "Parce que la tâche a disparu",
             "explanation": "« Automatiser une tâche ne la supprime pas » — it moves."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'humain y échoue, non par négligence, mais par construction.",
        "key_line_en": "Humans fail at it, not through carelessness, but by design.",
        "vocabulary": [
            {"term": "ingrat", "gloss": "thankless"},
            {"term": "la vigilance", "gloss": "vigilance"},
            {"term": "par construction", "gloss": "by design, inherently"},
            {"term": "déplacer", "gloss": "to shift"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "topic": "Société, citoyenneté & administration",
        "text": "Le nouveau règlement intérieur tient en une page, ce dont on se réjouira sans réserve.\nIl renvoie, pour le détail, à quatre annexes, elles-mêmes complétées par une note d'application. L'ensemble atteint quarante-deux pages, mais la page de garde, elle, reste admirablement brève.",
        "question_fr": "Que met en évidence l'auteur ?",
        "options": [
            {"id": "a", "text": "Une simplification purement apparente",
             "explanation": "One page pointing to forty-two: the front page is short, the rules are not."},
            {"id": "b", "text": "Un règlement réellement simplifié",
             "explanation": "Only the cover page is brief, which the last clause makes ironic."},
            {"id": "c", "text": "Un règlement trop strict",
             "explanation": "The content of the rules is not judged, only their presentation."},
            {"id": "d", "text": "Un manque d'annexes explicatives",
             "explanation": "There are four annexes plus a note of application."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'ensemble atteint quarante-deux pages, mais la page de garde, elle, reste admirablement brève.",
        "key_line_en": "The whole thing runs to forty-two pages, but the cover page remains admirably brief.",
        "vocabulary": [
            {"term": "un règlement intérieur", "gloss": "internal rules"},
            {"term": "une annexe", "gloss": "an appendix"},
            {"term": "une page de garde", "gloss": "a cover page"},
            {"term": "renvoyer à", "gloss": "to refer to"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "topic": "Travail & emploi",
        "text": "On annonce la pénurie de main-d'œuvre comme un phénomène démographique, alors qu'elle est d'abord sectorielle.\nCertains métiers ne manquent pas de candidats : ils manquent de candidats disposés à ces conditions-là. Confondre les deux revient à traiter un problème de salaire comme un problème de population.",
        "question_fr": "Quelle confusion l'auteur dénonce-t-il ?",
        "options": [
            {"id": "a", "text": "Entre pénurie réelle et refus des conditions offertes",
             "explanation": "« ils manquent de candidats disposés à ces conditions-là »; confusing the two treats a pay problem as a population one."},
            {"id": "b", "text": "Entre secteurs publics et privés",
             "explanation": "No such split is discussed."},
            {"id": "c", "text": "Entre chômage et inactivité",
             "explanation": "Neither term appears in the argument."},
            {"id": "d", "text": "Entre démographie et immigration",
             "explanation": "Immigration is never mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Confondre les deux revient à traiter un problème de salaire comme un problème de population.",
        "key_line_en": "Confusing the two means treating a pay problem as a population problem.",
        "vocabulary": [
            {"term": "une pénurie", "gloss": "a shortage"},
            {"term": "la main-d'œuvre", "gloss": "the workforce"},
            {"term": "sectoriel", "gloss": "sector-specific"},
            {"term": "disposé à", "gloss": "willing to accept"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "topic": "Loisirs, culture & médias",
        "text": "Ils s'écrivaient chaque semaine, et chaque lettre disait à peu près la même chose.\nCe n'était pas de la pauvreté : c'était la seule manière qu'ils avaient trouvée de se dire qu'ils étaient encore là, sans avoir à le dire.",
        "question_fr": "Que révèle la répétition des lettres ?",
        "options": [
            {"id": "a", "text": "Qu'ils n'avaient plus rien à se dire",
             "explanation": "« Ce n'était pas de la pauvreté » — emptiness is expressly denied."},
            {"id": "b", "text": "Qu'ils s'écrivaient par obligation",
             "explanation": "No duty is described; the practice is presented as chosen."},
            {"id": "c", "text": "Qu'elle servait à confirmer une présence",
             "explanation": "« se dire qu'ils étaient encore là, sans avoir à le dire »."},
            {"id": "d", "text": "Qu'ils préparaient une rencontre",
             "explanation": "No meeting is mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "La seule manière qu'ils avaient trouvée de se dire qu'ils étaient encore là, sans avoir à le dire.",
        "key_line_en": "The only way they had found of telling each other they were still there, without having to say it.",
        "vocabulary": [
            {"term": "à peu près", "gloss": "roughly"},
            {"term": "la pauvreté", "gloss": "poverty, thinness"},
            {"term": "une manière", "gloss": "a way"},
            {"term": "encore là", "gloss": "still there"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse urbaine / Urban analysis",
        "topic": "Vie quotidienne & logement",
        "text": "Le quartier a été conçu d'un seul tenant, par un seul architecte, en trois ans.\nC'est sa cohérence qui le rend fatigant : rien n'y dépasse, rien n'y date d'ailleurs, aucune façade ne contredit la suivante. Une ville se supporte à condition qu'elle ait été faite par plusieurs personnes qui ne s'entendaient pas.",
        "question_fr": "Que reproche l'auteur à ce quartier ?",
        "options": [
            {"id": "a", "text": "Son mauvais entretien",
             "explanation": "Maintenance is not discussed."},
            {"id": "b", "text": "Son uniformité voulue",
             "explanation": "« C'est sa cohérence qui le rend fatigant »; a liveable city needs several disagreeing hands."},
            {"id": "c", "text": "Sa construction trop lente",
             "explanation": "Three years is fast for a district."},
            {"id": "d", "text": "Le manque de logements",
             "explanation": "Housing supply is not mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une ville se supporte à condition qu'elle ait été faite par plusieurs personnes qui ne s'entendaient pas.",
        "key_line_en": "A city is bearable provided it was made by several people who did not agree.",
        "vocabulary": [
            {"term": "d'un seul tenant", "gloss": "in one piece, all at once"},
            {"term": "dépasser", "gloss": "to stick out"},
            {"term": "contredire", "gloss": "to contradict"},
            {"term": "se supporter", "gloss": "to be bearable"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "topic": "Environnement & nature",
        "text": "Une canicule ne se définit pas par une température, mais par un écart : trente-cinq degrés n'ont pas le même effet à Lille et à Séville.\nCe qui tue n'est pas la chaleur en soi, c'est l'absence d'habitude — des corps, mais aussi des bâtiments et des services.",
        "question_fr": "Qu'est-ce qui rend une canicule dangereuse ?",
        "options": [
            {"id": "a", "text": "Le fait qu'elle soit inhabituelle pour le lieu",
             "explanation": "« Ce qui tue […] c'est l'absence d'habitude », of bodies, buildings and services alike."},
            {"id": "b", "text": "Le niveau absolu de température",
             "explanation": "Thirty-five degrees differ in effect between Lille and Seville."},
            {"id": "c", "text": "La durée de l'épisode",
             "explanation": "Duration is not part of the definition given."},
            {"id": "d", "text": "L'état des services de santé seuls",
             "explanation": "Services are one of three factors, not the sole one."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Ce qui tue n'est pas la chaleur en soi, c'est l'absence d'habitude.",
        "key_line_en": "What kills is not the heat itself, it is the absence of habituation.",
        "vocabulary": [
            {"term": "une canicule", "gloss": "a heatwave"},
            {"term": "un écart", "gloss": "a deviation, gap"},
            {"term": "en soi", "gloss": "in itself"},
            {"term": "l'habitude", "gloss": "habituation, custom"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Commentaire institutionnel / Institutional commentary",
        "topic": "Santé & bien-être",
        "text": "Le rapport recommande de renforcer la prévention, et chiffre les économies attendues à horizon quinze ans.\nAucun budget public ne se vote à quinze ans. Recommander une dépense dont le bénéfice excède la durée du mandat, c'est recommander à personne.",
        "question_fr": "Quelle difficulté l'auteur souligne-t-il ?",
        "options": [
            {"id": "a", "text": "Les économies annoncées sont surestimées",
             "explanation": "The figures are not challenged; their horizon is."},
            {"id": "b", "text": "La prévention est inefficace",
             "explanation": "Its effectiveness is assumed by the report and not disputed."},
            {"id": "c", "text": "L'horizon du bénéfice dépasse celui de la décision",
             "explanation": "« Recommander une dépense dont le bénéfice excède la durée du mandat, c'est recommander à personne »."},
            {"id": "d", "text": "Le rapport manque de chiffres",
             "explanation": "It quantifies the expected savings."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Recommander une dépense dont le bénéfice excède la durée du mandat, c'est recommander à personne.",
        "key_line_en": "To recommend spending whose benefit outlasts the term of office is to recommend it to nobody.",
        "vocabulary": [
            {"term": "chiffrer", "gloss": "to quantify"},
            {"term": "à horizon", "gloss": "over a horizon of"},
            {"term": "un mandat", "gloss": "a term of office"},
            {"term": "excéder", "gloss": "to exceed"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la lecture / Essay on reading",
        "topic": "Loisirs, culture & médias",
        "text": "On cite pour être cru, rarement pour être compris.\nLa citation apporte l'autorité d'un nom là où manquait celle d'un argument ; elle interrompt l'examen au lieu de l'ouvrir. Le lecteur qui s'incline devant elle a cessé de lire au moment précis où il croyait le mieux le faire.",
        "question_fr": "Que reproche l'auteur à l'usage de la citation ?",
        "options": [
            {"id": "a", "text": "Elle déforme la pensée des auteurs",
             "explanation": "Fidelity to the source is not the objection; the function of quoting is."},
            {"id": "b", "text": "Elle remplace l'argument par l'autorité",
             "explanation": "« l'autorité d'un nom là où manquait celle d'un argument […] elle interrompt l'examen »."},
            {"id": "c", "text": "Elle est trop rarement employée",
             "explanation": "The essay describes it as over-used, not scarce."},
            {"id": "d", "text": "Elle rend les textes trop longs",
             "explanation": "Length is never mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Le lecteur qui s'incline devant elle a cessé de lire au moment précis où il croyait le mieux le faire.",
        "key_line_en": "The reader who bows to it has stopped reading at the very moment they thought they were reading best.",
        "vocabulary": [
            {"term": "s'incliner", "gloss": "to bow, defer"},
            {"term": "l'examen", "gloss": "scrutiny"},
            {"term": "interrompre", "gloss": "to interrupt"},
            {"term": "une citation", "gloss": "a quotation"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "topic": "Société, citoyenneté & administration",
        "text": "Une institution se juge à ce qu'elle fait quand personne ne regarde, non à ce qu'elle publie quand tout le monde regarde.\nLes chartes, les serments et les déclarations coûtent peu ; le seul engagement qui pèse est celui dont le manquement se verrait, et se paierait.",
        "question_fr": "Quel critère l'auteur retient-il ?",
        "options": [
            {"id": "a", "text": "La clarté des déclarations publiées",
             "explanation": "Declarations « coûtent peu » and are set aside as evidence."},
            {"id": "b", "text": "La réputation de l'institution",
             "explanation": "Reputation is what publication buys; the essay looks past it."},
            {"id": "c", "text": "L'existence de sanctions en cas de manquement",
             "explanation": "« le seul engagement qui pèse est celui dont le manquement se verrait, et se paierait »."},
            {"id": "d", "text": "L'ancienneté de l'institution",
             "explanation": "Age is never mentioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le seul engagement qui pèse est celui dont le manquement se verrait, et se paierait.",
        "key_line_en": "The only commitment that carries weight is the one whose breach would be seen, and would be paid for.",
        "vocabulary": [
            {"term": "un serment", "gloss": "an oath"},
            {"term": "un manquement", "gloss": "a breach"},
            {"term": "peser", "gloss": "to carry weight"},
            {"term": "une charte", "gloss": "a charter"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "topic": "Sciences & technologies",
        "text": "L'erreur féconde n'est pas celle qu'on corrige, c'est celle qui oblige à changer la question.\nUne expérience ratée dont on tire une meilleure méthode a produit davantage qu'une expérience réussie qui confirme ce qu'on savait — et l'on continue pourtant à ne publier que la seconde.",
        "question_fr": "Que reproche l'auteur à la pratique actuelle ?",
        "options": [
            {"id": "a", "text": "Elle ignore ce que les échecs apprennent",
             "explanation": "A failed experiment yielding a better method produces more, « et l'on continue pourtant à ne publier que la seconde »."},
            {"id": "b", "text": "Elle publie trop d'expériences ratées",
             "explanation": "The opposite: only the successful ones are published."},
            {"id": "c", "text": "Elle corrige trop rarement les erreurs",
             "explanation": "Correction is not the valued response here; changing the question is."},
            {"id": "d", "text": "Elle confirme des résultats faux",
             "explanation": "The confirmed results are not said to be wrong, merely already known."},
        ],
        "correct_answer": "a",
        "key_line_fr": "L'erreur féconde n'est pas celle qu'on corrige, c'est celle qui oblige à changer la question.",
        "key_line_en": "The fruitful error is not the one you correct, it is the one that forces you to change the question.",
        "vocabulary": [
            {"term": "fécond", "gloss": "fruitful"},
            {"term": "raté", "gloss": "failed"},
            {"term": "tirer de", "gloss": "to draw from"},
            {"term": "confirmer", "gloss": "to confirm"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "topic": "Vie quotidienne & logement",
        "text": "Le marché du samedi occupe la place depuis deux siècles, sans qu'aucun règlement ne l'y oblige.\nC'est ce qui le rend fragile : ce qui tient par l'habitude ne se défend pas le jour où l'habitude est contestée, faute d'un texte auquel se référer.",
        "question_fr": "Pourquoi le marché est-il fragile, selon l'auteur ?",
        "options": [
            {"id": "a", "text": "Parce qu'il attire trop peu de monde",
             "explanation": "Attendance is not discussed."},
            {"id": "b", "text": "Parce que la place est trop petite",
             "explanation": "The square's size is never mentioned."},
            {"id": "c", "text": "Parce qu'il repose sur un usage non écrit",
             "explanation": "« ce qui tient par l'habitude ne se défend pas […] faute d'un texte auquel se référer »."},
            {"id": "d", "text": "Parce qu'il existe depuis trop longtemps",
             "explanation": "Its age is what built the habit, not what weakens it."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ce qui tient par l'habitude ne se défend pas le jour où l'habitude est contestée.",
        "key_line_en": "What holds by custom cannot be defended on the day the custom is challenged.",
        "vocabulary": [
            {"term": "un usage", "gloss": "a custom, practice"},
            {"term": "contester", "gloss": "to challenge"},
            {"term": "se référer à", "gloss": "to refer to"},
            {"term": "faute de", "gloss": "for want of"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Critique de théâtre / Theatre review",
        "topic": "Loisirs, culture & médias",
        "text": "La pièce dure une heure et l'on en sort comme d'un examen réussi : content, et sans rien à en dire.\nTout y était juste, et rien n'y était risqué. À vouloir ne déplaire à personne, on finit par n'atteindre personne en particulier.",
        "question_fr": "Que reproche le critique à cette pièce ?",
        "options": [
            {"id": "a", "text": "Sa prudence l'empêche de toucher quiconque",
             "explanation": "« À vouloir ne déplaire à personne, on finit par n'atteindre personne en particulier »."},
            {"id": "b", "text": "Ses erreurs de mise en scène",
             "explanation": "« Tout y était juste » — nothing is wrong."},
            {"id": "c", "text": "Sa durée excessive",
             "explanation": "One hour is not presented as too long."},
            {"id": "d", "text": "Son sujet trop provocateur",
             "explanation": "The complaint is the absence of risk, not an excess of it."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Tout y était juste, et rien n'y était risqué.",
        "key_line_en": "Everything in it was right, and nothing in it was risked.",
        "vocabulary": [
            {"term": "juste", "gloss": "right, accurate"},
            {"term": "risquer", "gloss": "to risk"},
            {"term": "déplaire à", "gloss": "to displease"},
            {"term": "atteindre", "gloss": "to reach, affect"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la parole / Essay on speech",
        "topic": "Société, citoyenneté & administration",
        "text": "Se taire n'est pas ne rien dire : dans une assemblée, le silence de celui qu'on attend vaut position.\nAussi la neutralité n'existe-t-elle pas au moment du vote ; elle n'existe qu'avant, quand il est encore possible d'écouter sans que ce silence soit compté.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Le silence est toujours une forme de lâcheté",
             "explanation": "No moral judgement is passed; the claim is about how silence is read."},
            {"id": "b", "text": "La neutralité est impossible au moment de décider",
             "explanation": "« le silence de celui qu'on attend vaut position »; neutrality survives only before the vote."},
            {"id": "c", "text": "Il faut toujours prendre la parole",
             "explanation": "The essay values listening beforehand; it prescribes no duty to speak."},
            {"id": "d", "text": "Le vote devrait être secret",
             "explanation": "Voting procedure is not discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Dans une assemblée, le silence de celui qu'on attend vaut position.",
        "key_line_en": "In an assembly, the silence of the person everyone is waiting for counts as a position.",
        "vocabulary": [
            {"term": "se taire", "gloss": "to keep silent"},
            {"term": "valoir", "gloss": "to count as"},
            {"term": "la neutralité", "gloss": "neutrality"},
            {"term": "compter", "gloss": "to count, be counted"},
        ],
    },
]

QUESTIONS = balance(_RAW)
