"""Compréhension écrite — Test 05.

Forty questions climbing A1 → C2, the ordering the real TCF uses: the paper
starts with notes and signs and ends with irony and abstract argument, so a
candidate meets their ceiling rather than being stopped at the first hard item.

Distribution: A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
"""

QUESTIONS = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # Notes, signs, opening hours. One piece of information, stated outright.
    # ------------------------------------------------------------------
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Note personnelle / Personal note",
        "text": "Maman,\nJe fais mes devoirs de mathématiques chez Louise. Je rentre à 21 heures. Bises et à ce soir.\nPatrick",
        "question_fr": "Qu'est-ce que Patrick fait chez Louise ?",
        "question_en": "What is Patrick doing at Louise's?",
        "options": [
            {"id": "a", "text": "Il mange", "text_en": "He is eating",
             "explanation": "No food is mentioned. « Je rentre à 21 heures » only tells us the time he comes back."},
            {"id": "b", "text": "Il dort", "text_en": "He is sleeping",
             "explanation": "Nothing in the note mentions sleeping. Patrick says he is coming home at 9 p.m., so he is not staying the night."},
            {"id": "c", "text": "Il joue", "text_en": "He is playing",
             "explanation": "Homework is a school task, not play. This is the trap answer: many people assume a child at a friend's house is playing."},
            {"id": "d", "text": "Il travaille", "text_en": "He is working / studying",
             "explanation": "« faire ses devoirs » (to do homework) is study work. In French, school work belongs to the verb « travailler »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Je fais mes devoirs de mathématiques chez Louise.",
        "key_line_en": "I am doing my maths homework at Louise's.",
        "vocabulary": [
            {"term": "faire ses devoirs", "gloss": "to do homework"},
            {"term": "rentrer", "gloss": "to go/come home"},
            {"term": "à ce soir", "gloss": "see you tonight"},
            {"term": "bises", "gloss": "kisses (informal sign-off)"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Affiche / Notice",
        "text": "Attention,\nCette semaine, l'accueil de l'université est fermé lundi toute la journée et vendredi après-midi.",
        "question_fr": "À quoi sert cette affiche ?",
        "question_en": "What is the purpose of this notice?",
        "options": [
            {"id": "a", "text": "Décrire un endroit", "text_en": "To describe a place",
             "explanation": "The reception is named, but nothing describes what it looks like (size, colour, location)."},
            {"id": "b", "text": "Annoncer un changement", "text_en": "To announce a change",
             "explanation": "Giving special closing times for this week only announces a change to the normal schedule."},
            {"id": "c", "text": "Donner un rendez-vous", "text_en": "To give an appointment",
             "explanation": "No appointment is offered to anyone; the notice is addressed to everybody, not one person."},
            {"id": "d", "text": "Organiser une réunion", "text_en": "To organise a meeting",
             "explanation": "No meeting, no participants and no meeting room are mentioned."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Cette semaine, l'accueil de l'université est fermé lundi toute la journée et vendredi après-midi.",
        "key_line_en": "This week the university reception is closed all day Monday and Friday afternoon.",
        "vocabulary": [
            {"term": "l'accueil", "gloss": "reception / front desk"},
            {"term": "fermé", "gloss": "closed"},
            {"term": "une affiche", "gloss": "poster, notice"},
            {"term": "toute la journée", "gloss": "all day long"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Horaires de magasin / Shop opening hours",
        "text": "BOULANGERIE MARTIN\nOuvert du mardi au dimanche, de 7 h à 19 h 30.\nFermé le lundi.",
        "question_fr": "Quand la boulangerie est-elle fermée ?",
        "question_en": "When is the bakery closed?",
        "options": [
            {"id": "a", "text": "Le dimanche", "text_en": "On Sunday",
             "explanation": "« du mardi au dimanche » (from Tuesday to Sunday) includes Sunday, so it is open."},
            {"id": "b", "text": "À 7 heures", "text_en": "At 7 o'clock",
             "explanation": "7 h is the opening time, not the closing time. Closing is 19 h 30."},
            {"id": "c", "text": "Le lundi", "text_en": "On Monday",
             "explanation": "The last line says it directly: « Fermé le lundi »."},
            {"id": "d", "text": "Le samedi matin", "text_en": "On Saturday morning",
             "explanation": "Saturday is between Tuesday and Sunday, and the shop opens at 7 a.m., so the morning is open."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Fermé le lundi.",
        "key_line_en": "Closed on Mondays.",
        "vocabulary": [
            {"term": "ouvert / fermé", "gloss": "open / closed"},
            {"term": "du … au …", "gloss": "from … to …"},
            {"term": "19 h 30", "gloss": "7:30 p.m."},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "SMS",
        "text": "Salut Léa,\nJe suis à la gare. Mon train a 20 minutes de retard. On se voit à 18 h 30 au café, pas à 18 h.\nTom",
        "question_fr": "Pourquoi Tom écrit-il ce message ?",
        "question_en": "Why is Tom writing this message?",
        "options": [
            {"id": "a", "text": "Pour inviter Léa au restaurant", "text_en": "To invite Léa to a restaurant",
             "explanation": "« café » is the meeting point, and no invitation is made."},
            {"id": "b", "text": "Pour demander une adresse", "text_en": "To ask for an address",
             "explanation": "There is no question in the message; the place (le café) is already known."},
            {"id": "c", "text": "Pour annuler le rendez-vous", "text_en": "To cancel the meeting",
             "explanation": "He keeps the meeting; he only moves it later. « On se voit » = we are still meeting."},
            {"id": "d", "text": "Pour changer l'heure du rendez-vous", "text_en": "To change the time of the meeting",
             "explanation": "« à 18 h 30, pas à 18 h » clearly replaces the old time with a new one."},
        ],
        "correct_answer": "d",
        "key_line_fr": "On se voit à 18 h 30 au café, pas à 18 h.",
        "key_line_en": "Let's meet at 6:30 p.m. at the café, not at 6 p.m.",
        "vocabulary": [
            {"term": "avoir du retard", "gloss": "to be late"},
            {"term": "la gare", "gloss": "train station"},
            {"term": "on se voit", "gloss": "see you / let's meet"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Panneau d'immeuble / Building sign",
        "text": "AVIS AUX HABITANTS\nL'ascenseur est en panne. Merci d'utiliser l'escalier.\nRéparation prévue jeudi.",
        "question_fr": "Que doivent faire les habitants ?",
        "question_en": "What must the residents do?",
        "options": [
            {"id": "a", "text": "Monter par l'escalier", "text_en": "Use the stairs",
             "explanation": "« Merci d'utiliser l'escalier » is a polite instruction: please use the stairs."},
            {"id": "b", "text": "Sortir de l'immeuble", "text_en": "Leave the building",
             "explanation": "This is not an emergency notice; nobody is asked to evacuate."},
            {"id": "c", "text": "Appeler le gardien", "text_en": "Call the caretaker",
             "explanation": "Nobody is asked to phone anyone; the repair is already planned."},
            {"id": "d", "text": "Prendre l'ascenseur", "text_en": "Take the lift",
             "explanation": "The lift is « en panne » (out of order), so it cannot be used."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Merci d'utiliser l'escalier.",
        "key_line_en": "Please use the stairs.",
        "vocabulary": [
            {"term": "en panne", "gloss": "out of order, broken down"},
            {"term": "l'ascenseur", "gloss": "lift, elevator"},
            {"term": "l'escalier", "gloss": "stairs"},
            {"term": "merci de + infinitif", "gloss": "please do…"},
        ],
    },
    {
        "level": "A1",
        "band": "100 – 199 points",
        "doc_type": "Courriel amical / Friendly e-mail",
        "text": "Chère Sofia,\nC'est mon anniversaire samedi. Je fais une petite fête chez moi à 20 heures. Tu viens ?\nBises, Nadia",
        "question_fr": "Que fait Nadia dans ce message ?",
        "question_en": "What is Nadia doing in this message?",
        "options": [
            {"id": "a", "text": "Elle invite Sofia", "text_en": "She is inviting Sofia",
             "explanation": "« Je fais une petite fête… Tu viens ? » is a direct invitation."},
            {"id": "b", "text": "Elle s'excuse", "text_en": "She is apologising",
             "explanation": "No apology expression (« désolée », « pardon ») appears."},
            {"id": "c", "text": "Elle remercie Sofia", "text_en": "She is thanking Sofia",
             "explanation": "There is no « merci » and Sofia has not done anything yet."},
            {"id": "d", "text": "Elle refuse une invitation", "text_en": "She is refusing an invitation",
             "explanation": "Nadia is the one organising the party, so she gives the invitation, she does not receive it."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Je fais une petite fête chez moi à 20 heures. Tu viens ?",
        "key_line_en": "I'm having a little party at my place at 8 p.m. Are you coming?",
        "vocabulary": [
            {"term": "un anniversaire", "gloss": "birthday"},
            {"term": "une fête", "gloss": "party"},
            {"term": "chez moi", "gloss": "at my place"},
            {"term": "Tu viens ?", "gloss": "Are you coming?"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # Ads, formal e-mails, instructions, rules. Two pieces of information
    # to combine.
    # ------------------------------------------------------------------
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Petite annonce / Classified ad",
        "text": "À LOUER\nStudio meublé 25 m², proche du centre-ville.\n450 € par mois, charges comprises.\nLibre à partir du 1er septembre. Animaux non acceptés.",
        "question_fr": "Que comprend le prix de 450 € ?",
        "question_en": "What does the price of €450 include?",
        "options": [
            {"id": "a", "text": "Le loyer seulement", "text_en": "The rent only",
             "explanation": "« charges comprises » means extra costs (water, building fees…) are already inside the price."},
            {"id": "b", "text": "Le loyer et les meubles à acheter", "text_en": "The rent plus furniture to buy",
             "explanation": "« meublé » means it is already furnished; nothing is sold to the tenant."},
            {"id": "c", "text": "Le loyer et l'assurance", "text_en": "The rent and the insurance",
             "explanation": "Insurance (« assurance ») is never mentioned; do not confuse it with « charges »."},
            {"id": "d", "text": "Le loyer et les charges", "text_en": "The rent and the service charges",
             "explanation": "« charges comprises » = charges included, i.e. rent + charges for €450."},
        ],
        "correct_answer": "d",
        "key_line_fr": "450 € par mois, charges comprises.",
        "key_line_en": "€450 per month, service charges included.",
        "vocabulary": [
            {"term": "meublé", "gloss": "furnished"},
            {"term": "les charges", "gloss": "service charges"},
            {"term": "compris(es)", "gloss": "included"},
            {"term": "libre à partir du", "gloss": "available from"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Courriel formel / Formal e-mail",
        "text": "Madame, Monsieur,\nJ'ai réservé une chambre pour deux nuits, du 12 au 14 mai. Je dois finalement arriver le 13 au lieu du 12. Pouvez-vous modifier ma réservation ?\nCordialement, M. Berger",
        "question_fr": "Que demande M. Berger ?",
        "question_en": "What is Mr Berger asking for?",
        "options": [
            {"id": "a", "text": "De réserver une deuxième chambre", "text_en": "To book a second room",
             "explanation": "Only « une chambre » is mentioned, and he asks nothing extra."},
            {"id": "b", "text": "D'annuler sa réservation", "text_en": "To cancel his booking",
             "explanation": "He keeps the booking; « modifier » (to change) is not « annuler » (to cancel)."},
            {"id": "c", "text": "D'obtenir un remboursement", "text_en": "To get a refund",
             "explanation": "No money question appears in the message."},
            {"id": "d", "text": "De changer la date d'arrivée", "text_en": "To change the arrival date",
             "explanation": "« arriver le 13 au lieu du 12 » plus « modifier ma réservation » = a change of date."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Je dois finalement arriver le 13 au lieu du 12. Pouvez-vous modifier ma réservation ?",
        "key_line_en": "I now have to arrive on the 13th instead of the 12th. Could you change my booking?",
        "vocabulary": [
            {"term": "au lieu de", "gloss": "instead of"},
            {"term": "modifier", "gloss": "to change, amend"},
            {"term": "finalement", "gloss": "in the end"},
            {"term": "cordialement", "gloss": "kind regards"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Notice de médicament / Medicine instructions",
        "text": "SIROP TOUXNET\n1 cuillère le matin et 1 cuillère le soir, après les repas.\nNe pas dépasser 5 jours de traitement.\nDéconseillé aux enfants de moins de 6 ans.",
        "question_fr": "Comment faut-il prendre ce médicament ?",
        "question_en": "How must this medicine be taken?",
        "options": [
            {"id": "a", "text": "Une seule fois par jour", "text_en": "Only once a day",
             "explanation": "Two doses are listed: « le matin » and « le soir »."},
            {"id": "b", "text": "Deux fois par jour, après avoir mangé", "text_en": "Twice a day, after eating",
             "explanation": "Morning + evening = twice a day, and « après les repas » = after eating."},
            {"id": "c", "text": "Pendant au moins 5 jours", "text_en": "For at least 5 days",
             "explanation": "« ne pas dépasser 5 jours » sets a maximum, not a minimum."},
            {"id": "d", "text": "Avant les repas", "text_en": "Before meals",
             "explanation": "The text says « après les repas » (after meals). This tests the pair avant / après."},
        ],
        "correct_answer": "b",
        "key_line_fr": "1 cuillère le matin et 1 cuillère le soir, après les repas.",
        "key_line_en": "One spoonful in the morning and one in the evening, after meals.",
        "vocabulary": [
            {"term": "une cuillère", "gloss": "a spoonful"},
            {"term": "dépasser", "gloss": "to exceed"},
            {"term": "déconseillé à", "gloss": "not recommended for"},
            {"term": "un traitement", "gloss": "a course of treatment"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Note de service / Workplace memo",
        "text": "NOTE AU PERSONNEL\nEn raison de travaux, le parking de l'entreprise sera inaccessible du 3 au 7 mars.\nUn parking gratuit est mis à votre disposition rue des Lilas, à 5 minutes à pied.",
        "question_fr": "Que propose l'entreprise pendant les travaux ?",
        "question_en": "What is the company offering during the works?",
        "options": [
            {"id": "a", "text": "De travailler à la maison", "text_en": "To work from home",
             "explanation": "No mention of télétravail; only parking is affected."},
            {"id": "b", "text": "Un autre parking sans frais", "text_en": "Another car park at no cost",
             "explanation": "« un parking gratuit… rue des Lilas » = a free alternative car park."},
            {"id": "c", "text": "De venir en transport en commun", "text_en": "To come by public transport",
             "explanation": "Buses and trains are never mentioned; the solution offered is another car park."},
            {"id": "d", "text": "De payer un parking privé", "text_en": "To pay for a private car park",
             "explanation": "« gratuit » means free of charge, the opposite of paying."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un parking gratuit est mis à votre disposition rue des Lilas.",
        "key_line_en": "A free car park is made available to you on rue des Lilas.",
        "vocabulary": [
            {"term": "en raison de", "gloss": "because of"},
            {"term": "des travaux", "gloss": "building works"},
            {"term": "gratuit", "gloss": "free of charge"},
            {"term": "mettre à disposition", "gloss": "to make available"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Message de forum / Forum post",
        "text": "Bonjour à tous,\nJe cherche quelqu'un pour partager les frais d'essence. Je vais à Lyon tous les vendredis soir et je reviens le dimanche. Départ à 18 h de Grenoble.\nContactez-moi en message privé.",
        "question_fr": "Que propose cette personne ?",
        "question_en": "What is this person offering?",
        "options": [
            {"id": "a", "text": "De vendre sa voiture", "text_en": "To sell her car",
             "explanation": "She uses the car every week; nothing is for sale."},
            {"id": "b", "text": "Des cours de conduite", "text_en": "Driving lessons",
             "explanation": "No teaching or lessons are mentioned, only a journey."},
            {"id": "c", "text": "Un covoiturage régulier", "text_en": "A regular car-sharing arrangement",
             "explanation": "Same trip every week + sharing petrol costs = covoiturage (car-sharing)."},
            {"id": "d", "text": "Un emploi de chauffeur", "text_en": "A job as a driver",
             "explanation": "She is not hiring anyone and is not paid; costs are only shared."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Je cherche quelqu'un pour partager les frais d'essence.",
        "key_line_en": "I'm looking for someone to share the petrol costs.",
        "vocabulary": [
            {"term": "partager", "gloss": "to share"},
            {"term": "les frais", "gloss": "costs, expenses"},
            {"term": "l'essence", "gloss": "petrol"},
            {"term": "le covoiturage", "gloss": "car-sharing"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Règlement / Rules",
        "text": "MÉDIATHÈQUE MUNICIPALE — RÈGLEMENT\nLa médiathèque prête 5 documents pour 3 semaines.\nTout retard entraîne la suspension de la carte pendant une durée égale au retard.",
        "question_fr": "Que se passe-t-il si on rend les documents en retard ?",
        "question_en": "What happens if you return the items late?",
        "options": [
            {"id": "a", "text": "On ne peut plus emprunter pendant un certain temps", "text_en": "You cannot borrow for a certain period",
             "explanation": "« suspension de la carte » means the card is blocked for a while."},
            {"id": "b", "text": "On paie une amende", "text_en": "You pay a fine",
             "explanation": "No money is mentioned; the penalty is a suspension, not a fine."},
            {"id": "c", "text": "On doit racheter les documents", "text_en": "You must buy the items back",
             "explanation": "Buying replacements applies to lost items, which are not discussed here."},
            {"id": "d", "text": "On perd sa carte définitivement", "text_en": "You lose your card permanently",
             "explanation": "The suspension is temporary: it lasts as long as the delay."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Tout retard entraîne la suspension de la carte pendant une durée égale au retard.",
        "key_line_en": "Any delay leads to the card being suspended for a period equal to the delay.",
        "vocabulary": [
            {"term": "emprunter", "gloss": "to borrow"},
            {"term": "un retard", "gloss": "a delay"},
            {"term": "entraîner", "gloss": "to lead to, cause"},
            {"term": "une durée", "gloss": "a length of time"},
        ],
    },
    {
        "level": "A2",
        "band": "200 – 299 points",
        "doc_type": "Avis de passage / Delivery notice",
        "text": "AVIS DE PASSAGE\nNous sommes passés à votre domicile aujourd'hui à 10 h 15 en votre absence.\nVotre colis est disponible au bureau de poste de la rue Victor-Hugo à partir de demain 9 h, pendant 10 jours.\nMunissez-vous d'une pièce d'identité.",
        "question_fr": "Que doit faire le destinataire pour récupérer son colis ?",
        "question_en": "What must the addressee do to collect the parcel?",
        "options": [
            {"id": "a", "text": "Payer des frais supplémentaires", "text_en": "Pay an extra charge",
             "explanation": "No payment is mentioned; only a deadline of 10 days."},
            {"id": "b", "text": "Téléphoner au bureau de poste", "text_en": "Phone the post office",
             "explanation": "No phone number and no instruction to call appear on the notice."},
            {"id": "c", "text": "Aller à la poste avec un document d'identité", "text_en": "Go to the post office with an ID document",
             "explanation": "The place is given (bureau de poste, rue Victor-Hugo) and « munissez-vous d'une pièce d'identité » states what to bring."},
            {"id": "d", "text": "Attendre une nouvelle livraison à domicile", "text_en": "Wait for another home delivery",
             "explanation": "No second delivery is announced; the parcel is now waiting at the post office."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Votre colis est disponible au bureau de poste […]. Munissez-vous d'une pièce d'identité.",
        "key_line_en": "Your parcel is available at the post office […]. Please bring proof of identity.",
        "vocabulary": [
            {"term": "un colis", "gloss": "a parcel"},
            {"term": "un avis de passage", "gloss": "delivery attempt notice"},
            {"term": "se munir de", "gloss": "to bring, equip oneself with"},
            {"term": "une pièce d'identité", "gloss": "ID document"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # Press articles, surveys, letters of complaint. The main idea and the
    # reason behind it.
    # ------------------------------------------------------------------
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Article de presse / Press article",
        "text": "Depuis trois ans, l'épicerie Le Vrac propose des produits sans emballage : les clients viennent avec leurs propres bocaux.\n« Au début, les gens trouvaient ça compliqué », raconte la gérante. « Aujourd'hui, ils y pensent naturellement, et leur facture a même baissé, car ils achètent seulement la quantité dont ils ont besoin. »",
        "question_fr": "D'après la gérante, pourquoi les clients dépensent-ils moins ?",
        "question_en": "According to the manager, why do customers spend less?",
        "options": [
            {"id": "a", "text": "Ils reçoivent une réduction pour leurs bocaux", "text_en": "They get a discount for bringing jars",
             "explanation": "The jars are needed for packaging-free shopping, but no discount is attached to them."},
            {"id": "b", "text": "Ils achètent uniquement la quantité nécessaire", "text_en": "They buy only the quantity they need",
             "explanation": "The manager gives the reason herself with « car » : « ils achètent seulement la quantité dont ils ont besoin »."},
            {"id": "c", "text": "Les produits sont moins chers qu'ailleurs", "text_en": "The products are cheaper than elsewhere",
             "explanation": "No price comparison with other shops is made. The saving comes from quantity, not from unit price."},
            {"id": "d", "text": "Le magasin fait souvent des promotions", "text_en": "The shop often runs special offers",
             "explanation": "Promotions are never mentioned in the text."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Leur facture a même baissé, car ils achètent seulement la quantité dont ils ont besoin.",
        "key_line_en": "Their bill has even gone down, because they only buy the quantity they need.",
        "vocabulary": [
            {"term": "l'emballage", "gloss": "packaging"},
            {"term": "un bocal / des bocaux", "gloss": "jar(s)"},
            {"term": "la facture", "gloss": "the bill"},
            {"term": "baisser", "gloss": "to go down"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "text": "Une enquête menée auprès de 2 000 salariés montre que le télétravail est surtout apprécié pour le temps de trajet économisé.\nToutefois, un tiers des personnes interrogées déclarent avoir du mal à séparer vie professionnelle et vie privée.",
        "question_fr": "Quel inconvénient du télétravail le texte souligne-t-il ?",
        "question_en": "What drawback of remote work does the text point out?",
        "options": [
            {"id": "a", "text": "La difficulté à séparer travail et vie personnelle", "text_en": "The difficulty of separating work and private life",
             "explanation": "« Toutefois » introduces the drawback, then states it explicitly: « du mal à séparer vie professionnelle et vie privée »."},
            {"id": "b", "text": "Le manque de matériel informatique", "text_en": "A lack of computer equipment",
             "explanation": "Equipment is never mentioned; this is a plausible but invented idea."},
            {"id": "c", "text": "Les trajets trop longs", "text_en": "Journeys that are too long",
             "explanation": "The opposite: shorter commuting is presented as the main advantage."},
            {"id": "d", "text": "La perte de salaire", "text_en": "Loss of salary",
             "explanation": "Pay is not discussed anywhere in the extract."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Un tiers des personnes interrogées déclarent avoir du mal à séparer vie professionnelle et vie privée.",
        "key_line_en": "A third of respondents say they find it hard to separate work life from private life.",
        "vocabulary": [
            {"term": "une enquête", "gloss": "a survey"},
            {"term": "un trajet", "gloss": "a commute, journey"},
            {"term": "toutefois", "gloss": "however"},
            {"term": "avoir du mal à", "gloss": "to find it hard to"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Lettre de réclamation / Letter of complaint",
        "text": "Madame, Monsieur,\nLe 4 juin, j'ai commandé sur votre site une machine à café. Livrée le 12 juin, elle ne fonctionne pas : l'eau ne chauffe pas. J'ai appelé votre service client à trois reprises, sans obtenir de réponse.\nJe vous demande donc le remplacement de l'appareil sous quinze jours, faute de quoi je demanderai le remboursement intégral.",
        "question_fr": "Que demande le client en priorité ?",
        "question_en": "What is the customer asking for first?",
        "options": [
            {"id": "a", "text": "Être remboursé immédiatement", "text_en": "To be refunded immediately",
             "explanation": "The refund is only the second step: « faute de quoi » = failing that, if the first request is not met."},
            {"id": "b", "text": "Recevoir un appareil neuf", "text_en": "To receive a new machine",
             "explanation": "The main request is « le remplacement de l'appareil sous quinze jours »."},
            {"id": "c", "text": "Parler à un responsable", "text_en": "To speak to a manager",
             "explanation": "He mentions his failed phone calls as background, but he does not ask to speak to anyone."},
            {"id": "d", "text": "Annuler sa commande", "text_en": "To cancel his order",
             "explanation": "Cancelling is never asked; he wants the product to work."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Je vous demande donc le remplacement de l'appareil sous quinze jours, faute de quoi je demanderai le remboursement intégral.",
        "key_line_en": "I therefore ask for the device to be replaced within fifteen days, failing which I will request a full refund.",
        "vocabulary": [
            {"term": "livrer", "gloss": "to deliver"},
            {"term": "à trois reprises", "gloss": "three times"},
            {"term": "faute de quoi", "gloss": "failing which"},
            {"term": "le remboursement intégral", "gloss": "full refund"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Chronique santé / Health column",
        "text": "Les spécialistes le répètent : ce n'est pas la durée du sommeil qui compte le plus, mais sa régularité.\nSe coucher et se lever à des heures fixes, même le week-end, aurait plus d'effet sur la fatigue que de dormir une heure de plus.",
        "question_fr": "Quel conseil les spécialistes donnent-ils ?",
        "question_en": "What advice do the specialists give?",
        "options": [
            {"id": "a", "text": "Dormir plus longtemps chaque nuit", "text_en": "Sleep longer every night",
             "explanation": "The text says exactly the opposite: an extra hour matters less than regularity."},
            {"id": "b", "text": "Se coucher plus tôt le week-end", "text_en": "Go to bed earlier at weekends",
             "explanation": "The advice is the SAME time at weekends, not an earlier time."},
            {"id": "c", "text": "Garder des horaires de sommeil stables", "text_en": "Keep stable sleeping hours",
             "explanation": "« à des heures fixes, même le week-end » is the definition of « régularité »."},
            {"id": "d", "text": "Faire une sieste dans la journée", "text_en": "Take a nap during the day",
             "explanation": "Naps are not mentioned at all."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ce n'est pas la durée du sommeil qui compte le plus, mais sa régularité.",
        "key_line_en": "It is not the length of sleep that matters most, but its regularity.",
        "vocabulary": [
            {"term": "le sommeil", "gloss": "sleep"},
            {"term": "la durée", "gloss": "length, duration"},
            {"term": "à des heures fixes", "gloss": "at set times"},
            {"term": "la fatigue", "gloss": "tiredness"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Offre d'emploi / Job advert",
        "text": "Nous recherchons un(e) assistant(e) commercial(e) pour notre agence de Nantes.\nUne première expérience est appréciée, mais les débutants motivés sont les bienvenus.\nLa maîtrise de l'anglais est indispensable ; l'espagnol serait un plus.",
        "question_fr": "Quelle condition est obligatoire pour ce poste ?",
        "question_en": "Which requirement is compulsory for this job?",
        "options": [
            {"id": "a", "text": "Avoir un diplôme de commerce", "text_en": "To hold a business degree",
             "explanation": "No diploma is mentioned anywhere in the advert."},
            {"id": "b", "text": "Parler anglais", "text_en": "To speak English",
             "explanation": "« indispensable » is the strongest word in the advert: without English you cannot apply."},
            {"id": "c", "text": "Avoir déjà de l'expérience", "text_en": "To already have experience",
             "explanation": "« appréciée » means welcome but optional; beginners are explicitly accepted."},
            {"id": "d", "text": "Parler espagnol", "text_en": "To speak Spanish",
             "explanation": "« serait un plus » = a bonus, not a requirement."},
        ],
        "correct_answer": "b",
        "key_line_fr": "La maîtrise de l'anglais est indispensable ; l'espagnol serait un plus.",
        "key_line_en": "A good command of English is essential; Spanish would be a bonus.",
        "vocabulary": [
            {"term": "la maîtrise", "gloss": "command, mastery"},
            {"term": "indispensable", "gloss": "essential"},
            {"term": "un plus", "gloss": "an asset, a bonus"},
            {"term": "un débutant", "gloss": "a beginner"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Article municipal / Local news",
        "text": "La ville a doublé le nombre de pistes cyclables en cinq ans. Résultat : le nombre de cyclistes a augmenté de 40 %.\nMais les associations réclament désormais davantage de stationnements sécurisés, car les vols de vélos découragent de nombreux habitants.",
        "question_fr": "Que demandent les associations aujourd'hui ?",
        "question_en": "What are the associations asking for now?",
        "options": [
            {"id": "a", "text": "Des parkings à vélos sûrs", "text_en": "Secure bike parking",
             "explanation": "« davantage de stationnements sécurisés » is exactly the request, justified by bike theft."},
            {"id": "b", "text": "Encore plus de pistes cyclables", "text_en": "Even more cycle lanes",
             "explanation": "The lanes are presented as an achievement already done; « désormais » signals a NEW demand."},
            {"id": "c", "text": "Des vélos gratuits pour les habitants", "text_en": "Free bikes for residents",
             "explanation": "Free bikes are never mentioned."},
            {"id": "d", "text": "Une baisse des vols de voitures", "text_en": "A drop in car theft",
             "explanation": "The theft concerned is « vols de vélos » (bikes), not cars."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les associations réclament désormais davantage de stationnements sécurisés.",
        "key_line_en": "The associations are now calling for more secure parking facilities.",
        "vocabulary": [
            {"term": "une piste cyclable", "gloss": "cycle lane"},
            {"term": "réclamer", "gloss": "to demand, call for"},
            {"term": "désormais", "gloss": "from now on"},
            {"term": "un vol", "gloss": "a theft"},
        ],
    },
    {
        "level": "B1",
        "band": "300 – 399 points",
        "doc_type": "Appel à bénévoles / Call for volunteers",
        "text": "L'association Lire et Faire Lire recherche des bénévoles pour lire des histoires aux enfants des écoles primaires.\nAucune formation particulière n'est exigée : une séance d'information de deux heures suffit. L'engagement demandé est d'une heure par semaine, pendant toute l'année scolaire.\n« Ce qui compte, c'est la régularité », explique la coordinatrice. « Les enfants attendent leur lecteur. »",
        "question_fr": "Qu'est-ce que l'association attend surtout des bénévoles ?",
        "question_en": "What does the association mainly expect from volunteers?",
        "options": [
            {"id": "a", "text": "Une présence régulière toute l'année", "text_en": "A regular presence throughout the year",
             "explanation": "The coordinator names it herself: « Ce qui compte, c'est la régularité », backed by « pendant toute l'année scolaire »."},
            {"id": "b", "text": "Une expérience de l'enseignement", "text_en": "Teaching experience",
             "explanation": "« Aucune formation particulière n'est exigée » rules out any professional requirement."},
            {"id": "c", "text": "Une longue formation avant de commencer", "text_en": "Long training before starting",
             "explanation": "A two-hour information session is enough, which is the opposite of long training."},
            {"id": "d", "text": "Une disponibilité quotidienne", "text_en": "Daily availability",
             "explanation": "The commitment is one hour per WEEK, not every day. Regular is not the same as frequent."},
        ],
        "correct_answer": "a",
        "key_line_fr": "« Ce qui compte, c'est la régularité », explique la coordinatrice.",
        "key_line_en": "“What matters is regularity,” the coordinator explains.",
        "vocabulary": [
            {"term": "un bénévole", "gloss": "a volunteer"},
            {"term": "exiger", "gloss": "to require"},
            {"term": "l'engagement", "gloss": "the commitment"},
            {"term": "une séance", "gloss": "a session"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # Opinion pieces, reviews, analysis. The author's position, nuance and
    # concession.
    # ------------------------------------------------------------------
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "text": "On accuse volontiers les écrans de tous les maux.\nPourtant, les études sérieuses montrent que ce n'est pas tant le temps passé devant un écran qui pose problème que ce qui est regardé — et surtout ce que cet écran remplace : le sommeil, le sport ou les échanges familiaux.",
        "question_fr": "Quelle est la position de l'auteur ?",
        "question_en": "What is the author's position?",
        "options": [
            {"id": "a", "text": "La durée d'écran est le seul critère valable", "text_en": "Screen time is the only valid criterion",
             "explanation": "« ce n'est pas tant… que… » explicitly downgrades screen time as the key criterion."},
            {"id": "b", "text": "Les écrans sont totalement inoffensifs", "text_en": "Screens are completely harmless",
             "explanation": "Too absolute. The author admits there is a problem, but relocates it."},
            {"id": "c", "text": "Il faut interdire les écrans aux enfants", "text_en": "Screens should be banned for children",
             "explanation": "No ban is proposed; the tone is analytical, not prescriptive."},
            {"id": "d", "text": "Le vrai problème est ce que les écrans remplacent", "text_en": "The real problem is what screens replace",
             "explanation": "« et surtout ce que cet écran remplace » marks the author's main point: lost sleep, sport, family time."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Ce n'est pas tant le temps passé devant un écran qui pose problème que ce qui est regardé — et surtout ce que cet écran remplace.",
        "key_line_en": "It is not so much the time spent in front of a screen that is the problem as what is watched — and above all what the screen replaces.",
        "vocabulary": [
            {"term": "de tous les maux", "gloss": "for every ill"},
            {"term": "pas tant… que…", "gloss": "not so much… as…"},
            {"term": "remplacer", "gloss": "to replace"},
            {"term": "les échanges", "gloss": "interaction, exchanges"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "text": "Longtemps présenté comme une manne, le tourisme de masse montre ses limites. Les habitants de plusieurs villes européennes dénoncent la hausse des loyers et la disparition des commerces de proximité, remplacés par des boutiques de souvenirs.\nLes élus, eux, hésitent : réguler, c'est prendre le risque de fâcher un secteur qui fait vivre des milliers de familles.",
        "question_fr": "Quelle difficulté rencontrent les élus ?",
        "question_en": "What difficulty do the local politicians face?",
        "options": [
            {"id": "a", "text": "Ils doivent arbitrer entre les habitants et l'économie locale", "text_en": "They must arbitrate between residents and the local economy",
             "explanation": "« hésitent » plus « prendre le risque de fâcher un secteur qui fait vivre des milliers de familles » describes a dilemma between two legitimate interests."},
            {"id": "b", "text": "Ils veulent supprimer les commerces de proximité", "text_en": "They want to remove local shops",
             "explanation": "The disappearance of local shops is a complaint from residents, not a policy of the elected officials."},
            {"id": "c", "text": "Ils refusent toute forme de régulation", "text_en": "They refuse any form of regulation",
             "explanation": "« hésitent » means undecided, which is not the same as refusing."},
            {"id": "d", "text": "Ils manquent de touristes", "text_en": "They do not have enough tourists",
             "explanation": "The problem is an excess of tourism, not a shortage."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Réguler, c'est prendre le risque de fâcher un secteur qui fait vivre des milliers de familles.",
        "key_line_en": "To regulate means running the risk of angering an industry that supports thousands of families.",
        "vocabulary": [
            {"term": "une manne", "gloss": "a windfall, godsend"},
            {"term": "les commerces de proximité", "gloss": "local shops"},
            {"term": "fâcher", "gloss": "to upset, anger"},
            {"term": "faire vivre", "gloss": "to provide a living for"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Critique littéraire / Book review",
        "text": "Le nouveau roman de Delaunay ne manque pas d'ambition : trois cents pages pour raconter une seule journée. L'écriture est soignée, parfois brillante.\nOn regrettera seulement que l'auteur, trop occupé à séduire, oublie en chemin de nous émouvoir.",
        "question_fr": "Quel est le jugement du critique ?",
        "question_en": "What is the reviewer's judgement?",
        "options": [
            {"id": "a", "text": "Entièrement négatif", "text_en": "Entirely negative",
             "explanation": "The writing is openly admired; the criticism affects only the emotional effect."},
            {"id": "b", "text": "Élogieux, sans aucune réserve", "text_en": "Full praise, with no reservations",
             "explanation": "« On regrettera seulement que… » introduces a clear reservation."},
            {"id": "c", "text": "Neutre et purement descriptif", "text_en": "Neutral and purely descriptive",
             "explanation": "Evaluative words (« brillante », « on regrettera ») show a clear personal judgement."},
            {"id": "d", "text": "Globalement positif, mais avec une réserve importante", "text_en": "Broadly positive, but with a significant reservation",
             "explanation": "Praise first (« ambition », « soignée », « brillante »), then a real criticism: the book fails to move the reader."},
        ],
        "correct_answer": "d",
        "key_line_fr": "On regrettera seulement que l'auteur, trop occupé à séduire, oublie en chemin de nous émouvoir.",
        "key_line_en": "One only regrets that the author, too busy charming us, forgets along the way to move us.",
        "vocabulary": [
            {"term": "soigné", "gloss": "polished, careful"},
            {"term": "séduire", "gloss": "to charm, win over"},
            {"term": "émouvoir", "gloss": "to move (emotionally)"},
            {"term": "en chemin", "gloss": "along the way"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "text": "Contrairement à une idée reçue, consommer bio ne garantit pas une alimentation équilibrée : un biscuit bio reste un biscuit.\nLe label porte sur le mode de production, non sur la qualité nutritionnelle du produit fini.",
        "question_fr": "Que veut démontrer l'auteur ?",
        "question_en": "What is the author trying to demonstrate?",
        "options": [
            {"id": "a", "text": "Le label bio ne renseigne pas sur l'équilibre nutritionnel", "text_en": "The organic label says nothing about nutritional balance",
             "explanation": "« Le label porte sur le mode de production, non sur la qualité nutritionnelle » states it directly."},
            {"id": "b", "text": "Les biscuits bio sont meilleurs pour la santé", "text_en": "Organic biscuits are healthier",
             "explanation": "« un biscuit bio reste un biscuit » says the opposite: the label changes nothing nutritionally."},
            {"id": "c", "text": "Il faudrait supprimer le label bio", "text_en": "The organic label should be abolished",
             "explanation": "No such proposal is made; the text clarifies the label, it does not reject it."},
            {"id": "d", "text": "Le bio est mauvais pour la santé", "text_en": "Organic food is bad for your health",
             "explanation": "The author never attacks organic food; he only limits what the label proves."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le label porte sur le mode de production, non sur la qualité nutritionnelle du produit fini.",
        "key_line_en": "The label concerns the production method, not the nutritional quality of the finished product.",
        "vocabulary": [
            {"term": "une idée reçue", "gloss": "a received idea, a myth"},
            {"term": "équilibré", "gloss": "balanced"},
            {"term": "porter sur", "gloss": "to concern, relate to"},
            {"term": "le produit fini", "gloss": "the finished product"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "text": "Bonjour Karim,\nJe comprends parfaitement votre demande d'augmentation, et je ne conteste pas la qualité de votre travail. Cependant, le budget du service a été gelé jusqu'en décembre.\nJe vous propose d'en reparler lors de l'entretien annuel, avec, si possible, une revalorisation rétroactive.",
        "question_fr": "Que répond le responsable ?",
        "question_en": "How does the manager answer?",
        "options": [
            {"id": "a", "text": "Il refuse définitivement l'augmentation", "text_en": "He definitively refuses the raise",
             "explanation": "The refusal is temporary and a future option is left open (« rétroactive »)."},
            {"id": "b", "text": "Il reporte la décision tout en laissant une possibilité", "text_en": "He postpones the decision while leaving a possibility open",
             "explanation": "« en reparler lors de l'entretien annuel » = postponement; « revalorisation rétroactive » = the door stays open."},
            {"id": "c", "text": "Il critique le travail du salarié", "text_en": "He criticises the employee's work",
             "explanation": "The opposite: « je ne conteste pas la qualité de votre travail »."},
            {"id": "d", "text": "Il accepte immédiatement", "text_en": "He accepts immediately",
             "explanation": "« Cependant… gelé » blocks any immediate increase."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Je vous propose d'en reparler lors de l'entretien annuel, avec, si possible, une revalorisation rétroactive.",
        "key_line_en": "I suggest we discuss it again at the annual review, with a backdated increase if possible.",
        "vocabulary": [
            {"term": "une augmentation", "gloss": "a pay rise"},
            {"term": "geler", "gloss": "to freeze"},
            {"term": "l'entretien annuel", "gloss": "annual appraisal"},
            {"term": "rétroactif", "gloss": "backdated"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Analyse économique / Economic analysis",
        "text": "Le taux de chômage a reculé de 0,3 point ce trimestre.\nUne bonne nouvelle, à nuancer : cette baisse s'explique en partie par le retrait du marché du travail de personnes découragées, qui ne sont plus comptabilisées comme demandeurs d'emploi.",
        "question_fr": "Pourquoi faut-il nuancer cette baisse ?",
        "question_en": "Why should this fall be qualified?",
        "options": [
            {"id": "a", "text": "Certaines personnes sortent des statistiques sans avoir trouvé d'emploi", "text_en": "Some people leave the statistics without having found a job",
             "explanation": "Discouraged people stop being counted, so the figure improves without the situation improving."},
            {"id": "b", "text": "Les chiffres publiés sont faux", "text_en": "The published figures are false",
             "explanation": "The figures are not disputed; only their interpretation is."},
            {"id": "c", "text": "La baisse est trop importante pour être crédible", "text_en": "The fall is too large to be credible",
             "explanation": "0.3 point is small; the size of the drop is not the issue."},
            {"id": "d", "text": "Le chômage augmente en réalité", "text_en": "Unemployment is actually rising",
             "explanation": "Too strong. The text says the fall is partly artificial, not that it is a rise."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Cette baisse s'explique en partie par le retrait du marché du travail de personnes découragées.",
        "key_line_en": "This fall is partly explained by discouraged people withdrawing from the labour market.",
        "vocabulary": [
            {"term": "le taux de chômage", "gloss": "unemployment rate"},
            {"term": "reculer", "gloss": "to fall back, decrease"},
            {"term": "nuancer", "gloss": "to qualify, add nuance"},
            {"term": "un demandeur d'emploi", "gloss": "a jobseeker"},
        ],
    },
    {
        "level": "B2",
        "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "text": "La voiture électrique n'est pas la solution miracle que certains décrivent : sa fabrication, et en particulier celle des batteries, émet beaucoup de CO2.\nElle ne devient réellement avantageuse qu'au bout de plusieurs dizaines de milliers de kilomètres — et à condition que l'électricité qui l'alimente soit elle-même peu carbonée.",
        "question_fr": "Quelle est la position de l'auteur sur la voiture électrique ?",
        "question_en": "What is the author's position on the electric car?",
        "options": [
            {"id": "a", "text": "Elle est écologique dès le premier kilomètre", "text_en": "It is clean from the very first kilometre",
             "explanation": "The opposite: manufacturing creates a carbon debt that must be paid off over tens of thousands of km."},
            {"id": "b", "text": "Elle pollue davantage que la voiture thermique", "text_en": "It pollutes more than a petrol car",
             "explanation": "Too absolute. The author says it DOES become advantageous, just later than claimed."},
            {"id": "c", "text": "Son bénéfice écologique dépend de plusieurs conditions", "text_en": "Its environmental benefit depends on several conditions",
             "explanation": "Two conditions are stated: enough kilometres driven, and low-carbon electricity (« à condition que »)."},
            {"id": "d", "text": "Sa fabrication ne pose aucun problème", "text_en": "Its manufacture raises no problem",
             "explanation": "Battery production is named as the main source of emissions."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Elle ne devient réellement avantageuse qu'au bout de plusieurs dizaines de milliers de kilomètres — et à condition que l'électricité soit elle-même peu carbonée.",
        "key_line_en": "It only becomes genuinely advantageous after several tens of thousands of kilometres — and provided the electricity itself is low-carbon.",
        "vocabulary": [
            {"term": "la fabrication", "gloss": "manufacturing"},
            {"term": "ne… que", "gloss": "only"},
            {"term": "à condition que + subj.", "gloss": "provided that"},
            {"term": "peu carboné", "gloss": "low-carbon"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # Essays, irony, literary and institutional texts. Implicit meaning
    # and tone.
    # ------------------------------------------------------------------
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "text": "À force de tout conserver, nous ne conservons plus rien.\nL'archive numérique, en abolissant le tri, abolit aussi la hiérarchie : ce qui compte se noie dans ce qui ne compte pas. Nos ancêtres oubliaient beaucoup ; c'est peut-être pour cela qu'ils se souvenaient si bien.",
        "question_fr": "Quelle idée paradoxale l'auteur défend-il ?",
        "question_en": "What paradoxical idea does the author defend?",
        "options": [
            {"id": "a", "text": "Les archives numériques sont techniquement peu fiables", "text_en": "Digital archives are technically unreliable",
             "explanation": "The criticism is about meaning and hierarchy, not about technical reliability."},
            {"id": "b", "text": "L'oubli est une condition de la mémoire", "text_en": "Forgetting is a condition of memory",
             "explanation": "The closing sentence links forgetting and remembering causally: because they forgot much, they remembered well."},
            {"id": "c", "text": "Nos ancêtres avaient une meilleure mémoire biologique", "text_en": "Our ancestors had better biological memory",
             "explanation": "The argument is about selection, not about brain capacity."},
            {"id": "d", "text": "Il faudrait numériser davantage nos archives", "text_en": "We should digitise our archives further",
             "explanation": "The digital archive is precisely what the author criticises."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Nos ancêtres oubliaient beaucoup ; c'est peut-être pour cela qu'ils se souvenaient si bien.",
        "key_line_en": "Our ancestors forgot a great deal; perhaps that is why they remembered so well.",
        "vocabulary": [
            {"term": "à force de", "gloss": "by dint of, through constantly"},
            {"term": "abolir", "gloss": "to abolish"},
            {"term": "le tri", "gloss": "sorting, selection"},
            {"term": "se noyer", "gloss": "to drown, be lost"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "text": "On nous annonce, à grand renfort de communiqués, une « simplification administrative » : quatre formulaires remplacés par un seul, lequel exige désormais douze pièces justificatives.\nNul doute que l'usager saura apprécier le progrès.",
        "question_fr": "Quelle est l'intention de l'auteur dans la dernière phrase ?",
        "question_en": "What is the author's intention in the last sentence?",
        "options": [
            {"id": "a", "text": "Résumer objectivement la réforme", "text_en": "To summarise the reform objectively",
             "explanation": "The summary is in the FIRST sentence; the last one adds an evaluative, loaded comment."},
            {"id": "b", "text": "Féliciter sincèrement l'administration", "text_en": "To sincerely congratulate the administration",
             "explanation": "The preceding fact (12 documents instead of 4 forms) contradicts the word « progrès »: praise cannot be sincere here."},
            {"id": "c", "text": "Exprimer une critique par l'ironie", "text_en": "To express criticism through irony",
             "explanation": "« Nul doute que… » plus a contradicted claim is a classic ironic formula: the author means the opposite of what he writes."},
            {"id": "d", "text": "Donner un conseil pratique à l'usager", "text_en": "To give practical advice to the user",
             "explanation": "No instruction or advice is given to the reader."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Nul doute que l'usager saura apprécier le progrès.",
        "key_line_en": "No doubt the user will appreciate the progress.",
        "vocabulary": [
            {"term": "à grand renfort de", "gloss": "with a great deal of"},
            {"term": "une pièce justificative", "gloss": "supporting document"},
            {"term": "l'usager", "gloss": "the user (of a public service)"},
            {"term": "nul doute que", "gloss": "no doubt that"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "text": "Que l'intelligence artificielle transforme le travail, nul n'en doute. Reste à savoir si elle supprimera des emplois ou si elle en déplacera la nature.\nL'histoire industrielle plaide plutôt pour la seconde hypothèse ; encore faut-il que la formation suive, faute de quoi le déplacement se transformera, pour beaucoup, en éviction.",
        "question_fr": "Quelle condition l'auteur pose-t-il ?",
        "question_en": "What condition does the author set?",
        "options": [
            {"id": "a", "text": "Attendre les résultats d'études historiques", "text_en": "Wait for the results of historical studies",
             "explanation": "History is already cited as evidence; nothing is being awaited."},
            {"id": "b", "text": "Interdire l'IA dans certains secteurs", "text_en": "Ban AI in some sectors",
             "explanation": "No ban is suggested; the author sees transformation as inevitable."},
            {"id": "c", "text": "Adapter la formation, sinon des travailleurs seront exclus", "text_en": "Adapt training, otherwise workers will be pushed out",
             "explanation": "« encore faut-il que la formation suive, faute de quoi… éviction » is exactly a condition + consequence if unmet."},
            {"id": "d", "text": "Créer de nouveaux emplois industriels", "text_en": "Create new industrial jobs",
             "explanation": "Industrial history is used as an argument, not as a policy goal."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Encore faut-il que la formation suive, faute de quoi le déplacement se transformera, pour beaucoup, en éviction.",
        "key_line_en": "Training must keep up, however; otherwise the shift will turn, for many, into exclusion.",
        "vocabulary": [
            {"term": "encore faut-il que", "gloss": "but it still requires that"},
            {"term": "faute de quoi", "gloss": "failing which"},
            {"term": "l'éviction", "gloss": "ousting, exclusion"},
            {"term": "déplacer", "gloss": "to shift, relocate"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "text": "Elle relisait ses lettres non pour ce qu'elles disaient, mais pour ce qu'elle y avait mis d'espoir à l'époque.\nChaque phrase lui rappelait moins un homme qu'une femme qu'elle avait cessé d'être.",
        "question_fr": "Que cherche-t-elle en relisant ces lettres ?",
        "question_en": "What is she looking for when re-reading these letters?",
        "options": [
            {"id": "a", "text": "Des informations sur cet homme", "text_en": "Information about that man",
             "explanation": "« non pour ce qu'elles disaient » rules out the content, and « moins un homme que… » rules out the man."},
            {"id": "b", "text": "Des preuves d'une trahison", "text_en": "Evidence of a betrayal",
             "explanation": "No conflict or betrayal appears; the tone is nostalgic, not accusing."},
            {"id": "c", "text": "Une raison de lui écrire de nouveau", "text_en": "A reason to write to him again",
             "explanation": "No future action is contemplated; the whole passage looks backwards."},
            {"id": "d", "text": "La trace de ce qu'elle était autrefois", "text_en": "A trace of who she used to be",
             "explanation": "The letters bring back « une femme qu'elle avait cessé d'être »: a lost version of herself."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Chaque phrase lui rappelait moins un homme qu'une femme qu'elle avait cessé d'être.",
        "key_line_en": "Each sentence reminded her less of a man than of a woman she had stopped being.",
        "vocabulary": [
            {"term": "relire", "gloss": "to re-read"},
            {"term": "à l'époque", "gloss": "at the time"},
            {"term": "moins… que…", "gloss": "less… than…"},
            {"term": "cesser de", "gloss": "to stop doing"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "text": "« Corrélation n'est pas causalité », rappellent les auteurs.\nSi les consommateurs de café vivent plus longtemps, encore faut-il vérifier qu'ils ne cumulent pas d'autres avantages — revenus, sociabilité, accès aux soins — qui expliqueraient à eux seuls l'écart observé.",
        "question_fr": "Quel risque méthodologique les auteurs signalent-ils ?",
        "question_en": "What methodological risk do the authors point out?",
        "options": [
            {"id": "a", "text": "Un conflit d'intérêts avec l'industrie du café", "text_en": "A conflict of interest with the coffee industry",
             "explanation": "Funding and interests are not mentioned at all."},
            {"id": "b", "text": "Une erreur de calcul dans les résultats", "text_en": "A calculation error in the results",
             "explanation": "The data are accepted; only the causal reading is questioned."},
            {"id": "c", "text": "La présence de facteurs tiers non pris en compte", "text_en": "Third-party factors that were not taken into account",
             "explanation": "Income, sociability and healthcare access are confounding variables that could explain the gap on their own."},
            {"id": "d", "text": "Un échantillon trop petit", "text_en": "A sample that is too small",
             "explanation": "Sample size is never discussed; the issue is the interpretation of the link."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Encore faut-il vérifier qu'ils ne cumulent pas d'autres avantages qui expliqueraient à eux seuls l'écart observé.",
        "key_line_en": "One must still check that they do not combine other advantages that would alone explain the observed gap.",
        "vocabulary": [
            {"term": "cumuler", "gloss": "to combine, accumulate"},
            {"term": "les revenus", "gloss": "income"},
            {"term": "l'écart", "gloss": "the gap, difference"},
            {"term": "à eux seuls", "gloss": "on their own"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Commentaire institutionnel / Institutional commentary",
        "text": "Le texte adopté hier n'interdit pas la pratique : il la subordonne à une autorisation préalable, révocable à tout moment.\nAutant dire que le législateur, sans trancher, s'est donné les moyens de trancher plus tard.",
        "question_fr": "Comment l'auteur interprète-t-il cette loi ?",
        "question_en": "How does the author interpret this law?",
        "options": [
            {"id": "a", "text": "Elle autorise la pratique sans aucune condition", "text_en": "It authorises the practice with no conditions",
             "explanation": "The authorisation is « préalable » and « révocable »: those are strong conditions."},
            {"id": "b", "text": "Elle interdit clairement la pratique", "text_en": "It clearly bans the practice",
             "explanation": "The first words say the opposite: « n'interdit pas la pratique »."},
            {"id": "c", "text": "Elle diffère la décision tout en gardant un moyen d'agir", "text_en": "It defers the decision while keeping a means of acting",
             "explanation": "« sans trancher, s'est donné les moyens de trancher plus tard » = decision postponed, power retained (revocable authorisation)."},
            {"id": "d", "text": "Elle est inapplicable en pratique", "text_en": "It is unworkable in practice",
             "explanation": "The author never says it cannot be applied; he says it delays a choice."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le législateur, sans trancher, s'est donné les moyens de trancher plus tard.",
        "key_line_en": "The legislator, without deciding, has given itself the means to decide later.",
        "vocabulary": [
            {"term": "subordonner à", "gloss": "to make conditional on"},
            {"term": "préalable", "gloss": "prior"},
            {"term": "révocable", "gloss": "revocable"},
            {"term": "trancher", "gloss": "to settle, decide"},
        ],
    },
    {
        "level": "C1",
        "band": "500 – 599 points",
        "doc_type": "Analyse du monde du travail / Workplace analysis",
        "text": "On a longtemps construit des open spaces au nom de la collaboration. Les études récentes racontent une autre histoire : privés de murs, les salariés se parlent moins et s'écrivent davantage.\nL'espace ouvert n'a pas supprimé les cloisons ; il les a rendues invisibles.",
        "question_fr": "Que signifie la dernière phrase ?",
        "question_en": "What does the last sentence mean?",
        "options": [
            {"id": "a", "text": "Les cloisons transparentes sont plus efficaces", "text_en": "Glass partitions work better",
             "explanation": "No comparison of materials is made; « invisible » is figurative, not made of glass."},
            {"id": "b", "text": "Les barrières entre collègues subsistent sous une autre forme", "text_en": "Barriers between colleagues survive in another form",
             "explanation": "The walls became social: people now write instead of speaking, so the separation persists without being visible."},
            {"id": "c", "text": "Les open spaces ont supprimé toute séparation", "text_en": "Open spaces removed every separation",
             "explanation": "« n'a pas supprimé les cloisons » says exactly the opposite."},
            {"id": "d", "text": "Les salariés ont reconstruit des murs physiques", "text_en": "Employees have rebuilt physical walls",
             "explanation": "A literal reading. « Invisibles » signals a metaphor, not real partitions."},
        ],
        "correct_answer": "b",
        "key_line_fr": "L'espace ouvert n'a pas supprimé les cloisons ; il les a rendues invisibles.",
        "key_line_en": "The open-plan office did not remove the partitions; it made them invisible.",
        "vocabulary": [
            {"term": "une cloison", "gloss": "a partition wall"},
            {"term": "au nom de", "gloss": "in the name of"},
            {"term": "privé de", "gloss": "deprived of"},
            {"term": "davantage", "gloss": "more"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # Abstract argument, complex syntax, metaphor. Every wrong option is
    # only slightly wrong.
    # ------------------------------------------------------------------
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai sur la traduction / Essay on translation",
        "text": "Traduire, ce n'est pas transporter un sens intact d'une langue à l'autre : c'est consentir à une perte pour en éviter une plus grande, celle du silence.\nLe traducteur n'est pas un passeur fidèle, mais un négociateur permanent.",
        "question_fr": "Quelle conception de la traduction l'auteur défend-il ?",
        "question_en": "What conception of translation does the author defend?",
        "options": [
            {"id": "a", "text": "Un compromis assumé, préférable au renoncement", "text_en": "An accepted compromise, better than giving up",
             "explanation": "« consentir à une perte pour en éviter une plus grande, celle du silence »: an accepted loss chosen over no translation at all."},
            {"id": "b", "text": "Une trahison qu'il faudrait éviter", "text_en": "A betrayal that ought to be avoided",
             "explanation": "The loss is presented as legitimate and necessary, not as a fault to avoid."},
            {"id": "c", "text": "Une tâche réservée aux linguistes professionnels", "text_en": "A task reserved for professional linguists",
             "explanation": "The text describes the nature of translating, not who is entitled to do it."},
            {"id": "d", "text": "Une opération neutre et exacte", "text_en": "A neutral and exact operation",
             "explanation": "Explicitly rejected by « ce n'est pas transporter un sens intact »."},
        ],
        "correct_answer": "a",
        "key_line_fr": "C'est consentir à une perte pour en éviter une plus grande, celle du silence.",
        "key_line_en": "It means accepting a loss in order to avoid a greater one: silence.",
        "vocabulary": [
            {"term": "consentir à", "gloss": "to agree to, accept"},
            {"term": "une perte", "gloss": "a loss"},
            {"term": "un passeur", "gloss": "one who carries across, ferryman"},
            {"term": "un négociateur", "gloss": "a negotiator"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "text": "La transparence, érigée en vertu cardinale, produit parfois l'inverse de ce qu'elle promet. À force d'exposer chaque délibération, on n'obtient pas des décideurs plus honnêtes : on obtient des décideurs qui délibèrent ailleurs.\nCe qui disparaît, ce n'est pas le secret ; c'est la trace du secret.",
        "question_fr": "Quel effet pervers l'auteur décrit-il ?",
        "question_en": "What perverse effect does the author describe?",
        "options": [
            {"id": "a", "text": "La transparence rend les décideurs plus honnêtes qu'avant", "text_en": "Transparency makes decision-makers more honest than before",
             "explanation": "Exactly what the text denies: « on n'obtient pas des décideurs plus honnêtes »."},
            {"id": "b", "text": "Les délibérations se déplacent hors du regard, sans laisser de trace", "text_en": "Deliberation moves out of sight, leaving no record",
             "explanation": "« délibèrent ailleurs » plus « ce qui disparaît […] c'est la trace du secret »: secrecy survives, its record does not."},
            {"id": "c", "text": "Le secret a été entièrement supprimé", "text_en": "Secrecy has been entirely abolished",
             "explanation": "The final sentence rules this out: what vanishes is the trace, « ce n'est pas le secret »."},
            {"id": "d", "text": "Les citoyens ne s'intéressent plus aux décisions publiques", "text_en": "Citizens no longer take an interest in public decisions",
             "explanation": "Public attention is never discussed; the subject is the behaviour of decision-makers."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Ce qui disparaît, ce n'est pas le secret ; c'est la trace du secret.",
        "key_line_en": "What disappears is not secrecy; it is the record of secrecy.",
        "vocabulary": [
            {"term": "ériger en", "gloss": "to set up as, elevate into"},
            {"term": "une vertu cardinale", "gloss": "a cardinal virtue"},
            {"term": "délibérer", "gloss": "to deliberate"},
            {"term": "une trace", "gloss": "a trace, record"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Critique d'exposition / Exhibition review",
        "text": "Le commissaire a voulu tout dire, et l'on ressort en ayant tout lu : cartels, chronologies, citations murales.\nDes toiles, en revanche, on n'aura rien vu. L'exposition explique magnifiquement des œuvres qu'elle empêche de regarder.",
        "question_fr": "Que reproche le critique à cette exposition ?",
        "question_en": "What does the reviewer criticise about this exhibition?",
        "options": [
            {"id": "a", "text": "Les explications fournies sont fausses ou approximatives", "text_en": "The explanations provided are false or approximate",
             "explanation": "Their quality is praised (« magnifiquement »); the problem is their quantity and their effect."},
            {"id": "b", "text": "Les œuvres exposées sont de mauvaise qualité", "text_en": "The works on display are of poor quality",
             "explanation": "The paintings are never judged — the point is precisely that one does not get to look at them."},
            {"id": "c", "text": "L'abondance du commentaire empêche de voir les œuvres", "text_en": "The abundance of commentary prevents you from seeing the works",
             "explanation": "The closing paradox states it: the exhibition explains works « qu'elle empêche de regarder »."},
            {"id": "d", "text": "L'exposition manque de documents explicatifs", "text_en": "The exhibition lacks explanatory material",
             "explanation": "The opposite: labels, chronologies and wall quotations are listed as excessive."},
        ],
        "correct_answer": "c",
        "key_line_fr": "L'exposition explique magnifiquement des œuvres qu'elle empêche de regarder.",
        "key_line_en": "The exhibition magnificently explains works that it prevents you from looking at.",
        "vocabulary": [
            {"term": "un commissaire (d'exposition)", "gloss": "a curator"},
            {"term": "un cartel", "gloss": "a wall label (in a museum)"},
            {"term": "une toile", "gloss": "a canvas, painting"},
            {"term": "en revanche", "gloss": "on the other hand"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "text": "On reproche volontiers à la science de se contredire. C'est méconnaître qu'elle ne progresse qu'à ce prix : une théorie qu'aucune observation ne pourrait démentir n'est pas une théorie solide, elle est une croyance.\nLa fragilité assumée d'un énoncé fait sa force.",
        "question_fr": "Quelle est la thèse de l'auteur ?",
        "question_en": "What is the author's thesis?",
        "options": [
            {"id": "a", "text": "La science devrait éviter de se contredire", "text_en": "Science should avoid contradicting itself",
             "explanation": "Self-correction is presented as the very condition of progress, not as a flaw to avoid."},
            {"id": "b", "text": "Les croyances valent autant que les théories scientifiques", "text_en": "Beliefs are worth as much as scientific theories",
             "explanation": "« croyance » is used pejoratively, to name what a theory becomes when nothing could refute it."},
            {"id": "c", "text": "Une théorie est solide si elle peut être réfutée", "text_en": "A theory is sound if it can be refuted",
             "explanation": "The negative formulation says it: a theory no observation could contradict is not sound. Hence refutability is the criterion."},
            {"id": "d", "text": "Aucune théorie ne peut être considérée comme vraie", "text_en": "No theory can be considered true",
             "explanation": "Too radical. The author distinguishes solid theories from beliefs; he does not abolish the distinction."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une théorie qu'aucune observation ne pourrait démentir n'est pas une théorie solide, elle est une croyance.",
        "key_line_en": "A theory that no observation could contradict is not a sound theory; it is a belief.",
        "vocabulary": [
            {"term": "méconnaître", "gloss": "to fail to recognise"},
            {"term": "démentir", "gloss": "to contradict, refute"},
            {"term": "un énoncé", "gloss": "a statement"},
            {"term": "à ce prix", "gloss": "at that cost, only in this way"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "text": "Le quartier a été « requalifié » : façades ravalées, terrasses fleuries, loyers doublés.\nOn célèbre le retour de la vie dans des rues dont on a méthodiquement écarté les vivants. Le pittoresque a survécu ; ceux qui le produisaient, non.",
        "question_fr": "Que dénonce l'auteur ?",
        "question_en": "What is the author denouncing?",
        "options": [
            {"id": "a", "text": "Une rénovation qui a chassé les habitants qui faisaient le quartier", "text_en": "A renovation that drove out the residents who made the neighbourhood",
             "explanation": "The final antithesis carries it: the picturesque survived, « ceux qui le produisaient, non » — the people were displaced by doubled rents."},
            {"id": "b", "text": "Le mauvais goût des nouvelles façades", "text_en": "The bad taste of the new façades",
             "explanation": "Aesthetics are not attacked; the renovated street is described as attractive, which is the whole irony."},
            {"id": "c", "text": "L'abandon du quartier par les pouvoirs publics", "text_en": "The abandonment of the district by the authorities",
             "explanation": "The opposite of abandonment: the authorities invested heavily in the area."},
            {"id": "d", "text": "Le manque d'animation dans les rues rénovées", "text_en": "The lack of activity in the renovated streets",
             "explanation": "« On célèbre le retour de la vie » — there is activity; the author questions who is left to live it."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le pittoresque a survécu ; ceux qui le produisaient, non.",
        "key_line_en": "The picturesque survived; those who produced it did not.",
        "vocabulary": [
            {"term": "requalifier", "gloss": "to regenerate, upgrade (an area)"},
            {"term": "ravaler une façade", "gloss": "to clean/restore a façade"},
            {"term": "écarter", "gloss": "to push aside, remove"},
            {"term": "le pittoresque", "gloss": "picturesque character"},
        ],
    },
    {
        "level": "C2",
        "band": "600 – 699 points",
        "doc_type": "Essai sur la lecture / Essay on reading",
        "text": "Nous n'avons jamais tant lu, ni si peu relu. Or un livre ne se donne qu'à la seconde visite : la première, on court après l'intrigue ; la seconde seulement, on entend la phrase.\nLire beaucoup est une gourmandise ; relire est une fidélité.",
        "question_fr": "Quelle distinction l'auteur établit-il ?",
        "question_en": "What distinction does the author draw?",
        "options": [
            {"id": "a", "text": "Entre les bons livres et les livres médiocres", "text_en": "Between good books and mediocre ones",
             "explanation": "No book is judged; the distinction concerns the reader's manner of reading, not the works."},
            {"id": "b", "text": "Entre la quantité de lectures et la profondeur de la relecture", "text_en": "Between the quantity of reading and the depth of re-reading",
             "explanation": "« gourmandise » (appetite, quantity) is set against « fidélité » (returning, depth), backed by hearing the sentence only on a second pass."},
            {"id": "c", "text": "Entre la lecture sur papier et la lecture sur écran", "text_en": "Between reading on paper and reading on a screen",
             "explanation": "The medium is never mentioned; both readings could happen in the same book."},
            {"id": "d", "text": "Entre les lecteurs cultivés et les lecteurs débutants", "text_en": "Between cultivated readers and beginners",
             "explanation": "« Nous » includes the author: he describes a shared habit, not two categories of people."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Lire beaucoup est une gourmandise ; relire est une fidélité.",
        "key_line_en": "Reading a great deal is an appetite; re-reading is a loyalty.",
        "vocabulary": [
            {"term": "relire", "gloss": "to re-read"},
            {"term": "l'intrigue", "gloss": "the plot"},
            {"term": "la gourmandise", "gloss": "greed, appetite (for pleasure)"},
            {"term": "la fidélité", "gloss": "loyalty, faithfulness"},
        ],
    },
]
