"""Compréhension écrite — Test 08.

Forty questions climbing A1 → C2. Profile A1 6, A2 7, B1 7, B2 7, C1 7, C2 6.
French only in the question layer; balance() spreads the answer key.
"""
from ._balance import balance

_RAW = [
    # ------------------------------------------------------------------
    # A1 — 100 – 199 points
    # ------------------------------------------------------------------
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Mot / Note",
        "topic": "Vie quotidienne & logement",
        "text": "Julie,\nJ'ai fait les courses. Le lait est dans le frigo.\nIl reste du pain d'hier.\nÀ ce soir,\nPapa",
        "question_fr": "Où est le lait ?",
        "options": [
            {"id": "a", "text": "Dans le frigo",
             "explanation": "« Le lait est dans le frigo » says so directly."},
            {"id": "b", "text": "Au magasin",
             "explanation": "The shopping has already been done and brought home."},
            {"id": "c", "text": "Sur la table",
             "explanation": "No table is mentioned."},
            {"id": "d", "text": "Il n'y a pas de lait",
             "explanation": "There is milk; the note says where it is."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le lait est dans le frigo.",
        "key_line_en": "The milk is in the fridge.",
        "vocabulary": [
            {"term": "faire les courses", "gloss": "to do the shopping"},
            {"term": "le frigo", "gloss": "the fridge"},
            {"term": "il reste", "gloss": "there is some left"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Panneau / Sign",
        "topic": "Transports & voyages",
        "text": "SORTIE DE SECOURS\nNe pas encombrer.\nEn cas d'alarme, sortir calmement.\nAscenseur interdit.",
        "question_fr": "Que ne faut-il pas utiliser en cas d'alarme ?",
        "options": [
            {"id": "a", "text": "La sortie de secours",
             "explanation": "That is precisely the way out to use."},
            {"id": "b", "text": "L'escalier",
             "explanation": "Stairs are the alternative to the lift, not forbidden."},
            {"id": "c", "text": "L'ascenseur",
             "explanation": "« Ascenseur interdit »."},
            {"id": "d", "text": "L'alarme",
             "explanation": "The alarm is the signal, not something to use or avoid."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Ascenseur interdit.",
        "key_line_en": "Lift not to be used.",
        "vocabulary": [
            {"term": "une sortie de secours", "gloss": "an emergency exit"},
            {"term": "encombrer", "gloss": "to block, clutter"},
            {"term": "interdit", "gloss": "forbidden"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Ordonnance / Prescription",
        "topic": "Santé & bien-être",
        "text": "Docteur Nadia Bassi\n1 comprimé matin et soir, pendant 5 jours.\nÀ prendre pendant le repas.\nNe pas conduire après la prise.",
        "question_fr": "Quand faut-il prendre le comprimé ?",
        "options": [
            {"id": "a", "text": "Avant de dormir seulement",
             "explanation": "Two doses are prescribed: morning and evening."},
            {"id": "b", "text": "Pendant les repas",
             "explanation": "« À prendre pendant le repas »."},
            {"id": "c", "text": "Avant de manger",
             "explanation": "The instruction is during the meal, not before it."},
            {"id": "d", "text": "Après avoir conduit",
             "explanation": "Driving is forbidden after taking it, which is a warning, not a schedule."},
        ],
        "correct_answer": "b",
        "key_line_fr": "À prendre pendant le repas.",
        "key_line_en": "To be taken with a meal.",
        "vocabulary": [
            {"term": "un comprimé", "gloss": "a tablet"},
            {"term": "la prise", "gloss": "taking (a dose)"},
            {"term": "conduire", "gloss": "to drive"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Affichette / Small notice",
        "topic": "Alimentation & consommation",
        "text": "CAFÉ DU MARCHÉ\nPetit-déjeuner servi jusqu'à 11 h.\nFormule : café, jus d'orange, croissant — 6 €.\nSur place ou à emporter.",
        "question_fr": "Jusqu'à quelle heure sert-on le petit-déjeuner ?",
        "options": [
            {"id": "a", "text": "Jusqu'à 6 h",
             "explanation": "6 is the price in euros, not a time."},
            {"id": "b", "text": "Toute la journée",
             "explanation": "A closing time is given for breakfast."},
            {"id": "c", "text": "Jusqu'à midi",
             "explanation": "The notice says 11 a.m., not noon."},
            {"id": "d", "text": "Jusqu'à 11 h",
             "explanation": "« Petit-déjeuner servi jusqu'à 11 h »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Petit-déjeuner servi jusqu'à 11 h.",
        "key_line_en": "Breakfast served until 11 a.m.",
        "vocabulary": [
            {"term": "une formule", "gloss": "a set deal"},
            {"term": "à emporter", "gloss": "takeaway"},
            {"term": "sur place", "gloss": "eat in"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Message / Message",
        "topic": "Loisirs, culture & médias",
        "text": "Salut !\nJ'ai deux places pour le match samedi.\nTu viens avec moi ?\nRéponds-moi vite, sinon je propose à Malik.\nYanis",
        "question_fr": "Que veut savoir Yanis ?",
        "options": [
            {"id": "a", "text": "Si son ami veut venir au match",
             "explanation": "« Tu viens avec moi ? » and he wants a quick answer before asking Malik."},
            {"id": "b", "text": "Où acheter des places",
             "explanation": "He already has two tickets."},
            {"id": "c", "text": "Qui est Malik",
             "explanation": "Malik is his back-up option, not a question."},
            {"id": "d", "text": "Le prix des places",
             "explanation": "No price is mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "J'ai deux places pour le match samedi. Tu viens avec moi ?",
        "key_line_en": "I've got two tickets for Saturday's match. Are you coming with me?",
        "vocabulary": [
            {"term": "une place", "gloss": "a ticket, seat"},
            {"term": "sinon", "gloss": "otherwise"},
            {"term": "proposer à", "gloss": "to offer to"},
        ],
    },
    {
        "level": "A1", "band": "100 – 199 points",
        "doc_type": "Emploi du temps / Timetable",
        "topic": "Études & formation",
        "text": "LUNDI\n9 h – 11 h : français\n11 h – 12 h : sport\n14 h – 16 h : mathématiques\nPas de cours le lundi après 16 h.",
        "question_fr": "Que font les élèves à 11 h 30 ?",
        "options": [
            {"id": "a", "text": "Du français",
             "explanation": "French finishes at 11 a.m."},
            {"id": "b", "text": "Des mathématiques",
             "explanation": "Maths starts at 2 p.m."},
            {"id": "c", "text": "Rien",
             "explanation": "The free time starts after 4 p.m."},
            {"id": "d", "text": "Du sport",
             "explanation": "« 11 h – 12 h : sport » covers 11:30."},
        ],
        "correct_answer": "d",
        "key_line_fr": "11 h – 12 h : sport.",
        "key_line_en": "11 a.m. – 12 p.m.: PE.",
        "vocabulary": [
            {"term": "un emploi du temps", "gloss": "a timetable"},
            {"term": "un cours", "gloss": "a lesson"},
            {"term": "après", "gloss": "after"},
        ],
    },

    # ------------------------------------------------------------------
    # A2 — 200 – 299 points
    # ------------------------------------------------------------------
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Petite annonce / Classified ad",
        "topic": "Travail & emploi",
        "text": "SAISONNIER — RÉCOLTE DES POMMES\nDu 15 septembre au 20 octobre, six jours sur sept.\nLogement possible sur place, 6 € par nuit, repas non compris.\nAucune expérience nécessaire, mais le travail est physique.",
        "question_fr": "Que propose l'employeur en plus du travail ?",
        "options": [
            {"id": "a", "text": "Les repas gratuits",
             "explanation": "« repas non compris » — meals are not included."},
            {"id": "b", "text": "Un hébergement payant",
             "explanation": "« Logement possible sur place, 6 € par nuit »."},
            {"id": "c", "text": "Une formation à la récolte",
             "explanation": "No experience is needed, but no training is offered either."},
            {"id": "d", "text": "Un jour de repos par semaine payé",
             "explanation": "Six days out of seven means one day off, but nothing says it is paid."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Logement possible sur place, 6 € par nuit, repas non compris.",
        "key_line_en": "Accommodation available on site, €6 a night, meals not included.",
        "vocabulary": [
            {"term": "un saisonnier", "gloss": "a seasonal worker"},
            {"term": "la récolte", "gloss": "the harvest"},
            {"term": "un logement", "gloss": "accommodation"},
            {"term": "physique", "gloss": "physically demanding"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Courrier administratif / Official letter",
        "topic": "Société, citoyenneté & administration",
        "text": "Madame, Monsieur,\nVotre dossier est incomplet : il manque le justificatif de domicile.\nVous disposez de trente jours pour le fournir.\nPassé ce délai, la demande sera classée sans suite et devra être déposée à nouveau.",
        "question_fr": "Que se passe-t-il après trente jours ?",
        "options": [
            {"id": "a", "text": "Le dossier est accepté",
             "explanation": "Acceptance requires the missing document."},
            {"id": "b", "text": "Un rappel est envoyé",
             "explanation": "No reminder is promised; this letter is the notice."},
            {"id": "c", "text": "Il faut recommencer la demande",
             "explanation": "« la demande sera classée sans suite et devra être déposée à nouveau »."},
            {"id": "d", "text": "Le justificatif est demandé à la mairie",
             "explanation": "The applicant must supply it; nothing says the office will fetch it."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Passé ce délai, la demande sera classée sans suite et devra être déposée à nouveau.",
        "key_line_en": "After that period, the application will be closed and must be submitted again.",
        "vocabulary": [
            {"term": "un justificatif", "gloss": "a supporting document"},
            {"term": "disposer de", "gloss": "to have (time) available"},
            {"term": "classer sans suite", "gloss": "to close without action"},
            {"term": "un délai", "gloss": "a time limit"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Consigne / Instructions",
        "topic": "Sciences & technologies",
        "text": "SAUVEGARDE AUTOMATIQUE\nVos fichiers sont copiés chaque nuit sur le serveur.\nSeuls les documents placés dans le dossier « Travail » sont sauvegardés.\nLes fichiers du bureau ne le sont pas.",
        "question_fr": "Quels fichiers ne sont pas sauvegardés ?",
        "options": [
            {"id": "a", "text": "Ceux du dossier « Travail »",
             "explanation": "Those are precisely the ones that are backed up."},
            {"id": "b", "text": "Tous les fichiers",
             "explanation": "One folder is backed up every night."},
            {"id": "c", "text": "Ceux modifiés la nuit",
             "explanation": "Night is when the backup runs, not a category of file."},
            {"id": "d", "text": "Ceux qui sont sur le bureau",
             "explanation": "« Les fichiers du bureau ne le sont pas »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Seuls les documents placés dans le dossier « Travail » sont sauvegardés.",
        "key_line_en": "Only documents placed in the “Travail” folder are backed up.",
        "vocabulary": [
            {"term": "une sauvegarde", "gloss": "a backup"},
            {"term": "un dossier", "gloss": "a folder"},
            {"term": "le bureau", "gloss": "the desktop"},
            {"term": "un serveur", "gloss": "a server"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "État des lieux / Inventory notice",
        "topic": "Vie quotidienne & logement",
        "text": "ÉTAT DES LIEUX DE SORTIE\nRendez-vous fixé le 30 juin à 10 h, logement vide et nettoyé.\nLes clés sont remises à ce moment-là, pas avant.\nLe dépôt de garantie est restitué sous un mois.",
        "question_fr": "Quand faut-il rendre les clés ?",
        "options": [
            {"id": "a", "text": "Le jour de l'état des lieux",
             "explanation": "« Les clés sont remises à ce moment-là, pas avant » — at the 30 June appointment."},
            {"id": "b", "text": "Avant le 30 juin",
             "explanation": "« pas avant » rules this out explicitly."},
            {"id": "c", "text": "Un mois après",
             "explanation": "One month is the deadline for returning the deposit."},
            {"id": "d", "text": "Quand le logement est nettoyé",
             "explanation": "Cleaning is a condition of the appointment, not a separate handover moment."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les clés sont remises à ce moment-là, pas avant.",
        "key_line_en": "The keys are handed over then, not before.",
        "vocabulary": [
            {"term": "un état des lieux", "gloss": "an inventory/condition report"},
            {"term": "remettre", "gloss": "to hand over"},
            {"term": "un dépôt de garantie", "gloss": "a security deposit"},
            {"term": "restituer", "gloss": "to return"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Information municipale / Council notice",
        "topic": "Environnement & nature",
        "text": "ARROSAGE\nEn raison de la sécheresse, l'arrosage des jardins est interdit entre 9 h et 20 h.\nIl reste autorisé la nuit.\nLe remplissage des piscines est interdit jusqu'à nouvel ordre.",
        "question_fr": "Quand peut-on arroser son jardin ?",
        "options": [
            {"id": "a", "text": "Jamais",
             "explanation": "Night watering remains allowed."},
            {"id": "b", "text": "La nuit",
             "explanation": "« Il reste autorisé la nuit » — the ban covers 9 a.m. to 8 p.m."},
            {"id": "c", "text": "L'après-midi",
             "explanation": "The afternoon falls inside the banned hours."},
            {"id": "d", "text": "Le matin avant 9 h seulement",
             "explanation": "The permission stated is for the night, not an early-morning window."},
        ],
        "correct_answer": "b",
        "key_line_fr": "L'arrosage des jardins est interdit entre 9 h et 20 h. Il reste autorisé la nuit.",
        "key_line_en": "Watering gardens is banned between 9 a.m. and 8 p.m. It remains allowed at night.",
        "vocabulary": [
            {"term": "l'arrosage", "gloss": "watering"},
            {"term": "la sécheresse", "gloss": "drought"},
            {"term": "le remplissage", "gloss": "filling"},
            {"term": "jusqu'à nouvel ordre", "gloss": "until further notice"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Conditions / Terms",
        "topic": "Transports & voyages",
        "text": "ABONNEMENT TRANSPORT\nRésiliation possible à tout moment, avec un préavis de trente jours.\nL'abonnement annuel payé en une fois n'est pas remboursable.\nLa carte est nominative : tout prêt entraîne sa suppression.",
        "question_fr": "Que risque une personne qui prête sa carte ?",
        "options": [
            {"id": "a", "text": "De payer un préavis",
             "explanation": "The thirty days' notice applies to cancelling, not to lending."},
            {"id": "b", "text": "Rien de particulier",
             "explanation": "A specific consequence is stated."},
            {"id": "c", "text": "Un remboursement partiel",
             "explanation": "No refund exists for the annual pass."},
            {"id": "d", "text": "La suppression de sa carte",
             "explanation": "« tout prêt entraîne sa suppression »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "La carte est nominative : tout prêt entraîne sa suppression.",
        "key_line_en": "The card is personal: lending it leads to its cancellation.",
        "vocabulary": [
            {"term": "une résiliation", "gloss": "a cancellation"},
            {"term": "un préavis", "gloss": "a notice period"},
            {"term": "nominatif", "gloss": "personal, in one name"},
            {"term": "un prêt", "gloss": "a lending"},
        ],
    },
    {
        "level": "A2", "band": "200 – 299 points",
        "doc_type": "Annonce / Announcement",
        "topic": "Loisirs, culture & médias",
        "text": "ATELIER PHOTO\nSix séances, le samedi matin, à partir du 12 mars.\nAppareil personnel indispensable : le téléphone est accepté.\nLes photos seront exposées à la médiathèque en juin.",
        "question_fr": "Que faut-il apporter à l'atelier ?",
        "options": [
            {"id": "a", "text": "Un appareil ou un téléphone",
             "explanation": "« Appareil personnel indispensable : le téléphone est accepté »."},
            {"id": "b", "text": "Des photos déjà prises",
             "explanation": "Photos are produced during the workshop and shown in June."},
            {"id": "c", "text": "Un ordinateur",
             "explanation": "No computer is mentioned."},
            {"id": "d", "text": "Rien, tout est fourni",
             "explanation": "A camera of one's own is described as essential."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Appareil personnel indispensable : le téléphone est accepté.",
        "key_line_en": "Your own camera is essential: a phone is acceptable.",
        "vocabulary": [
            {"term": "un atelier", "gloss": "a workshop"},
            {"term": "un appareil", "gloss": "a camera, device"},
            {"term": "exposer", "gloss": "to exhibit"},
            {"term": "une séance", "gloss": "a session"},
        ],
    },

    # ------------------------------------------------------------------
    # B1 — 300 – 399 points
    # ------------------------------------------------------------------
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Chronique santé / Health column",
        "topic": "Santé & bien-être",
        "text": "Se soigner soi-même avec des restes d'antibiotiques est une mauvaise idée, même quand les symptômes ressemblent à ceux d'une infection connue.\nUn traitement interrompu trop tôt sélectionne les bactéries les plus résistantes, celles qui survivent aux premières doses. On soigne alors moins bien, et pour tout le monde.",
        "question_fr": "Pourquoi ce comportement est-il dangereux au-delà du patient ?",
        "options": [
            {"id": "a", "text": "Parce qu'il coûte cher au système de santé",
             "explanation": "Cost is not mentioned; the harm described is biological."},
            {"id": "b", "text": "Parce qu'il favorise des bactéries résistantes",
             "explanation": "An interrupted course selects the survivors: « On soigne alors moins bien, et pour tout le monde »."},
            {"id": "c", "text": "Parce qu'il retarde le diagnostic",
             "explanation": "Diagnosis delay is not the mechanism given."},
            {"id": "d", "text": "Parce que les antibiotiques périment vite",
             "explanation": "Expiry is never discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Un traitement interrompu trop tôt sélectionne les bactéries les plus résistantes.",
        "key_line_en": "A course stopped too early selects the most resistant bacteria.",
        "vocabulary": [
            {"term": "des restes", "gloss": "leftovers"},
            {"term": "interrompre", "gloss": "to interrupt"},
            {"term": "résistant", "gloss": "resistant"},
            {"term": "une dose", "gloss": "a dose"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Enquête / Survey report",
        "topic": "Travail & emploi",
        "text": "Les entreprises qui affichent leurs grilles de salaires reçoivent moins de candidatures, mais des candidatures plus adaptées.\nLe temps de recrutement diminue d'un tiers : les personnes qui postulent savent déjà que l'offre leur convient.",
        "question_fr": "Quel est l'effet de l'affichage des salaires ?",
        "options": [
            {"id": "a", "text": "Un recrutement plus rapide malgré moins de candidats",
             "explanation": "Fewer but better-matched applications cut hiring time by a third."},
            {"id": "b", "text": "Une hausse du nombre de candidatures",
             "explanation": "The number falls; it is the fit that improves."},
            {"id": "c", "text": "Une augmentation des salaires proposés",
             "explanation": "Pay levels are not said to change, only their visibility."},
            {"id": "d", "text": "Un allongement du recrutement",
             "explanation": "The recruitment time drops by a third."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le temps de recrutement diminue d'un tiers : les personnes qui postulent savent déjà que l'offre leur convient.",
        "key_line_en": "Hiring time falls by a third: applicants already know the offer suits them.",
        "vocabulary": [
            {"term": "une grille de salaires", "gloss": "a pay scale"},
            {"term": "afficher", "gloss": "to display, publish"},
            {"term": "adapté", "gloss": "suitable, well matched"},
            {"term": "postuler", "gloss": "to apply"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Reportage / Report",
        "topic": "Alimentation & consommation",
        "text": "La boulangerie vend son pain de la veille à moitié prix, le matin, dans un panier près de la caisse.\n« Certains clients hésitaient à demander, explique la boulangère. Depuis qu'il est visible, il part en une heure. »",
        "question_fr": "Qu'est-ce qui a changé le comportement des clients ?",
        "options": [
            {"id": "a", "text": "La baisse du prix",
             "explanation": "The half price existed before; what changed is where the bread sits."},
            {"id": "b", "text": "La qualité du pain",
             "explanation": "The bread is the same day-old loaf."},
            {"id": "c", "text": "Le fait qu'il soit exposé",
             "explanation": "« Certains clients hésitaient à demander […] Depuis qu'il est visible, il part en une heure »."},
            {"id": "d", "text": "L'heure de vente",
             "explanation": "Morning sale is the setting, not the change described."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Depuis qu'il est visible, il part en une heure.",
        "key_line_en": "Since it has been on show, it sells out in an hour.",
        "vocabulary": [
            {"term": "la veille", "gloss": "the day before"},
            {"term": "hésiter à", "gloss": "to hesitate to"},
            {"term": "partir", "gloss": "to sell out, go"},
            {"term": "la caisse", "gloss": "the till"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Présentation de dispositif / Scheme description",
        "topic": "Études & formation",
        "text": "L'université ouvre ses amphithéâtres au public une fois par mois.\nAucune inscription, aucun diplôme requis : on entre, on écoute, on repart. Les enseignants ne modifient pas leur cours, ce qui est précisément l'intérêt du dispositif.",
        "question_fr": "Pourquoi les enseignants ne modifient-ils pas leur cours ?",
        "options": [
            {"id": "a", "text": "Parce qu'ils manquent de temps",
             "explanation": "Time is not mentioned; the choice is presented as deliberate."},
            {"id": "b", "text": "Parce que le public assiste à un vrai cours",
             "explanation": "« ce qui est précisément l'intérêt du dispositif » — visitors hear the real thing."},
            {"id": "c", "text": "Parce que le public est trop nombreux",
             "explanation": "Numbers are never discussed."},
            {"id": "d", "text": "Parce que les étudiants le demandent",
             "explanation": "No student request is reported."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les enseignants ne modifient pas leur cours, ce qui est précisément l'intérêt du dispositif.",
        "key_line_en": "The lecturers do not adapt their course, which is exactly the point of the scheme.",
        "vocabulary": [
            {"term": "un amphithéâtre", "gloss": "a lecture hall"},
            {"term": "requis", "gloss": "required"},
            {"term": "un dispositif", "gloss": "a scheme, arrangement"},
            {"term": "l'intérêt", "gloss": "the point, value"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article municipal / Local news",
        "topic": "Environnement & nature",
        "text": "La ville a cessé de tondre certains espaces verts entre avril et juillet.\nLes habitants ont d'abord cru à un abandon ; des panneaux expliquant la démarche ont été installés, et les plaintes ont chuté. La mesure économise du carburant et laisse fleurir les prairies.",
        "question_fr": "Qu'est-ce qui a fait baisser les plaintes ?",
        "options": [
            {"id": "a", "text": "La reprise de la tonte",
             "explanation": "Mowing was not resumed; the pause continues."},
            {"id": "b", "text": "L'explication donnée aux habitants",
             "explanation": "Residents thought the areas had been abandoned; the signs corrected that and complaints fell."},
            {"id": "c", "text": "L'économie de carburant réalisée",
             "explanation": "That is a benefit of the measure, not what changed residents' minds."},
            {"id": "d", "text": "La floraison des prairies",
             "explanation": "The flowering is a result; the article credits the explanatory signs."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Des panneaux expliquant la démarche ont été installés, et les plaintes ont chuté.",
        "key_line_en": "Signs explaining the approach were put up, and complaints dropped.",
        "vocabulary": [
            {"term": "tondre", "gloss": "to mow"},
            {"term": "un abandon", "gloss": "neglect, abandonment"},
            {"term": "chuter", "gloss": "to drop sharply"},
            {"term": "une prairie", "gloss": "a meadow"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Information administrative / Administrative notice",
        "topic": "Société, citoyenneté & administration",
        "text": "Un médiateur peut être saisi gratuitement en cas de litige avec une administration.\nSa saisine ne remplace pas un recours : elle suspend simplement les délais pendant l'examen du dossier.\nL'avis rendu n'est pas contraignant, mais il est suivi dans huit cas sur dix.",
        "question_fr": "Quelle est la portée de l'avis du médiateur ?",
        "options": [
            {"id": "a", "text": "Il s'impose à l'administration",
             "explanation": "« L'avis rendu n'est pas contraignant » — it is not binding."},
            {"id": "b", "text": "Il remplace un recours en justice",
             "explanation": "« Sa saisine ne remplace pas un recours »."},
            {"id": "c", "text": "Il est sans effet en pratique",
             "explanation": "It is followed in eight cases out of ten."},
            {"id": "d", "text": "Il n'oblige personne mais est souvent suivi",
             "explanation": "Not binding, yet followed « dans huit cas sur dix »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "L'avis rendu n'est pas contraignant, mais il est suivi dans huit cas sur dix.",
        "key_line_en": "The opinion given is not binding, but it is followed in eight cases out of ten.",
        "vocabulary": [
            {"term": "un médiateur", "gloss": "an ombudsman"},
            {"term": "saisir", "gloss": "to refer a matter to"},
            {"term": "un recours", "gloss": "an appeal"},
            {"term": "contraignant", "gloss": "binding"},
        ],
    },
    {
        "level": "B1", "band": "300 – 399 points",
        "doc_type": "Article de presse / Press article",
        "topic": "Transports & voyages",
        "text": "La gare routière a été déplacée à côté de la gare ferroviaire, à huit cents mètres de son ancien emplacement.\nLes correspondances sont devenues faciles, mais les commerces de l'ancienne place ont perdu la moitié de leur clientèle en six mois.",
        "question_fr": "Quelle conséquence l'article signale-t-il ?",
        "options": [
            {"id": "a", "text": "Les correspondances sont plus difficiles",
             "explanation": "They became easier — that is the benefit of the move."},
            {"id": "b", "text": "Les commerces de l'ancien site ont souffert",
             "explanation": "They lost half their customers in six months."},
            {"id": "c", "text": "La gare ferroviaire a fermé",
             "explanation": "The bus station moved next to it; the railway station is still there."},
            {"id": "d", "text": "Les voyageurs sont moins nombreux",
             "explanation": "Passenger numbers are not discussed."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Les commerces de l'ancienne place ont perdu la moitié de leur clientèle en six mois.",
        "key_line_en": "The shops on the old square lost half their customers in six months.",
        "vocabulary": [
            {"term": "une gare routière", "gloss": "a bus station"},
            {"term": "une correspondance", "gloss": "a connection"},
            {"term": "un emplacement", "gloss": "a site, location"},
            {"term": "la clientèle", "gloss": "the customers"},
        ],
    },

    # ------------------------------------------------------------------
    # B2 — 400 – 499 points
    # ------------------------------------------------------------------
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Tribune d'opinion / Opinion piece",
        "topic": "Société, citoyenneté & administration",
        "text": "On demande aux jeunes de s'engager, et l'on s'étonne qu'ils préfèrent les causes ponctuelles aux organisations durables.\nC'est oublier ce qu'on leur propose : des réunions longues, des mandats de trois ans et une parole qui arrive après celle de tout le monde. L'engagement ne manque pas ; c'est la forme qui ne suit plus.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Les jeunes refusent de s'engager",
             "explanation": "« L'engagement ne manque pas » — willingness is not the issue."},
            {"id": "b", "text": "Les organisations proposent des formes inadaptées",
             "explanation": "Long meetings, three-year terms, last word: « c'est la forme qui ne suit plus »."},
            {"id": "c", "text": "Les causes ponctuelles sont inefficaces",
             "explanation": "Their effectiveness is not judged."},
            {"id": "d", "text": "Il faut allonger la durée des mandats",
             "explanation": "Long terms are part of what deters, not a remedy."},
        ],
        "correct_answer": "b",
        "key_line_fr": "L'engagement ne manque pas ; c'est la forme qui ne suit plus.",
        "key_line_en": "Commitment is not lacking; it is the format that no longer follows.",
        "vocabulary": [
            {"term": "s'engager", "gloss": "to get involved"},
            {"term": "ponctuel", "gloss": "one-off, specific"},
            {"term": "un mandat", "gloss": "a term of office"},
            {"term": "une parole", "gloss": "a say, a voice"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article de fond / Feature article",
        "topic": "Loisirs, culture & médias",
        "text": "Les festivals de province attirent désormais un public venu de loin, ce dont les organisateurs se félicitent.\nCe succès a un revers : les habitants ne trouvent plus de billets, et un événement né pour animer un territoire finit par en exclure ceux qui y vivent.",
        "question_fr": "Quel effet indésirable l'article décrit-il ?",
        "options": [
            {"id": "a", "text": "Les habitants sont écartés de leur propre festival",
             "explanation": "Locals can no longer get tickets: the event « finit par en exclure ceux qui y vivent »."},
            {"id": "b", "text": "Les festivals attirent trop peu de public",
             "explanation": "The problem is an excess of outside demand."},
            {"id": "c", "text": "Les organisateurs perdent de l'argent",
             "explanation": "Finances are not discussed; they are pleased with the turnout."},
            {"id": "d", "text": "La programmation s'est appauvrie",
             "explanation": "The line-up is never mentioned."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Un événement né pour animer un territoire finit par en exclure ceux qui y vivent.",
        "key_line_en": "An event created to enliven an area ends up shutting out the people who live there.",
        "vocabulary": [
            {"term": "un revers", "gloss": "a downside"},
            {"term": "se féliciter de", "gloss": "to be pleased about"},
            {"term": "animer", "gloss": "to enliven"},
            {"term": "un territoire", "gloss": "an area, region"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Vulgarisation / Popular science",
        "topic": "Sciences & technologies",
        "text": "Un système de recommandation apprend de ce que l'on a déjà regardé, et propose donc ce qui ressemble à ce que l'on connaît.\nIl n'a pas de préférence idéologique ; il a une préférence pour ce qui retient. Ce n'est pas la même chose, mais les effets se ressemblent beaucoup.",
        "question_fr": "Quelle nuance l'auteur apporte-t-il ?",
        "options": [
            {"id": "a", "text": "Le système est délibérément orienté",
             "explanation": "« Il n'a pas de préférence idéologique » — intention is denied."},
            {"id": "b", "text": "Le système n'a aucun effet sur les usagers",
             "explanation": "The effects are said to resemble those of a biased system."},
            {"id": "c", "text": "Le biais vient du mécanisme, non d'une intention",
             "explanation": "It prefers « ce qui retient »: « Ce n'est pas la même chose, mais les effets se ressemblent beaucoup »."},
            {"id": "d", "text": "Les usagers choisissent librement",
             "explanation": "What is offered is shaped by past viewing, which constrains the choice."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Il n'a pas de préférence idéologique ; il a une préférence pour ce qui retient.",
        "key_line_en": "It has no ideological preference; it has a preference for whatever holds attention.",
        "vocabulary": [
            {"term": "retenir", "gloss": "to hold (attention)"},
            {"term": "une préférence", "gloss": "a preference"},
            {"term": "se ressembler", "gloss": "to resemble each other"},
            {"term": "une recommandation", "gloss": "a recommendation"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Courriel professionnel / Professional e-mail",
        "topic": "Travail & emploi",
        "text": "Bonjour,\nJ'ai relu le rapport. Le fond est solide ; la forme dessert le propos.\nTrois pages d'introduction avant la première recommandation, c'est trois pages pendant lesquelles le lecteur décide que ce document ne le concerne pas. Placez les conclusions en tête.",
        "question_fr": "Que reproche l'auteur au rapport ?",
        "options": [
            {"id": "a", "text": "Ses conclusions sont fausses",
             "explanation": "« Le fond est solide » — the substance is not in question."},
            {"id": "b", "text": "Il est trop court",
             "explanation": "The complaint is that the reader waits three pages, not that there is too little."},
            {"id": "c", "text": "Son organisation retarde l'essentiel",
             "explanation": "« la forme dessert le propos »; the fix is « Placez les conclusions en tête »."},
            {"id": "d", "text": "Il manque de recommandations",
             "explanation": "Recommendations exist; they arrive too late."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Le fond est solide ; la forme dessert le propos.",
        "key_line_en": "The substance is sound; the form works against the message.",
        "vocabulary": [
            {"term": "le fond / la forme", "gloss": "substance / form"},
            {"term": "desservir", "gloss": "to work against, harm"},
            {"term": "le propos", "gloss": "the message, point"},
            {"term": "en tête", "gloss": "at the top"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article société / Society article",
        "topic": "Vie quotidienne & logement",
        "text": "Le nombre de personnes vivant seules a doublé en quarante ans, et l'on y voit souvent un signe d'isolement.\nLes enquêtes disent autre chose : vivre seul et se sentir seul ne coïncident guère. Certains des plus entourés sont ceux qui rentrent le soir dans un logement vide.",
        "question_fr": "Que montrent les enquêtes citées ?",
        "options": [
            {"id": "a", "text": "Vivre seul entraîne l'isolement",
             "explanation": "The surveys are cited precisely to break that link."},
            {"id": "b", "text": "Les personnes seules sortent moins",
             "explanation": "The opposite is suggested: some of the best-connected go home alone."},
            {"id": "c", "text": "L'isolement a doublé en quarante ans",
             "explanation": "What doubled is the number living alone, not loneliness."},
            {"id": "d", "text": "Habiter seul et se sentir seul sont distincts",
             "explanation": "« vivre seul et se sentir seul ne coïncident guère »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Vivre seul et se sentir seul ne coïncident guère.",
        "key_line_en": "Living alone and feeling alone barely coincide.",
        "vocabulary": [
            {"term": "coïncider", "gloss": "to coincide"},
            {"term": "entouré", "gloss": "surrounded, well connected"},
            {"term": "guère", "gloss": "hardly"},
            {"term": "l'isolement", "gloss": "isolation"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article environnement / Environmental article",
        "topic": "Environnement & nature",
        "text": "Une éolienne produit en vingt ans plus de trente fois l'énergie nécessaire à sa fabrication.\nCe rapport, rarement cité, ne règle pourtant pas la question du paysage ni celle du bruit, qui sont d'un autre ordre : on ne répond pas à une objection esthétique par un calcul énergétique.",
        "question_fr": "Quelle position l'auteur défend-il ?",
        "options": [
            {"id": "a", "text": "Les objections au paysage sont sans fondement",
             "explanation": "They are called « d'un autre ordre », not baseless."},
            {"id": "b", "text": "Le bilan énergétique ne répond pas à toutes les objections",
             "explanation": "« on ne répond pas à une objection esthétique par un calcul énergétique »."},
            {"id": "c", "text": "Les éoliennes consomment plus qu'elles ne produisent",
             "explanation": "They produce over thirty times what their manufacture costs."},
            {"id": "d", "text": "Le bruit est le principal problème",
             "explanation": "Noise is one objection among others, not ranked first."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On ne répond pas à une objection esthétique par un calcul énergétique.",
        "key_line_en": "You do not answer an aesthetic objection with an energy calculation.",
        "vocabulary": [
            {"term": "une éolienne", "gloss": "a wind turbine"},
            {"term": "un rapport", "gloss": "a ratio"},
            {"term": "d'un autre ordre", "gloss": "of a different kind"},
            {"term": "régler", "gloss": "to settle"},
        ],
    },
    {
        "level": "B2", "band": "400 – 499 points",
        "doc_type": "Article santé / Health article",
        "topic": "Santé & bien-être",
        "text": "Les urgences reçoivent chaque année davantage de patients qui auraient pu être vus en ville.\nOn accuse volontiers ces patients de mal s'orienter. Ils s'orientent au contraire très bien : les urgences sont ouvertes, gratuites à l'entrée et sans rendez-vous. Le reste ne l'est pas.",
        "question_fr": "Comment l'auteur explique-t-il l'afflux aux urgences ?",
        "options": [
            {"id": "a", "text": "Par une réaction rationnelle à l'offre disponible",
             "explanation": "Open, free at the door, no appointment: « Ils s'orientent au contraire très bien. Le reste ne l'est pas »."},
            {"id": "b", "text": "Par l'ignorance des patients",
             "explanation": "That is the accusation the article rejects."},
            {"id": "c", "text": "Par la gravité croissante des cas",
             "explanation": "The patients described could have been seen elsewhere."},
            {"id": "d", "text": "Par le manque de personnel hospitalier",
             "explanation": "Staffing is not the explanation offered."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Les urgences sont ouvertes, gratuites à l'entrée et sans rendez-vous. Le reste ne l'est pas.",
        "key_line_en": "A&E is open, free at the door and needs no appointment. The rest is not.",
        "vocabulary": [
            {"term": "les urgences", "gloss": "A&E, the emergency department"},
            {"term": "en ville", "gloss": "in general practice, outside hospital"},
            {"term": "s'orienter", "gloss": "to find one's way"},
            {"term": "un afflux", "gloss": "an influx"},
        ],
    },

    # ------------------------------------------------------------------
    # C1 — 500 – 599 points
    # ------------------------------------------------------------------
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Essai / Essay",
        "topic": "Sciences & technologies",
        "text": "Un outil bien conçu se laisse oublier ; c'est à sa disparition qu'on le reconnaît.\nCelui qui doit penser à son marteau ne pense plus au clou. Les objets que nous célébrons le plus sont souvent ceux qui exigent le plus d'attention — signe qu'ils fonctionnent mal, non qu'ils fonctionnent bien.",
        "question_fr": "Quel critère l'auteur propose-t-il ?",
        "options": [
            {"id": "a", "text": "Un bon outil se fait oublier pendant l'usage",
             "explanation": "« Celui qui doit penser à son marteau ne pense plus au clou »; demanding attention is a sign of malfunction."},
            {"id": "b", "text": "Un bon outil doit être admiré",
             "explanation": "Celebrated objects are precisely those the essay suspects."},
            {"id": "c", "text": "Un outil doit être simple à fabriquer",
             "explanation": "Manufacture is never discussed."},
            {"id": "d", "text": "Un outil doit durer longtemps",
             "explanation": "Durability is not the criterion offered."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Celui qui doit penser à son marteau ne pense plus au clou.",
        "key_line_en": "Anyone who has to think about their hammer is no longer thinking about the nail.",
        "vocabulary": [
            {"term": "se laisser oublier", "gloss": "to let itself be forgotten"},
            {"term": "un clou", "gloss": "a nail"},
            {"term": "exiger", "gloss": "to demand"},
            {"term": "célébrer", "gloss": "to celebrate"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Chronique ironique / Ironic column",
        "topic": "Société, citoyenneté & administration",
        "text": "La consultation a recueilli douze mille contributions, ce dont le communiqué se félicite longuement.\nIl ne précise pas combien ont été lues, ni par qui, ni ce qu'il en est advenu. On saluera néanmoins la mobilisation, qui restera le principal résultat de l'opération.",
        "question_fr": "Que suggère la dernière phrase ?",
        "options": [
            {"id": "a", "text": "Que la participation a été décevante",
             "explanation": "Twelve thousand contributions came in; participation is not what failed."},
            {"id": "b", "text": "Que la consultation n'a produit aucune suite",
             "explanation": "Turnout « restera le principal résultat » — that is, nothing came of the contributions themselves."},
            {"id": "c", "text": "Que le communiqué est trop court",
             "explanation": "It congratulates itself « longuement »."},
            {"id": "d", "text": "Que les contributions étaient de mauvaise qualité",
             "explanation": "Their quality is never assessed — nobody says they were read."},
        ],
        "correct_answer": "b",
        "key_line_fr": "On saluera néanmoins la mobilisation, qui restera le principal résultat de l'opération.",
        "key_line_en": "One will nonetheless applaud the turnout, which will remain the operation's main result.",
        "vocabulary": [
            {"term": "recueillir", "gloss": "to collect, gather"},
            {"term": "advenir", "gloss": "to become of"},
            {"term": "saluer", "gloss": "to applaud"},
            {"term": "la mobilisation", "gloss": "turnout, mobilisation"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse prospective / Forward-looking analysis",
        "topic": "Travail & emploi",
        "text": "On imagine la formation continue comme un rattrapage, alors qu'elle devient une condition d'entrée.\nUn métier qui exige d'apprendre en permanence exclut d'abord ceux qui n'ont pas le temps d'apprendre : parents seuls, horaires décalés, seconds emplois. L'obstacle n'est pas cognitif, il est calendaire.",
        "question_fr": "Quel obstacle l'auteur identifie-t-il ?",
        "options": [
            {"id": "a", "text": "La difficulté intellectuelle des formations",
             "explanation": "« L'obstacle n'est pas cognitif » — explicitly not ability."},
            {"id": "b", "text": "Le coût des formations",
             "explanation": "Money is not mentioned; time is."},
            {"id": "c", "text": "Le manque de temps disponible",
             "explanation": "« il est calendaire » — single parents, shift work, second jobs."},
            {"id": "d", "text": "Le manque d'offres de formation",
             "explanation": "Supply of courses is not questioned."},
        ],
        "correct_answer": "c",
        "key_line_fr": "L'obstacle n'est pas cognitif, il est calendaire.",
        "key_line_en": "The obstacle is not cognitive, it is a matter of the calendar.",
        "vocabulary": [
            {"term": "un rattrapage", "gloss": "a catching-up"},
            {"term": "des horaires décalés", "gloss": "shift or unsocial hours"},
            {"term": "calendaire", "gloss": "to do with the calendar"},
            {"term": "exclure", "gloss": "to exclude"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Extrait littéraire / Literary extract",
        "topic": "Loisirs, culture & médias",
        "text": "On lui avait toujours dit qu'elle avait de la chance, et elle avait fini par le croire.\nCe mot commode expliquait à la fois ce qu'elle avait obtenu et pourquoi elle n'avait pas à s'en vanter : la chance dispense de reconnaître le travail, y compris à celui qui l'a fourni.",
        "question_fr": "Quel effet le mot « chance » a-t-il sur le personnage ?",
        "options": [
            {"id": "a", "text": "Il l'empêche de reconnaître son propre travail",
             "explanation": "« la chance dispense de reconnaître le travail, y compris à celui qui l'a fourni »."},
            {"id": "b", "text": "Il la rend arrogante",
             "explanation": "The opposite: it gives her a reason not to boast."},
            {"id": "c", "text": "Il la pousse à travailler davantage",
             "explanation": "No such motivation is described."},
            {"id": "d", "text": "Il explique ses échecs",
             "explanation": "The word is used to explain what she obtained, not what she failed at."},
        ],
        "correct_answer": "a",
        "key_line_fr": "La chance dispense de reconnaître le travail, y compris à celui qui l'a fourni.",
        "key_line_en": "Luck excuses everyone from acknowledging the work — including the person who did it.",
        "vocabulary": [
            {"term": "commode", "gloss": "convenient"},
            {"term": "se vanter", "gloss": "to boast"},
            {"term": "dispenser de", "gloss": "to excuse from"},
            {"term": "fournir", "gloss": "to put in, supply"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article scientifique / Scientific article",
        "topic": "Environnement & nature",
        "text": "Les espèces qui disparaissent en premier ne sont pas les plus fragiles, mais les plus spécialisées.\nUn oiseau qui mange dix insectes différents s'adapte ; celui qui n'en mange qu'un disparaît avec lui. La spécialisation est un avantage tant que le milieu ne change pas — et une dette dès qu'il change.",
        "question_fr": "Pourquoi la spécialisation devient-elle un risque ?",
        "options": [
            {"id": "a", "text": "Parce que les espèces spécialisées sont plus rares",
             "explanation": "Rarity is not the mechanism; dependence on one resource is."},
            {"id": "b", "text": "Parce qu'elle empêche de s'adapter au changement",
             "explanation": "« un avantage tant que le milieu ne change pas — et une dette dès qu'il change »."},
            {"id": "c", "text": "Parce qu'elle affaiblit physiquement les espèces",
             "explanation": "« ne sont pas les plus fragiles » — physical weakness is ruled out."},
            {"id": "d", "text": "Parce que les insectes disparaissent en premier",
             "explanation": "The insect is an example of the resource, not a general claim."},
        ],
        "correct_answer": "b",
        "key_line_fr": "La spécialisation est un avantage tant que le milieu ne change pas — et une dette dès qu'il change.",
        "key_line_en": "Specialisation is an advantage as long as the habitat does not change — and a debt as soon as it does.",
        "vocabulary": [
            {"term": "spécialisé", "gloss": "specialised"},
            {"term": "s'adapter", "gloss": "to adapt"},
            {"term": "un milieu", "gloss": "a habitat"},
            {"term": "une dette", "gloss": "a debt, liability"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Analyse urbaine / Urban analysis",
        "topic": "Vie quotidienne & logement",
        "text": "La nuit, une rue n'est pas sûre parce qu'elle est éclairée, mais parce qu'elle est habitée.\nUne fenêtre allumée fait davantage qu'un lampadaire : elle suppose quelqu'un derrière. C'est pourquoi les rues bordées de bureaux inquiètent dès dix-neuf heures, quelle que soit leur luminosité.",
        "question_fr": "Qu'est-ce qui rend une rue rassurante, selon l'auteur ?",
        "options": [
            {"id": "a", "text": "La puissance de l'éclairage public",
             "explanation": "Office streets are lit and still uneasy « quelle que soit leur luminosité »."},
            {"id": "b", "text": "La largeur de la rue",
             "explanation": "Width is never mentioned."},
            {"id": "c", "text": "La présence de commerces",
             "explanation": "Shops are not the example given; lit windows with people behind them are."},
            {"id": "d", "text": "La présence de personnes qui l'habitent",
             "explanation": "« Une fenêtre allumée […] suppose quelqu'un derrière »."},
        ],
        "correct_answer": "d",
        "key_line_fr": "Une rue n'est pas sûre parce qu'elle est éclairée, mais parce qu'elle est habitée.",
        "key_line_en": "A street is not safe because it is lit, but because it is lived in.",
        "vocabulary": [
            {"term": "un lampadaire", "gloss": "a streetlamp"},
            {"term": "bordé de", "gloss": "lined with"},
            {"term": "la luminosité", "gloss": "brightness"},
            {"term": "supposer", "gloss": "to imply, presuppose"},
        ],
    },
    {
        "level": "C1", "band": "500 – 599 points",
        "doc_type": "Article consommation / Consumer analysis",
        "topic": "Alimentation & consommation",
        "text": "Le consommateur informé est devenu l'alibi de tout le monde.\nOn lui fournit des étiquettes, des scores, des applications, et l'on considère le devoir accompli. Transférer la décision à celui qui la subit n'est pas l'éclairer : c'est le rendre responsable d'un choix qu'il ne peut pas modifier.",
        "question_fr": "Que reproche l'auteur à cette approche ?",
        "options": [
            {"id": "a", "text": "Elle donne trop peu d'informations",
             "explanation": "Labels, scores and apps are supplied in abundance."},
            {"id": "b", "text": "Elle rend responsable qui n'a pas le pouvoir de changer l'offre",
             "explanation": "« Transférer la décision à celui qui la subit […] c'est le rendre responsable d'un choix qu'il ne peut pas modifier »."},
            {"id": "c", "text": "Elle complique inutilement les étiquettes",
             "explanation": "Complexity of labels is not the objection."},
            {"id": "d", "text": "Elle empêche les consommateurs de choisir",
             "explanation": "They can choose; the point is that choosing does not change what is on offer."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Transférer la décision à celui qui la subit n'est pas l'éclairer.",
        "key_line_en": "Transferring the decision to the person who bears it is not the same as informing them.",
        "vocabulary": [
            {"term": "un alibi", "gloss": "an alibi, excuse"},
            {"term": "subir", "gloss": "to undergo, be subject to"},
            {"term": "éclairer", "gloss": "to inform, enlighten"},
            {"term": "accompli", "gloss": "fulfilled, done"},
        ],
    },

    # ------------------------------------------------------------------
    # C2 — 600 – 699 points
    # ------------------------------------------------------------------
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la mémoire / Essay on memory",
        "topic": "Loisirs, culture & médias",
        "text": "Un monument n'est pas fait pour qu'on se souvienne : il est fait pour qu'on n'ait plus à le faire.\nUne fois la pierre posée, le souvenir cesse d'être une tâche et devient un lieu — que l'on peut, dès lors, ne plus visiter.",
        "question_fr": "Quel paradoxe l'auteur formule-t-il ?",
        "options": [
            {"id": "a", "text": "Le monument dispense du travail de mémoire",
             "explanation": "Once the stone is laid, remembering « cesse d'être une tâche et devient un lieu » one may then stop visiting."},
            {"id": "b", "text": "Les monuments sont mal entretenus",
             "explanation": "Upkeep is never discussed."},
            {"id": "c", "text": "Il faudrait construire davantage de monuments",
             "explanation": "The essay questions what they do, and proposes no building programme."},
            {"id": "d", "text": "Le souvenir se transmet mieux par la pierre",
             "explanation": "The stone is presented as what lets memory be set down and left."},
        ],
        "correct_answer": "a",
        "key_line_fr": "Le souvenir cesse d'être une tâche et devient un lieu.",
        "key_line_en": "Remembrance stops being a task and becomes a place.",
        "vocabulary": [
            {"term": "poser la pierre", "gloss": "to lay the stone"},
            {"term": "cesser de", "gloss": "to stop being"},
            {"term": "dès lors", "gloss": "from then on"},
            {"term": "une tâche", "gloss": "a task"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai politique / Political essay",
        "topic": "Société, citoyenneté & administration",
        "text": "On dit d'une réforme qu'elle est technique lorsqu'on souhaite qu'elle ne soit pas discutée.\nLe mot ne décrit pas le contenu, il désigne l'auditoire admis : dès qu'une question devient technique, la liste de ceux qui ont le droit d'en parler se réduit d'elle-même.",
        "question_fr": "Que soutient l'auteur sur le mot « technique » ?",
        "options": [
            {"id": "a", "text": "Il garantit la rigueur d'une réforme",
             "explanation": "The essay treats it as a device for restricting debate, not a mark of rigour."},
            {"id": "b", "text": "Il sert à restreindre le débat",
             "explanation": "« il désigne l'auditoire admis »: the list of those entitled to speak shrinks."},
            {"id": "c", "text": "Il décrit fidèlement le contenu",
             "explanation": "« Le mot ne décrit pas le contenu » — explicitly denied."},
            {"id": "d", "text": "Il rend les réformes impopulaires",
             "explanation": "Popularity is not the subject."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Dès qu'une question devient technique, la liste de ceux qui ont le droit d'en parler se réduit d'elle-même.",
        "key_line_en": "As soon as a question becomes technical, the list of those entitled to speak about it shrinks by itself.",
        "vocabulary": [
            {"term": "un auditoire", "gloss": "an audience"},
            {"term": "admis", "gloss": "admitted, allowed"},
            {"term": "se réduire", "gloss": "to shrink"},
            {"term": "désigner", "gloss": "to denote"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Réflexion épistémologique / Epistemological reflection",
        "topic": "Sciences & technologies",
        "text": "Une explication qui vaut pour tout n'explique rien, et l'on s'en aperçoit toujours trop tard : elle a d'abord la séduction de l'évidence.\nOn devrait tester une théorie non sur ce qu'elle éclaire, mais sur ce qu'elle refuserait d'admettre. Ce refus, seul, la rend informative.",
        "question_fr": "Quel test l'auteur propose-t-il ?",
        "options": [
            {"id": "a", "text": "Vérifier tout ce qu'une théorie éclaire",
             "explanation": "Explaining everything is exactly the symptom of emptiness here."},
            {"id": "b", "text": "Comparer plusieurs théories rivales",
             "explanation": "Comparison is not the test proposed."},
            {"id": "c", "text": "Identifier ce qu'elle exclurait",
             "explanation": "« sur ce qu'elle refuserait d'admettre. Ce refus, seul, la rend informative »."},
            {"id": "d", "text": "Mesurer son degré d'évidence",
             "explanation": "Obviousness is the seduction that misleads, not a criterion."},
        ],
        "correct_answer": "c",
        "key_line_fr": "On devrait tester une théorie non sur ce qu'elle éclaire, mais sur ce qu'elle refuserait d'admettre.",
        "key_line_en": "A theory should be tested not on what it illuminates, but on what it would refuse to allow.",
        "vocabulary": [
            {"term": "la séduction", "gloss": "the appeal"},
            {"term": "l'évidence", "gloss": "obviousness"},
            {"term": "admettre", "gloss": "to allow, accept"},
            {"term": "informatif", "gloss": "informative"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Chronique urbaine / Urban column",
        "topic": "Vie quotidienne & logement",
        "text": "On a rendu la place piétonne, planté des arbres, installé du mobilier design.\nIl y manque encore ce qu'aucun aménagement ne fournit : une raison d'y rester quand il pleut. Une place ne vit pas de son sol, mais de ce qui l'entoure et qui ouvre.",
        "question_fr": "Que manque-t-il à cette place, selon l'auteur ?",
        "options": [
            {"id": "a", "text": "Des arbres et du mobilier",
             "explanation": "Both were installed."},
            {"id": "b", "text": "Un revêtement de meilleure qualité",
             "explanation": "« Une place ne vit pas de son sol » — the surface is not the issue."},
            {"id": "c", "text": "Des lieux ouverts autour d'elle",
             "explanation": "« de ce qui l'entoure et qui ouvre » — a reason to stay when it rains."},
            {"id": "d", "text": "Une meilleure protection contre la pluie",
             "explanation": "Rain is the test of the place, not a problem to be solved with shelter."},
        ],
        "correct_answer": "c",
        "key_line_fr": "Une place ne vit pas de son sol, mais de ce qui l'entoure et qui ouvre.",
        "key_line_en": "A square does not live from its paving, but from what surrounds it and opens onto it.",
        "vocabulary": [
            {"term": "piéton(ne)", "gloss": "pedestrianised"},
            {"term": "un aménagement", "gloss": "a development, layout"},
            {"term": "le mobilier", "gloss": "street furniture"},
            {"term": "entourer", "gloss": "to surround"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Critique de roman / Novel review",
        "topic": "Loisirs, culture & médias",
        "text": "Le roman raconte une vie entière en cent pages, ce qui suppose de choisir. L'auteur choisit mal : il garde les événements et sacrifie les intervalles.\nOr une existence tient moins à ce qui lui arrive qu'à la durée pendant laquelle il ne lui arrive rien.",
        "question_fr": "Que reproche le critique à l'auteur ?",
        "options": [
            {"id": "a", "text": "D'avoir écrit un roman trop long",
             "explanation": "A hundred pages for a whole life is short; brevity is the constraint, not the fault."},
            {"id": "b", "text": "D'avoir gardé les événements aux dépens des temps morts",
             "explanation": "« il garde les événements et sacrifie les intervalles », yet a life holds by the empty stretches."},
            {"id": "c", "text": "D'avoir inventé des événements",
             "explanation": "Invention is not questioned."},
            {"id": "d", "text": "D'avoir refusé de choisir",
             "explanation": "He does choose — the objection is what he chose."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Une existence tient moins à ce qui lui arrive qu'à la durée pendant laquelle il ne lui arrive rien.",
        "key_line_en": "A life holds less by what happens to it than by the stretches in which nothing happens.",
        "vocabulary": [
            {"term": "un intervalle", "gloss": "an interval, gap"},
            {"term": "sacrifier", "gloss": "to sacrifice"},
            {"term": "tenir à", "gloss": "to depend on"},
            {"term": "une existence", "gloss": "a life"},
        ],
    },
    {
        "level": "C2", "band": "600 – 699 points",
        "doc_type": "Essai sur la décision / Essay on decision-making",
        "topic": "Société, citoyenneté & administration",
        "text": "Reporter une décision est encore une décision, mais c'est la seule qu'on n'ait pas à justifier.\nLà tient tout son attrait, et tout son coût : elle laisse le champ libre à ce qui se produira de toute façon, tout en donnant à celui qui s'abstient le sentiment d'être resté prudent.",
        "question_fr": "Que soutient l'auteur ?",
        "options": [
            {"id": "a", "text": "Reporter permet souvent de mieux décider",
             "explanation": "Delay is said to hand the outcome to whatever would happen anyway."},
            {"id": "b", "text": "L'abstention est un choix déguisé en prudence",
             "explanation": "It needs no justification and « donn[e] à celui qui s'abstient le sentiment d'être resté prudent », while events decide."},
            {"id": "c", "text": "Toute décision doit être justifiée publiquement",
             "explanation": "No such requirement is proposed."},
            {"id": "d", "text": "Les décisions rapides sont préférables",
             "explanation": "Speed is not defended; the analysis concerns what postponement conceals."},
        ],
        "correct_answer": "b",
        "key_line_fr": "Reporter une décision est encore une décision, mais c'est la seule qu'on n'ait pas à justifier.",
        "key_line_en": "Postponing a decision is still a decision, but it is the only one you never have to justify.",
        "vocabulary": [
            {"term": "reporter", "gloss": "to postpone"},
            {"term": "un attrait", "gloss": "an appeal"},
            {"term": "s'abstenir", "gloss": "to abstain"},
            {"term": "laisser le champ libre", "gloss": "to leave the field clear"},
        ],
    },
]

QUESTIONS = balance(_RAW)
